// This file is auto-generated by @hey-api/openapi-ts

export const FileSchema = {
  "x-fal-order-properties": ["url", "content_type", "file_name", "file_size"],
  type: "object",
  title: "File",
  required: ["url"],
  properties: {
    content_type: {
      description: "The mime type of the file.",
      examples: ["image/png"],
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Content Type",
    },
    file_size: {
      description: "The size of the file in bytes.",
      examples: [4404019],
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "File Size",
    },
    url: {
      description: "The URL where the file can be downloaded from.",
      type: "string",
      title: "Url",
    },
    file_name: {
      description:
        "The name of the file. It will be auto-generated if not provided.",
      examples: ["z9RV14K95DvU.png"],
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "File Name",
    },
  },
} as const;

export const PromptTokensDetailsSchema = {
  type: "object",
  title: "PromptTokensDetails",
  "x-fal-order-properties": ["cached_tokens", "cache_write_tokens"],
  properties: {
    cache_write_tokens: {
      type: "integer",
      title: "Cache Write Tokens",
      default: 0,
    },
    cached_tokens: {
      type: "integer",
      title: "Cached Tokens",
      default: 0,
    },
  },
} as const;

export const QueueStatusSchema = {
  type: "object",
  properties: {
    status: {
      type: "string",
      enum: ["IN_QUEUE", "IN_PROGRESS", "COMPLETED"],
    },
    request_id: {
      type: "string",
      description: "The request id.",
    },
    response_url: {
      type: "string",
      description: "The response url.",
    },
    status_url: {
      type: "string",
      description: "The status url.",
    },
    cancel_url: {
      type: "string",
      description: "The cancel url.",
    },
    logs: {
      type: "object",
      description: "The logs.",
      additionalProperties: true,
    },
    metrics: {
      type: "object",
      description: "The metrics.",
      additionalProperties: true,
    },
    queue_position: {
      type: "integer",
      description: "The queue position.",
    },
  },
  required: ["status", "request_id"],
} as const;

export const RouterAudioInputSchema = {
  type: "object",
  title: "AudioInput",
  "x-fal-order-properties": [
    "audio_url",
    "prompt",
    "system_prompt",
    "model",
    "reasoning",
    "temperature",
    "max_tokens",
  ],
  properties: {
    system_prompt: {
      examples: [
        "Transcribe the audio accurately, including speaker identification if multiple speakers are present.",
      ],
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description:
        "System prompt to provide context or instructions to the model",
      title: "System Prompt",
    },
    temperature: {
      type: "number",
      title: "Temperature",
      description:
        "This setting influences the variety in the model's responses. Lower values lead to more predictable and typical responses, while higher values encourage more diverse and less common responses. At 0, the model always gives the same response for a given input.",
      minimum: 0,
      default: 1,
      maximum: 2,
    },
    max_tokens: {
      anyOf: [
        {
          type: "integer",
          minimum: 1,
        },
        {
          type: "null",
        },
      ],
      description:
        "This sets the upper limit for the number of tokens the model can generate in response. It won't produce more than this limit. The maximum value is the context length minus the prompt length.",
      title: "Max Tokens",
    },
    reasoning: {
      type: "boolean",
      title: "Reasoning",
      description: "Should reasoning be the part of the final answer.",
      default: false,
    },
    audio_url: {
      examples: [
        "https://storage.googleapis.com/falserverless/model_tests/audio-understanding/Title_%20Running%20on%20Fal.mp3",
      ],
      title: "Audio Url",
      description:
        "URL or data URI of the audio file to process. Supported formats: wav, mp3, aiff, aac, ogg, flac, m4a.",
      type: "string",
      "x-fal-file-input": true,
    },
    model: {
      examples: [
        "google/gemini-3-flash-preview",
        "google/gemini-2.5-flash",
        "google/gemini-3-pro-preview",
        "google/gemini-3.1-pro-preview",
      ],
      title: "Model",
      description:
        "Name of the model to use. Charged based on actual token usage.",
      type: "string",
    },
    prompt: {
      examples: [
        "Please transcribe this audio file.",
        "What is being said in this audio?",
      ],
      title: "Prompt",
      description: "Prompt to be used for the audio processing",
      type: "string",
    },
  },
  required: ["prompt", "audio_url", "model"],
} as const;

export const RouterAudioOutputSchema = {
  type: "object",
  title: "AudioOutput",
  "x-fal-order-properties": ["output", "usage"],
  properties: {
    usage: {
      examples: [
        {
          prompt_tokens: 500,
          cost: 0.0003,
          total_tokens: 550,
          completion_tokens: 50,
        },
      ],
      anyOf: [
        {
          $ref: "#/components/schemas/UsageInfo",
        },
        {
          type: "null",
        },
      ],
      description: "Token usage information",
    },
    output: {
      examples: [
        "The audio contains a conversation between two people discussing the weather forecast for the upcoming week.",
      ],
      title: "Output",
      description: "Generated output from audio processing",
      type: "string",
    },
  },
  required: ["output", "usage"],
} as const;

export const UsageInfoSchema = {
  type: "object",
  title: "UsageInfo",
  "x-fal-order-properties": [
    "prompt_tokens",
    "completion_tokens",
    "total_tokens",
    "cost",
    "prompt_tokens_details",
  ],
  properties: {
    prompt_tokens: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Prompt Tokens",
    },
    prompt_tokens_details: {
      anyOf: [
        {
          $ref: "#/components/schemas/PromptTokensDetails",
        },
        {
          type: "null",
        },
      ],
    },
    total_tokens: {
      type: "integer",
      title: "Total Tokens",
      default: 0,
    },
    cost: {
      type: "number",
      title: "Cost",
    },
    completion_tokens: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Completion Tokens",
    },
  },
  required: ["cost"],
} as const;

export const WorkflowUtilitiesInterleaveVideoInputSchema = {
  description: "Input model for interleaving multiple videos",
  "x-fal-order-properties": ["video_urls", "frames_per_second"],
  type: "object",
  title: "InterleaveVideoInput",
  required: ["video_urls"],
  properties: {
    video_urls: {
      items: {
        type: "string",
        _fal_ui_field: "video",
        "x-fal-file-input": true,
      },
      max_file_size: 100000000,
      examples: [
        [
          "https://storage.googleapis.com/falserverless/example_outputs/wan-25-i2v-output.mp4",
          "https://storage.googleapis.com/falserverless/model_tests/kling/kling-v2.5-turbo-pro-image-to-video-output.mp4",
          "https://storage.googleapis.com/falserverless/example_inputs/seedance_pro_i2v.mp4",
          "https://storage.googleapis.com/falserverless/example_outputs/wan-25-i2v-output.mp4",
          "https://storage.googleapis.com/falserverless/model_tests/kling/kling-v2.5-turbo-pro-image-to-video-output.mp4",
          "https://storage.googleapis.com/falserverless/example_inputs/seedance_pro_i2v.mp4",
        ],
      ],
      description: "List of video URLs to interleave in order",
      type: "array",
      title: "Video Urls",
    },
    frames_per_second: {
      description:
        "Frame rate of the interleaved output video. When set, all interleaved frames are emitted at this rate, so lower values produce a longer output while higher values produce a shorter, faster one. Leave unset to preserve the legacy behavior, which derives the output rate from the input videos (this can yield non-standard rates such as 384.0098).",
      examples: [24],
      anyOf: [
        {
          maximum: 120,
          minimum: 1,
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Frames Per Second",
    },
  },
} as const;

export const WorkflowUtilitiesInterleaveVideoOutputSchema = {
  description: "Output model for interleaved video",
  "x-fal-order-properties": ["video"],
  type: "object",
  title: "InterleaveVideoOutput",
  required: ["video"],
  properties: {
    video: {
      description: "The interleaved video output",
      examples: [
        {
          content_type: "application/octet-stream",
          file_size: 3886177,
          url: "https://v3b.fal.media/files/b/monkey/xVp56BqDLgb39NONPs1Gb_output.mp4",
          file_name: "output.mp4",
        },
      ],
      $ref: "#/components/schemas/File",
    },
  },
} as const;
