// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * File
 */
export const zFile = z.object({
  content_type: z.union([z.string(), z.unknown()]).optional(),
  file_size: z.union([z.int(), z.unknown()]).optional(),
  url: z.string().register(z.globalRegistry, {
    description: "The URL where the file can be downloaded from.",
  }),
  file_name: z.union([z.string(), z.unknown()]).optional(),
});

/**
 * PromptTokensDetails
 */
export const zPromptTokensDetails = z.object({
  cache_write_tokens: z.int().optional().default(0),
  cached_tokens: z.int().optional().default(0),
});

export const zQueueStatus = z.object({
  status: z.enum(["IN_QUEUE", "IN_PROGRESS", "COMPLETED"]),
  request_id: z.string().register(z.globalRegistry, {
    description: "The request id.",
  }),
  response_url: z
    .string()
    .register(z.globalRegistry, {
      description: "The response url.",
    })
    .optional(),
  status_url: z
    .string()
    .register(z.globalRegistry, {
      description: "The status url.",
    })
    .optional(),
  cancel_url: z
    .string()
    .register(z.globalRegistry, {
      description: "The cancel url.",
    })
    .optional(),
  logs: z
    .record(z.string(), z.unknown())
    .register(z.globalRegistry, {
      description: "The logs.",
    })
    .optional(),
  metrics: z
    .record(z.string(), z.unknown())
    .register(z.globalRegistry, {
      description: "The metrics.",
    })
    .optional(),
  queue_position: z
    .int()
    .register(z.globalRegistry, {
      description: "The queue position.",
    })
    .optional(),
});

/**
 * AudioInput
 */
export const zRouterAudioInput = z.object({
  system_prompt: z.union([z.string(), z.unknown()]).optional(),
  temperature: z
    .number()
    .gte(0)
    .lte(2)
    .register(z.globalRegistry, {
      description:
        "This setting influences the variety in the model's responses. Lower values lead to more predictable and typical responses, while higher values encourage more diverse and less common responses. At 0, the model always gives the same response for a given input.",
    })
    .optional()
    .default(1),
  max_tokens: z.union([z.int().gte(1), z.unknown()]).optional(),
  reasoning: z
    .boolean()
    .register(z.globalRegistry, {
      description: "Should reasoning be the part of the final answer.",
    })
    .optional()
    .default(false),
  audio_url: z.string().register(z.globalRegistry, {
    description:
      "URL or data URI of the audio file to process. Supported formats: wav, mp3, aiff, aac, ogg, flac, m4a.",
  }),
  model: z.string().register(z.globalRegistry, {
    description:
      "Name of the model to use. Charged based on actual token usage.",
  }),
  prompt: z.string().register(z.globalRegistry, {
    description: "Prompt to be used for the audio processing",
  }),
});

/**
 * UsageInfo
 */
export const zUsageInfo = z.object({
  prompt_tokens: z.union([z.int(), z.unknown()]).optional(),
  prompt_tokens_details: z
    .union([zPromptTokensDetails, z.unknown()])
    .optional(),
  total_tokens: z.int().optional().default(0),
  cost: z.number(),
  completion_tokens: z.union([z.int(), z.unknown()]).optional(),
});

/**
 * AudioOutput
 */
export const zRouterAudioOutput = z.object({
  usage: z.union([zUsageInfo, z.unknown()]),
  output: z.string().register(z.globalRegistry, {
    description: "Generated output from audio processing",
  }),
});

/**
 * InterleaveVideoInput
 *
 * Input model for interleaving multiple videos
 */
export const zWorkflowUtilitiesInterleaveVideoInput = z
  .object({
    video_urls: z.array(z.string()).register(z.globalRegistry, {
      description: "List of video URLs to interleave in order",
    }),
    frames_per_second: z
      .union([z.number().gte(1).lte(120), z.unknown()])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Input model for interleaving multiple videos",
  });

/**
 * InterleaveVideoOutput
 *
 * Output model for interleaved video
 */
export const zWorkflowUtilitiesInterleaveVideoOutput = z
  .object({
    video: zFile,
  })
  .register(z.globalRegistry, {
    description: "Output model for interleaved video",
  });

export const zPostFalAiWorkflowUtilitiesInterleaveVideoBody =
  zWorkflowUtilitiesInterleaveVideoInput;

/**
 * The request status.
 */
export const zPostFalAiWorkflowUtilitiesInterleaveVideoResponse = zQueueStatus;

export const zGetFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * Result of the request.
 */
export const zGetFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdResponse =
  zWorkflowUtilitiesInterleaveVideoOutput;

export const zPutFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * The request was cancelled.
 */
export const zPutFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdCancelResponse =
  z
    .object({
      success: z
        .boolean()
        .register(z.globalRegistry, {
          description: "Whether the request was cancelled successfully.",
        })
        .optional(),
    })
    .register(z.globalRegistry, {
      description: "The request was cancelled.",
    });

export const zGetFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

export const zGetFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdStatusQuery =
  z.object({
    logs: z
      .number()
      .register(z.globalRegistry, {
        description:
          "Whether to include logs (`1`) in the response or not (`0`).",
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiWorkflowUtilitiesInterleaveVideoRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostOpenrouterRouterAudioBody = zRouterAudioInput;

/**
 * The request status.
 */
export const zPostOpenrouterRouterAudioResponse = zQueueStatus;

export const zGetOpenrouterRouterAudioRequestsByRequestIdPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * Result of the request.
 */
export const zGetOpenrouterRouterAudioRequestsByRequestIdResponse =
  zRouterAudioOutput;

export const zPutOpenrouterRouterAudioRequestsByRequestIdCancelPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * The request was cancelled.
 */
export const zPutOpenrouterRouterAudioRequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zGetOpenrouterRouterAudioRequestsByRequestIdStatusPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

export const zGetOpenrouterRouterAudioRequestsByRequestIdStatusQuery = z.object(
  {
    logs: z
      .number()
      .register(z.globalRegistry, {
        description:
          "Whether to include logs (`1`) in the response or not (`0`).",
      })
      .optional(),
  },
);

/**
 * The request status.
 */
export const zGetOpenrouterRouterAudioRequestsByRequestIdStatusResponse =
  zQueueStatus;
