// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * MultiMeasurementOutput
 */
export const zArbiterImageImageOutput = z.object({
  values: z
    .array(
      z.record(
        z.string(),
        z.union([z.number(), z.record(z.string(), z.number())]),
      ),
    )
    .register(z.globalRegistry, {
      description: "The values of the measurements.",
    })
    .optional(),
});

/**
 * MultiMeasurementOutput
 */
export const zArbiterImageOutput = z.object({
  values: z
    .array(
      z.record(
        z.string(),
        z.union([z.number(), z.record(z.string(), z.number())]),
      ),
    )
    .register(z.globalRegistry, {
      description: "The values of the measurements.",
    })
    .optional(),
});

/**
 * MultiMeasurementOutput
 */
export const zArbiterImageTextOutput = z.object({
  values: z
    .array(
      z.record(
        z.string(),
        z.union([z.number(), z.record(z.string(), z.number())]),
      ),
    )
    .register(z.globalRegistry, {
      description: "The values of the measurements.",
    })
    .optional(),
});

/**
 * CompletionUsage
 */
export const zCompletionUsage = z.object({
  completion_tokens: z.int().register(z.globalRegistry, {
    description: "Number of tokens in the completion",
  }),
  total_tokens: z.int().register(z.globalRegistry, {
    description: "Total tokens used",
  }),
  prompt_tokens: z.int().register(z.globalRegistry, {
    description: "Number of tokens in the prompt",
  }),
});

/**
 * File
 */
export const zFile = z.object({
  file_name: z.union([z.string(), z.unknown()]).optional(),
  file_size: z.union([z.int(), z.unknown()]).optional(),
  content_type: z.union([z.string(), z.unknown()]).optional(),
  url: z.string().register(z.globalRegistry, {
    description: "The URL where the file can be downloaded from.",
  }),
});

/**
 * ImageInput
 */
export const zFlorence2LargeCaptionInput = z.object({
  image_url: z.string().register(z.globalRegistry, {
    description: "The URL of the image to be processed.",
  }),
});

/**
 * TextOutput
 */
export const zFlorence2LargeCaptionOutput = z.object({
  results: z.string().register(z.globalRegistry, {
    description: "Results from the model",
  }),
});

/**
 * ImageInput
 */
export const zFlorence2LargeDetailedCaptionInput = z.object({
  image_url: z.string().register(z.globalRegistry, {
    description: "The URL of the image to be processed.",
  }),
});

/**
 * TextOutput
 */
export const zFlorence2LargeDetailedCaptionOutput = z.object({
  results: z.string().register(z.globalRegistry, {
    description: "Results from the model",
  }),
});

/**
 * ImageInput
 */
export const zFlorence2LargeMoreDetailedCaptionInput = z.object({
  image_url: z.string().register(z.globalRegistry, {
    description: "The URL of the image to be processed.",
  }),
});

/**
 * TextOutput
 */
export const zFlorence2LargeMoreDetailedCaptionOutput = z.object({
  results: z.string().register(z.globalRegistry, {
    description: "Results from the model",
  }),
});

/**
 * ImageInput
 */
export const zFlorence2LargeOcrInput = z.object({
  image_url: z.string().register(z.globalRegistry, {
    description: "The URL of the image to be processed.",
  }),
});

/**
 * TextOutput
 */
export const zFlorence2LargeOcrOutput = z.object({
  results: z.string().register(z.globalRegistry, {
    description: "Results from the model",
  }),
});

/**
 * TextOutput
 */
export const zFlorence2LargeRegionToCategoryOutput = z.object({
  results: z.string().register(z.globalRegistry, {
    description: "Results from the model",
  }),
});

/**
 * TextOutput
 */
export const zFlorence2LargeRegionToDescriptionOutput = z.object({
  results: z.string().register(z.globalRegistry, {
    description: "Results from the model",
  }),
});

/**
 * ImageInput
 */
export const zGotOcrV2Input = z.object({
  input_image_urls: z
    .array(z.string())
    .register(z.globalRegistry, {
      description: "URL of images.",
    })
    .optional()
    .default([]),
  multi_page: z
    .boolean()
    .register(z.globalRegistry, {
      description: "Use provided images to generate a single output.",
    })
    .optional()
    .default(false),
  do_format: z
    .boolean()
    .register(z.globalRegistry, {
      description: "Generate the output in formatted mode.",
    })
    .optional()
    .default(false),
});

/**
 * ImageChatOutput
 */
export const zGotOcrV2Output = z.object({
  outputs: z.array(z.string()).register(z.globalRegistry, {
    description: "Generated output",
  }),
});

/**
 * Image
 *
 * Represents an image file.
 */
export const zImage = z
  .object({
    width: z.union([z.int(), z.unknown()]).optional(),
    file_name: z.union([z.string(), z.unknown()]).optional(),
    url: z.string().register(z.globalRegistry, {
      description: "The URL where the file can be downloaded from.",
    }),
    height: z.union([z.int(), z.unknown()]).optional(),
    file_size: z.union([z.int(), z.unknown()]).optional(),
    content_type: z.union([z.string(), z.unknown()]).optional(),
  })
  .register(z.globalRegistry, {
    description: "Represents an image file.",
  });

/**
 * ImageFile
 */
export const zImageFile = z.object({
  file_size: z.union([z.int(), z.unknown()]).optional(),
  file_name: z.union([z.string(), z.unknown()]).optional(),
  content_type: z.union([z.string(), z.unknown()]).optional(),
  height: z.union([z.int(), z.unknown()]).optional(),
  width: z.union([z.int(), z.unknown()]).optional(),
  url: z.string().register(z.globalRegistry, {
    description: "The URL where the file can be downloaded from.",
  }),
});

/**
 * ImageInput
 */
export const zImageInput = z.object({
  hypothesis: z.string().register(z.globalRegistry, {
    description: "The image to use for the measurement.",
  }),
});

/**
 * ImageMultiMeasurementInput
 */
export const zArbiterImageInput = z.object({
  inputs: z.array(zImageInput).register(z.globalRegistry, {
    description: "The inputs to use for the measurement.",
  }),
  measurements: z
    .array(z.enum(["arniqa", "clip_iqa", "musiq", "nima", "lapvar"]))
    .register(z.globalRegistry, {
      description: "The measurements to use for the measurement.",
    }),
});

/**
 * NSFWImageDetectionInput
 */
export const zImageutilsNsfwInput = z.object({
  image_url: z.string().register(z.globalRegistry, {
    description: "Input image url.",
  }),
});

/**
 * NSFWImageDetectionOutput
 */
export const zImageutilsNsfwOutput = z.object({
  nsfw_probability: z.number().register(z.globalRegistry, {
    description: "The probability of the image being NSFW.",
  }),
});

/**
 * VisionInput
 */
export const zIsaac01Input = z.object({
  prompt: z.string().register(z.globalRegistry, {
    description: "Prompt to be used for the image",
  }),
  response_style: z
    .enum(["text", "box", "point", "polygon"])
    .register(z.globalRegistry, {
      description:
        "\nResponse style to be used for the image.\n\n- text: Model will output text. Good for descriptions and captioning.\n- box: Model will output a combination of text and bounding boxes. Good for\nlocalization.\n- point: Model will output a combination of text and points. Good for counting many\nobjects.\n- polygon: Model will output a combination of text and polygons. Good for granular\nsegmentation.\n",
    })
    .optional()
    .default("text"),
  image_url: z.string().register(z.globalRegistry, {
    description: "Image URL to be processed",
  }),
});

/**
 * Schema referenced but not defined by fal.ai (missing from source OpenAPI spec)
 */
export const zIsaac01OpenaiV1ChatCompletionsInput = z
  .record(z.string(), z.unknown())
  .register(z.globalRegistry, {
    description:
      "Schema referenced but not defined by fal.ai (missing from source OpenAPI spec)",
  });

export const zIsaac01OpenaiV1ChatCompletionsOutput = z.unknown();

/**
 * ChatOutput
 */
export const zIsaac01Output = z.object({
  usage: z.union([zCompletionUsage, z.unknown()]).optional(),
  error: z.union([z.string(), z.unknown()]).optional(),
  partial: z
    .boolean()
    .register(z.globalRegistry, {
      description: "Whether the output is partial",
    })
    .optional()
    .default(false),
  output: z.string().register(z.globalRegistry, {
    description: "Generated output",
  }),
});

/**
 * LLavaInput
 */
export const zLlavaNextInput = z.object({
  prompt: z.string().register(z.globalRegistry, {
    description: "Prompt to be used for the image",
  }),
  top_p: z
    .number()
    .gte(0)
    .lte(1)
    .register(z.globalRegistry, {
      description: "Top P for sampling",
    })
    .optional()
    .default(1),
  temperature: z
    .number()
    .lte(1)
    .register(z.globalRegistry, {
      description: "Temperature for sampling",
    })
    .optional()
    .default(0.2),
  max_tokens: z
    .int()
    .register(z.globalRegistry, {
      description: "Maximum number of tokens to generate",
    })
    .optional()
    .default(64),
  image_url: z.string().register(z.globalRegistry, {
    description: "URL of the image to be processed",
  }),
});

/**
 * LLavaOutput
 */
export const zLlavaNextOutput = z.object({
  output: z.string().register(z.globalRegistry, {
    description: "Generated output",
  }),
  partial: z
    .boolean()
    .register(z.globalRegistry, {
      description: "Whether the output is partial",
    })
    .optional()
    .default(false),
});

/**
 * MoondreamInput
 */
export const zMoondream2Input = z.object({
  image_url: z.string().register(z.globalRegistry, {
    description: "URL of the image to be processed",
  }),
});

/**
 * MoondreamObjectInput
 */
export const zMoondream2ObjectDetectionInput = z.object({
  object: z.string().register(z.globalRegistry, {
    description: "Object to be detected in the image",
  }),
  image_url: z.string().register(z.globalRegistry, {
    description: "URL of the image to be processed",
  }),
});

/**
 * MoondreamObjectOutput
 */
export const zMoondream2ObjectDetectionOutput = z.object({
  image: zImage,
  objects: z
    .array(z.record(z.string(), z.unknown()))
    .register(z.globalRegistry, {
      description: "Objects detected in the image",
    }),
});

/**
 * MoondreamOutput
 */
export const zMoondream2Output = z.object({
  output: z.string().register(z.globalRegistry, {
    description: "Output for the given query",
  }),
});

/**
 * MoondreamObjectInput
 */
export const zMoondream2PointObjectDetectionInput = z.object({
  object: z.string().register(z.globalRegistry, {
    description: "Object to be detected in the image",
  }),
  image_url: z.string().register(z.globalRegistry, {
    description: "URL of the image to be processed",
  }),
});

/**
 * MoondreamObjectOutput
 */
export const zMoondream2PointObjectDetectionOutput = z.object({
  image: zImage,
  objects: z
    .array(z.record(z.string(), z.unknown()))
    .register(z.globalRegistry, {
      description: "Objects detected in the image",
    }),
});

/**
 * MoondreamQueryInput
 */
export const zMoondream2VisualQueryInput = z.object({
  prompt: z.string().register(z.globalRegistry, {
    description: "Query to be asked in the image",
  }),
  image_url: z.string().register(z.globalRegistry, {
    description: "URL of the image to be processed",
  }),
});

/**
 * MoondreamOutput
 */
export const zMoondream2VisualQueryOutput = z.object({
  output: z.string().register(z.globalRegistry, {
    description: "Output for the given query",
  }),
});

/**
 * MoondreamCaptionInput
 */
export const zMoondream3PreviewCaptionInput = z.object({
  image_url: z.string().register(z.globalRegistry, {
    description: "URL of the image to be processed",
  }),
  top_p: z.union([z.number().gte(0).lte(1), z.unknown()]).optional(),
  temperature: z.union([z.number().gte(0).lte(1), z.unknown()]).optional(),
  length: z
    .enum(["short", "normal", "long"])
    .register(z.globalRegistry, {
      description: "Length of the caption to generate",
    })
    .optional()
    .default("normal"),
});

/**
 * MoondreamDetectInput
 */
export const zMoondream3PreviewDetectInput = z.object({
  image_url: z.string().register(z.globalRegistry, {
    description: "URL of the image to be processed",
  }),
  preview: z
    .boolean()
    .register(z.globalRegistry, {
      description: "Whether to preview the output",
    })
    .optional()
    .default(false),
  prompt: z.string().min(1).register(z.globalRegistry, {
    description: "Object to be detected in the image",
  }),
});

/**
 * MoondreamPointInput
 */
export const zMoondream3PreviewPointInput = z.object({
  image_url: z.string().register(z.globalRegistry, {
    description: "URL of the image to be processed",
  }),
  preview: z
    .boolean()
    .register(z.globalRegistry, {
      description: "Whether to preview the output",
    })
    .optional()
    .default(false),
  prompt: z.string().min(1).register(z.globalRegistry, {
    description: "Object to be located in the image",
  }),
});

/**
 * MoondreamQueryInput
 */
export const zMoondream3PreviewQueryInput = z.object({
  image_url: z.string().register(z.globalRegistry, {
    description: "URL of the image to be processed",
  }),
  top_p: z.union([z.number().gte(0).lte(1), z.unknown()]).optional(),
  reasoning: z
    .boolean()
    .register(z.globalRegistry, {
      description: "Whether to include detailed reasoning behind the answer",
    })
    .optional()
    .default(true),
  prompt: z.string().min(1).register(z.globalRegistry, {
    description: "Query to be asked in the image",
  }),
  temperature: z.union([z.number().gte(0).lte(1), z.unknown()]).optional(),
});

/**
 * BatchedMoondreamOutput
 */
export const zMoondreamBatchedOutput = z.object({
  partial: z
    .boolean()
    .register(z.globalRegistry, {
      description: "Whether the output is partial",
    })
    .optional()
    .default(false),
  filenames: z.union([z.array(z.string()), z.unknown()]).nullish(),
  outputs: z.array(z.string()).register(z.globalRegistry, {
    description: "List of generated outputs",
  }),
  timings: z.record(z.string(), z.number()).register(z.globalRegistry, {
    description: "Timings for different parts of the process",
  }),
});

/**
 * MoondreamInputParam
 */
export const zMoondreamInputParam = z.object({
  image_url: z.string().register(z.globalRegistry, {
    description: "URL of the image to be processed",
  }),
  prompt: z
    .string()
    .register(z.globalRegistry, {
      description: "Prompt to be used for the image",
    })
    .optional()
    .default("Describe this image."),
});

/**
 * BatchedMoondreamInput
 */
export const zMoondreamBatchedInput = z.object({
  max_tokens: z
    .int()
    .gte(32)
    .lte(1024)
    .register(z.globalRegistry, {
      description: "Maximum number of new tokens to generate",
    })
    .optional()
    .default(64),
  top_p: z
    .number()
    .gte(0)
    .lte(1)
    .register(z.globalRegistry, {
      description: "Top P for sampling",
    })
    .optional()
    .default(1),
  inputs: z.array(zMoondreamInputParam).register(z.globalRegistry, {
    description: "List of input prompts and image URLs",
  }),
  temperature: z
    .number()
    .lte(1)
    .register(z.globalRegistry, {
      description: "Temperature for sampling",
    })
    .optional()
    .default(0.2),
  model_id: z
    .enum(["vikhyatk/moondream2", "fal-ai/moondream2-docci"])
    .register(z.globalRegistry, {
      description: "Model ID to use for inference",
    })
    .optional()
    .default("vikhyatk/moondream2"),
  repetition_penalty: z
    .number()
    .gte(1)
    .lte(2)
    .register(z.globalRegistry, {
      description: "Repetition penalty for sampling",
    })
    .optional()
    .default(1),
});

/**
 * BatchQueryInput
 */
export const zMoondreamNextBatchInput = z.object({
  images_data_url: z.string().register(z.globalRegistry, {
    description: "List of image URLs to be processed (maximum 32 images)",
  }),
  prompt: z.string().register(z.globalRegistry, {
    description: "Single prompt to apply to all images",
  }),
  max_tokens: z
    .int()
    .gte(1)
    .lte(512)
    .register(z.globalRegistry, {
      description: "Maximum number of tokens to generate",
    })
    .optional()
    .default(64),
});

/**
 * BatchMoonDreamOutput
 */
export const zMoondreamNextBatchOutput = z.object({
  captions_file: zFile,
  outputs: z.array(z.string()).register(z.globalRegistry, {
    description: "List of generated captions",
  }),
});

/**
 * QueryInput
 */
export const zMoondreamNextInput = z.object({
  image_url: z.string().register(z.globalRegistry, {
    description: "Image URL to be processed",
  }),
  task_type: z
    .enum(["caption", "query"])
    .register(z.globalRegistry, {
      description: "Type of task to perform",
    })
    .optional()
    .default("caption"),
  prompt: z.string().register(z.globalRegistry, {
    description: "Prompt for query task",
  }),
  max_tokens: z
    .int()
    .gte(1)
    .lte(512)
    .register(z.globalRegistry, {
      description: "Maximum number of tokens to generate",
    })
    .optional()
    .default(64),
});

/**
 * MoonDreamOutput
 */
export const zMoondreamNextOutput = z.object({
  output: z.string().register(z.globalRegistry, {
    description: "Response from the model",
  }),
});

/**
 * Object
 */
export const zObject = z.object({
  x_max: z.number().register(z.globalRegistry, {
    description:
      "Right boundary of detection box in normalized format (0 to 1)",
  }),
  y_max: z.number().register(z.globalRegistry, {
    description:
      "Bottom boundary of detection box in normalized format (0 to 1)",
  }),
  x_min: z.number().register(z.globalRegistry, {
    description: "Left boundary of detection box in normalized format (0 to 1)",
  }),
  y_min: z.number().register(z.globalRegistry, {
    description: "Top boundary of detection box in normalized format (0 to 1)",
  }),
});

/**
 * Point
 */
export const zPoint = z.object({
  y: z.number().register(z.globalRegistry, {
    description: "Y coordinate of the point in normalized format (0 to 1)",
  }),
  x: z.number().register(z.globalRegistry, {
    description: "X coordinate of the point in normalized format (0 to 1)",
  }),
});

/**
 * PromptTokensDetails
 */
export const zPromptTokensDetails = z.object({
  cache_write_tokens: z.int().optional().default(0),
  cached_tokens: z.int().optional().default(0),
});

export const zQueueStatus = z.object({
  status: z.enum(["IN_QUEUE", "IN_PROGRESS", "COMPLETED"]),
  request_id: z.string().register(z.globalRegistry, {
    description: "The request id.",
  }),
  response_url: z
    .string()
    .register(z.globalRegistry, {
      description: "The response url.",
    })
    .optional(),
  status_url: z
    .string()
    .register(z.globalRegistry, {
      description: "The status url.",
    })
    .optional(),
  cancel_url: z
    .string()
    .register(z.globalRegistry, {
      description: "The cancel url.",
    })
    .optional(),
  logs: z
    .record(z.string(), z.unknown())
    .register(z.globalRegistry, {
      description: "The logs.",
    })
    .optional(),
  metrics: z
    .record(z.string(), z.unknown())
    .register(z.globalRegistry, {
      description: "The metrics.",
    })
    .optional(),
  queue_position: z
    .int()
    .register(z.globalRegistry, {
      description: "The queue position.",
    })
    .optional(),
});

/**
 * ReferenceImageInput
 */
export const zReferenceImageInput = z.object({
  hypothesis: z.string().register(z.globalRegistry, {
    description: "The hypothesis image to use for the measurement.",
  }),
  reference: z.string().register(z.globalRegistry, {
    description: "The image to use for the measurement.",
  }),
});

/**
 * ImageReferenceMeasurementInput
 */
export const zArbiterImageImageInput = z.object({
  inputs: z.array(zReferenceImageInput).register(z.globalRegistry, {
    description: "The inputs to use for the measurement.",
  }),
  measurements: z
    .array(z.enum(["dists", "mse", "lpips", "sdi", "ssim"]))
    .register(z.globalRegistry, {
      description: "The measurements to use for the measurement.",
    }),
});

/**
 * Region
 */
export const zRegion = z.object({
  y1: z.int().gte(0).lte(999).register(z.globalRegistry, {
    description: "Y-coordinate of the top-left corner",
  }),
  x1: z.int().gte(0).lte(999).register(z.globalRegistry, {
    description: "X-coordinate of the top-left corner",
  }),
  y2: z.int().gte(0).lte(999).register(z.globalRegistry, {
    description: "Y-coordinate of the bottom-right corner",
  }),
  x2: z.int().gte(0).lte(999).register(z.globalRegistry, {
    description: "X-coordinate of the bottom-right corner",
  }),
});

/**
 * ImageWithUserCoordinatesInput
 */
export const zFlorence2LargeRegionToCategoryInput = z.object({
  image_url: z.string().register(z.globalRegistry, {
    description: "The URL of the image to be processed.",
  }),
  region: zRegion,
});

/**
 * ImageWithUserCoordinatesInput
 */
export const zFlorence2LargeRegionToDescriptionInput = z.object({
  image_url: z.string().register(z.globalRegistry, {
    description: "The URL of the image to be processed.",
  }),
  region: zRegion,
});

/**
 * VisionInput
 */
export const zRouterVisionInput = z.object({
  image_urls: z.array(z.string()).register(z.globalRegistry, {
    description: "List of image URLs to be processed",
  }),
  temperature: z
    .number()
    .gte(0)
    .lte(2)
    .register(z.globalRegistry, {
      description:
        "This setting influences the variety in the model's responses. Lower values lead to more predictable and typical responses, while higher values encourage more diverse and less common responses. At 0, the model always gives the same response for a given input.",
    })
    .optional()
    .default(1),
  max_tokens: z.union([z.int().gte(1), z.unknown()]).optional(),
  reasoning: z
    .boolean()
    .register(z.globalRegistry, {
      description: "Should reasoning be the part of the final answer.",
    })
    .optional()
    .default(false),
  prompt: z.string().register(z.globalRegistry, {
    description: "Prompt to be used for the image",
  }),
  model: z.string().register(z.globalRegistry, {
    description:
      "Name of the model to use. Charged based on actual token usage.",
  }),
  system_prompt: z.union([z.string(), z.unknown()]).optional(),
});

/**
 * ImageInput
 */
export const zSa2Va4bImageInput = z.object({
  prompt: z.string().register(z.globalRegistry, {
    description: "Prompt to be used for the chat completion",
  }),
  image_url: z.string().register(z.globalRegistry, {
    description: "Url for the Input image.",
  }),
});

/**
 * ImageChatOutput
 */
export const zSa2Va4bImageOutput = z.object({
  masks: z.array(zImage).register(z.globalRegistry, {
    description: "Dictionary of label: mask image",
  }),
  output: z.string().register(z.globalRegistry, {
    description: "Generated output",
  }),
});

/**
 * VideoInput
 */
export const zSa2Va4bVideoInput = z.object({
  num_frames_to_sample: z
    .union([z.int().gte(5).lte(100), z.unknown()])
    .optional(),
  prompt: z.string().register(z.globalRegistry, {
    description: "Prompt to be used for the chat completion",
  }),
  video_url: z.string().register(z.globalRegistry, {
    description: "The URL of the input video.",
  }),
});

/**
 * VideoChatOutput
 */
export const zSa2Va4bVideoOutput = z.object({
  masks: z.array(zFile).register(z.globalRegistry, {
    description: "Dictionary of label: mask video",
  }),
  output: z.string().register(z.globalRegistry, {
    description: "Generated output",
  }),
});

/**
 * ImageInput
 */
export const zSa2Va8bImageInput = z.object({
  prompt: z.string().register(z.globalRegistry, {
    description: "Prompt to be used for the chat completion",
  }),
  image_url: z.string().register(z.globalRegistry, {
    description: "Url for the Input image.",
  }),
});

/**
 * ImageChatOutput
 */
export const zSa2Va8bImageOutput = z.object({
  masks: z.array(zImage).register(z.globalRegistry, {
    description: "Dictionary of label: mask image",
  }),
  output: z.string().register(z.globalRegistry, {
    description: "Generated output",
  }),
});

/**
 * VideoInput
 */
export const zSa2Va8bVideoInput = z.object({
  num_frames_to_sample: z
    .union([z.int().gte(5).lte(100), z.unknown()])
    .optional(),
  prompt: z.string().register(z.globalRegistry, {
    description: "Prompt to be used for the chat completion",
  }),
  video_url: z.string().register(z.globalRegistry, {
    description: "The URL of the input video.",
  }),
});

/**
 * VideoChatOutput
 */
export const zSa2Va8bVideoOutput = z.object({
  masks: z.array(zFile).register(z.globalRegistry, {
    description: "Dictionary of label: mask video",
  }),
  output: z.string().register(z.globalRegistry, {
    description: "Generated output",
  }),
});

/**
 * SAM3EmbeddingInput
 */
export const zSam3ImageEmbedInput = z.object({
  image_url: z.string().register(z.globalRegistry, {
    description: "URL of the image to embed.",
  }),
});

/**
 * SAM3EmbeddingOutput
 */
export const zSam3ImageEmbedOutput = z.object({
  embedding_b64: z.string().register(z.globalRegistry, {
    description: "Embedding of the image",
  }),
});

/**
 * SemanticImageInput
 */
export const zSemanticImageInput = z.object({
  hypothesis: z.string().register(z.globalRegistry, {
    description: "The hypothesis image to use for the measurement.",
  }),
  reference: z.string().register(z.globalRegistry, {
    description: "The text reference to use for the measurement.",
  }),
});

/**
 * SemanticImageMeasurementInput
 */
export const zArbiterImageTextInput = z.object({
  inputs: z.array(zSemanticImageInput).register(z.globalRegistry, {
    description: "The inputs to use for the measurement.",
  }),
  measurements: z.array(z.string()).register(z.globalRegistry, {
    description: "The measurements to use for the measurement.",
  }),
});

/**
 * UsageInfo
 */
export const zUsageInfo = z.object({
  prefill_time_ms: z.number().register(z.globalRegistry, {
    description: "Time taken for prefill in milliseconds",
  }),
  input_tokens: z.int().register(z.globalRegistry, {
    description: "Number of input tokens processed",
  }),
  output_tokens: z.int().register(z.globalRegistry, {
    description: "Number of output tokens generated",
  }),
  ttft_ms: z.number().register(z.globalRegistry, {
    description: "Time to first token in milliseconds",
  }),
  decode_time_ms: z.number().register(z.globalRegistry, {
    description: "Time taken for decoding in milliseconds",
  }),
});

/**
 * MoondreamCaptionOutput
 */
export const zMoondream3PreviewCaptionOutput = z.object({
  usage_info: zUsageInfo,
  finish_reason: z.string().register(z.globalRegistry, {
    description: "Reason for finishing the output generation",
  }),
  output: z.string().register(z.globalRegistry, {
    description: "Generated caption for the image",
  }),
});

/**
 * MoondreamDetectOutput
 */
export const zMoondream3PreviewDetectOutput = z.object({
  usage_info: zUsageInfo,
  finish_reason: z.string().register(z.globalRegistry, {
    description: "Reason for finishing the output generation",
  }),
  image: z.union([zImageFile, z.unknown()]).optional(),
  objects: z.array(zObject).register(z.globalRegistry, {
    description: "List of detected objects with their bounding boxes",
  }),
});

/**
 * MoondreamPointOutput
 */
export const zMoondream3PreviewPointOutput = z.object({
  usage_info: zUsageInfo,
  finish_reason: z.string().register(z.globalRegistry, {
    description: "Reason for finishing the output generation",
  }),
  points: z.array(zPoint).register(z.globalRegistry, {
    description: "List of points marking the detected objects",
  }),
  image: z.union([zImageFile, z.unknown()]).optional(),
});

/**
 * MoondreamQueryOutput
 */
export const zMoondream3PreviewQueryOutput = z.object({
  usage_info: zUsageInfo,
  finish_reason: z.string().register(z.globalRegistry, {
    description: "Reason for finishing the output generation",
  }),
  reasoning: z.union([z.string(), z.unknown()]).optional(),
  output: z.string().register(z.globalRegistry, {
    description: "Answer to the query about the image",
  }),
});

/**
 * UsageInfo
 */
export const zUsageInfoType2 = z.object({
  prompt_tokens: z.union([z.int(), z.unknown()]).optional(),
  prompt_tokens_details: z
    .union([zPromptTokensDetails, z.unknown()])
    .optional(),
  total_tokens: z.int().optional().default(0),
  cost: z.number(),
  completion_tokens: z.union([z.int(), z.unknown()]).optional(),
});

/**
 * VisionOutput
 */
export const zRouterVisionOutput = z.object({
  usage: z.union([zUsageInfoType2, z.unknown()]),
  output: z.string().register(z.globalRegistry, {
    description: "Generated output",
  }),
});

/**
 * VideoUnderstandingInput
 */
export const zVideoUnderstandingInput = z.object({
  prompt: z.string().min(1).max(5000).register(z.globalRegistry, {
    description: "The question or prompt about the video content.",
  }),
  video_url: z.string().register(z.globalRegistry, {
    description: "URL of the video to analyze",
  }),
  detailed_analysis: z
    .boolean()
    .register(z.globalRegistry, {
      description: "Whether to request a more detailed analysis of the video",
    })
    .optional()
    .default(false),
});

/**
 * VideoUnderstandingOutput
 */
export const zVideoUnderstandingOutput = z.object({
  output: z.string().register(z.globalRegistry, {
    description: "The analysis of the video content based on the prompt",
  }),
});

/**
 * NSFWInput
 */
export const zXAilabNsfwInput = z.object({
  image_urls: z.array(z.string()).register(z.globalRegistry, {
    description:
      "List of image URLs to check. If more than 10 images are provided, only the first 10 will be checked.",
  }),
});

/**
 * NSFWOutput
 */
export const zXAilabNsfwOutput = z.object({
  has_nsfw_concepts: z.array(z.boolean()).register(z.globalRegistry, {
    description: "List of booleans indicating if the image has an NSFW concept",
  }),
});

export const zPostFalAiArbiterImageBody = zArbiterImageInput;

/**
 * The request status.
 */
export const zPostFalAiArbiterImageResponse = zQueueStatus;

export const zPostFalAiArbiterImageImageBody = zArbiterImageImageInput;

/**
 * The request status.
 */
export const zPostFalAiArbiterImageImageResponse = zQueueStatus;

export const zGetFalAiArbiterImageImageRequestsByRequestIdPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * Result of the request.
 */
export const zGetFalAiArbiterImageImageRequestsByRequestIdResponse =
  zArbiterImageImageOutput;

export const zPutFalAiArbiterImageImageRequestsByRequestIdCancelPath = z.object(
  {
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  },
);

/**
 * The request was cancelled.
 */
export const zPutFalAiArbiterImageImageRequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zGetFalAiArbiterImageImageRequestsByRequestIdStatusPath = z.object(
  {
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  },
);

export const zGetFalAiArbiterImageImageRequestsByRequestIdStatusQuery =
  z.object({
    logs: z
      .number()
      .register(z.globalRegistry, {
        description:
          "Whether to include logs (`1`) in the response or not (`0`).",
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiArbiterImageImageRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zGetFalAiArbiterImageRequestsByRequestIdPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * Result of the request.
 */
export const zGetFalAiArbiterImageRequestsByRequestIdResponse =
  zArbiterImageOutput;

export const zPutFalAiArbiterImageRequestsByRequestIdCancelPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * The request was cancelled.
 */
export const zPutFalAiArbiterImageRequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zGetFalAiArbiterImageRequestsByRequestIdStatusPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

export const zGetFalAiArbiterImageRequestsByRequestIdStatusQuery = z.object({
  logs: z
    .number()
    .register(z.globalRegistry, {
      description:
        "Whether to include logs (`1`) in the response or not (`0`).",
    })
    .optional(),
});

/**
 * The request status.
 */
export const zGetFalAiArbiterImageRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiArbiterImageTextBody = zArbiterImageTextInput;

/**
 * The request status.
 */
export const zPostFalAiArbiterImageTextResponse = zQueueStatus;

export const zGetFalAiArbiterImageTextRequestsByRequestIdPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * Result of the request.
 */
export const zGetFalAiArbiterImageTextRequestsByRequestIdResponse =
  zArbiterImageTextOutput;

export const zPutFalAiArbiterImageTextRequestsByRequestIdCancelPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * The request was cancelled.
 */
export const zPutFalAiArbiterImageTextRequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zGetFalAiArbiterImageTextRequestsByRequestIdStatusPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

export const zGetFalAiArbiterImageTextRequestsByRequestIdStatusQuery = z.object(
  {
    logs: z
      .number()
      .register(z.globalRegistry, {
        description:
          "Whether to include logs (`1`) in the response or not (`0`).",
      })
      .optional(),
  },
);

/**
 * The request status.
 */
export const zGetFalAiArbiterImageTextRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiFlorence2LargeCaptionBody = zFlorence2LargeCaptionInput;

/**
 * The request status.
 */
export const zPostFalAiFlorence2LargeCaptionResponse = zQueueStatus;

export const zGetFalAiFlorence2LargeCaptionRequestsByRequestIdPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * Result of the request.
 */
export const zGetFalAiFlorence2LargeCaptionRequestsByRequestIdResponse =
  zFlorence2LargeCaptionOutput;

export const zPutFalAiFlorence2LargeCaptionRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * The request was cancelled.
 */
export const zPutFalAiFlorence2LargeCaptionRequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zGetFalAiFlorence2LargeCaptionRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

export const zGetFalAiFlorence2LargeCaptionRequestsByRequestIdStatusQuery =
  z.object({
    logs: z
      .number()
      .register(z.globalRegistry, {
        description:
          "Whether to include logs (`1`) in the response or not (`0`).",
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiFlorence2LargeCaptionRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiFlorence2LargeDetailedCaptionBody =
  zFlorence2LargeDetailedCaptionInput;

/**
 * The request status.
 */
export const zPostFalAiFlorence2LargeDetailedCaptionResponse = zQueueStatus;

export const zGetFalAiFlorence2LargeDetailedCaptionRequestsByRequestIdPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * Result of the request.
 */
export const zGetFalAiFlorence2LargeDetailedCaptionRequestsByRequestIdResponse =
  zFlorence2LargeDetailedCaptionOutput;

export const zPutFalAiFlorence2LargeDetailedCaptionRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * The request was cancelled.
 */
export const zPutFalAiFlorence2LargeDetailedCaptionRequestsByRequestIdCancelResponse =
  z
    .object({
      success: z
        .boolean()
        .register(z.globalRegistry, {
          description: "Whether the request was cancelled successfully.",
        })
        .optional(),
    })
    .register(z.globalRegistry, {
      description: "The request was cancelled.",
    });

export const zGetFalAiFlorence2LargeDetailedCaptionRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

export const zGetFalAiFlorence2LargeDetailedCaptionRequestsByRequestIdStatusQuery =
  z.object({
    logs: z
      .number()
      .register(z.globalRegistry, {
        description:
          "Whether to include logs (`1`) in the response or not (`0`).",
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiFlorence2LargeDetailedCaptionRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiFlorence2LargeMoreDetailedCaptionBody =
  zFlorence2LargeMoreDetailedCaptionInput;

/**
 * The request status.
 */
export const zPostFalAiFlorence2LargeMoreDetailedCaptionResponse = zQueueStatus;

export const zGetFalAiFlorence2LargeMoreDetailedCaptionRequestsByRequestIdPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * Result of the request.
 */
export const zGetFalAiFlorence2LargeMoreDetailedCaptionRequestsByRequestIdResponse =
  zFlorence2LargeMoreDetailedCaptionOutput;

export const zPutFalAiFlorence2LargeMoreDetailedCaptionRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * The request was cancelled.
 */
export const zPutFalAiFlorence2LargeMoreDetailedCaptionRequestsByRequestIdCancelResponse =
  z
    .object({
      success: z
        .boolean()
        .register(z.globalRegistry, {
          description: "Whether the request was cancelled successfully.",
        })
        .optional(),
    })
    .register(z.globalRegistry, {
      description: "The request was cancelled.",
    });

export const zGetFalAiFlorence2LargeMoreDetailedCaptionRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

export const zGetFalAiFlorence2LargeMoreDetailedCaptionRequestsByRequestIdStatusQuery =
  z.object({
    logs: z
      .number()
      .register(z.globalRegistry, {
        description:
          "Whether to include logs (`1`) in the response or not (`0`).",
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiFlorence2LargeMoreDetailedCaptionRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiFlorence2LargeOcrBody = zFlorence2LargeOcrInput;

/**
 * The request status.
 */
export const zPostFalAiFlorence2LargeOcrResponse = zQueueStatus;

export const zGetFalAiFlorence2LargeOcrRequestsByRequestIdPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * Result of the request.
 */
export const zGetFalAiFlorence2LargeOcrRequestsByRequestIdResponse =
  zFlorence2LargeOcrOutput;

export const zPutFalAiFlorence2LargeOcrRequestsByRequestIdCancelPath = z.object(
  {
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  },
);

/**
 * The request was cancelled.
 */
export const zPutFalAiFlorence2LargeOcrRequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zGetFalAiFlorence2LargeOcrRequestsByRequestIdStatusPath = z.object(
  {
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  },
);

export const zGetFalAiFlorence2LargeOcrRequestsByRequestIdStatusQuery =
  z.object({
    logs: z
      .number()
      .register(z.globalRegistry, {
        description:
          "Whether to include logs (`1`) in the response or not (`0`).",
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiFlorence2LargeOcrRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiFlorence2LargeRegionToCategoryBody =
  zFlorence2LargeRegionToCategoryInput;

/**
 * The request status.
 */
export const zPostFalAiFlorence2LargeRegionToCategoryResponse = zQueueStatus;

export const zGetFalAiFlorence2LargeRegionToCategoryRequestsByRequestIdPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * Result of the request.
 */
export const zGetFalAiFlorence2LargeRegionToCategoryRequestsByRequestIdResponse =
  zFlorence2LargeRegionToCategoryOutput;

export const zPutFalAiFlorence2LargeRegionToCategoryRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * The request was cancelled.
 */
export const zPutFalAiFlorence2LargeRegionToCategoryRequestsByRequestIdCancelResponse =
  z
    .object({
      success: z
        .boolean()
        .register(z.globalRegistry, {
          description: "Whether the request was cancelled successfully.",
        })
        .optional(),
    })
    .register(z.globalRegistry, {
      description: "The request was cancelled.",
    });

export const zGetFalAiFlorence2LargeRegionToCategoryRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

export const zGetFalAiFlorence2LargeRegionToCategoryRequestsByRequestIdStatusQuery =
  z.object({
    logs: z
      .number()
      .register(z.globalRegistry, {
        description:
          "Whether to include logs (`1`) in the response or not (`0`).",
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiFlorence2LargeRegionToCategoryRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiFlorence2LargeRegionToDescriptionBody =
  zFlorence2LargeRegionToDescriptionInput;

/**
 * The request status.
 */
export const zPostFalAiFlorence2LargeRegionToDescriptionResponse = zQueueStatus;

export const zGetFalAiFlorence2LargeRegionToDescriptionRequestsByRequestIdPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * Result of the request.
 */
export const zGetFalAiFlorence2LargeRegionToDescriptionRequestsByRequestIdResponse =
  zFlorence2LargeRegionToDescriptionOutput;

export const zPutFalAiFlorence2LargeRegionToDescriptionRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * The request was cancelled.
 */
export const zPutFalAiFlorence2LargeRegionToDescriptionRequestsByRequestIdCancelResponse =
  z
    .object({
      success: z
        .boolean()
        .register(z.globalRegistry, {
          description: "Whether the request was cancelled successfully.",
        })
        .optional(),
    })
    .register(z.globalRegistry, {
      description: "The request was cancelled.",
    });

export const zGetFalAiFlorence2LargeRegionToDescriptionRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

export const zGetFalAiFlorence2LargeRegionToDescriptionRequestsByRequestIdStatusQuery =
  z.object({
    logs: z
      .number()
      .register(z.globalRegistry, {
        description:
          "Whether to include logs (`1`) in the response or not (`0`).",
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiFlorence2LargeRegionToDescriptionRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiGotOcrV2Body = zGotOcrV2Input;

/**
 * The request status.
 */
export const zPostFalAiGotOcrV2Response = zQueueStatus;

export const zGetFalAiGotOcrV2RequestsByRequestIdPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * Result of the request.
 */
export const zGetFalAiGotOcrV2RequestsByRequestIdResponse = zGotOcrV2Output;

export const zPutFalAiGotOcrV2RequestsByRequestIdCancelPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * The request was cancelled.
 */
export const zPutFalAiGotOcrV2RequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zGetFalAiGotOcrV2RequestsByRequestIdStatusPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

export const zGetFalAiGotOcrV2RequestsByRequestIdStatusQuery = z.object({
  logs: z
    .number()
    .register(z.globalRegistry, {
      description:
        "Whether to include logs (`1`) in the response or not (`0`).",
    })
    .optional(),
});

/**
 * The request status.
 */
export const zGetFalAiGotOcrV2RequestsByRequestIdStatusResponse = zQueueStatus;

export const zPostFalAiImageutilsNsfwBody = zImageutilsNsfwInput;

/**
 * The request status.
 */
export const zPostFalAiImageutilsNsfwResponse = zQueueStatus;

export const zGetFalAiImageutilsNsfwRequestsByRequestIdPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * Result of the request.
 */
export const zGetFalAiImageutilsNsfwRequestsByRequestIdResponse =
  zImageutilsNsfwOutput;

export const zPutFalAiImageutilsNsfwRequestsByRequestIdCancelPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * The request was cancelled.
 */
export const zPutFalAiImageutilsNsfwRequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zGetFalAiImageutilsNsfwRequestsByRequestIdStatusPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

export const zGetFalAiImageutilsNsfwRequestsByRequestIdStatusQuery = z.object({
  logs: z
    .number()
    .register(z.globalRegistry, {
      description:
        "Whether to include logs (`1`) in the response or not (`0`).",
    })
    .optional(),
});

/**
 * The request status.
 */
export const zGetFalAiImageutilsNsfwRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiLlavaNextBody = zLlavaNextInput;

/**
 * The request status.
 */
export const zPostFalAiLlavaNextResponse = zQueueStatus;

export const zGetFalAiLlavaNextRequestsByRequestIdPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * Result of the request.
 */
export const zGetFalAiLlavaNextRequestsByRequestIdResponse = zLlavaNextOutput;

export const zPutFalAiLlavaNextRequestsByRequestIdCancelPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * The request was cancelled.
 */
export const zPutFalAiLlavaNextRequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zGetFalAiLlavaNextRequestsByRequestIdStatusPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

export const zGetFalAiLlavaNextRequestsByRequestIdStatusQuery = z.object({
  logs: z
    .number()
    .register(z.globalRegistry, {
      description:
        "Whether to include logs (`1`) in the response or not (`0`).",
    })
    .optional(),
});

/**
 * The request status.
 */
export const zGetFalAiLlavaNextRequestsByRequestIdStatusResponse = zQueueStatus;

export const zPostFalAiMoondreamNextBody = zMoondreamNextInput;

/**
 * The request status.
 */
export const zPostFalAiMoondreamNextResponse = zQueueStatus;

export const zPostFalAiMoondreamNextBatchBody = zMoondreamNextBatchInput;

/**
 * The request status.
 */
export const zPostFalAiMoondreamNextBatchResponse = zQueueStatus;

export const zGetFalAiMoondreamNextBatchRequestsByRequestIdPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * Result of the request.
 */
export const zGetFalAiMoondreamNextBatchRequestsByRequestIdResponse =
  zMoondreamNextBatchOutput;

export const zPutFalAiMoondreamNextBatchRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * The request was cancelled.
 */
export const zPutFalAiMoondreamNextBatchRequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zGetFalAiMoondreamNextBatchRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

export const zGetFalAiMoondreamNextBatchRequestsByRequestIdStatusQuery =
  z.object({
    logs: z
      .number()
      .register(z.globalRegistry, {
        description:
          "Whether to include logs (`1`) in the response or not (`0`).",
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiMoondreamNextBatchRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zGetFalAiMoondreamNextRequestsByRequestIdPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * Result of the request.
 */
export const zGetFalAiMoondreamNextRequestsByRequestIdResponse =
  zMoondreamNextOutput;

export const zPutFalAiMoondreamNextRequestsByRequestIdCancelPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * The request was cancelled.
 */
export const zPutFalAiMoondreamNextRequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zGetFalAiMoondreamNextRequestsByRequestIdStatusPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

export const zGetFalAiMoondreamNextRequestsByRequestIdStatusQuery = z.object({
  logs: z
    .number()
    .register(z.globalRegistry, {
      description:
        "Whether to include logs (`1`) in the response or not (`0`).",
    })
    .optional(),
});

/**
 * The request status.
 */
export const zGetFalAiMoondreamNextRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiMoondreamBatchedBody = zMoondreamBatchedInput;

/**
 * The request status.
 */
export const zPostFalAiMoondreamBatchedResponse = zQueueStatus;

export const zGetFalAiMoondreamBatchedRequestsByRequestIdPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * Result of the request.
 */
export const zGetFalAiMoondreamBatchedRequestsByRequestIdResponse =
  zMoondreamBatchedOutput;

export const zPutFalAiMoondreamBatchedRequestsByRequestIdCancelPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * The request was cancelled.
 */
export const zPutFalAiMoondreamBatchedRequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zGetFalAiMoondreamBatchedRequestsByRequestIdStatusPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

export const zGetFalAiMoondreamBatchedRequestsByRequestIdStatusQuery = z.object(
  {
    logs: z
      .number()
      .register(z.globalRegistry, {
        description:
          "Whether to include logs (`1`) in the response or not (`0`).",
      })
      .optional(),
  },
);

/**
 * The request status.
 */
export const zGetFalAiMoondreamBatchedRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiMoondream2Body = zMoondream2Input;

/**
 * The request status.
 */
export const zPostFalAiMoondream2Response = zQueueStatus;

export const zPostFalAiMoondream2ObjectDetectionBody =
  zMoondream2ObjectDetectionInput;

/**
 * The request status.
 */
export const zPostFalAiMoondream2ObjectDetectionResponse = zQueueStatus;

export const zGetFalAiMoondream2ObjectDetectionRequestsByRequestIdPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * Result of the request.
 */
export const zGetFalAiMoondream2ObjectDetectionRequestsByRequestIdResponse =
  zMoondream2ObjectDetectionOutput;

export const zPutFalAiMoondream2ObjectDetectionRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * The request was cancelled.
 */
export const zPutFalAiMoondream2ObjectDetectionRequestsByRequestIdCancelResponse =
  z
    .object({
      success: z
        .boolean()
        .register(z.globalRegistry, {
          description: "Whether the request was cancelled successfully.",
        })
        .optional(),
    })
    .register(z.globalRegistry, {
      description: "The request was cancelled.",
    });

export const zGetFalAiMoondream2ObjectDetectionRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

export const zGetFalAiMoondream2ObjectDetectionRequestsByRequestIdStatusQuery =
  z.object({
    logs: z
      .number()
      .register(z.globalRegistry, {
        description:
          "Whether to include logs (`1`) in the response or not (`0`).",
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiMoondream2ObjectDetectionRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiMoondream2PointObjectDetectionBody =
  zMoondream2PointObjectDetectionInput;

/**
 * The request status.
 */
export const zPostFalAiMoondream2PointObjectDetectionResponse = zQueueStatus;

export const zGetFalAiMoondream2PointObjectDetectionRequestsByRequestIdPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * Result of the request.
 */
export const zGetFalAiMoondream2PointObjectDetectionRequestsByRequestIdResponse =
  zMoondream2PointObjectDetectionOutput;

export const zPutFalAiMoondream2PointObjectDetectionRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * The request was cancelled.
 */
export const zPutFalAiMoondream2PointObjectDetectionRequestsByRequestIdCancelResponse =
  z
    .object({
      success: z
        .boolean()
        .register(z.globalRegistry, {
          description: "Whether the request was cancelled successfully.",
        })
        .optional(),
    })
    .register(z.globalRegistry, {
      description: "The request was cancelled.",
    });

export const zGetFalAiMoondream2PointObjectDetectionRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

export const zGetFalAiMoondream2PointObjectDetectionRequestsByRequestIdStatusQuery =
  z.object({
    logs: z
      .number()
      .register(z.globalRegistry, {
        description:
          "Whether to include logs (`1`) in the response or not (`0`).",
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiMoondream2PointObjectDetectionRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zGetFalAiMoondream2RequestsByRequestIdPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * Result of the request.
 */
export const zGetFalAiMoondream2RequestsByRequestIdResponse = zMoondream2Output;

export const zPutFalAiMoondream2RequestsByRequestIdCancelPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * The request was cancelled.
 */
export const zPutFalAiMoondream2RequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zGetFalAiMoondream2RequestsByRequestIdStatusPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

export const zGetFalAiMoondream2RequestsByRequestIdStatusQuery = z.object({
  logs: z
    .number()
    .register(z.globalRegistry, {
      description:
        "Whether to include logs (`1`) in the response or not (`0`).",
    })
    .optional(),
});

/**
 * The request status.
 */
export const zGetFalAiMoondream2RequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiMoondream2VisualQueryBody = zMoondream2VisualQueryInput;

/**
 * The request status.
 */
export const zPostFalAiMoondream2VisualQueryResponse = zQueueStatus;

export const zGetFalAiMoondream2VisualQueryRequestsByRequestIdPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * Result of the request.
 */
export const zGetFalAiMoondream2VisualQueryRequestsByRequestIdResponse =
  zMoondream2VisualQueryOutput;

export const zPutFalAiMoondream2VisualQueryRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * The request was cancelled.
 */
export const zPutFalAiMoondream2VisualQueryRequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zGetFalAiMoondream2VisualQueryRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

export const zGetFalAiMoondream2VisualQueryRequestsByRequestIdStatusQuery =
  z.object({
    logs: z
      .number()
      .register(z.globalRegistry, {
        description:
          "Whether to include logs (`1`) in the response or not (`0`).",
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiMoondream2VisualQueryRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiMoondream3PreviewCaptionBody =
  zMoondream3PreviewCaptionInput;

/**
 * The request status.
 */
export const zPostFalAiMoondream3PreviewCaptionResponse = zQueueStatus;

export const zGetFalAiMoondream3PreviewCaptionRequestsByRequestIdPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * Result of the request.
 */
export const zGetFalAiMoondream3PreviewCaptionRequestsByRequestIdResponse =
  zMoondream3PreviewCaptionOutput;

export const zPutFalAiMoondream3PreviewCaptionRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * The request was cancelled.
 */
export const zPutFalAiMoondream3PreviewCaptionRequestsByRequestIdCancelResponse =
  z
    .object({
      success: z
        .boolean()
        .register(z.globalRegistry, {
          description: "Whether the request was cancelled successfully.",
        })
        .optional(),
    })
    .register(z.globalRegistry, {
      description: "The request was cancelled.",
    });

export const zGetFalAiMoondream3PreviewCaptionRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

export const zGetFalAiMoondream3PreviewCaptionRequestsByRequestIdStatusQuery =
  z.object({
    logs: z
      .number()
      .register(z.globalRegistry, {
        description:
          "Whether to include logs (`1`) in the response or not (`0`).",
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiMoondream3PreviewCaptionRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiMoondream3PreviewDetectBody =
  zMoondream3PreviewDetectInput;

/**
 * The request status.
 */
export const zPostFalAiMoondream3PreviewDetectResponse = zQueueStatus;

export const zGetFalAiMoondream3PreviewDetectRequestsByRequestIdPath = z.object(
  {
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  },
);

/**
 * Result of the request.
 */
export const zGetFalAiMoondream3PreviewDetectRequestsByRequestIdResponse =
  zMoondream3PreviewDetectOutput;

export const zPutFalAiMoondream3PreviewDetectRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * The request was cancelled.
 */
export const zPutFalAiMoondream3PreviewDetectRequestsByRequestIdCancelResponse =
  z
    .object({
      success: z
        .boolean()
        .register(z.globalRegistry, {
          description: "Whether the request was cancelled successfully.",
        })
        .optional(),
    })
    .register(z.globalRegistry, {
      description: "The request was cancelled.",
    });

export const zGetFalAiMoondream3PreviewDetectRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

export const zGetFalAiMoondream3PreviewDetectRequestsByRequestIdStatusQuery =
  z.object({
    logs: z
      .number()
      .register(z.globalRegistry, {
        description:
          "Whether to include logs (`1`) in the response or not (`0`).",
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiMoondream3PreviewDetectRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiMoondream3PreviewPointBody =
  zMoondream3PreviewPointInput;

/**
 * The request status.
 */
export const zPostFalAiMoondream3PreviewPointResponse = zQueueStatus;

export const zGetFalAiMoondream3PreviewPointRequestsByRequestIdPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * Result of the request.
 */
export const zGetFalAiMoondream3PreviewPointRequestsByRequestIdResponse =
  zMoondream3PreviewPointOutput;

export const zPutFalAiMoondream3PreviewPointRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * The request was cancelled.
 */
export const zPutFalAiMoondream3PreviewPointRequestsByRequestIdCancelResponse =
  z
    .object({
      success: z
        .boolean()
        .register(z.globalRegistry, {
          description: "Whether the request was cancelled successfully.",
        })
        .optional(),
    })
    .register(z.globalRegistry, {
      description: "The request was cancelled.",
    });

export const zGetFalAiMoondream3PreviewPointRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

export const zGetFalAiMoondream3PreviewPointRequestsByRequestIdStatusQuery =
  z.object({
    logs: z
      .number()
      .register(z.globalRegistry, {
        description:
          "Whether to include logs (`1`) in the response or not (`0`).",
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiMoondream3PreviewPointRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiMoondream3PreviewQueryBody =
  zMoondream3PreviewQueryInput;

/**
 * The request status.
 */
export const zPostFalAiMoondream3PreviewQueryResponse = zQueueStatus;

export const zGetFalAiMoondream3PreviewQueryRequestsByRequestIdPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * Result of the request.
 */
export const zGetFalAiMoondream3PreviewQueryRequestsByRequestIdResponse =
  zMoondream3PreviewQueryOutput;

export const zPutFalAiMoondream3PreviewQueryRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * The request was cancelled.
 */
export const zPutFalAiMoondream3PreviewQueryRequestsByRequestIdCancelResponse =
  z
    .object({
      success: z
        .boolean()
        .register(z.globalRegistry, {
          description: "Whether the request was cancelled successfully.",
        })
        .optional(),
    })
    .register(z.globalRegistry, {
      description: "The request was cancelled.",
    });

export const zGetFalAiMoondream3PreviewQueryRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

export const zGetFalAiMoondream3PreviewQueryRequestsByRequestIdStatusQuery =
  z.object({
    logs: z
      .number()
      .register(z.globalRegistry, {
        description:
          "Whether to include logs (`1`) in the response or not (`0`).",
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiMoondream3PreviewQueryRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiSa2Va4bImageBody = zSa2Va4bImageInput;

/**
 * The request status.
 */
export const zPostFalAiSa2Va4bImageResponse = zQueueStatus;

export const zGetFalAiSa2Va4bImageRequestsByRequestIdPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * Result of the request.
 */
export const zGetFalAiSa2Va4bImageRequestsByRequestIdResponse =
  zSa2Va4bImageOutput;

export const zPutFalAiSa2Va4bImageRequestsByRequestIdCancelPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * The request was cancelled.
 */
export const zPutFalAiSa2Va4bImageRequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zGetFalAiSa2Va4bImageRequestsByRequestIdStatusPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

export const zGetFalAiSa2Va4bImageRequestsByRequestIdStatusQuery = z.object({
  logs: z
    .number()
    .register(z.globalRegistry, {
      description:
        "Whether to include logs (`1`) in the response or not (`0`).",
    })
    .optional(),
});

/**
 * The request status.
 */
export const zGetFalAiSa2Va4bImageRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiSa2Va4bVideoBody = zSa2Va4bVideoInput;

/**
 * The request status.
 */
export const zPostFalAiSa2Va4bVideoResponse = zQueueStatus;

export const zGetFalAiSa2Va4bVideoRequestsByRequestIdPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * Result of the request.
 */
export const zGetFalAiSa2Va4bVideoRequestsByRequestIdResponse =
  zSa2Va4bVideoOutput;

export const zPutFalAiSa2Va4bVideoRequestsByRequestIdCancelPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * The request was cancelled.
 */
export const zPutFalAiSa2Va4bVideoRequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zGetFalAiSa2Va4bVideoRequestsByRequestIdStatusPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

export const zGetFalAiSa2Va4bVideoRequestsByRequestIdStatusQuery = z.object({
  logs: z
    .number()
    .register(z.globalRegistry, {
      description:
        "Whether to include logs (`1`) in the response or not (`0`).",
    })
    .optional(),
});

/**
 * The request status.
 */
export const zGetFalAiSa2Va4bVideoRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiSa2Va8bImageBody = zSa2Va8bImageInput;

/**
 * The request status.
 */
export const zPostFalAiSa2Va8bImageResponse = zQueueStatus;

export const zGetFalAiSa2Va8bImageRequestsByRequestIdPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * Result of the request.
 */
export const zGetFalAiSa2Va8bImageRequestsByRequestIdResponse =
  zSa2Va8bImageOutput;

export const zPutFalAiSa2Va8bImageRequestsByRequestIdCancelPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * The request was cancelled.
 */
export const zPutFalAiSa2Va8bImageRequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zGetFalAiSa2Va8bImageRequestsByRequestIdStatusPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

export const zGetFalAiSa2Va8bImageRequestsByRequestIdStatusQuery = z.object({
  logs: z
    .number()
    .register(z.globalRegistry, {
      description:
        "Whether to include logs (`1`) in the response or not (`0`).",
    })
    .optional(),
});

/**
 * The request status.
 */
export const zGetFalAiSa2Va8bImageRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiSa2Va8bVideoBody = zSa2Va8bVideoInput;

/**
 * The request status.
 */
export const zPostFalAiSa2Va8bVideoResponse = zQueueStatus;

export const zGetFalAiSa2Va8bVideoRequestsByRequestIdPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * Result of the request.
 */
export const zGetFalAiSa2Va8bVideoRequestsByRequestIdResponse =
  zSa2Va8bVideoOutput;

export const zPutFalAiSa2Va8bVideoRequestsByRequestIdCancelPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * The request was cancelled.
 */
export const zPutFalAiSa2Va8bVideoRequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zGetFalAiSa2Va8bVideoRequestsByRequestIdStatusPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

export const zGetFalAiSa2Va8bVideoRequestsByRequestIdStatusQuery = z.object({
  logs: z
    .number()
    .register(z.globalRegistry, {
      description:
        "Whether to include logs (`1`) in the response or not (`0`).",
    })
    .optional(),
});

/**
 * The request status.
 */
export const zGetFalAiSa2Va8bVideoRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiSam3ImageEmbedBody = zSam3ImageEmbedInput;

/**
 * The request status.
 */
export const zPostFalAiSam3ImageEmbedResponse = zQueueStatus;

export const zGetFalAiSam3ImageEmbedRequestsByRequestIdPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * Result of the request.
 */
export const zGetFalAiSam3ImageEmbedRequestsByRequestIdResponse =
  zSam3ImageEmbedOutput;

export const zPutFalAiSam3ImageEmbedRequestsByRequestIdCancelPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * The request was cancelled.
 */
export const zPutFalAiSam3ImageEmbedRequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zGetFalAiSam3ImageEmbedRequestsByRequestIdStatusPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

export const zGetFalAiSam3ImageEmbedRequestsByRequestIdStatusQuery = z.object({
  logs: z
    .number()
    .register(z.globalRegistry, {
      description:
        "Whether to include logs (`1`) in the response or not (`0`).",
    })
    .optional(),
});

/**
 * The request status.
 */
export const zGetFalAiSam3ImageEmbedRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiVideoUnderstandingBody = zVideoUnderstandingInput;

/**
 * The request status.
 */
export const zPostFalAiVideoUnderstandingResponse = zQueueStatus;

export const zGetFalAiVideoUnderstandingRequestsByRequestIdPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * Result of the request.
 */
export const zGetFalAiVideoUnderstandingRequestsByRequestIdResponse =
  zVideoUnderstandingOutput;

export const zPutFalAiVideoUnderstandingRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * The request was cancelled.
 */
export const zPutFalAiVideoUnderstandingRequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zGetFalAiVideoUnderstandingRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

export const zGetFalAiVideoUnderstandingRequestsByRequestIdStatusQuery =
  z.object({
    logs: z
      .number()
      .register(z.globalRegistry, {
        description:
          "Whether to include logs (`1`) in the response or not (`0`).",
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiVideoUnderstandingRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiXAilabNsfwBody = zXAilabNsfwInput;

/**
 * The request status.
 */
export const zPostFalAiXAilabNsfwResponse = zQueueStatus;

export const zGetFalAiXAilabNsfwRequestsByRequestIdPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * Result of the request.
 */
export const zGetFalAiXAilabNsfwRequestsByRequestIdResponse = zXAilabNsfwOutput;

export const zPutFalAiXAilabNsfwRequestsByRequestIdCancelPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * The request was cancelled.
 */
export const zPutFalAiXAilabNsfwRequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zGetFalAiXAilabNsfwRequestsByRequestIdStatusPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

export const zGetFalAiXAilabNsfwRequestsByRequestIdStatusQuery = z.object({
  logs: z
    .number()
    .register(z.globalRegistry, {
      description:
        "Whether to include logs (`1`) in the response or not (`0`).",
    })
    .optional(),
});

/**
 * The request status.
 */
export const zGetFalAiXAilabNsfwRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostOpenrouterRouterVisionBody = zRouterVisionInput;

/**
 * The request status.
 */
export const zPostOpenrouterRouterVisionResponse = zQueueStatus;

export const zGetOpenrouterRouterVisionRequestsByRequestIdPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * Result of the request.
 */
export const zGetOpenrouterRouterVisionRequestsByRequestIdResponse =
  zRouterVisionOutput;

export const zPutOpenrouterRouterVisionRequestsByRequestIdCancelPath = z.object(
  {
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  },
);

/**
 * The request was cancelled.
 */
export const zPutOpenrouterRouterVisionRequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zGetOpenrouterRouterVisionRequestsByRequestIdStatusPath = z.object(
  {
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  },
);

export const zGetOpenrouterRouterVisionRequestsByRequestIdStatusQuery =
  z.object({
    logs: z
      .number()
      .register(z.globalRegistry, {
        description:
          "Whether to include logs (`1`) in the response or not (`0`).",
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetOpenrouterRouterVisionRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostPerceptronIsaac01Body = zIsaac01Input;

/**
 * The request status.
 */
export const zPostPerceptronIsaac01Response = zQueueStatus;

export const zPostPerceptronIsaac01OpenaiV1ChatCompletionsBody =
  zIsaac01OpenaiV1ChatCompletionsInput;

/**
 * The request status.
 */
export const zPostPerceptronIsaac01OpenaiV1ChatCompletionsResponse =
  zQueueStatus;

export const zGetPerceptronIsaac01OpenaiV1ChatCompletionsRequestsByRequestIdPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * Result of the request.
 */
export const zGetPerceptronIsaac01OpenaiV1ChatCompletionsRequestsByRequestIdResponse =
  zIsaac01OpenaiV1ChatCompletionsOutput;

export const zPutPerceptronIsaac01OpenaiV1ChatCompletionsRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * The request was cancelled.
 */
export const zPutPerceptronIsaac01OpenaiV1ChatCompletionsRequestsByRequestIdCancelResponse =
  z
    .object({
      success: z
        .boolean()
        .register(z.globalRegistry, {
          description: "Whether the request was cancelled successfully.",
        })
        .optional(),
    })
    .register(z.globalRegistry, {
      description: "The request was cancelled.",
    });

export const zGetPerceptronIsaac01OpenaiV1ChatCompletionsRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

export const zGetPerceptronIsaac01OpenaiV1ChatCompletionsRequestsByRequestIdStatusQuery =
  z.object({
    logs: z
      .number()
      .register(z.globalRegistry, {
        description:
          "Whether to include logs (`1`) in the response or not (`0`).",
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetPerceptronIsaac01OpenaiV1ChatCompletionsRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zGetPerceptronIsaac01RequestsByRequestIdPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * Result of the request.
 */
export const zGetPerceptronIsaac01RequestsByRequestIdResponse = zIsaac01Output;

export const zPutPerceptronIsaac01RequestsByRequestIdCancelPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

/**
 * The request was cancelled.
 */
export const zPutPerceptronIsaac01RequestsByRequestIdCancelResponse = z
  .object({
    success: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      })
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zGetPerceptronIsaac01RequestsByRequestIdStatusPath = z.object({
  request_id: z.string().register(z.globalRegistry, {
    description: "Request ID",
  }),
});

export const zGetPerceptronIsaac01RequestsByRequestIdStatusQuery = z.object({
  logs: z
    .number()
    .register(z.globalRegistry, {
      description:
        "Whether to include logs (`1`) in the response or not (`0`).",
    })
    .optional(),
});

/**
 * The request status.
 */
export const zGetPerceptronIsaac01RequestsByRequestIdStatusResponse =
  zQueueStatus;
