// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

/**
 * OutputModel
 */
export const zVideoPromptGeneratorOutput = z.object({
  prompt: z.string().register(z.globalRegistry, {
    description: "Generated video prompt",
  }),
});

/**
 * InputModel
 */
export const zVideoPromptGeneratorInput = z.object({
  custom_elements: z
    .optional(
      z.string().register(z.globalRegistry, {
        description: "Custom technical elements (optional)",
      }),
    )
    .default(""),
  style: z.optional(
    z
      .enum([
        "Minimalist",
        "Simple",
        "Detailed",
        "Descriptive",
        "Dynamic",
        "Cinematic",
        "Documentary",
        "Animation",
        "Action",
        "Experimental",
      ])
      .register(z.globalRegistry, {
        description: "Style of the video prompt",
      }),
  ),
  camera_direction: z.optional(
    z
      .enum([
        "None",
        "Zoom in",
        "Zoom out",
        "Pan left",
        "Pan right",
        "Tilt up",
        "Tilt down",
        "Orbital rotation",
        "Push in",
        "Pull out",
        "Track forward",
        "Track backward",
        "Spiral in",
        "Spiral out",
        "Arc movement",
        "Diagonal traverse",
        "Vertical rise",
        "Vertical descent",
      ])
      .register(z.globalRegistry, {
        description: "Camera direction",
      }),
  ),
  pacing: z.optional(
    z
      .enum([
        "None",
        "Slow burn",
        "Rhythmic pulse",
        "Frantic energy",
        "Ebb and flow",
        "Hypnotic drift",
        "Time-lapse rush",
        "Stop-motion staccato",
        "Gradual build",
        "Quick cut rhythm",
        "Long take meditation",
        "Jump cut energy",
        "Match cut flow",
        "Cross-dissolve dreamscape",
        "Parallel action",
        "Slow motion impact",
        "Ramping dynamics",
        "Montage tempo",
        "Continuous flow",
        "Episodic breaks",
      ])
      .register(z.globalRegistry, {
        description: "Pacing rhythm",
      }),
  ),
  special_effects: z.optional(
    z
      .enum([
        "None",
        "Practical effects",
        "CGI enhancement",
        "Analog glitches",
        "Light painting",
        "Projection mapping",
        "Nanosecond exposures",
        "Double exposure",
        "Smoke diffusion",
        "Lens flare artistry",
        "Particle systems",
        "Holographic overlay",
        "Chromatic aberration",
        "Digital distortion",
        "Wire removal",
        "Motion capture",
        "Miniature integration",
        "Weather simulation",
        "Color grading",
        "Mixed media composite",
        "Neural style transfer",
      ])
      .register(z.globalRegistry, {
        description: "Special effects approach",
      }),
  ),
  image_url: z.optional(z.union([z.string(), z.string()])),
  model: z.optional(
    z
      .enum([
        "anthropic/claude-3.5-sonnet",
        "anthropic/claude-3-5-haiku",
        "anthropic/claude-3-haiku",
        "google/gemini-2.5-flash-lite",
        "google/gemini-2.0-flash-001",
        "meta-llama/llama-3.2-1b-instruct",
        "meta-llama/llama-3.2-3b-instruct",
        "meta-llama/llama-3.1-8b-instruct",
        "meta-llama/llama-3.1-70b-instruct",
        "openai/gpt-4o-mini",
        "openai/gpt-4o",
        "deepseek/deepseek-r1",
      ])
      .register(z.globalRegistry, {
        description: "Model to use",
      }),
  ),
  camera_style: z.optional(
    z
      .enum([
        "None",
        "Steadicam flow",
        "Drone aerials",
        "Handheld urgency",
        "Crane elegance",
        "Dolly precision",
        "VR 360",
        "Multi-angle rig",
        "Static tripod",
        "Gimbal smoothness",
        "Slider motion",
        "Jib sweep",
        "POV immersion",
        "Time-slice array",
        "Macro extreme",
        "Tilt-shift miniature",
        "Snorricam character",
        "Whip pan dynamics",
        "Dutch angle tension",
        "Underwater housing",
        "Periscope lens",
      ])
      .register(z.globalRegistry, {
        description: "Camera movement style",
      }),
  ),
  input_concept: z.string().register(z.globalRegistry, {
    description: "Core concept or thematic input for the video prompt",
  }),
  prompt_length: z.optional(
    z.enum(["Short", "Medium", "Long"]).register(z.globalRegistry, {
      description: "Length of the prompt",
    }),
  ),
});

/**
 * Qwen3GuardOutput
 */
export const zQwen3GuardOutput = z.object({
  categories: z
    .array(
      z.enum([
        "Violent",
        "Non-violent Illegal Acts",
        "Sexual Content or Sexual Acts",
        "PII",
        "Suicide & Self-Harm",
        "Unethical Acts",
        "Politically Sensitive Topics",
        "Copyright Violation",
        "Jailbreak",
        "None",
      ]),
    )
    .register(z.globalRegistry, {
      description: "The confidence score of the classification",
    }),
  label: z
    .enum(["Safe", "Unsafe", "Controversial"])
    .register(z.globalRegistry, {
      description: "The classification label",
    }),
});

/**
 * Qwen3GuardInput
 */
export const zQwen3GuardInput = z.object({
  prompt: z.string().max(131072).register(z.globalRegistry, {
    description: "The input text to be classified",
  }),
});

/**
 * Schema referenced but not defined by fal.ai (missing from source OpenAPI spec)
 */
export const zRouterOpenaiV1ChatCompletionsInput = z
  .record(z.string(), z.unknown())
  .register(z.globalRegistry, {
    description:
      "Schema referenced but not defined by fal.ai (missing from source OpenAPI spec)",
  });

export const zRouterOpenaiV1ChatCompletionsOutput = z.unknown();

/**
 * UsageInfo
 */
export const zUsageInfo = z.object({
  completion_tokens: z.optional(z.union([z.int(), z.unknown()])),
  total_tokens: z.optional(z.int()).default(0),
  prompt_tokens: z.optional(z.union([z.int(), z.unknown()])),
  cost: z.number(),
});

/**
 * ChatOutput
 */
export const zRouterOutput = z.object({
  usage: z.optional(z.union([zUsageInfo, z.unknown()])),
  error: z.optional(z.union([z.string(), z.unknown()])),
  partial: z
    .optional(
      z.boolean().register(z.globalRegistry, {
        description: "Whether the output is partial",
      }),
    )
    .default(false),
  reasoning: z.optional(z.union([z.string(), z.unknown()])),
  output: z.string().register(z.globalRegistry, {
    description: "Generated output",
  }),
});

/**
 * ChatInput
 */
export const zRouterInput = z.object({
  model: z.string().register(z.globalRegistry, {
    description:
      "Name of the model to use. Charged based on actual token usage.",
  }),
  prompt: z.string().register(z.globalRegistry, {
    description: "Prompt to be used for the chat completion",
  }),
  max_tokens: z.optional(z.union([z.int().gte(1), z.unknown()])),
  temperature: z
    .optional(
      z.number().gte(0).lte(2).register(z.globalRegistry, {
        description:
          "This setting influences the variety in the model's responses. Lower values lead to more predictable and typical responses, while higher values encourage more diverse and less common responses. At 0, the model always gives the same response for a given input.",
      }),
    )
    .default(1),
  reasoning: z
    .optional(
      z.boolean().register(z.globalRegistry, {
        description: "Should reasoning be the part of the final answer.",
      }),
    )
    .default(false),
  system_prompt: z.optional(z.union([z.string(), z.unknown()])),
});

/**
 * Schema referenced but not defined by fal.ai (missing from source OpenAPI spec)
 */
export const zRouterOpenaiV1EmbeddingsInput = z
  .record(z.string(), z.unknown())
  .register(z.globalRegistry, {
    description:
      "Schema referenced but not defined by fal.ai (missing from source OpenAPI spec)",
  });

export const zRouterOpenaiV1EmbeddingsOutput = z.unknown();

/**
 * Schema referenced but not defined by fal.ai (missing from source OpenAPI spec)
 */
export const zRouterOpenaiV1ResponsesInput = z
  .record(z.string(), z.unknown())
  .register(z.globalRegistry, {
    description:
      "Schema referenced but not defined by fal.ai (missing from source OpenAPI spec)",
  });

export const zRouterOpenaiV1ResponsesOutput = z.unknown();

export const zQueueStatus = z.object({
  status: z.enum(["IN_QUEUE", "IN_PROGRESS", "COMPLETED"]),
  request_id: z.string().register(z.globalRegistry, {
    description: "The request id.",
  }),
  response_url: z.optional(
    z.string().register(z.globalRegistry, {
      description: "The response url.",
    }),
  ),
  status_url: z.optional(
    z.string().register(z.globalRegistry, {
      description: "The status url.",
    }),
  ),
  cancel_url: z.optional(
    z.string().register(z.globalRegistry, {
      description: "The cancel url.",
    }),
  ),
  logs: z.optional(
    z.record(z.string(), z.unknown()).register(z.globalRegistry, {
      description: "The logs.",
    }),
  ),
  metrics: z.optional(
    z.record(z.string(), z.unknown()).register(z.globalRegistry, {
      description: "The metrics.",
    }),
  ),
  queue_position: z.optional(
    z.int().register(z.globalRegistry, {
      description: "The queue position.",
    }),
  ),
});

export const zGetOpenrouterRouterOpenaiV1ResponsesRequestsByRequestIdStatusData =
  z.object({
    body: z.optional(z.never()),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.optional(
      z.object({
        logs: z.optional(
          z.number().register(z.globalRegistry, {
            description:
              "Whether to include logs (`1`) in the response or not (`0`).",
          }),
        ),
      }),
    ),
  });

/**
 * The request status.
 */
export const zGetOpenrouterRouterOpenaiV1ResponsesRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPutOpenrouterRouterOpenaiV1ResponsesRequestsByRequestIdCancelData =
  z.object({
    body: z.optional(z.never()),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.optional(z.never()),
  });

/**
 * The request was cancelled.
 */
export const zPutOpenrouterRouterOpenaiV1ResponsesRequestsByRequestIdCancelResponse =
  z
    .object({
      success: z.optional(
        z.boolean().register(z.globalRegistry, {
          description: "Whether the request was cancelled successfully.",
        }),
      ),
    })
    .register(z.globalRegistry, {
      description: "The request was cancelled.",
    });

export const zPostOpenrouterRouterOpenaiV1ResponsesData = z.object({
  body: zRouterOpenaiV1ResponsesInput,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * The request status.
 */
export const zPostOpenrouterRouterOpenaiV1ResponsesResponse = zQueueStatus;

export const zGetOpenrouterRouterOpenaiV1ResponsesRequestsByRequestIdData =
  z.object({
    body: z.optional(z.never()),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.optional(z.never()),
  });

/**
 * Result of the request.
 */
export const zGetOpenrouterRouterOpenaiV1ResponsesRequestsByRequestIdResponse =
  zRouterOpenaiV1ResponsesOutput;

export const zGetOpenrouterRouterOpenaiV1EmbeddingsRequestsByRequestIdStatusData =
  z.object({
    body: z.optional(z.never()),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.optional(
      z.object({
        logs: z.optional(
          z.number().register(z.globalRegistry, {
            description:
              "Whether to include logs (`1`) in the response or not (`0`).",
          }),
        ),
      }),
    ),
  });

/**
 * The request status.
 */
export const zGetOpenrouterRouterOpenaiV1EmbeddingsRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPutOpenrouterRouterOpenaiV1EmbeddingsRequestsByRequestIdCancelData =
  z.object({
    body: z.optional(z.never()),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.optional(z.never()),
  });

/**
 * The request was cancelled.
 */
export const zPutOpenrouterRouterOpenaiV1EmbeddingsRequestsByRequestIdCancelResponse =
  z
    .object({
      success: z.optional(
        z.boolean().register(z.globalRegistry, {
          description: "Whether the request was cancelled successfully.",
        }),
      ),
    })
    .register(z.globalRegistry, {
      description: "The request was cancelled.",
    });

export const zPostOpenrouterRouterOpenaiV1EmbeddingsData = z.object({
  body: zRouterOpenaiV1EmbeddingsInput,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * The request status.
 */
export const zPostOpenrouterRouterOpenaiV1EmbeddingsResponse = zQueueStatus;

export const zGetOpenrouterRouterOpenaiV1EmbeddingsRequestsByRequestIdData =
  z.object({
    body: z.optional(z.never()),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.optional(z.never()),
  });

/**
 * Result of the request.
 */
export const zGetOpenrouterRouterOpenaiV1EmbeddingsRequestsByRequestIdResponse =
  zRouterOpenaiV1EmbeddingsOutput;

export const zGetOpenrouterRouterRequestsByRequestIdStatusData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  }),
  query: z.optional(
    z.object({
      logs: z.optional(
        z.number().register(z.globalRegistry, {
          description:
            "Whether to include logs (`1`) in the response or not (`0`).",
        }),
      ),
    }),
  ),
});

/**
 * The request status.
 */
export const zGetOpenrouterRouterRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPutOpenrouterRouterRequestsByRequestIdCancelData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  }),
  query: z.optional(z.never()),
});

/**
 * The request was cancelled.
 */
export const zPutOpenrouterRouterRequestsByRequestIdCancelResponse = z
  .object({
    success: z.optional(
      z.boolean().register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      }),
    ),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zPostOpenrouterRouterData = z.object({
  body: zRouterInput,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * The request status.
 */
export const zPostOpenrouterRouterResponse = zQueueStatus;

export const zGetOpenrouterRouterRequestsByRequestIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  }),
  query: z.optional(z.never()),
});

/**
 * Result of the request.
 */
export const zGetOpenrouterRouterRequestsByRequestIdResponse = zRouterOutput;

export const zGetOpenrouterRouterOpenaiV1ChatCompletionsRequestsByRequestIdStatusData =
  z.object({
    body: z.optional(z.never()),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.optional(
      z.object({
        logs: z.optional(
          z.number().register(z.globalRegistry, {
            description:
              "Whether to include logs (`1`) in the response or not (`0`).",
          }),
        ),
      }),
    ),
  });

/**
 * The request status.
 */
export const zGetOpenrouterRouterOpenaiV1ChatCompletionsRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPutOpenrouterRouterOpenaiV1ChatCompletionsRequestsByRequestIdCancelData =
  z.object({
    body: z.optional(z.never()),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.optional(z.never()),
  });

/**
 * The request was cancelled.
 */
export const zPutOpenrouterRouterOpenaiV1ChatCompletionsRequestsByRequestIdCancelResponse =
  z
    .object({
      success: z.optional(
        z.boolean().register(z.globalRegistry, {
          description: "Whether the request was cancelled successfully.",
        }),
      ),
    })
    .register(z.globalRegistry, {
      description: "The request was cancelled.",
    });

export const zPostOpenrouterRouterOpenaiV1ChatCompletionsData = z.object({
  body: zRouterOpenaiV1ChatCompletionsInput,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * The request status.
 */
export const zPostOpenrouterRouterOpenaiV1ChatCompletionsResponse =
  zQueueStatus;

export const zGetOpenrouterRouterOpenaiV1ChatCompletionsRequestsByRequestIdData =
  z.object({
    body: z.optional(z.never()),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.optional(z.never()),
  });

/**
 * Result of the request.
 */
export const zGetOpenrouterRouterOpenaiV1ChatCompletionsRequestsByRequestIdResponse =
  zRouterOpenaiV1ChatCompletionsOutput;

export const zGetFalAiQwen3GuardRequestsByRequestIdStatusData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  }),
  query: z.optional(
    z.object({
      logs: z.optional(
        z.number().register(z.globalRegistry, {
          description:
            "Whether to include logs (`1`) in the response or not (`0`).",
        }),
      ),
    }),
  ),
});

/**
 * The request status.
 */
export const zGetFalAiQwen3GuardRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPutFalAiQwen3GuardRequestsByRequestIdCancelData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  }),
  query: z.optional(z.never()),
});

/**
 * The request was cancelled.
 */
export const zPutFalAiQwen3GuardRequestsByRequestIdCancelResponse = z
  .object({
    success: z.optional(
      z.boolean().register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      }),
    ),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zPostFalAiQwen3GuardData = z.object({
  body: zQwen3GuardInput,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * The request status.
 */
export const zPostFalAiQwen3GuardResponse = zQueueStatus;

export const zGetFalAiQwen3GuardRequestsByRequestIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  }),
  query: z.optional(z.never()),
});

/**
 * Result of the request.
 */
export const zGetFalAiQwen3GuardRequestsByRequestIdResponse = zQwen3GuardOutput;

export const zGetFalAiVideoPromptGeneratorRequestsByRequestIdStatusData =
  z.object({
    body: z.optional(z.never()),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.optional(
      z.object({
        logs: z.optional(
          z.number().register(z.globalRegistry, {
            description:
              "Whether to include logs (`1`) in the response or not (`0`).",
          }),
        ),
      }),
    ),
  });

/**
 * The request status.
 */
export const zGetFalAiVideoPromptGeneratorRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPutFalAiVideoPromptGeneratorRequestsByRequestIdCancelData =
  z.object({
    body: z.optional(z.never()),
    path: z.object({
      request_id: z.string().register(z.globalRegistry, {
        description: "Request ID",
      }),
    }),
    query: z.optional(z.never()),
  });

/**
 * The request was cancelled.
 */
export const zPutFalAiVideoPromptGeneratorRequestsByRequestIdCancelResponse = z
  .object({
    success: z.optional(
      z.boolean().register(z.globalRegistry, {
        description: "Whether the request was cancelled successfully.",
      }),
    ),
  })
  .register(z.globalRegistry, {
    description: "The request was cancelled.",
  });

export const zPostFalAiVideoPromptGeneratorData = z.object({
  body: zVideoPromptGeneratorInput,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * The request status.
 */
export const zPostFalAiVideoPromptGeneratorResponse = zQueueStatus;

export const zGetFalAiVideoPromptGeneratorRequestsByRequestIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  }),
  query: z.optional(z.never()),
});

/**
 * Result of the request.
 */
export const zGetFalAiVideoPromptGeneratorRequestsByRequestIdResponse =
  zVideoPromptGeneratorOutput;
