// AUTO-GENERATED - Do not edit manually
// Generated from types.gen.ts via scripts/generate-endpoint-maps.ts

import { z } from "zod";

import {
  zBytedanceSeed3dImageTo3dInput,
  zBytedanceSeed3dImageTo3dOutput,
  zHunyuan3dV21Input,
  zHunyuan3dV21Output,
  zHunyuan3dV2Input,
  zHunyuan3dV2MiniInput,
  zHunyuan3dV2MiniOutput,
  zHunyuan3dV2MiniTurboInput,
  zHunyuan3dV2MiniTurboOutput,
  zHunyuan3dV2MultiViewInput,
  zHunyuan3dV2MultiViewOutput,
  zHunyuan3dV2MultiViewTurboInput,
  zHunyuan3dV2MultiViewTurboOutput,
  zHunyuan3dV2Output,
  zHunyuan3dV2TurboInput,
  zHunyuan3dV2TurboOutput,
  zHunyuan3dV31ProImageTo3dInput,
  zHunyuan3dV31ProImageTo3dOutput,
  zHunyuan3dV31ProTextTo3dInput,
  zHunyuan3dV31ProTextTo3dOutput,
  zHunyuan3dV31RapidImageTo3dInput,
  zHunyuan3dV31RapidImageTo3dOutput,
  zHunyuan3dV31RapidTextTo3dInput,
  zHunyuan3dV31RapidTextTo3dOutput,
  zHunyuan3dV31SmartTopologyInput,
  zHunyuan3dV31SmartTopologyOutput,
  zHunyuan3dV3ImageTo3dInput,
  zHunyuan3dV3ImageTo3dOutput,
  zHunyuan3dV3SketchTo3dInput,
  zHunyuan3dV3SketchTo3dOutput,
  zHunyuan3dV3TextTo3dInput,
  zHunyuan3dV3TextTo3dOutput,
  zHunyuanMotionFastInput,
  zHunyuanMotionFastOutput,
  zHunyuanMotionInput,
  zHunyuanMotionOutput,
  zHunyuanWorldImageToWorldInput,
  zHunyuanWorldImageToWorldOutput,
  zHyper3dRodinInput,
  zHyper3dRodinOutput,
  zHyper3dRodinV2Input,
  zHyper3dRodinV2Output,
  zMeshyV5MultiImageTo3dInput,
  zMeshyV5MultiImageTo3dOutput,
  zMeshyV6PreviewImageTo3dInput,
  zMeshyV6PreviewImageTo3dOutput,
  zMeshyV6PreviewTextTo3dInput,
  zMeshyV6PreviewTextTo3dOutput,
  zOmnipartInput,
  zOmnipartOutput,
  zPshumanInput,
  zPshumanOutput,
  zSam33dBodyInput,
  zSam33dBodyOutput,
  zSam33dObjectsInput,
  zSam33dObjectsOutput,
  zTrellis2Input,
  zTrellis2Output,
  zTrellisInput,
  zTrellisMultiInput,
  zTrellisMultiOutput,
  zTrellisOutput,
  zTripoV25ImageTo3dInput,
  zTripoV25ImageTo3dOutput,
  zTripoV25MultiviewTo3dInput,
  zTripoV25MultiviewTo3dOutput,
  zTriposrInput,
  zTriposrOutput,
} from "./zod.gen";

/** Zod schema for 3d endpoints using discriminatedUnion */
export const Gen3dEndpointSchema = z.discriminatedUnion("endpoint", [
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-3d/v3.1/smart-topology"),
    input: zHunyuan3dV31SmartTopologyInput,
    output: zHunyuan3dV31SmartTopologyOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-3d/v3.1/rapid/image-to-3d"),
    input: zHunyuan3dV31RapidImageTo3dInput,
    output: zHunyuan3dV31RapidImageTo3dOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-3d/v3.1/pro/image-to-3d"),
    input: zHunyuan3dV31ProImageTo3dInput,
    output: zHunyuan3dV31ProImageTo3dOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/trellis-2"),
    input: zTrellis2Input,
    output: zTrellis2Output,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan3d-v3/sketch-to-3d"),
    input: zHunyuan3dV3SketchTo3dInput,
    output: zHunyuan3dV3SketchTo3dOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan3d-v3/image-to-3d"),
    input: zHunyuan3dV3ImageTo3dInput,
    output: zHunyuan3dV3ImageTo3dOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sam-3/3d-body"),
    input: zSam33dBodyInput,
    output: zSam33dBodyOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sam-3/3d-objects"),
    input: zSam33dObjectsInput,
    output: zSam33dObjectsOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/omnipart"),
    input: zOmnipartInput,
    output: zOmnipartOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seed3d/image-to-3d"),
    input: zBytedanceSeed3dImageTo3dInput,
    output: zBytedanceSeed3dImageTo3dOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/meshy/v5/multi-image-to-3d"),
    input: zMeshyV5MultiImageTo3dInput,
    output: zMeshyV5MultiImageTo3dOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/meshy/v6-preview/image-to-3d"),
    input: zMeshyV6PreviewImageTo3dInput,
    output: zMeshyV6PreviewImageTo3dOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hyper3d/rodin/v2"),
    input: zHyper3dRodinV2Input,
    output: zHyper3dRodinV2Output,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pshuman"),
    input: zPshumanInput,
    output: zPshumanOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan_world/image-to-world"),
    input: zHunyuanWorldImageToWorldInput,
    output: zHunyuanWorldImageToWorldOutput,
  }),
  z.object({
    endpoint: z.literal("tripo3d/tripo/v2.5/multiview-to-3d"),
    input: zTripoV25MultiviewTo3dInput,
    output: zTripoV25MultiviewTo3dOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan3d-v21"),
    input: zHunyuan3dV21Input,
    output: zHunyuan3dV21Output,
  }),
  z.object({
    endpoint: z.literal("fal-ai/trellis/multi"),
    input: zTrellisMultiInput,
    output: zTrellisMultiOutput,
  }),
  z.object({
    endpoint: z.literal("tripo3d/tripo/v2.5/image-to-3d"),
    input: zTripoV25ImageTo3dInput,
    output: zTripoV25ImageTo3dOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan3d/v2/multi-view"),
    input: zHunyuan3dV2MultiViewInput,
    output: zHunyuan3dV2MultiViewOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan3d/v2/mini"),
    input: zHunyuan3dV2MiniInput,
    output: zHunyuan3dV2MiniOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan3d/v2/turbo"),
    input: zHunyuan3dV2TurboInput,
    output: zHunyuan3dV2TurboOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan3d/v2/mini/turbo"),
    input: zHunyuan3dV2MiniTurboInput,
    output: zHunyuan3dV2MiniTurboOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan3d/v2"),
    input: zHunyuan3dV2Input,
    output: zHunyuan3dV2Output,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan3d/v2/multi-view/turbo"),
    input: zHunyuan3dV2MultiViewTurboInput,
    output: zHunyuan3dV2MultiViewTurboOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hyper3d/rodin"),
    input: zHyper3dRodinInput,
    output: zHyper3dRodinOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/trellis"),
    input: zTrellisInput,
    output: zTrellisOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/triposr"),
    input: zTriposrInput,
    output: zTriposrOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-3d/v3.1/rapid/text-to-3d"),
    input: zHunyuan3dV31RapidTextTo3dInput,
    output: zHunyuan3dV31RapidTextTo3dOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-3d/v3.1/pro/text-to-3d"),
    input: zHunyuan3dV31ProTextTo3dInput,
    output: zHunyuan3dV31ProTextTo3dOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-motion/fast"),
    input: zHunyuanMotionFastInput,
    output: zHunyuanMotionFastOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-motion"),
    input: zHunyuanMotionInput,
    output: zHunyuanMotionOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan3d-v3/text-to-3d"),
    input: zHunyuan3dV3TextTo3dInput,
    output: zHunyuan3dV3TextTo3dOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/meshy/v6-preview/text-to-3d"),
    input: zMeshyV6PreviewTextTo3dInput,
    output: zMeshyV6PreviewTextTo3dOutput,
  }),
]);

/** Inferred type from Gen3dEndpointSchema */
export type Gen3dEndpoint = z.infer<typeof Gen3dEndpointSchema>;
