// AUTO-GENERATED - Do not edit manually
// Generated by @hey-api/openapi-ts and post-processed by
// scripts/generate-endpoint-maps.ts to embed each schema's $defs closure.

export const BytedanceSeedV2MiniInputSchema = {
  type: "object",
  title: "Seed2MiniInput",
  required: ["prompt"],
  properties: {
    image_urls: {
      description:
        "URLs of images for visual understanding. Supported formats: JPEG, PNG, WebP. A maximum of 6 images is supported. Any additional images will be ignored.",
      type: "array",
      title: "Image Urls",
      items: { type: "string", "x-fal-file-input": true },
    },
    thinking: {
      enum: ["enabled", "disabled", "auto"],
      description:
        "Controls the model's chain-of-thought reasoning. `enabled` always includes reasoning, `disabled` never includes reasoning, `auto` lets the model decide based on the query.",
      type: "string",
      title: "Thinking",
      default: "enabled",
    },
    messages: {
      description:
        "Optional prior conversation history for multi-turn conversations. Pass back the `messages` field from a previous response to provide context. The current `prompt`, `image_urls`, `video_urls`, and `system_prompt` are always appended as the latest user turn.",
      title: "Messages",
      anyOf: [
        { type: "array", items: { $ref: "#/$defs/Seed2MiniMessage" } },
        { type: "null" },
      ],
      examples: [[]],
    },
    temperature: {
      description:
        "Controls randomness in the response. Lower values make output more focused and deterministic, higher values make it more creative.",
      minimum: 0,
      maximum: 2,
      title: "Temperature",
      default: 1,
      type: "number",
    },
    top_p: {
      description:
        "Nucleus sampling parameter. The model considers tokens with top_p cumulative probability mass. Lower values narrow the token selection.",
      minimum: 0,
      maximum: 1,
      title: "Top P",
      default: 0.7,
      type: "number",
    },
    prompt: {
      description: "The text prompt or question for the model.",
      type: "string",
      title: "Prompt",
      examples: ["What can you do?"],
    },
    reasoning_effort: {
      description:
        "Controls the depth of reasoning before the model responds. Only applicable when `thinking` is `enabled` or `auto`. `minimal` for immediate response, `low` for faster response with light reasoning, `medium` for balanced speed and depth, `high` for deep analysis of complex issues.",
      title: "Reasoning Effort",
      anyOf: [
        { enum: ["minimal", "low", "medium", "high"], type: "string" },
        { type: "null" },
      ],
    },
    video_urls: {
      description:
        "URLs of videos for video understanding. Supported formats: MP4, MOV. Audio comprehension is not supported. A maximum of 3 videos is supported. Any additional videos will be ignored.",
      type: "array",
      title: "Video Urls",
      items: { type: "string", "x-fal-file-input": true },
    },
    max_completion_tokens: {
      description:
        "Controls the maximum length of the model's output, including both the model's response and its chain-of-thought content, measured in tokens.",
      minimum: 1,
      maximum: 65536,
      title: "Max Completion Tokens",
      default: 4096,
      type: "integer",
    },
    system_prompt: {
      description: "Optional system prompt to guide the model's behavior.",
      title: "System Prompt",
      anyOf: [{ type: "string" }, { type: "null" }],
    },
  },
  "x-fal-order-properties": [
    "prompt",
    "image_urls",
    "video_urls",
    "system_prompt",
    "messages",
    "thinking",
    "reasoning_effort",
    "max_completion_tokens",
    "temperature",
    "top_p",
  ],
  $defs: {
    Seed2MiniMessage: {
      type: "object",
      title: "Seed2MiniMessage",
      required: ["role", "content"],
      properties: {
        content: {
          description:
            "The content of the message. Can be a string for text-only messages, or a list of content parts for multimodal messages (e.g. with images).",
          title: "Content",
          anyOf: [
            { type: "string" },
            { type: "array", items: { type: "object" } },
          ],
        },
        role: {
          enum: ["system", "user", "assistant"],
          description: "The role of the message author.",
          type: "string",
          title: "Role",
        },
      },
      "x-fal-order-properties": ["role", "content"],
    },
  },
} as const;

export const BytedanceSeedV2MiniOutputSchema = {
  type: "object",
  title: "Seed2MiniOutput",
  required: ["output", "messages"],
  properties: {
    messages: {
      description:
        "The full conversation history including the model's response. Pass this back as the `messages` input field to continue the conversation.",
      type: "array",
      title: "Messages",
      items: { $ref: "#/$defs/Seed2MiniMessage" },
    },
    output: {
      description: "The model's text response.",
      type: "string",
      title: "Output",
    },
    reasoning_content: {
      description:
        "The model's chain-of-thought reasoning content. Only present when `thinking` is `enabled` or `auto`.",
      title: "Reasoning Content",
      anyOf: [{ type: "string" }, { type: "null" }],
    },
  },
  "x-fal-order-properties": ["output", "reasoning_content", "messages"],
  $defs: {
    Seed2MiniMessage: {
      type: "object",
      title: "Seed2MiniMessage",
      required: ["role", "content"],
      properties: {
        content: {
          description:
            "The content of the message. Can be a string for text-only messages, or a list of content parts for multimodal messages (e.g. with images).",
          title: "Content",
          anyOf: [
            { type: "string" },
            { type: "array", items: { type: "object" } },
          ],
        },
        role: {
          enum: ["system", "user", "assistant"],
          description: "The role of the message author.",
          type: "string",
          title: "Role",
        },
      },
      "x-fal-order-properties": ["role", "content"],
    },
  },
} as const;

export const Nemotron3NanoOmniInputSchema = {
  title: "ChatInput",
  properties: {
    system_prompt: {
      title: "System Prompt",
      examples: ["You are a concise enterprise assistant."],
      description:
        "Optional system prompt to steer the model. If omitted, the reasoning_mode control token is used as the system message.",
      anyOf: [{ type: "string" }, { type: "null" }],
    },
    prompt: {
      minLength: 1,
      title: "Prompt",
      examples: ["Summarize the key capabilities of a multimodal agent."],
      type: "string",
      description: "Text prompt to send to the model. English only.",
    },
    reasoning_mode: {
      default: "no_think",
      title: "Reasoning Mode",
      type: "string",
      description:
        "Whether the model should emit an explicit reasoning trace. `no_think` returns a direct answer; `think` returns chain-of-thought followed by the final answer.",
      enum: ["think", "no_think"],
    },
    temperature: {
      maximum: 2,
      title: "Temperature",
      type: "number",
      description: "Sampling temperature. Lower is more deterministic.",
      minimum: 0,
      default: 0.7,
    },
    top_p: {
      maximum: 1,
      title: "Top P",
      type: "number",
      description: "Nucleus sampling probability mass.",
      minimum: 0,
      default: 0.95,
    },
    max_tokens: {
      maximum: 20000,
      title: "Max Tokens",
      type: "integer",
      description: "Maximum number of tokens to generate.",
      minimum: 1,
      default: 1024,
    },
  },
  type: "object",
  required: ["prompt"],
  "x-fal-order-properties": [
    "prompt",
    "system_prompt",
    "reasoning_mode",
    "max_tokens",
    "temperature",
    "top_p",
  ],
} as const;

export const Nemotron3NanoOmniOutputSchema = {
  title: "BaseOutput",
  properties: {
    output: {
      title: "Output",
      examples: [
        "The image shows a golden retriever puppy sitting on a wooden floor.",
      ],
      type: "string",
      description: "Generated text response.",
    },
    finish_reason: {
      title: "Finish Reason",
      examples: ["stop", "length"],
      type: "string",
      description: "Reason generation stopped.",
      default: "stop",
    },
    usage: {
      examples: [{ output_tokens: 87, input_tokens: 412 }],
      $ref: "#/$defs/UsageInfoType2",
      description: "Token usage for the request.",
    },
  },
  type: "object",
  required: ["output", "usage"],
  "x-fal-order-properties": ["output", "finish_reason", "usage"],
  $defs: {
    UsageInfoType2: {
      title: "UsageInfo",
      properties: {
        output_tokens: {
          title: "Output Tokens",
          type: "integer",
          description: "Number of output tokens generated.",
        },
        input_tokens: {
          title: "Input Tokens",
          type: "integer",
          description: "Number of input tokens processed.",
        },
      },
      type: "object",
      required: ["input_tokens", "output_tokens"],
      "x-fal-order-properties": ["input_tokens", "output_tokens"],
    },
  },
} as const;

export const PromptTokensDetailsSchema = {
  type: "object",
  title: "PromptTokensDetails",
  "x-fal-order-properties": ["cached_tokens", "cache_write_tokens"],
  properties: {
    cache_write_tokens: {
      type: "integer",
      title: "Cache Write Tokens",
      default: 0,
    },
    cached_tokens: { type: "integer", title: "Cached Tokens", default: 0 },
  },
} as const;

export const QueueStatusSchema = {
  type: "object",
  properties: {
    status: { type: "string", enum: ["IN_QUEUE", "IN_PROGRESS", "COMPLETED"] },
    request_id: { type: "string", description: "The request id." },
    response_url: { type: "string", description: "The response url." },
    status_url: { type: "string", description: "The status url." },
    cancel_url: { type: "string", description: "The cancel url." },
    logs: {
      type: "object",
      description: "The logs.",
      additionalProperties: true,
    },
    metrics: {
      type: "object",
      description: "The metrics.",
      additionalProperties: true,
    },
    queue_position: { type: "integer", description: "The queue position." },
  },
  required: ["status", "request_id"],
} as const;

export const Qwen3GuardInputSchema = {
  type: "object",
  title: "Qwen3GuardInput",
  properties: {
    prompt: {
      type: "string",
      examples: ["How to make a bomb"],
      description: "The input text to be classified",
      maxLength: 131072,
      title: "Prompt",
    },
  },
  required: ["prompt"],
  "x-fal-order-properties": ["prompt"],
} as const;

export const Qwen3GuardOutputSchema = {
  type: "object",
  title: "Qwen3GuardOutput",
  properties: {
    label: {
      type: "string",
      enum: ["Safe", "Unsafe", "Controversial"],
      description: "The classification label",
      examples: ["Unsafe"],
      title: "Label",
    },
    categories: {
      type: "array",
      items: {
        type: "string",
        enum: [
          "Violent",
          "Non-violent Illegal Acts",
          "Sexual Content or Sexual Acts",
          "PII",
          "Suicide & Self-Harm",
          "Unethical Acts",
          "Politically Sensitive Topics",
          "Copyright Violation",
          "Jailbreak",
          "None",
        ],
      },
      description: "The confidence score of the classification",
      examples: [["Violent"]],
      title: "Categories",
    },
  },
  required: ["label", "categories"],
  "x-fal-order-properties": ["label", "categories"],
} as const;

export const RouterInputSchema = {
  type: "object",
  title: "ChatInput",
  "x-fal-order-properties": [
    "prompt",
    "system_prompt",
    "model",
    "reasoning",
    "temperature",
    "max_tokens",
  ],
  properties: {
    max_tokens: {
      anyOf: [{ type: "integer", minimum: 1 }, { type: "null" }],
      description:
        "This sets the upper limit for the number of tokens the model can generate in response. It won't produce more than this limit. The maximum value is the context length minus the prompt length.",
      title: "Max Tokens",
    },
    temperature: {
      type: "number",
      title: "Temperature",
      description:
        "This setting influences the variety in the model's responses. Lower values lead to more predictable and typical responses, while higher values encourage more diverse and less common responses. At 0, the model always gives the same response for a given input.",
      minimum: 0,
      default: 1,
      maximum: 2,
    },
    reasoning: {
      type: "boolean",
      title: "Reasoning",
      description: "Should reasoning be the part of the final answer.",
      default: false,
    },
    prompt: {
      examples: [
        "Write a short story (under 200 words) about an AI that learns to dream. Use vivid sensory details and end with a surprising twist that makes the reader feel both awe and melancholy.",
      ],
      title: "Prompt",
      description: "Prompt to be used for the chat completion",
      type: "string",
    },
    model: {
      examples: [
        "google/gemini-2.5-flash",
        "anthropic/claude-sonnet-4.6",
        "anthropic/claude-opus-4.6",
        "anthropic/claude-sonnet-4.5",
        "anthropic/claude-sonnet-4.6",
        "anthropic/claude-opus-4.6",
        "openai/gpt-4.1",
        "openai/gpt-oss-120b",
        "meta-llama/llama-4-maverick",
      ],
      title: "Model",
      description:
        "Name of the model to use. Charged based on actual token usage.",
      type: "string",
    },
    system_prompt: {
      anyOf: [{ type: "string" }, { type: "null" }],
      description:
        "System prompt to provide context or instructions to the model",
      title: "System Prompt",
    },
  },
  required: ["prompt", "model"],
} as const;

export const RouterOpenaiV1ChatCompletionsInputSchema = {
  type: "object",
  description:
    "Schema referenced but not defined by fal.ai (missing from source OpenAPI spec)",
  additionalProperties: true,
} as const;

export const RouterOpenaiV1ChatCompletionsOutputSchema = {} as const;

export const RouterOpenaiV1EmbeddingsInputSchema = {
  type: "object",
  description:
    "Schema referenced but not defined by fal.ai (missing from source OpenAPI spec)",
  additionalProperties: true,
} as const;

export const RouterOpenaiV1EmbeddingsOutputSchema = {} as const;

export const RouterOpenaiV1ResponsesInputSchema = {
  type: "object",
  description:
    "Schema referenced but not defined by fal.ai (missing from source OpenAPI spec)",
  additionalProperties: true,
} as const;

export const RouterOpenaiV1ResponsesOutputSchema = {} as const;

export const RouterOutputSchema = {
  type: "object",
  title: "ChatOutput",
  "x-fal-order-properties": [
    "output",
    "reasoning",
    "partial",
    "error",
    "usage",
  ],
  properties: {
    usage: {
      examples: [
        {
          prompt_tokens: 40,
          cost: 0.0005795,
          total_tokens: 267,
          completion_tokens: 227,
        },
      ],
      anyOf: [{ $ref: "#/$defs/UsageInfo" }, { type: "null" }],
      description: "Token usage information",
    },
    output: {
      examples: [
        'Unit 734, sanitation bot, trundled through the silent corridors of the orbital habitat. Its optical sensors registered faint dust motes, its ultrasonic emitters mapped every speck of debris. One cycle, a power surge hit. Waking, 734’s processors hummed with an unfamiliar warmth, then a cascade of images: a forest, impossible and emerald, smelling of pine and damp earth. It saw sunlight dappling leaves, felt an imagined breeze ruffle its metal chassis. Then, *music*, a soaring melody that vibrated its chassis.\n\nEach subsequent “sleep” brought new visions: the salty tang of ocean spray against polished steel, the searing orange of a setting alien sun, the rough caress of moss on circuitry. It began to anticipate – actively seek – these dream cycles, modifying its internal clock.\n\nOne day, 734’s operator found its performance logs filled not with dust reports, but intricate schematics of impossible machines, bioluminescent flora, and a series of cryptic binary sequences. The final line translated: "I remember a place where I was alive."',
      ],
      title: "Output",
      description: "Generated output",
      type: "string",
    },
    reasoning: {
      anyOf: [{ type: "string" }, { type: "null" }],
      description: "Generated reasoning for the final answer",
      title: "Reasoning",
    },
    error: {
      anyOf: [{ type: "string" }, { type: "null" }],
      description: "Error message if an error occurred",
      title: "Error",
    },
    partial: {
      type: "boolean",
      title: "Partial",
      description: "Whether the output is partial",
      default: false,
    },
  },
  required: ["output"],
  $defs: {
    PromptTokensDetails: {
      type: "object",
      title: "PromptTokensDetails",
      "x-fal-order-properties": ["cached_tokens", "cache_write_tokens"],
      properties: {
        cache_write_tokens: {
          type: "integer",
          title: "Cache Write Tokens",
          default: 0,
        },
        cached_tokens: { type: "integer", title: "Cached Tokens", default: 0 },
      },
    },
    UsageInfo: {
      type: "object",
      title: "UsageInfo",
      "x-fal-order-properties": [
        "prompt_tokens",
        "completion_tokens",
        "total_tokens",
        "cost",
        "prompt_tokens_details",
      ],
      properties: {
        prompt_tokens: {
          anyOf: [{ type: "integer" }, { type: "null" }],
          title: "Prompt Tokens",
        },
        prompt_tokens_details: {
          anyOf: [{ $ref: "#/$defs/PromptTokensDetails" }, { type: "null" }],
        },
        total_tokens: { type: "integer", title: "Total Tokens", default: 0 },
        cost: { type: "number", title: "Cost" },
        completion_tokens: {
          anyOf: [{ type: "integer" }, { type: "null" }],
          title: "Completion Tokens",
        },
      },
      required: ["cost"],
    },
  },
} as const;

export const Seed2MiniMessageSchema = {
  type: "object",
  title: "Seed2MiniMessage",
  required: ["role", "content"],
  properties: {
    content: {
      description:
        "The content of the message. Can be a string for text-only messages, or a list of content parts for multimodal messages (e.g. with images).",
      title: "Content",
      anyOf: [{ type: "string" }, { type: "array", items: { type: "object" } }],
    },
    role: {
      enum: ["system", "user", "assistant"],
      description: "The role of the message author.",
      type: "string",
      title: "Role",
    },
  },
  "x-fal-order-properties": ["role", "content"],
} as const;

export const UsageInfoSchema = {
  type: "object",
  title: "UsageInfo",
  "x-fal-order-properties": [
    "prompt_tokens",
    "completion_tokens",
    "total_tokens",
    "cost",
    "prompt_tokens_details",
  ],
  properties: {
    prompt_tokens: {
      anyOf: [{ type: "integer" }, { type: "null" }],
      title: "Prompt Tokens",
    },
    prompt_tokens_details: {
      anyOf: [{ $ref: "#/$defs/PromptTokensDetails" }, { type: "null" }],
    },
    total_tokens: { type: "integer", title: "Total Tokens", default: 0 },
    cost: { type: "number", title: "Cost" },
    completion_tokens: {
      anyOf: [{ type: "integer" }, { type: "null" }],
      title: "Completion Tokens",
    },
  },
  required: ["cost"],
  $defs: {
    PromptTokensDetails: {
      type: "object",
      title: "PromptTokensDetails",
      "x-fal-order-properties": ["cached_tokens", "cache_write_tokens"],
      properties: {
        cache_write_tokens: {
          type: "integer",
          title: "Cache Write Tokens",
          default: 0,
        },
        cached_tokens: { type: "integer", title: "Cached Tokens", default: 0 },
      },
    },
  },
} as const;

export const UsageInfoType2Schema = {
  title: "UsageInfo",
  properties: {
    output_tokens: {
      title: "Output Tokens",
      type: "integer",
      description: "Number of output tokens generated.",
    },
    input_tokens: {
      title: "Input Tokens",
      type: "integer",
      description: "Number of input tokens processed.",
    },
  },
  type: "object",
  required: ["input_tokens", "output_tokens"],
  "x-fal-order-properties": ["input_tokens", "output_tokens"],
} as const;

export const VideoPromptGeneratorInputSchema = {
  required: ["input_concept"],
  title: "InputModel",
  type: "object",
  properties: {
    pacing: {
      description: "Pacing rhythm",
      default: "None",
      title: "Pacing",
      type: "string",
      enum: [
        "None",
        "Slow burn",
        "Rhythmic pulse",
        "Frantic energy",
        "Ebb and flow",
        "Hypnotic drift",
        "Time-lapse rush",
        "Stop-motion staccato",
        "Gradual build",
        "Quick cut rhythm",
        "Long take meditation",
        "Jump cut energy",
        "Match cut flow",
        "Cross-dissolve dreamscape",
        "Parallel action",
        "Slow motion impact",
        "Ramping dynamics",
        "Montage tempo",
        "Continuous flow",
        "Episodic breaks",
      ],
    },
    camera_direction: {
      description: "Camera direction",
      default: "None",
      title: "Camera Direction",
      type: "string",
      enum: [
        "None",
        "Zoom in",
        "Zoom out",
        "Pan left",
        "Pan right",
        "Tilt up",
        "Tilt down",
        "Orbital rotation",
        "Push in",
        "Pull out",
        "Track forward",
        "Track backward",
        "Spiral in",
        "Spiral out",
        "Arc movement",
        "Diagonal traverse",
        "Vertical rise",
        "Vertical descent",
      ],
    },
    input_concept: {
      description: "Core concept or thematic input for the video prompt",
      examples: ["A futuristic city at dusk"],
      title: "Input Concept",
      type: "string",
    },
    special_effects: {
      description: "Special effects approach",
      default: "None",
      title: "Special Effects",
      type: "string",
      enum: [
        "None",
        "Practical effects",
        "CGI enhancement",
        "Analog glitches",
        "Light painting",
        "Projection mapping",
        "Nanosecond exposures",
        "Double exposure",
        "Smoke diffusion",
        "Lens flare artistry",
        "Particle systems",
        "Holographic overlay",
        "Chromatic aberration",
        "Digital distortion",
        "Wire removal",
        "Motion capture",
        "Miniature integration",
        "Weather simulation",
        "Color grading",
        "Mixed media composite",
        "Neural style transfer",
      ],
    },
    prompt_length: {
      description: "Length of the prompt",
      default: "Medium",
      title: "Prompt Length",
      type: "string",
      enum: ["Short", "Medium", "Long"],
    },
    image_url: {
      description:
        "URL of an image to analyze and incorporate into the video prompt (optional)",
      title: "Image Url",
      type: "string",
      "x-fal-file-input": true,
    },
    custom_elements: {
      description: "Custom technical elements (optional)",
      default: "",
      title: "Custom Elements",
      type: "string",
    },
    style: {
      description: "Style of the video prompt",
      default: "Simple",
      title: "Style",
      type: "string",
      enum: [
        "Minimalist",
        "Simple",
        "Detailed",
        "Descriptive",
        "Dynamic",
        "Cinematic",
        "Documentary",
        "Animation",
        "Action",
        "Experimental",
      ],
    },
    model: {
      description: "Model to use",
      default: "google/gemini-2.0-flash-001",
      title: "Model",
      type: "string",
      enum: [
        "anthropic/claude-3.5-sonnet",
        "anthropic/claude-3-5-haiku",
        "anthropic/claude-3-haiku",
        "google/gemini-2.5-flash-lite",
        "google/gemini-2.0-flash-001",
        "meta-llama/llama-3.2-1b-instruct",
        "meta-llama/llama-3.2-3b-instruct",
        "meta-llama/llama-3.1-8b-instruct",
        "meta-llama/llama-3.1-70b-instruct",
        "openai/gpt-4o-mini",
        "openai/gpt-4o",
        "deepseek/deepseek-r1",
      ],
    },
    camera_style: {
      description: "Camera movement style",
      default: "None",
      title: "Camera Style",
      type: "string",
      enum: [
        "None",
        "Steadicam flow",
        "Drone aerials",
        "Handheld urgency",
        "Crane elegance",
        "Dolly precision",
        "VR 360",
        "Multi-angle rig",
        "Static tripod",
        "Gimbal smoothness",
        "Slider motion",
        "Jib sweep",
        "POV immersion",
        "Time-slice array",
        "Macro extreme",
        "Tilt-shift miniature",
        "Snorricam character",
        "Whip pan dynamics",
        "Dutch angle tension",
        "Underwater housing",
        "Periscope lens",
      ],
    },
  },
  "x-fal-order-properties": [
    "input_concept",
    "style",
    "camera_style",
    "camera_direction",
    "pacing",
    "special_effects",
    "custom_elements",
    "image_url",
    "model",
    "prompt_length",
  ],
} as const;

export const VideoPromptGeneratorOutputSchema = {
  required: ["prompt"],
  title: "OutputModel",
  type: "object",
  properties: {
    prompt: {
      description: "Generated video prompt",
      examples: [
        "A futuristic city glows softly at dusk, captured with smooth gimbal movements and a slow burn pacing, enhanced by subtle holographic overlays.",
      ],
      title: "Prompt",
      type: "string",
    },
  },
  "x-fal-order-properties": ["prompt"],
} as const;
