// AUTO-GENERATED - Do not edit manually
// Generated via scripts/generate-endpoint-maps.ts

import { z } from "zod";

import {
  zAiAvatarInput,
  zAiAvatarMultiInput,
  zAiAvatarMultiTextInput,
  zAiAvatarSingleTextInput,
  zAmtInterpolationFrameInterpolationInput,
  zAmtInterpolationInput,
  zAnimatediffSparsectrlLcmInput,
  zAutoCaptionInput,
  zAvatarsAudioToVideoInput,
  zAvatarsAudioToVideoInputType2,
  zAvatarsTextToVideoInput,
  zAvatarsTextToVideoInputType2,
  zBenV2VideoInput,
  zBriaVideoEraserEraseKeypointsInput,
  zBriaVideoEraserEraseMaskInput,
  zBriaVideoEraserErasePromptInput,
  zBytedanceDreamactorV2Input,
  zBytedanceOmnihumanInput,
  zBytedanceOmnihumanV15Input,
  zBytedanceSeedanceV15ProImageToVideoInput,
  zBytedanceSeedanceV15ProTextToVideoInput,
  zBytedanceSeedanceV1LiteImageToVideoInput,
  zBytedanceSeedanceV1LiteReferenceToVideoInput,
  zBytedanceSeedanceV1LiteTextToVideoInput,
  zBytedanceSeedanceV1ProFastImageToVideoInput,
  zBytedanceSeedanceV1ProFastTextToVideoInput,
  zBytedanceSeedanceV1ProImageToVideoInput,
  zBytedanceSeedanceV1ProTextToVideoInput,
  zBytedanceUpscalerUpscaleVideoInput,
  zBytedanceVideoStylizeInput,
  zCogvideox5bImageToVideoInput,
  zCogvideox5bInput,
  zCogvideox5bVideoToVideoInput,
  zControlfoleyInput,
  zControlnextInput,
  zCosmosPredict25DistilledTextToVideoInput,
  zCosmosPredict25ImageToVideoInput,
  zCosmosPredict25TextToVideoInput,
  zCosmosPredict25VideoToVideoInput,
  zCreatifyAuroraInput,
  zCrystalVideoUpscalerInput,
  zDavinciMagihumanInput,
  zDepthAnythingVideoInput,
  zDubbingInput,
  zDwposeVideoInput,
  zEchomimicV3Input,
  zEdittoInput,
  zElevenlabsDubbingInput,
  zFabric10FastInput,
  zFabric10Input,
  zFabric10TextInput,
  zFastAnimatediffTextToVideoInput,
  zFastAnimatediffTurboTextToVideoInput,
  zFastAnimatediffTurboVideoToVideoInput,
  zFastAnimatediffVideoToVideoInput,
  zFastSvdLcmInput,
  zFastSvdLcmTextToVideoInput,
  zFastSvdTextToVideoInput,
  zFlashheadInput,
  zFlashtalkInput,
  zFlashvsrUpscaleVideoInput,
  zFramepackF1Input,
  zFramepackFlf2vInput,
  zFramepackInput,
  zGoalForceInput,
  zGrokImagineVideoEditVideoInput,
  zGrokImagineVideoExtendVideoInput,
  zGrokImagineVideoImageToVideoInput,
  zGrokImagineVideoReferenceToVideoInput,
  zGrokImagineVideoTextToVideoInput,
  zHappyHorseImageToVideoInput,
  zHappyHorseReferenceToVideoInput,
  zHappyHorseTextToVideoInput,
  zHappyHorseVideoEditInput,
  zHeygenAvatar3DigitalTwinInput,
  zHeygenAvatar4DigitalTwinInput,
  zHeygenAvatar4ImageToVideoInput,
  zHeygenV2TranslatePrecisionInput,
  zHeygenV2TranslateSpeedInput,
  zHeygenV2VideoAgentInput,
  zHeygenV3LipsyncPrecisionInput,
  zHeygenV3LipsyncSpeedInput,
  zHeygenV3VideoAgentInput,
  zHunyuanAvatarInput,
  zHunyuanCustomInput,
  zHunyuanPortraitInput,
  zHunyuanVideoFoleyInput,
  zHunyuanVideoImageToVideoInput,
  zHunyuanVideoImg2VidLoraInput,
  zHunyuanVideoInput,
  zHunyuanVideoLoraInput,
  zHunyuanVideoLoraVideoToVideoInput,
  zHunyuanVideoV15ImageToVideoInput,
  zHunyuanVideoV15TextToVideoInput,
  zHunyuanVideoVideoToVideoInput,
  zInfinitalkInput,
  zInfinitalkSingleTextInput,
  zInfinitalkVideoToVideoInput,
  zInfinityStarTextToVideoInput,
  zKandinsky5ProImageToVideoInput,
  zKandinsky5ProTextToVideoInput,
  zKandinsky5TextToVideoDistillInput,
  zKandinsky5TextToVideoInput,
  zKlingVideoAiAvatarV2ProInput,
  zKlingVideoAiAvatarV2StandardInput,
  zKlingVideoLipsyncAudioToVideoInput,
  zKlingVideoLipsyncTextToVideoInput,
  zKlingVideoO1ImageToVideoInput,
  zKlingVideoO1ReferenceToVideoInput,
  zKlingVideoO1StandardImageToVideoInput,
  zKlingVideoO1StandardReferenceToVideoInput,
  zKlingVideoO1StandardVideoToVideoEditInput,
  zKlingVideoO1StandardVideoToVideoReferenceInput,
  zKlingVideoO1VideoToVideoEditInput,
  zKlingVideoO1VideoToVideoReferenceInput,
  zKlingVideoO34kImageToVideoInput,
  zKlingVideoO34kReferenceToVideoInput,
  zKlingVideoO34kTextToVideoInput,
  zKlingVideoO3ProImageToVideoInput,
  zKlingVideoO3ProReferenceToVideoInput,
  zKlingVideoO3ProTextToVideoInput,
  zKlingVideoO3ProVideoToVideoEditInput,
  zKlingVideoO3ProVideoToVideoReferenceInput,
  zKlingVideoO3StandardImageToVideoInput,
  zKlingVideoO3StandardReferenceToVideoInput,
  zKlingVideoO3StandardTextToVideoInput,
  zKlingVideoO3StandardVideoToVideoEditInput,
  zKlingVideoO3StandardVideoToVideoReferenceInput,
  zKlingVideoV15ProEffectsInput,
  zKlingVideoV15ProImageToVideoInput,
  zKlingVideoV15ProTextToVideoInput,
  zKlingVideoV16ProEffectsInput,
  zKlingVideoV16ProElementsInput,
  zKlingVideoV16ProImageToVideoInput,
  zKlingVideoV16ProTextToVideoInput,
  zKlingVideoV16StandardEffectsInput,
  zKlingVideoV16StandardElementsInput,
  zKlingVideoV16StandardImageToVideoInput,
  zKlingVideoV16StandardTextToVideoInput,
  zKlingVideoV1ProAiAvatarInput,
  zKlingVideoV1StandardAiAvatarInput,
  zKlingVideoV1StandardEffectsInput,
  zKlingVideoV1StandardImageToVideoInput,
  zKlingVideoV1StandardTextToVideoInput,
  zKlingVideoV21MasterImageToVideoInput,
  zKlingVideoV21MasterTextToVideoInput,
  zKlingVideoV21ProImageToVideoInput,
  zKlingVideoV21StandardImageToVideoInput,
  zKlingVideoV25TurboProImageToVideoInput,
  zKlingVideoV25TurboProTextToVideoInput,
  zKlingVideoV25TurboStandardImageToVideoInput,
  zKlingVideoV26ProImageToVideoInput,
  zKlingVideoV26ProMotionControlInput,
  zKlingVideoV26ProTextToVideoInput,
  zKlingVideoV26StandardMotionControlInput,
  zKlingVideoV2MasterImageToVideoInput,
  zKlingVideoV2MasterTextToVideoInput,
  zKlingVideoV34kImageToVideoInput,
  zKlingVideoV34kTextToVideoInput,
  zKlingVideoV3ProImageToVideoInput,
  zKlingVideoV3ProMotionControlInput,
  zKlingVideoV3ProTextToVideoInput,
  zKlingVideoV3StandardImageToVideoInput,
  zKlingVideoV3StandardMotionControlInput,
  zKlingVideoV3StandardTextToVideoInput,
  zKreaWan14bTextToVideoInput,
  zKreaWan14bVideoToVideoInput,
  zLatentsyncInput,
  zLightxRecameraInput,
  zLightxRelightInput,
  zLipsyncInput,
  zLivePortraitInput,
  zLongcatMultiAvatarImageAudioToVideoInput,
  zLongcatSingleAvatarAudioToVideoInput,
  zLongcatSingleAvatarImageAudioToVideoInput,
  zLongcatVideoDistilledImageToVideo480pInput,
  zLongcatVideoDistilledImageToVideo720pInput,
  zLongcatVideoDistilledTextToVideo480pInput,
  zLongcatVideoDistilledTextToVideo720pInput,
  zLongcatVideoImageToVideo480pInput,
  zLongcatVideoImageToVideo720pInput,
  zLongcatVideoTextToVideo480pInput,
  zLongcatVideoTextToVideo720pInput,
  zLtx219bAudioToVideoInput,
  zLtx219bAudioToVideoLoraInput,
  zLtx219bDistilledAudioToVideoInput,
  zLtx219bDistilledAudioToVideoLoraInput,
  zLtx219bDistilledExtendVideoInput,
  zLtx219bDistilledExtendVideoLoraInput,
  zLtx219bDistilledImageToVideoInput,
  zLtx219bDistilledImageToVideoLoraInput,
  zLtx219bDistilledTextToVideoInput,
  zLtx219bDistilledTextToVideoLoraInput,
  zLtx219bDistilledVideoToVideoInput,
  zLtx219bDistilledVideoToVideoLoraInput,
  zLtx219bExtendVideoInput,
  zLtx219bExtendVideoLoraInput,
  zLtx219bImageToVideoInput,
  zLtx219bImageToVideoLoraInput,
  zLtx219bTextToVideoInput,
  zLtx219bTextToVideoLoraInput,
  zLtx219bVideoToVideoInput,
  zLtx219bVideoToVideoLoraInput,
  zLtx2322bAudioToVideoInput,
  zLtx2322bAudioToVideoLoraInput,
  zLtx2322bDistilledAudioToVideoInput,
  zLtx2322bDistilledAudioToVideoLoraInput,
  zLtx2322bDistilledImageToVideoInput,
  zLtx2322bDistilledImageToVideoLoraInput,
  zLtx2322bDistilledReferenceVideoToVideoInput,
  zLtx2322bDistilledReferenceVideoToVideoLoraInput,
  zLtx2322bDistilledTextToVideoInput,
  zLtx2322bDistilledTextToVideoLoraInput,
  zLtx2322bDistilledVideoToVideoInput,
  zLtx2322bDistilledVideoToVideoLoraInput,
  zLtx2322bExtendVideoInput,
  zLtx2322bExtendVideoLoraInput,
  zLtx2322bImageToVideoInput,
  zLtx2322bImageToVideoLoraInput,
  zLtx2322bReferenceVideoToVideoInput,
  zLtx2322bReferenceVideoToVideoLoraInput,
  zLtx2322bTextToVideoInput,
  zLtx2322bTextToVideoLoraInput,
  zLtx2322bVideoToVideoInput,
  zLtx2322bVideoToVideoLoraInput,
  zLtx23AudioToVideoInput,
  zLtx23ExtendVideoInput,
  zLtx23ImageToVideoFastInput,
  zLtx23ImageToVideoInput,
  zLtx23RetakeVideoInput,
  zLtx23TextToVideoFastInput,
  zLtx23TextToVideoInput,
  zLtx2AudioToVideoInput,
  zLtx2ExtendVideoInput,
  zLtx2ImageToVideoFastInput,
  zLtx2ImageToVideoInput,
  zLtx2RetakeVideoInput,
  zLtx2TextToVideoFastInput,
  zLtx2TextToVideoInput,
  zLtxVideo13bDevExtendInput,
  zLtxVideo13bDevImageToVideoInput,
  zLtxVideo13bDevInput,
  zLtxVideo13bDevMulticonditioningInput,
  zLtxVideo13bDistilledExtendInput,
  zLtxVideo13bDistilledImageToVideoInput,
  zLtxVideo13bDistilledInput,
  zLtxVideo13bDistilledMulticonditioningInput,
  zLtxVideoImageToVideoInput,
  zLtxVideoInput,
  zLtxVideoLoraImageToVideoInput,
  zLtxVideoLoraMulticonditioningInput,
  zLtxVideoV095ExtendInput,
  zLtxVideoV095Input,
  zLtxVideoV095MulticonditioningInput,
  zLtxv13B098DistilledExtendInput,
  zLtxv13B098DistilledImageToVideoInput,
  zLtxv13B098DistilledInput,
  zLtxv13B098DistilledMulticonditioningInput,
  zLucy2VtonRealtimeInput,
  zLucyEditProInput,
  zLucyRestyleInput,
  zLumaDreamMachineRay2FlashImageToVideoInput,
  zLumaDreamMachineRay2FlashInput,
  zLumaDreamMachineRay2FlashModifyInput,
  zLumaDreamMachineRay2FlashReframeInput,
  zLumaDreamMachineRay2ImageToVideoInput,
  zLumaDreamMachineRay2Input,
  zLumaDreamMachineRay2ModifyInput,
  zLumaDreamMachineRay2ReframeInput,
  zLynxInput,
  zLyra2ZoomInput,
  zMagiDistilledExtendVideoInput,
  zMagiDistilledImageToVideoInput,
  zMagiDistilledInput,
  zMagiExtendVideoInput,
  zMagiImageToVideoInput,
  zMagiInput,
  zMareyI2vInput,
  zMareyMotionTransferInput,
  zMareyPoseTransferInput,
  zMareyT2vInput,
  zMinimaxHailuo02FastImageToVideoInput,
  zMinimaxHailuo02ProImageToVideoInput,
  zMinimaxHailuo02ProTextToVideoInput,
  zMinimaxHailuo02StandardImageToVideoInput,
  zMinimaxHailuo02StandardTextToVideoInput,
  zMinimaxHailuo23FastProImageToVideoInput,
  zMinimaxHailuo23FastStandardImageToVideoInput,
  zMinimaxHailuo23ProImageToVideoInput,
  zMinimaxHailuo23ProTextToVideoInput,
  zMinimaxHailuo23StandardImageToVideoInput,
  zMinimaxHailuo23StandardTextToVideoInput,
  zMinimaxVideo01DirectorImageToVideoInput,
  zMinimaxVideo01DirectorInput,
  zMinimaxVideo01ImageToVideoInput,
  zMinimaxVideo01Input,
  zMinimaxVideo01LiveImageToVideoInput,
  zMinimaxVideo01LiveInput,
  zMinimaxVideo01SubjectReferenceInput,
  zMmaudioV2Input,
  zMochiV1Input,
  zMultishotMasterInput,
  zMusetalkInput,
  zOneToAllAnimation13bInput,
  zOneToAllAnimation14bInput,
  zOviImageToVideoInput,
  zOviInput,
  zPikaV15PikaffectsInput,
  zPikaV21ImageToVideoInput,
  zPikaV21TextToVideoInput,
  zPikaV22ImageToVideoInput,
  zPikaV22PikaframesInput,
  zPikaV22PikascenesInput,
  zPikaV22TextToVideoInput,
  zPikaV2PikadditionsInput,
  zPikaV2TurboImageToVideoInput,
  zPikaV2TurboTextToVideoInput,
  zPixverseC1ImageToVideoInput,
  zPixverseC1ReferenceToVideoInput,
  zPixverseC1TextToVideoInput,
  zPixverseC1TransitionInput,
  zPixverseExtendFastInput,
  zPixverseExtendInput,
  zPixverseLipsyncInput,
  zPixverseSoundEffectsInput,
  zPixverseSwapInput,
  zPixverseV35EffectsInput,
  zPixverseV35ImageToVideoFastInput,
  zPixverseV35ImageToVideoInput,
  zPixverseV35TextToVideoFastInput,
  zPixverseV35TextToVideoInput,
  zPixverseV35TransitionInput,
  zPixverseV45EffectsInput,
  zPixverseV45ImageToVideoFastInput,
  zPixverseV45ImageToVideoInput,
  zPixverseV45TextToVideoFastInput,
  zPixverseV45TextToVideoInput,
  zPixverseV45TransitionInput,
  zPixverseV4EffectsInput,
  zPixverseV4ImageToVideoFastInput,
  zPixverseV4ImageToVideoInput,
  zPixverseV4TextToVideoFastInput,
  zPixverseV4TextToVideoInput,
  zPixverseV55EffectsInput,
  zPixverseV55ImageToVideoInput,
  zPixverseV55TextToVideoInput,
  zPixverseV55TransitionInput,
  zPixverseV56ImageToVideoInput,
  zPixverseV56TextToVideoInput,
  zPixverseV56TransitionInput,
  zPixverseV5EffectsInput,
  zPixverseV5ImageToVideoInput,
  zPixverseV5TextToVideoInput,
  zPixverseV5TransitionInput,
  zPixverseV6ExtendInput,
  zPixverseV6ImageToVideoInput,
  zPixverseV6TextToVideoInput,
  zPixverseV6TransitionInput,
  zQueueStatus,
  zRifeVideoInput,
  zSadtalkerInput,
  zSadtalkerReferenceInput,
  zSam2VideoInput,
  zSam31VideoInput,
  zSam31VideoRleInput,
  zSam3VideoInput,
  zSam3VideoRleInput,
  zSanaVideoInput,
  zScailInput,
  zSeedance20FastImageToVideoInput,
  zSeedance20FastReferenceToVideoInput,
  zSeedance20FastTextToVideoInput,
  zSeedance20ImageToVideoInput,
  zSeedance20ReferenceToVideoInput,
  zSeedance20TextToVideoInput,
  zSeedvrUpscaleVideoInput,
  zSfxV15VideoToVideoInput,
  zSfxV1VideoToVideoInput,
  zSkyreelsI2vInput,
  zSora2CharactersInput,
  zSora2ImageToVideoInput,
  zSora2ImageToVideoProInput,
  zSora2TextToVideoInput,
  zSora2TextToVideoProInput,
  zSora2VideoToVideoRemixInput,
  zStableAvatarInput,
  zStableVideoInput,
  zSyncLipsyncInput,
  zSyncLipsyncReact1Input,
  zSyncLipsyncV2Input,
  zSyncLipsyncV2ProInput,
  zSyncLipsyncV3Input,
  zT2vTurboInput,
  zThinksoundAudioInput,
  zThinksoundInput,
  zTopazUpscaleVideoInput,
  zTranspixarInput,
  zV26ImageToVideoFlashInput,
  zV26ImageToVideoInput,
  zV26ReferenceToVideoFlashInput,
  zV26ReferenceToVideoInput,
  zV26TextToVideoInput,
  zVeo2ImageToVideoInput,
  zVeo2Input,
  zVeo31ExtendVideoInput,
  zVeo31FastExtendVideoInput,
  zVeo31FastFirstLastFrameToVideoInput,
  zVeo31FastImageToVideoInput,
  zVeo31FastInput,
  zVeo31FastReferenceToVideoInput,
  zVeo31FirstLastFrameToVideoInput,
  zVeo31ImageToVideoInput,
  zVeo31Input,
  zVeo31LiteFirstLastFrameToVideoInput,
  zVeo31LiteImageToVideoInput,
  zVeo31LiteInput,
  zVeo31ReferenceToVideoInput,
  zVeo3FastImageToVideoInput,
  zVeo3FastInput,
  zVeo3ImageToVideoInput,
  zVeo3Input,
  zVideoAsPromptInput,
  zVideoBackgroundRemovalFastInput,
  zVideoBackgroundRemovalGreenScreenInput,
  zVideoBackgroundRemovalInput,
  zVideoBackgroundRemovalInputType2,
  zVideoEraseKeypointsInput,
  zVideoEraseMaskInput,
  zVideoErasePromptInput,
  zVideoIncreaseResolutionInput,
  zVideoSoundEffectsGeneratorInput,
  zVideoUpscalerInput,
  zViduImageToVideoInput,
  zViduQ1ImageToVideoInput,
  zViduQ1ReferenceToVideoInput,
  zViduQ1StartEndToVideoInput,
  zViduQ1TextToVideoInput,
  zViduQ2ImageToVideoProInput,
  zViduQ2ImageToVideoTurboInput,
  zViduQ2ReferenceToVideoProInput,
  zViduQ2TextToVideoInput,
  zViduQ2VideoExtensionProInput,
  zViduQ3ImageToVideoInput,
  zViduQ3ImageToVideoTurboInput,
  zViduQ3ReferenceToVideoMixInput,
  zViduQ3TextToVideoInput,
  zViduQ3TextToVideoTurboInput,
  zViduReferenceToVideoInput,
  zViduStartEndToVideoInput,
  zViduTemplateToVideoInput,
  zVoidVideoInpaintingInput,
  zWan22VaceFunA14bDepthInput,
  zWan22VaceFunA14bInpaintingInput,
  zWan22VaceFunA14bOutpaintingInput,
  zWan22VaceFunA14bReframeInput,
  zWan25PreviewImageToVideoInput,
  zWan25PreviewTextToVideoInput,
  zWanAlphaInput,
  zWanAtiInput,
  zWanEffectsInput,
  zWanFlf2vInput,
  zWanFunControlInput,
  zWanI2vInput,
  zWanI2vLoraInput,
  zWanMotionInput,
  zWanMoveInput,
  zWanT2vInput,
  zWanT2vLoraInput,
  zWanV2214bAnimateMoveInput,
  zWanV2214bAnimateReplaceInput,
  zWanV2214bSpeechToVideoInput,
  zWanV225bImageToVideoInput,
  zWanV225bTextToVideoDistillInput,
  zWanV225bTextToVideoFastWanInput,
  zWanV225bTextToVideoInput,
  zWanV22A14bImageToVideoInput,
  zWanV22A14bImageToVideoLoraInput,
  zWanV22A14bImageToVideoTurboInput,
  zWanV22A14bTextToVideoInput,
  zWanV22A14bTextToVideoLoraInput,
  zWanV22A14bTextToVideoTurboInput,
  zWanV22A14bVideoToVideoInput,
  zWanV27EditVideoInput,
  zWanV27ReferenceToVideoInput,
  zWanV27TextToVideoInput,
  zWanVace14bDepthInput,
  zWanVace14bInpaintingInput,
  zWanVace14bInput,
  zWanVace14bOutpaintingInput,
  zWanVace14bPoseInput,
  zWanVace14bReframeInput,
  zWanVaceAppsLongReframeInput,
  zWanVaceAppsVideoEditInput,
  zWanVaceInput,
  zWanVisionEnhancerInput,
  zWorkflowUtilitiesAutoSubtitleInput,
  zWorkflowUtilitiesBlendVideoInput,
  zWorkflowUtilitiesReverseVideoInput,
  zWorkflowUtilitiesScaleVideoInput,
  zWorkflowUtilitiesTrimVideoInput,
} from "./zod.gen";

/** Zod schema for video endpoints using discriminatedUnion */
export const VideoEndpointSchema = z.discriminatedUnion("endpoint", [
  z.object({
    endpoint: z.literal("alibaba/happy-horse/image-to-video"),
    input: zHappyHorseImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("alibaba/happy-horse/reference-to-video"),
    input: zHappyHorseReferenceToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("alibaba/happy-horse/text-to-video"),
    input: zHappyHorseTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("alibaba/happy-horse/video-edit"),
    input: zHappyHorseVideoEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("argil/avatars/audio-to-video"),
    input: zAvatarsAudioToVideoInputType2,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("argil/avatars/text-to-video"),
    input: zAvatarsTextToVideoInputType2,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/bria_video_eraser/erase/keypoints"),
    input: zBriaVideoEraserEraseKeypointsInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/bria_video_eraser/erase/mask"),
    input: zBriaVideoEraserEraseMaskInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/bria_video_eraser/erase/prompt"),
    input: zBriaVideoEraserErasePromptInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/video/background-removal"),
    input: zVideoBackgroundRemovalInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/video/erase/keypoints"),
    input: zVideoEraseKeypointsInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/video/erase/mask"),
    input: zVideoEraseMaskInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/video/erase/prompt"),
    input: zVideoErasePromptInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/video/increase-resolution"),
    input: zVideoIncreaseResolutionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bytedance/lynx"),
    input: zLynxInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bytedance/seedance-2.0/fast/image-to-video"),
    input: zSeedance20FastImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bytedance/seedance-2.0/fast/reference-to-video"),
    input: zSeedance20FastReferenceToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bytedance/seedance-2.0/fast/text-to-video"),
    input: zSeedance20FastTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bytedance/seedance-2.0/image-to-video"),
    input: zSeedance20ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bytedance/seedance-2.0/reference-to-video"),
    input: zSeedance20ReferenceToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bytedance/seedance-2.0/text-to-video"),
    input: zSeedance20TextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("cassetteai/video-sound-effects-generator"),
    input: zVideoSoundEffectsGeneratorInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("clarityai/crystal-video-upscaler"),
    input: zCrystalVideoUpscalerInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("decart/lucy-edit/pro"),
    input: zLucyEditProInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("decart/lucy-restyle"),
    input: zLucyRestyleInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("decart/lucy2-vton/realtime"),
    input: zLucy2VtonRealtimeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ai-avatar"),
    input: zAiAvatarInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ai-avatar/multi"),
    input: zAiAvatarMultiInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ai-avatar/multi-text"),
    input: zAiAvatarMultiTextInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ai-avatar/single-text"),
    input: zAiAvatarSingleTextInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/amt-interpolation"),
    input: zAmtInterpolationInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/amt-interpolation/frame-interpolation"),
    input: zAmtInterpolationFrameInterpolationInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/animatediff-sparsectrl-lcm"),
    input: zAnimatediffSparsectrlLcmInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/auto-caption"),
    input: zAutoCaptionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ben/v2/video"),
    input: zBenV2VideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance-upscaler/upscale/video"),
    input: zBytedanceUpscalerUpscaleVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/dreamactor/v2"),
    input: zBytedanceDreamactorV2Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/omnihuman"),
    input: zBytedanceOmnihumanInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/omnihuman/v1.5"),
    input: zBytedanceOmnihumanV15Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seedance/v1.5/pro/image-to-video"),
    input: zBytedanceSeedanceV15ProImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seedance/v1.5/pro/text-to-video"),
    input: zBytedanceSeedanceV15ProTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seedance/v1/lite/image-to-video"),
    input: zBytedanceSeedanceV1LiteImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seedance/v1/lite/reference-to-video"),
    input: zBytedanceSeedanceV1LiteReferenceToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seedance/v1/lite/text-to-video"),
    input: zBytedanceSeedanceV1LiteTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seedance/v1/pro/fast/image-to-video"),
    input: zBytedanceSeedanceV1ProFastImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seedance/v1/pro/fast/text-to-video"),
    input: zBytedanceSeedanceV1ProFastTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seedance/v1/pro/image-to-video"),
    input: zBytedanceSeedanceV1ProImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seedance/v1/pro/text-to-video"),
    input: zBytedanceSeedanceV1ProTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/video-stylize"),
    input: zBytedanceVideoStylizeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/cogvideox-5b"),
    input: zCogvideox5bInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/cogvideox-5b/image-to-video"),
    input: zCogvideox5bImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/cogvideox-5b/video-to-video"),
    input: zCogvideox5bVideoToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/controlfoley"),
    input: zControlfoleyInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/controlnext"),
    input: zControlnextInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/cosmos-predict-2.5/distilled/text-to-video"),
    input: zCosmosPredict25DistilledTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/cosmos-predict-2.5/image-to-video"),
    input: zCosmosPredict25ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/cosmos-predict-2.5/text-to-video"),
    input: zCosmosPredict25TextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/cosmos-predict-2.5/video-to-video"),
    input: zCosmosPredict25VideoToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/creatify/aurora"),
    input: zCreatifyAuroraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/davinci-magihuman"),
    input: zDavinciMagihumanInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/depth-anything-video"),
    input: zDepthAnythingVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/dubbing"),
    input: zDubbingInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/dwpose/video"),
    input: zDwposeVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/echomimic-v3"),
    input: zEchomimicV3Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/editto"),
    input: zEdittoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/elevenlabs/dubbing"),
    input: zElevenlabsDubbingInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-animatediff/text-to-video"),
    input: zFastAnimatediffTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-animatediff/turbo/text-to-video"),
    input: zFastAnimatediffTurboTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-animatediff/turbo/video-to-video"),
    input: zFastAnimatediffTurboVideoToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-animatediff/video-to-video"),
    input: zFastAnimatediffVideoToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-svd-lcm"),
    input: zFastSvdLcmInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-svd-lcm/text-to-video"),
    input: zFastSvdLcmTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-svd/text-to-video"),
    input: zFastSvdTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flashhead"),
    input: zFlashheadInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flashtalk"),
    input: zFlashtalkInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flashvsr/upscale/video"),
    input: zFlashvsrUpscaleVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/framepack"),
    input: zFramepackInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/framepack/f1"),
    input: zFramepackF1Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/framepack/flf2v"),
    input: zFramepackFlf2vInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/goal-force"),
    input: zGoalForceInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/heygen/avatar3/digital-twin"),
    input: zHeygenAvatar3DigitalTwinInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/heygen/avatar4/digital-twin"),
    input: zHeygenAvatar4DigitalTwinInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/heygen/avatar4/image-to-video"),
    input: zHeygenAvatar4ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/heygen/v2/translate/precision"),
    input: zHeygenV2TranslatePrecisionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/heygen/v2/translate/speed"),
    input: zHeygenV2TranslateSpeedInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/heygen/v2/video-agent"),
    input: zHeygenV2VideoAgentInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/heygen/v3/lipsync/precision"),
    input: zHeygenV3LipsyncPrecisionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/heygen/v3/lipsync/speed"),
    input: zHeygenV3LipsyncSpeedInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/heygen/v3/video-agent"),
    input: zHeygenV3VideoAgentInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-avatar"),
    input: zHunyuanAvatarInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-custom"),
    input: zHunyuanCustomInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-portrait"),
    input: zHunyuanPortraitInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-video"),
    input: zHunyuanVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-video-foley"),
    input: zHunyuanVideoFoleyInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-video-image-to-video"),
    input: zHunyuanVideoImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-video-img2vid-lora"),
    input: zHunyuanVideoImg2VidLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-video-lora"),
    input: zHunyuanVideoLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-video-lora/video-to-video"),
    input: zHunyuanVideoLoraVideoToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-video-v1.5/image-to-video"),
    input: zHunyuanVideoV15ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-video-v1.5/text-to-video"),
    input: zHunyuanVideoV15TextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-video/video-to-video"),
    input: zHunyuanVideoVideoToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/infinitalk"),
    input: zInfinitalkInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/infinitalk/single-text"),
    input: zInfinitalkSingleTextInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/infinitalk/video-to-video"),
    input: zInfinitalkVideoToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/infinity-star/text-to-video"),
    input: zInfinityStarTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kandinsky5-pro/image-to-video"),
    input: zKandinsky5ProImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kandinsky5-pro/text-to-video"),
    input: zKandinsky5ProTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kandinsky5/text-to-video"),
    input: zKandinsky5TextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kandinsky5/text-to-video/distill"),
    input: zKandinsky5TextToVideoDistillInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/ai-avatar/v2/pro"),
    input: zKlingVideoAiAvatarV2ProInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/ai-avatar/v2/standard"),
    input: zKlingVideoAiAvatarV2StandardInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/lipsync/audio-to-video"),
    input: zKlingVideoLipsyncAudioToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/lipsync/text-to-video"),
    input: zKlingVideoLipsyncTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o1/image-to-video"),
    input: zKlingVideoO1ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o1/reference-to-video"),
    input: zKlingVideoO1ReferenceToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o1/standard/image-to-video"),
    input: zKlingVideoO1StandardImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o1/standard/reference-to-video"),
    input: zKlingVideoO1StandardReferenceToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o1/standard/video-to-video/edit"),
    input: zKlingVideoO1StandardVideoToVideoEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/kling-video/o1/standard/video-to-video/reference",
    ),
    input: zKlingVideoO1StandardVideoToVideoReferenceInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o1/video-to-video/edit"),
    input: zKlingVideoO1VideoToVideoEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o1/video-to-video/reference"),
    input: zKlingVideoO1VideoToVideoReferenceInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o3/4k/image-to-video"),
    input: zKlingVideoO34kImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o3/4k/reference-to-video"),
    input: zKlingVideoO34kReferenceToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o3/4k/text-to-video"),
    input: zKlingVideoO34kTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o3/pro/image-to-video"),
    input: zKlingVideoO3ProImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o3/pro/reference-to-video"),
    input: zKlingVideoO3ProReferenceToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o3/pro/text-to-video"),
    input: zKlingVideoO3ProTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o3/pro/video-to-video/edit"),
    input: zKlingVideoO3ProVideoToVideoEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o3/pro/video-to-video/reference"),
    input: zKlingVideoO3ProVideoToVideoReferenceInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o3/standard/image-to-video"),
    input: zKlingVideoO3StandardImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o3/standard/reference-to-video"),
    input: zKlingVideoO3StandardReferenceToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o3/standard/text-to-video"),
    input: zKlingVideoO3StandardTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o3/standard/video-to-video/edit"),
    input: zKlingVideoO3StandardVideoToVideoEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/kling-video/o3/standard/video-to-video/reference",
    ),
    input: zKlingVideoO3StandardVideoToVideoReferenceInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1.5/pro/effects"),
    input: zKlingVideoV15ProEffectsInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1.5/pro/image-to-video"),
    input: zKlingVideoV15ProImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1.5/pro/text-to-video"),
    input: zKlingVideoV15ProTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1.6/pro/effects"),
    input: zKlingVideoV16ProEffectsInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1.6/pro/elements"),
    input: zKlingVideoV16ProElementsInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1.6/pro/image-to-video"),
    input: zKlingVideoV16ProImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1.6/pro/text-to-video"),
    input: zKlingVideoV16ProTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1.6/standard/effects"),
    input: zKlingVideoV16StandardEffectsInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1.6/standard/elements"),
    input: zKlingVideoV16StandardElementsInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1.6/standard/image-to-video"),
    input: zKlingVideoV16StandardImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1.6/standard/text-to-video"),
    input: zKlingVideoV16StandardTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1/pro/ai-avatar"),
    input: zKlingVideoV1ProAiAvatarInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1/standard/ai-avatar"),
    input: zKlingVideoV1StandardAiAvatarInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1/standard/effects"),
    input: zKlingVideoV1StandardEffectsInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1/standard/image-to-video"),
    input: zKlingVideoV1StandardImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1/standard/text-to-video"),
    input: zKlingVideoV1StandardTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v2.1/master/image-to-video"),
    input: zKlingVideoV21MasterImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v2.1/master/text-to-video"),
    input: zKlingVideoV21MasterTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v2.1/pro/image-to-video"),
    input: zKlingVideoV21ProImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v2.1/standard/image-to-video"),
    input: zKlingVideoV21StandardImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v2.5-turbo/pro/image-to-video"),
    input: zKlingVideoV25TurboProImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v2.5-turbo/pro/text-to-video"),
    input: zKlingVideoV25TurboProTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/kling-video/v2.5-turbo/standard/image-to-video",
    ),
    input: zKlingVideoV25TurboStandardImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v2.6/pro/image-to-video"),
    input: zKlingVideoV26ProImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v2.6/pro/motion-control"),
    input: zKlingVideoV26ProMotionControlInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v2.6/pro/text-to-video"),
    input: zKlingVideoV26ProTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v2.6/standard/motion-control"),
    input: zKlingVideoV26StandardMotionControlInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v2/master/image-to-video"),
    input: zKlingVideoV2MasterImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v2/master/text-to-video"),
    input: zKlingVideoV2MasterTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v3/4k/image-to-video"),
    input: zKlingVideoV34kImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v3/4k/text-to-video"),
    input: zKlingVideoV34kTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v3/pro/image-to-video"),
    input: zKlingVideoV3ProImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v3/pro/motion-control"),
    input: zKlingVideoV3ProMotionControlInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v3/pro/text-to-video"),
    input: zKlingVideoV3ProTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v3/standard/image-to-video"),
    input: zKlingVideoV3StandardImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v3/standard/motion-control"),
    input: zKlingVideoV3StandardMotionControlInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v3/standard/text-to-video"),
    input: zKlingVideoV3StandardTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/krea-wan-14b/text-to-video"),
    input: zKreaWan14bTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/krea-wan-14b/video-to-video"),
    input: zKreaWan14bVideoToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/latentsync"),
    input: zLatentsyncInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/lightx/recamera"),
    input: zLightxRecameraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/lightx/relight"),
    input: zLightxRelightInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/live-portrait"),
    input: zLivePortraitInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/longcat-multi-avatar/image-audio-to-video"),
    input: zLongcatMultiAvatarImageAudioToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/longcat-single-avatar/audio-to-video"),
    input: zLongcatSingleAvatarAudioToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/longcat-single-avatar/image-audio-to-video"),
    input: zLongcatSingleAvatarImageAudioToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/longcat-video/distilled/image-to-video/480p"),
    input: zLongcatVideoDistilledImageToVideo480pInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/longcat-video/distilled/image-to-video/720p"),
    input: zLongcatVideoDistilledImageToVideo720pInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/longcat-video/distilled/text-to-video/480p"),
    input: zLongcatVideoDistilledTextToVideo480pInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/longcat-video/distilled/text-to-video/720p"),
    input: zLongcatVideoDistilledTextToVideo720pInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/longcat-video/image-to-video/480p"),
    input: zLongcatVideoImageToVideo480pInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/longcat-video/image-to-video/720p"),
    input: zLongcatVideoImageToVideo720pInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/longcat-video/text-to-video/480p"),
    input: zLongcatVideoTextToVideo480pInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/longcat-video/text-to-video/720p"),
    input: zLongcatVideoTextToVideo720pInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/audio-to-video"),
    input: zLtx219bAudioToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/audio-to-video/lora"),
    input: zLtx219bAudioToVideoLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/distilled/audio-to-video"),
    input: zLtx219bDistilledAudioToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/distilled/audio-to-video/lora"),
    input: zLtx219bDistilledAudioToVideoLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/distilled/extend-video"),
    input: zLtx219bDistilledExtendVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/distilled/extend-video/lora"),
    input: zLtx219bDistilledExtendVideoLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/distilled/image-to-video"),
    input: zLtx219bDistilledImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/distilled/image-to-video/lora"),
    input: zLtx219bDistilledImageToVideoLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/distilled/text-to-video"),
    input: zLtx219bDistilledTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/distilled/text-to-video/lora"),
    input: zLtx219bDistilledTextToVideoLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/distilled/video-to-video"),
    input: zLtx219bDistilledVideoToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/distilled/video-to-video/lora"),
    input: zLtx219bDistilledVideoToVideoLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/extend-video"),
    input: zLtx219bExtendVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/extend-video/lora"),
    input: zLtx219bExtendVideoLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/image-to-video"),
    input: zLtx219bImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/image-to-video/lora"),
    input: zLtx219bImageToVideoLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/text-to-video"),
    input: zLtx219bTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/text-to-video/lora"),
    input: zLtx219bTextToVideoLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/video-to-video"),
    input: zLtx219bVideoToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/video-to-video/lora"),
    input: zLtx219bVideoToVideoLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3-22b/audio-to-video"),
    input: zLtx2322bAudioToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3-22b/audio-to-video/lora"),
    input: zLtx2322bAudioToVideoLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3-22b/distilled/audio-to-video"),
    input: zLtx2322bDistilledAudioToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3-22b/distilled/audio-to-video/lora"),
    input: zLtx2322bDistilledAudioToVideoLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3-22b/distilled/image-to-video"),
    input: zLtx2322bDistilledImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3-22b/distilled/image-to-video/lora"),
    input: zLtx2322bDistilledImageToVideoLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/ltx-2.3-22b/distilled/reference-video-to-video",
    ),
    input: zLtx2322bDistilledReferenceVideoToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/ltx-2.3-22b/distilled/reference-video-to-video/lora",
    ),
    input: zLtx2322bDistilledReferenceVideoToVideoLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3-22b/distilled/text-to-video"),
    input: zLtx2322bDistilledTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3-22b/distilled/text-to-video/lora"),
    input: zLtx2322bDistilledTextToVideoLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3-22b/distilled/video-to-video"),
    input: zLtx2322bDistilledVideoToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3-22b/distilled/video-to-video/lora"),
    input: zLtx2322bDistilledVideoToVideoLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3-22b/extend-video"),
    input: zLtx2322bExtendVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3-22b/extend-video/lora"),
    input: zLtx2322bExtendVideoLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3-22b/image-to-video"),
    input: zLtx2322bImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3-22b/image-to-video/lora"),
    input: zLtx2322bImageToVideoLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3-22b/reference-video-to-video"),
    input: zLtx2322bReferenceVideoToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3-22b/reference-video-to-video/lora"),
    input: zLtx2322bReferenceVideoToVideoLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3-22b/text-to-video"),
    input: zLtx2322bTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3-22b/text-to-video/lora"),
    input: zLtx2322bTextToVideoLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3-22b/video-to-video"),
    input: zLtx2322bVideoToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3-22b/video-to-video/lora"),
    input: zLtx2322bVideoToVideoLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3/audio-to-video"),
    input: zLtx23AudioToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3/extend-video"),
    input: zLtx23ExtendVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3/image-to-video"),
    input: zLtx23ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3/image-to-video/fast"),
    input: zLtx23ImageToVideoFastInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3/retake-video"),
    input: zLtx23RetakeVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3/text-to-video"),
    input: zLtx23TextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2.3/text-to-video/fast"),
    input: zLtx23TextToVideoFastInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2/audio-to-video"),
    input: zLtx2AudioToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2/extend-video"),
    input: zLtx2ExtendVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2/image-to-video"),
    input: zLtx2ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2/image-to-video/fast"),
    input: zLtx2ImageToVideoFastInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2/retake-video"),
    input: zLtx2RetakeVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2/text-to-video"),
    input: zLtx2TextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2/text-to-video/fast"),
    input: zLtx2TextToVideoFastInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video"),
    input: zLtxVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-13b-dev"),
    input: zLtxVideo13bDevInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-13b-dev/extend"),
    input: zLtxVideo13bDevExtendInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-13b-dev/image-to-video"),
    input: zLtxVideo13bDevImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-13b-dev/multiconditioning"),
    input: zLtxVideo13bDevMulticonditioningInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-13b-distilled"),
    input: zLtxVideo13bDistilledInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-13b-distilled/extend"),
    input: zLtxVideo13bDistilledExtendInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-13b-distilled/image-to-video"),
    input: zLtxVideo13bDistilledImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-13b-distilled/multiconditioning"),
    input: zLtxVideo13bDistilledMulticonditioningInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-lora/image-to-video"),
    input: zLtxVideoLoraImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-lora/multiconditioning"),
    input: zLtxVideoLoraMulticonditioningInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-v095"),
    input: zLtxVideoV095Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-v095/extend"),
    input: zLtxVideoV095ExtendInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-v095/multiconditioning"),
    input: zLtxVideoV095MulticonditioningInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video/image-to-video"),
    input: zLtxVideoImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltxv-13b-098-distilled"),
    input: zLtxv13B098DistilledInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltxv-13b-098-distilled/extend"),
    input: zLtxv13B098DistilledExtendInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltxv-13b-098-distilled/image-to-video"),
    input: zLtxv13B098DistilledImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltxv-13b-098-distilled/multiconditioning"),
    input: zLtxv13B098DistilledMulticonditioningInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/luma-dream-machine/ray-2"),
    input: zLumaDreamMachineRay2Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/luma-dream-machine/ray-2-flash"),
    input: zLumaDreamMachineRay2FlashInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/luma-dream-machine/ray-2-flash/image-to-video"),
    input: zLumaDreamMachineRay2FlashImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/luma-dream-machine/ray-2-flash/modify"),
    input: zLumaDreamMachineRay2FlashModifyInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/luma-dream-machine/ray-2-flash/reframe"),
    input: zLumaDreamMachineRay2FlashReframeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/luma-dream-machine/ray-2/image-to-video"),
    input: zLumaDreamMachineRay2ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/luma-dream-machine/ray-2/modify"),
    input: zLumaDreamMachineRay2ModifyInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/luma-dream-machine/ray-2/reframe"),
    input: zLumaDreamMachineRay2ReframeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/lyra-2/zoom"),
    input: zLyra2ZoomInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/magi"),
    input: zMagiInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/magi-distilled"),
    input: zMagiDistilledInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/magi-distilled/extend-video"),
    input: zMagiDistilledExtendVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/magi-distilled/image-to-video"),
    input: zMagiDistilledImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/magi/extend-video"),
    input: zMagiExtendVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/magi/image-to-video"),
    input: zMagiImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/hailuo-02-fast/image-to-video"),
    input: zMinimaxHailuo02FastImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/hailuo-02/pro/image-to-video"),
    input: zMinimaxHailuo02ProImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/hailuo-02/pro/text-to-video"),
    input: zMinimaxHailuo02ProTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/hailuo-02/standard/image-to-video"),
    input: zMinimaxHailuo02StandardImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/hailuo-02/standard/text-to-video"),
    input: zMinimaxHailuo02StandardTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/hailuo-2.3-fast/pro/image-to-video"),
    input: zMinimaxHailuo23FastProImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/minimax/hailuo-2.3-fast/standard/image-to-video",
    ),
    input: zMinimaxHailuo23FastStandardImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/hailuo-2.3/pro/image-to-video"),
    input: zMinimaxHailuo23ProImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/hailuo-2.3/pro/text-to-video"),
    input: zMinimaxHailuo23ProTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/hailuo-2.3/standard/image-to-video"),
    input: zMinimaxHailuo23StandardImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/hailuo-2.3/standard/text-to-video"),
    input: zMinimaxHailuo23StandardTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/video-01"),
    input: zMinimaxVideo01Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/video-01-director"),
    input: zMinimaxVideo01DirectorInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/video-01-director/image-to-video"),
    input: zMinimaxVideo01DirectorImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/video-01-live"),
    input: zMinimaxVideo01LiveInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/video-01-live/image-to-video"),
    input: zMinimaxVideo01LiveImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/video-01-subject-reference"),
    input: zMinimaxVideo01SubjectReferenceInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/video-01/image-to-video"),
    input: zMinimaxVideo01ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/mmaudio-v2"),
    input: zMmaudioV2Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/mochi-v1"),
    input: zMochiV1Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/multishot-master"),
    input: zMultishotMasterInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/musetalk"),
    input: zMusetalkInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/one-to-all-animation/1.3b"),
    input: zOneToAllAnimation13bInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/one-to-all-animation/14b"),
    input: zOneToAllAnimation14bInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ovi"),
    input: zOviInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ovi/image-to-video"),
    input: zOviImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pika/v1.5/pikaffects"),
    input: zPikaV15PikaffectsInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pika/v2.1/image-to-video"),
    input: zPikaV21ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pika/v2.1/text-to-video"),
    input: zPikaV21TextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pika/v2.2/image-to-video"),
    input: zPikaV22ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pika/v2.2/pikaframes"),
    input: zPikaV22PikaframesInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pika/v2.2/pikascenes"),
    input: zPikaV22PikascenesInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pika/v2.2/text-to-video"),
    input: zPikaV22TextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pika/v2/pikadditions"),
    input: zPikaV2PikadditionsInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pika/v2/turbo/image-to-video"),
    input: zPikaV2TurboImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pika/v2/turbo/text-to-video"),
    input: zPikaV2TurboTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/c1/image-to-video"),
    input: zPixverseC1ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/c1/reference-to-video"),
    input: zPixverseC1ReferenceToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/c1/text-to-video"),
    input: zPixverseC1TextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/c1/transition"),
    input: zPixverseC1TransitionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/extend"),
    input: zPixverseExtendInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/extend/fast"),
    input: zPixverseExtendFastInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/lipsync"),
    input: zPixverseLipsyncInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/sound-effects"),
    input: zPixverseSoundEffectsInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/swap"),
    input: zPixverseSwapInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v3.5/effects"),
    input: zPixverseV35EffectsInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v3.5/image-to-video"),
    input: zPixverseV35ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v3.5/image-to-video/fast"),
    input: zPixverseV35ImageToVideoFastInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v3.5/text-to-video"),
    input: zPixverseV35TextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v3.5/text-to-video/fast"),
    input: zPixverseV35TextToVideoFastInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v3.5/transition"),
    input: zPixverseV35TransitionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v4.5/effects"),
    input: zPixverseV45EffectsInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v4.5/image-to-video"),
    input: zPixverseV45ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v4.5/image-to-video/fast"),
    input: zPixverseV45ImageToVideoFastInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v4.5/text-to-video"),
    input: zPixverseV45TextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v4.5/text-to-video/fast"),
    input: zPixverseV45TextToVideoFastInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v4.5/transition"),
    input: zPixverseV45TransitionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v4/effects"),
    input: zPixverseV4EffectsInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v4/image-to-video"),
    input: zPixverseV4ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v4/image-to-video/fast"),
    input: zPixverseV4ImageToVideoFastInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v4/text-to-video"),
    input: zPixverseV4TextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v4/text-to-video/fast"),
    input: zPixverseV4TextToVideoFastInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v5.5/effects"),
    input: zPixverseV55EffectsInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v5.5/image-to-video"),
    input: zPixverseV55ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v5.5/text-to-video"),
    input: zPixverseV55TextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v5.5/transition"),
    input: zPixverseV55TransitionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v5.6/image-to-video"),
    input: zPixverseV56ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v5.6/text-to-video"),
    input: zPixverseV56TextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v5.6/transition"),
    input: zPixverseV56TransitionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v5/effects"),
    input: zPixverseV5EffectsInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v5/image-to-video"),
    input: zPixverseV5ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v5/text-to-video"),
    input: zPixverseV5TextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v5/transition"),
    input: zPixverseV5TransitionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v6/extend"),
    input: zPixverseV6ExtendInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v6/image-to-video"),
    input: zPixverseV6ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v6/text-to-video"),
    input: zPixverseV6TextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v6/transition"),
    input: zPixverseV6TransitionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/rife/video"),
    input: zRifeVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sadtalker"),
    input: zSadtalkerInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sadtalker/reference"),
    input: zSadtalkerReferenceInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sam-3-1/video"),
    input: zSam31VideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sam-3-1/video-rle"),
    input: zSam31VideoRleInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sam-3/video"),
    input: zSam3VideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sam-3/video-rle"),
    input: zSam3VideoRleInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sam2/video"),
    input: zSam2VideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sana-video"),
    input: zSanaVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/scail"),
    input: zScailInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/seedvr/upscale/video"),
    input: zSeedvrUpscaleVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/skyreels-i2v"),
    input: zSkyreelsI2vInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sora-2/characters"),
    input: zSora2CharactersInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sora-2/image-to-video"),
    input: zSora2ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sora-2/image-to-video/pro"),
    input: zSora2ImageToVideoProInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sora-2/text-to-video"),
    input: zSora2TextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sora-2/text-to-video/pro"),
    input: zSora2TextToVideoProInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sora-2/video-to-video/remix"),
    input: zSora2VideoToVideoRemixInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/stable-avatar"),
    input: zStableAvatarInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/stable-video"),
    input: zStableVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sync-lipsync"),
    input: zSyncLipsyncInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sync-lipsync/react-1"),
    input: zSyncLipsyncReact1Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sync-lipsync/v2"),
    input: zSyncLipsyncV2Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sync-lipsync/v2/pro"),
    input: zSyncLipsyncV2ProInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sync-lipsync/v3"),
    input: zSyncLipsyncV3Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/t2v-turbo"),
    input: zT2vTurboInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/thinksound"),
    input: zThinksoundInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/thinksound/audio"),
    input: zThinksoundAudioInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/topaz/upscale/video"),
    input: zTopazUpscaleVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/transpixar"),
    input: zTranspixarInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo2"),
    input: zVeo2Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo2/image-to-video"),
    input: zVeo2ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3"),
    input: zVeo3Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3.1"),
    input: zVeo31Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3.1/extend-video"),
    input: zVeo31ExtendVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3.1/fast"),
    input: zVeo31FastInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3.1/fast/extend-video"),
    input: zVeo31FastExtendVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3.1/fast/first-last-frame-to-video"),
    input: zVeo31FastFirstLastFrameToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3.1/fast/image-to-video"),
    input: zVeo31FastImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3.1/fast/reference-to-video"),
    input: zVeo31FastReferenceToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3.1/first-last-frame-to-video"),
    input: zVeo31FirstLastFrameToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3.1/image-to-video"),
    input: zVeo31ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3.1/lite"),
    input: zVeo31LiteInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3.1/lite/first-last-frame-to-video"),
    input: zVeo31LiteFirstLastFrameToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3.1/lite/image-to-video"),
    input: zVeo31LiteImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3.1/reference-to-video"),
    input: zVeo31ReferenceToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3/fast"),
    input: zVeo3FastInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3/fast/image-to-video"),
    input: zVeo3FastImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3/image-to-video"),
    input: zVeo3ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/video-as-prompt"),
    input: zVideoAsPromptInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/video-upscaler"),
    input: zVideoUpscalerInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/image-to-video"),
    input: zViduImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q1/image-to-video"),
    input: zViduQ1ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q1/reference-to-video"),
    input: zViduQ1ReferenceToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q1/start-end-to-video"),
    input: zViduQ1StartEndToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q1/text-to-video"),
    input: zViduQ1TextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q2/image-to-video/pro"),
    input: zViduQ2ImageToVideoProInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q2/image-to-video/turbo"),
    input: zViduQ2ImageToVideoTurboInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q2/reference-to-video/pro"),
    input: zViduQ2ReferenceToVideoProInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q2/text-to-video"),
    input: zViduQ2TextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q2/video-extension/pro"),
    input: zViduQ2VideoExtensionProInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q3/image-to-video"),
    input: zViduQ3ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q3/image-to-video/turbo"),
    input: zViduQ3ImageToVideoTurboInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q3/reference-to-video/mix"),
    input: zViduQ3ReferenceToVideoMixInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q3/text-to-video"),
    input: zViduQ3TextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q3/text-to-video/turbo"),
    input: zViduQ3TextToVideoTurboInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/reference-to-video"),
    input: zViduReferenceToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/start-end-to-video"),
    input: zViduStartEndToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/template-to-video"),
    input: zViduTemplateToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/void-video-inpainting"),
    input: zVoidVideoInpaintingInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-22-vace-fun-a14b/depth"),
    input: zWan22VaceFunA14bDepthInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-22-vace-fun-a14b/inpainting"),
    input: zWan22VaceFunA14bInpaintingInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-22-vace-fun-a14b/outpainting"),
    input: zWan22VaceFunA14bOutpaintingInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-22-vace-fun-a14b/reframe"),
    input: zWan22VaceFunA14bReframeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-25-preview/image-to-video"),
    input: zWan25PreviewImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-25-preview/text-to-video"),
    input: zWan25PreviewTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-alpha"),
    input: zWanAlphaInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-ati"),
    input: zWanAtiInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-effects"),
    input: zWanEffectsInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-flf2v"),
    input: zWanFlf2vInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-fun-control"),
    input: zWanFunControlInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-i2v"),
    input: zWanI2vInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-i2v-lora"),
    input: zWanI2vLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-motion"),
    input: zWanMotionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-move"),
    input: zWanMoveInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-t2v"),
    input: zWanT2vInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-t2v-lora"),
    input: zWanT2vLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-vace"),
    input: zWanVaceInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-vace-14b"),
    input: zWanVace14bInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-vace-14b/depth"),
    input: zWanVace14bDepthInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-vace-14b/inpainting"),
    input: zWanVace14bInpaintingInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-vace-14b/outpainting"),
    input: zWanVace14bOutpaintingInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-vace-14b/pose"),
    input: zWanVace14bPoseInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-vace-14b/reframe"),
    input: zWanVace14bReframeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-vace-apps/long-reframe"),
    input: zWanVaceAppsLongReframeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-vace-apps/video-edit"),
    input: zWanVaceAppsVideoEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-vision-enhancer"),
    input: zWanVisionEnhancerInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-14b/animate/move"),
    input: zWanV2214bAnimateMoveInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-14b/animate/replace"),
    input: zWanV2214bAnimateReplaceInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-14b/speech-to-video"),
    input: zWanV2214bSpeechToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-5b/image-to-video"),
    input: zWanV225bImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-5b/text-to-video"),
    input: zWanV225bTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-5b/text-to-video/distill"),
    input: zWanV225bTextToVideoDistillInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-5b/text-to-video/fast-wan"),
    input: zWanV225bTextToVideoFastWanInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-a14b/image-to-video"),
    input: zWanV22A14bImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-a14b/image-to-video/lora"),
    input: zWanV22A14bImageToVideoLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-a14b/image-to-video/turbo"),
    input: zWanV22A14bImageToVideoTurboInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-a14b/text-to-video"),
    input: zWanV22A14bTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-a14b/text-to-video/lora"),
    input: zWanV22A14bTextToVideoLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-a14b/text-to-video/turbo"),
    input: zWanV22A14bTextToVideoTurboInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-a14b/video-to-video"),
    input: zWanV22A14bVideoToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.7/edit-video"),
    input: zWanV27EditVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.7/reference-to-video"),
    input: zWanV27ReferenceToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.7/text-to-video"),
    input: zWanV27TextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/workflow-utilities/auto-subtitle"),
    input: zWorkflowUtilitiesAutoSubtitleInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/workflow-utilities/blend-video"),
    input: zWorkflowUtilitiesBlendVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/workflow-utilities/reverse-video"),
    input: zWorkflowUtilitiesReverseVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/workflow-utilities/scale-video"),
    input: zWorkflowUtilitiesScaleVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/workflow-utilities/trim-video"),
    input: zWorkflowUtilitiesTrimVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("mirelo-ai/sfx-v1.5/video-to-video"),
    input: zSfxV15VideoToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("mirelo-ai/sfx-v1/video-to-video"),
    input: zSfxV1VideoToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("moonvalley/marey/i2v"),
    input: zMareyI2vInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("moonvalley/marey/motion-transfer"),
    input: zMareyMotionTransferInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("moonvalley/marey/pose-transfer"),
    input: zMareyPoseTransferInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("moonvalley/marey/t2v"),
    input: zMareyT2vInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("veed/avatars/audio-to-video"),
    input: zAvatarsAudioToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("veed/avatars/text-to-video"),
    input: zAvatarsTextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("veed/fabric-1.0"),
    input: zFabric10Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("veed/fabric-1.0/fast"),
    input: zFabric10FastInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("veed/fabric-1.0/text"),
    input: zFabric10TextInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("veed/lipsync"),
    input: zLipsyncInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("veed/video-background-removal"),
    input: zVideoBackgroundRemovalInputType2,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("veed/video-background-removal/fast"),
    input: zVideoBackgroundRemovalFastInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("veed/video-background-removal/green-screen"),
    input: zVideoBackgroundRemovalGreenScreenInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("wan/v2.6/image-to-video"),
    input: zV26ImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("wan/v2.6/image-to-video/flash"),
    input: zV26ImageToVideoFlashInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("wan/v2.6/reference-to-video"),
    input: zV26ReferenceToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("wan/v2.6/reference-to-video/flash"),
    input: zV26ReferenceToVideoFlashInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("wan/v2.6/text-to-video"),
    input: zV26TextToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("xai/grok-imagine-video/edit-video"),
    input: zGrokImagineVideoEditVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("xai/grok-imagine-video/extend-video"),
    input: zGrokImagineVideoExtendVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("xai/grok-imagine-video/image-to-video"),
    input: zGrokImagineVideoImageToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("xai/grok-imagine-video/reference-to-video"),
    input: zGrokImagineVideoReferenceToVideoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("xai/grok-imagine-video/text-to-video"),
    input: zGrokImagineVideoTextToVideoInput,
    output: zQueueStatus,
  }),
]);

/** Inferred type from VideoEndpointSchema */
export type VideoEndpoint = z.infer<typeof VideoEndpointSchema>;
