// AUTO-GENERATED - Do not edit manually
// Generated from types.gen.ts via scripts/generate-endpoint-maps.ts

import { z } from "zod";

import {
  zAceStepAudioInpaintInput,
  zAceStepAudioInpaintOutput,
  zAceStepAudioOutpaintInput,
  zAceStepAudioOutpaintOutput,
  zAceStepAudioToAudioInput,
  zAceStepAudioToAudioOutput,
  zAceStepInput,
  zAceStepOutput,
  zAceStepPromptToAudioInput,
  zAceStepPromptToAudioOutput,
  zAudioUnderstandingInput,
  zAudioUnderstandingOutput,
  zCsm1bInput,
  zCsm1bOutput,
  zDeepfilternet3Input,
  zDeepfilternet3Output,
  zDemucsInput,
  zDemucsOutput,
  zDiaTtsVoiceCloneInput,
  zDiaTtsVoiceCloneOutput,
  zDiffrhythmInput,
  zDiffrhythmOutput,
  zElevenlabsAudioIsolationInput,
  zElevenlabsAudioIsolationOutput,
  zElevenlabsMusicInput,
  zElevenlabsMusicOutput,
  zElevenlabsSoundEffectsV2Input,
  zElevenlabsSoundEffectsV2Output,
  zElevenlabsTextToDialogueElevenV3Input,
  zElevenlabsTextToDialogueElevenV3Output,
  zElevenlabsTtsElevenV3Input,
  zElevenlabsTtsElevenV3Output,
  zElevenlabsTtsMultilingualV2Input,
  zElevenlabsTtsMultilingualV2Output,
  zElevenlabsVoiceChangerInput,
  zElevenlabsVoiceChangerOutput,
  zF5TtsInput,
  zF5TtsOutput,
  zFfmpegApiMergeAudiosInput,
  zFfmpegApiMergeAudiosOutput,
  zKlingVideoCreateVoiceInput,
  zKlingVideoCreateVoiceOutput,
  zKlingVideoVideoToAudioInput,
  zKlingVideoVideoToAudioOutput,
  zKokoroAmericanEnglishInput,
  zKokoroAmericanEnglishOutput,
  zKokoroBrazilianPortugueseInput,
  zKokoroBrazilianPortugueseOutput,
  zKokoroBritishEnglishInput,
  zKokoroBritishEnglishOutput,
  zKokoroFrenchInput,
  zKokoroFrenchOutput,
  zKokoroHindiInput,
  zKokoroHindiOutput,
  zKokoroItalianInput,
  zKokoroItalianOutput,
  zKokoroJapaneseInput,
  zKokoroJapaneseOutput,
  zKokoroMandarinChineseInput,
  zKokoroMandarinChineseOutput,
  zKokoroSpanishInput,
  zKokoroSpanishOutput,
  zLyria2Input,
  zLyria2Output,
  zMinimaxMusicInput,
  zMinimaxMusicOutput,
  zMinimaxMusicV15Input,
  zMinimaxMusicV15Output,
  zMinimaxMusicV2Input,
  zMinimaxMusicV2Output,
  zMmaudioV2TextToAudioInput,
  zMmaudioV2TextToAudioOutput,
  zMusicGenerationInput,
  zMusicGenerationOutput,
  zMusicGeneratorInput,
  zMusicGeneratorOutput,
  zNovaSrInput,
  zNovaSrOutput,
  zSamAudioSeparateInput,
  zSamAudioSeparateOutput,
  zSamAudioSpanSeparateInput,
  zSamAudioSpanSeparateOutput,
  zSamAudioVisualSeparateInput,
  zSamAudioVisualSeparateOutput,
  zSfxV15VideoToAudioInput,
  zSfxV15VideoToAudioOutput,
  zSfxV1VideoToAudioInput,
  zSfxV1VideoToAudioOutput,
  zSoundEffectGenerationInput,
  zSoundEffectGenerationOutput,
  zSoundEffectsGeneratorInput,
  zSoundEffectsGeneratorOutput,
  zStableAudio25AudioToAudioInput,
  zStableAudio25AudioToAudioOutput,
  zStableAudio25InpaintInput,
  zStableAudio25InpaintOutput,
  zStableAudio25TextToAudioInput,
  zStableAudio25TextToAudioOutput,
  zStableAudioInput,
  zStableAudioOutput,
  zV2ExtendInput,
  zV2ExtendOutput,
  zV2InpaintInput,
  zV2InpaintOutput,
  zV2TextToMusicInput,
  zV2TextToMusicOutput,
  zYueInput,
  zYueOutput,
  zZonosInput,
  zZonosOutput,
} from "./zod.gen";

/** Zod schema for audio endpoints using discriminatedUnion */
export const AudioEndpointSchema = z.discriminatedUnion("endpoint", [
  z.object({
    endpoint: z.literal("fal-ai/elevenlabs/voice-changer"),
    input: zElevenlabsVoiceChangerInput,
    output: zElevenlabsVoiceChangerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/nova-sr"),
    input: zNovaSrInput,
    output: zNovaSrOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/deepfilternet3"),
    input: zDeepfilternet3Input,
    output: zDeepfilternet3Output,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sam-audio/separate"),
    input: zSamAudioSeparateInput,
    output: zSamAudioSeparateOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sam-audio/span-separate"),
    input: zSamAudioSpanSeparateInput,
    output: zSamAudioSpanSeparateOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ffmpeg-api/merge-audios"),
    input: zFfmpegApiMergeAudiosInput,
    output: zFfmpegApiMergeAudiosOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/create-voice"),
    input: zKlingVideoCreateVoiceInput,
    output: zKlingVideoCreateVoiceOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/demucs"),
    input: zDemucsInput,
    output: zDemucsOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/audio-understanding"),
    input: zAudioUnderstandingInput,
    output: zAudioUnderstandingOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/stable-audio-25/audio-to-audio"),
    input: zStableAudio25AudioToAudioInput,
    output: zStableAudio25AudioToAudioOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/stable-audio-25/inpaint"),
    input: zStableAudio25InpaintInput,
    output: zStableAudio25InpaintOutput,
  }),
  z.object({
    endpoint: z.literal("sonauto/v2/extend"),
    input: zV2ExtendInput,
    output: zV2ExtendOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ace-step/audio-outpaint"),
    input: zAceStepAudioOutpaintInput,
    output: zAceStepAudioOutpaintOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ace-step/audio-inpaint"),
    input: zAceStepAudioInpaintInput,
    output: zAceStepAudioInpaintOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ace-step/audio-to-audio"),
    input: zAceStepAudioToAudioInput,
    output: zAceStepAudioToAudioOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/dia-tts/voice-clone"),
    input: zDiaTtsVoiceCloneInput,
    output: zDiaTtsVoiceCloneOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/elevenlabs/audio-isolation"),
    input: zElevenlabsAudioIsolationInput,
    output: zElevenlabsAudioIsolationOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/elevenlabs/music"),
    input: zElevenlabsMusicInput,
    output: zElevenlabsMusicOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax-music/v2"),
    input: zMinimaxMusicV2Input,
    output: zMinimaxMusicV2Output,
  }),
  z.object({
    endpoint: z.literal("beatoven/sound-effect-generation"),
    input: zSoundEffectGenerationInput,
    output: zSoundEffectGenerationOutput,
  }),
  z.object({
    endpoint: z.literal("beatoven/music-generation"),
    input: zMusicGenerationInput,
    output: zMusicGenerationOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax-music/v1.5"),
    input: zMinimaxMusicV15Input,
    output: zMinimaxMusicV15Output,
  }),
  z.object({
    endpoint: z.literal("fal-ai/stable-audio-25/text-to-audio"),
    input: zStableAudio25TextToAudioInput,
    output: zStableAudio25TextToAudioOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/elevenlabs/text-to-dialogue/eleven-v3"),
    input: zElevenlabsTextToDialogueElevenV3Input,
    output: zElevenlabsTextToDialogueElevenV3Output,
  }),
  z.object({
    endpoint: z.literal("fal-ai/elevenlabs/sound-effects/v2"),
    input: zElevenlabsSoundEffectsV2Input,
    output: zElevenlabsSoundEffectsV2Output,
  }),
  z.object({
    endpoint: z.literal("sonauto/v2/inpaint"),
    input: zV2InpaintInput,
    output: zV2InpaintOutput,
  }),
  z.object({
    endpoint: z.literal("sonauto/v2/text-to-music"),
    input: zV2TextToMusicInput,
    output: zV2TextToMusicOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/elevenlabs/tts/eleven-v3"),
    input: zElevenlabsTtsElevenV3Input,
    output: zElevenlabsTtsElevenV3Output,
  }),
  z.object({
    endpoint: z.literal("fal-ai/lyria2"),
    input: zLyria2Input,
    output: zLyria2Output,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ace-step/prompt-to-audio"),
    input: zAceStepPromptToAudioInput,
    output: zAceStepPromptToAudioOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ace-step"),
    input: zAceStepInput,
    output: zAceStepOutput,
  }),
  z.object({
    endpoint: z.literal("cassetteai/sound-effects-generator"),
    input: zSoundEffectsGeneratorInput,
    output: zSoundEffectsGeneratorOutput,
  }),
  z.object({
    endpoint: z.literal("cassetteai/music-generator"),
    input: zMusicGeneratorInput,
    output: zMusicGeneratorOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/csm-1b"),
    input: zCsm1bInput,
    output: zCsm1bOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/diffrhythm"),
    input: zDiffrhythmInput,
    output: zDiffrhythmOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/elevenlabs/tts/multilingual-v2"),
    input: zElevenlabsTtsMultilingualV2Input,
    output: zElevenlabsTtsMultilingualV2Output,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kokoro/hindi"),
    input: zKokoroHindiInput,
    output: zKokoroHindiOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kokoro/british-english"),
    input: zKokoroBritishEnglishInput,
    output: zKokoroBritishEnglishOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kokoro/american-english"),
    input: zKokoroAmericanEnglishInput,
    output: zKokoroAmericanEnglishOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/zonos"),
    input: zZonosInput,
    output: zZonosOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kokoro/italian"),
    input: zKokoroItalianInput,
    output: zKokoroItalianOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kokoro/brazilian-portuguese"),
    input: zKokoroBrazilianPortugueseInput,
    output: zKokoroBrazilianPortugueseOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kokoro/french"),
    input: zKokoroFrenchInput,
    output: zKokoroFrenchOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kokoro/japanese"),
    input: zKokoroJapaneseInput,
    output: zKokoroJapaneseOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kokoro/mandarin-chinese"),
    input: zKokoroMandarinChineseInput,
    output: zKokoroMandarinChineseOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kokoro/spanish"),
    input: zKokoroSpanishInput,
    output: zKokoroSpanishOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/yue"),
    input: zYueInput,
    output: zYueOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/mmaudio-v2/text-to-audio"),
    input: zMmaudioV2TextToAudioInput,
    output: zMmaudioV2TextToAudioOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax-music"),
    input: zMinimaxMusicInput,
    output: zMinimaxMusicOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/f5-tts"),
    input: zF5TtsInput,
    output: zF5TtsOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/stable-audio"),
    input: zStableAudioInput,
    output: zStableAudioOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sam-audio/visual-separate"),
    input: zSamAudioVisualSeparateInput,
    output: zSamAudioVisualSeparateOutput,
  }),
  z.object({
    endpoint: z.literal("mirelo-ai/sfx-v1.5/video-to-audio"),
    input: zSfxV15VideoToAudioInput,
    output: zSfxV15VideoToAudioOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/video-to-audio"),
    input: zKlingVideoVideoToAudioInput,
    output: zKlingVideoVideoToAudioOutput,
  }),
  z.object({
    endpoint: z.literal("mirelo-ai/sfx-v1/video-to-audio"),
    input: zSfxV1VideoToAudioInput,
    output: zSfxV1VideoToAudioOutput,
  }),
]);

/** Inferred type from AudioEndpointSchema */
export type AudioEndpoint = z.infer<typeof AudioEndpointSchema>;
