// AUTO-GENERATED - Do not edit manually
// Generated via scripts/generate-endpoint-maps.ts

import { z } from "zod";

import {
  zAuraFlowInput,
  zAuraSrInput,
  zBackgroundRemovalInput,
  zBagelEditInput,
  zBagelInput,
  zBenV2ImageInput,
  zBitdanceInput,
  zBriaBackgroundRemoveInput,
  zBriaBackgroundReplaceInput,
  zBriaEraserInput,
  zBriaExpandInput,
  zBriaGenfillInput,
  zBriaProductShotInput,
  zBriaReimagineInput,
  zBriaTextToImageBaseInput,
  zBriaTextToImageFastInput,
  zBriaTextToImageHdInput,
  zBytedanceDreaminaV31TextToImageInput,
  zBytedanceSeedreamV3TextToImageInput,
  zBytedanceSeedreamV45EditInput,
  zBytedanceSeedreamV45TextToImageInput,
  zBytedanceSeedreamV4EditInput,
  zBytedanceSeedreamV4TextToImageInput,
  zBytedanceSeedreamV5LiteEditInput,
  zBytedanceSeedreamV5LiteTextToImageInput,
  zCartoonifyInput,
  zCatVtonInput,
  zCcsrInput,
  zChainOfZoomInput,
  zChronoEditInput,
  zChronoEditLoraGalleryPaintbrushInput,
  zChronoEditLoraGalleryUpscalerInput,
  zChronoEditLoraInput,
  zClarityUpscalerInput,
  zCodeformerInput,
  zCogview4Input,
  zCreativeUpscalerInput,
  zCrystalUpscalerInput,
  zDdcolorInput,
  zDocresDewarpInput,
  zDocresInput,
  zDrctSuperResolutionInput,
  zDreamoInput,
  zDreamomni2EditInput,
  zDreamshaperInput,
  zDwposeInput,
  zEmbedProductInput,
  zEmu35ImageEditImageInput,
  zEmu35ImageTextToImageInput,
  zEra3dInput,
  zErnieImageInput,
  zErnieImageLoraInput,
  zErnieImageLoraTurboInput,
  zErnieImageTurboInput,
  zEsrganInput,
  zEvfSamInput,
  zFLiteStandardInput,
  zFLiteTextureInput,
  zFaceToStickerInput,
  zFashnTryonV15Input,
  zFashnTryonV16Input,
  zFastFooocusSdxlImageToImageInput,
  zFastFooocusSdxlInput,
  zFastLcmDiffusionImageToImageInput,
  zFastLcmDiffusionInpaintingInput,
  zFastLcmDiffusionInput,
  zFastLightningSdxlImageToImageInput,
  zFastLightningSdxlInpaintingInput,
  zFastLightningSdxlInput,
  zFastSdxlControlnetCannyImageToImageInput,
  zFastSdxlControlnetCannyInpaintingInput,
  zFastSdxlControlnetCannyInput,
  zFastSdxlImageToImageInput,
  zFastSdxlInpaintingInput,
  zFastSdxlInput,
  zFiboBbqPreviewGenerateInput,
  zFiboEditAddObjectByTextInput,
  zFiboEditBlendInput,
  zFiboEditColorizeInput,
  zFiboEditEditInput,
  zFiboEditEraseByTextInput,
  zFiboEditRelightInput,
  zFiboEditReplaceObjectByTextInput,
  zFiboEditReseasonInput,
  zFiboEditRestoreInput,
  zFiboEditRestyleInput,
  zFiboEditRewriteTextInput,
  zFiboEditSketchToColoredImageInput,
  zFiboGenerateInput,
  zFiboLiteGenerateInput,
  zFireredImageEditInput,
  zFireredImageEditV11Input,
  zFlorence2LargeCaptionToPhraseGroundingInput,
  zFlorence2LargeDenseRegionCaptionInput,
  zFlorence2LargeObjectDetectionInput,
  zFlorence2LargeOcrWithRegionInput,
  zFlorence2LargeOpenVocabularyDetectionInput,
  zFlorence2LargeReferringExpressionSegmentationInput,
  zFlorence2LargeRegionProposalInput,
  zFlorence2LargeRegionToSegmentationInput,
  zFloweditInput,
  zFlux1DevImageToImageInput,
  zFlux1DevInput,
  zFlux1DevReduxInput,
  zFlux1KreaImageToImageInput,
  zFlux1KreaInput,
  zFlux1KreaReduxInput,
  zFlux1SchnellInput,
  zFlux1SchnellReduxInput,
  zFlux1SrpoImageToImageInput,
  zFlux1SrpoInput,
  zFlux2EditInput,
  zFlux2FlashEditInput,
  zFlux2FlashInput,
  zFlux2FlexEditInput,
  zFlux2FlexInput,
  zFlux2Input,
  zFlux2Klein4bBaseEditInput,
  zFlux2Klein4bBaseEditLoraInput,
  zFlux2Klein4bBaseInput,
  zFlux2Klein4bBaseLoraInput,
  zFlux2Klein4bEditInput,
  zFlux2Klein4bEditLoraInput,
  zFlux2Klein4bInput,
  zFlux2Klein4bLoraInput,
  zFlux2Klein9bBaseEditInput,
  zFlux2Klein9bBaseEditLoraInput,
  zFlux2Klein9bBaseInput,
  zFlux2Klein9bBaseLoraInput,
  zFlux2Klein9bEditInput,
  zFlux2Klein9bEditLoraInput,
  zFlux2Klein9bInput,
  zFlux2Klein9bLoraInput,
  zFlux2KleinRealtimeInput,
  zFlux2LoraEditInput,
  zFlux2LoraGalleryAddBackgroundInput,
  zFlux2LoraGalleryApartmentStagingInput,
  zFlux2LoraGalleryBallpointPenSketchInput,
  zFlux2LoraGalleryDigitalComicArtInput,
  zFlux2LoraGalleryFaceToFullPortraitInput,
  zFlux2LoraGalleryHdrStyleInput,
  zFlux2LoraGalleryMultipleAnglesInput,
  zFlux2LoraGalleryRealismInput,
  zFlux2LoraGallerySatelliteViewStyleInput,
  zFlux2LoraGallerySepiaVintageInput,
  zFlux2LoraGalleryVirtualTryonInput,
  zFlux2LoraInput,
  zFlux2MaxEditInput,
  zFlux2MaxInput,
  zFlux2ProEditInput,
  zFlux2ProInput,
  zFlux2TurboEditInput,
  zFlux2TurboInput,
  zFluxControlLoraCannyImageToImageInput,
  zFluxControlLoraCannyInput,
  zFluxControlLoraDepthImageToImageInput,
  zFluxControlLoraDepthInput,
  zFluxDevImageToImageInput,
  zFluxDevInput,
  zFluxDevReduxInput,
  zFluxDifferentialDiffusionInput,
  zFluxGeneralDifferentialDiffusionInput,
  zFluxGeneralImageToImageInput,
  zFluxGeneralInpaintingInput,
  zFluxGeneralInput,
  zFluxGeneralRfInversionInput,
  zFluxKontextDevInput,
  zFluxKontextLoraInpaintInput,
  zFluxKontextLoraInput,
  zFluxKontextLoraTextToImageInput,
  zFluxKreaImageToImageInput,
  zFluxKreaInput,
  zFluxKreaLoraImageToImageInput,
  zFluxKreaLoraInpaintingInput,
  zFluxKreaLoraInput,
  zFluxKreaLoraStreamInput,
  zFluxKreaReduxInput,
  zFluxLoraCannyInput,
  zFluxLoraDepthInput,
  zFluxLoraFillInput,
  zFluxLoraImageToImageInput,
  zFluxLoraInpaintingInput,
  zFluxLoraInput,
  zFluxLoraStreamInput,
  zFluxProKontextInput,
  zFluxProKontextMaxInput,
  zFluxProKontextMaxMultiInput,
  zFluxProKontextMaxTextToImageInput,
  zFluxProKontextMultiInput,
  zFluxProKontextTextToImageInput,
  zFluxProV11Input,
  zFluxProV11ReduxInput,
  zFluxProV11UltraFinetunedInput,
  zFluxProV11UltraInput,
  zFluxProV11UltraReduxInput,
  zFluxProV1FillFinetunedInput,
  zFluxProV1FillInput,
  zFluxPulidInput,
  zFluxSchnellInput,
  zFluxSchnellReduxInput,
  zFluxSrpoImageToImageInput,
  zFluxSrpoInput,
  zFluxSubjectInput,
  zFluxVisionUpscalerInput,
  zFooocusImagePromptInput,
  zFooocusInpaintInput,
  zFooocusInput,
  zFooocusUpscaleOrVaryInput,
  zGemini25FlashImageEditInput,
  zGemini25FlashImageInput,
  zGemini31FlashImagePreviewEditInput,
  zGemini31FlashImagePreviewInput,
  zGemini3ProImagePreviewEditInput,
  zGemini3ProImagePreviewInput,
  zGenfocusAllInFocusInput,
  zGenfocusInput,
  zGhiblifyInput,
  zGlmImageImageToImageInput,
  zGlmImageInput,
  zGptImage15EditInput,
  zGptImage15Input,
  zGptImage1EditImageInput,
  zGptImage1MiniEditInput,
  zGptImage1MiniInput,
  zGptImage1TextToImageInput,
  zGptImage2EditInput,
  zGptImage2Input,
  zGrokImagineImageEditInput,
  zGrokImagineImageInput,
  zGrokImagineImageQualityEditInput,
  zGrokImagineImageQualityTextToImageInput,
  zHidreamE11Input,
  zHidreamI1DevInput,
  zHidreamI1FastInput,
  zHidreamI1FullImageToImageInput,
  zHidreamI1FullInput,
  zHidreamO1ImageDevEditInput,
  zHidreamO1ImageDevInput,
  zHidreamO1ImageEditInput,
  zHidreamO1ImageInput,
  zHunyuanImageV21TextToImageInput,
  zHunyuanImageV3InstructEditInput,
  zHunyuanImageV3InstructTextToImageInput,
  zHunyuanImageV3TextToImageInput,
  zHunyuanWorldInput,
  zHyWuEditInput,
  zIclightV2Input,
  zIdeogramCharacterEditInput,
  zIdeogramCharacterInput,
  zIdeogramCharacterRemixInput,
  zIdeogramCustomModelsGenerateInput,
  zIdeogramRemoveBackgroundInput,
  zIdeogramUpscaleInput,
  zIdeogramV2EditInput,
  zIdeogramV2Input,
  zIdeogramV2RemixInput,
  zIdeogramV2TurboEditInput,
  zIdeogramV2TurboInput,
  zIdeogramV2TurboRemixInput,
  zIdeogramV2aInput,
  zIdeogramV2aRemixInput,
  zIdeogramV2aTurboInput,
  zIdeogramV2aTurboRemixInput,
  zIdeogramV3EditInput,
  zIdeogramV3GenerateTransparentInput,
  zIdeogramV3Input,
  zIdeogramV3LayerizeTextInput,
  zIdeogramV3ReframeInput,
  zIdeogramV3RemixInput,
  zIdeogramV3ReplaceBackgroundInput,
  zIllusionDiffusionInput,
  zImage2PixelInput,
  zImage2SvgInput,
  zImageAppsV2AgeModifyInput,
  zImageAppsV2CityTeleportInput,
  zImageAppsV2ExpressionChangeInput,
  zImageAppsV2HairChangeInput,
  zImageAppsV2HeadshotPhotoInput,
  zImageAppsV2MakeupApplicationInput,
  zImageAppsV2ObjectRemovalInput,
  zImageAppsV2OutpaintInput,
  zImageAppsV2PerspectiveInput,
  zImageAppsV2PhotoRestorationInput,
  zImageAppsV2PhotographyEffectsInput,
  zImageAppsV2PortraitEnhanceInput,
  zImageAppsV2ProductHoldingInput,
  zImageAppsV2ProductPhotographyInput,
  zImageAppsV2RelightingInput,
  zImageAppsV2StyleTransferInput,
  zImageAppsV2TextureTransformInput,
  zImageAppsV2VirtualTryOnInput,
  zImageEditingAgeProgressionInput,
  zImageEditingBabyVersionInput,
  zImageEditingBackgroundChangeInput,
  zImageEditingBroccoliHaircutInput,
  zImageEditingCartoonifyInput,
  zImageEditingColorCorrectionInput,
  zImageEditingExpressionChangeInput,
  zImageEditingFaceEnhancementInput,
  zImageEditingHairChangeInput,
  zImageEditingObjectRemovalInput,
  zImageEditingPhotoRestorationInput,
  zImageEditingPlushieStyleInput,
  zImageEditingProfessionalPhotoInput,
  zImageEditingRealismInput,
  zImageEditingReframeInput,
  zImageEditingRetouchInput,
  zImageEditingSceneCompositionInput,
  zImageEditingStyleTransferInput,
  zImageEditingTextRemovalInput,
  zImageEditingTimeOfDayInput,
  zImageEditingWeatherEffectInput,
  zImageEditingWojakStyleInput,
  zImageEditingYoutubeThumbnailsInput,
  zImagePreprocessorsDepthAnythingV2Input,
  zImagePreprocessorsHedInput,
  zImagePreprocessorsLineartInput,
  zImagePreprocessorsMidasInput,
  zImagePreprocessorsMlsdInput,
  zImagePreprocessorsPidiInput,
  zImagePreprocessorsSamInput,
  zImagePreprocessorsScribbleInput,
  zImagePreprocessorsTeedInput,
  zImagePreprocessorsZoeInput,
  zImagen3FastInput,
  zImagen3Input,
  zImagen4PreviewFastInput,
  zImagen4PreviewInput,
  zImagen4PreviewUltraInput,
  zImageutilsDepthInput,
  zImageutilsMarigoldDepthInput,
  zImageutilsRembgInput,
  zImagineart15PreviewTextToImageInput,
  zImagineart15ProPreviewTextToImageInput,
  zImagineart20PreviewTextToImageInput,
  zInpaintInput,
  zInstantCharacterInput,
  zInvisibleWatermarkInput,
  zIpAdapterFaceIdInput,
  zJanusInput,
  zJoyaiImageEditInput,
  zJuggernautFluxLoraInpaintingInput,
  zJuggernautFluxLoraInput,
  zKlingImageO1Input,
  zKlingImageO3ImageToImageInput,
  zKlingImageO3TextToImageInput,
  zKlingImageV3ImageToImageInput,
  zKlingImageV3TextToImageInput,
  zKlingV15KolorsVirtualTryOnInput,
  zKolorsImageToImageInput,
  zKolorsInput,
  zLayerDiffusionInput,
  zLcmInput,
  zLcmSd15I2iInput,
  zLeffaPoseTransferInput,
  zLeffaVirtualTryonInput,
  zLightningModelsInput,
  zLivePortraitImageInput,
  zLongcatImageEditInput,
  zLongcatImageInput,
  zLoraImageToImageInput,
  zLoraInpaintInput,
  zLoraInput,
  zLucidfluxInput,
  zLumaPhotonFlashInput,
  zLumaPhotonFlashModifyInput,
  zLumaPhotonFlashReframeInput,
  zLumaPhotonInput,
  zLumaPhotonModifyInput,
  zLumaPhotonReframeInput,
  zLuminaImageV2Input,
  zMinimaxImage01Input,
  zMinimaxImage01SubjectReferenceInput,
  zMixDehazeNetInput,
  zMoondream3PreviewSegmentInput,
  zMoondreamNextDetectionInput,
  zNafnetDeblurInput,
  zNafnetDenoiseInput,
  zNanoBanana2EditInput,
  zNanoBanana2Input,
  zNanoBananaEditInput,
  zNanoBananaInput,
  zNanoBananaProEditInput,
  zNanoBananaProInput,
  zNucleusImageInput,
  zObjectRemovalBboxInput,
  zObjectRemovalInput,
  zObjectRemovalMaskInput,
  zOmniZeroInput,
  zOmnigenV1Input,
  zOmnigenV2Input,
  zOnerewardInput,
  zOvisImageInput,
  zPasdInput,
  zPatinaInput,
  zPatinaMaterialExtractInput,
  zPatinaMaterialInput,
  zPhotaEditInput,
  zPhotaEnhanceInput,
  zPhotaInput,
  zPhotomakerInput,
  zPhysicEditInput,
  zPiflowInput,
  zPixartSigmaInput,
  zPlaygroundV25ImageToImageInput,
  zPlaygroundV25InpaintingInput,
  zPlaygroundV25Input,
  zPlushifyInput,
  zPonyV7Input,
  zPostProcessingBlurInput,
  zPostProcessingChromaticAberrationInput,
  zPostProcessingColorCorrectionInput,
  zPostProcessingColorTintInput,
  zPostProcessingDesaturateInput,
  zPostProcessingDissolveInput,
  zPostProcessingDodgeBurnInput,
  zPostProcessingGrainInput,
  zPostProcessingInput,
  zPostProcessingParabolizeInput,
  zPostProcessingSharpenInput,
  zPostProcessingSolarizeInput,
  zPostProcessingVignetteInput,
  zPulidInput,
  zQueueStatus,
  zQwenImage2512Input,
  zQwenImage2512LoraInput,
  zQwenImage2EditInput,
  zQwenImage2ProEditInput,
  zQwenImage2ProTextToImageInput,
  zQwenImage2TextToImageInput,
  zQwenImageEdit2509Input,
  zQwenImageEdit2509LoraGalleryAddBackgroundInput,
  zQwenImageEdit2509LoraGalleryFaceToFullPortraitInput,
  zQwenImageEdit2509LoraGalleryGroupPhotoInput,
  zQwenImageEdit2509LoraGalleryIntegrateProductInput,
  zQwenImageEdit2509LoraGalleryLightingRestorationInput,
  zQwenImageEdit2509LoraGalleryMultipleAnglesInput,
  zQwenImageEdit2509LoraGalleryNextSceneInput,
  zQwenImageEdit2509LoraGalleryRemoveElementInput,
  zQwenImageEdit2509LoraGalleryRemoveLightingInput,
  zQwenImageEdit2509LoraGalleryShirtDesignInput,
  zQwenImageEdit2509LoraInput,
  zQwenImageEdit2511Input,
  zQwenImageEdit2511LoraInput,
  zQwenImageEdit2511MultipleAnglesInput,
  zQwenImageEditImageToImageInput,
  zQwenImageEditInpaintInput,
  zQwenImageEditInput,
  zQwenImageEditLoraInput,
  zQwenImageEditPlusInput,
  zQwenImageEditPlusLoraGalleryAddBackgroundInput,
  zQwenImageEditPlusLoraGalleryFaceToFullPortraitInput,
  zQwenImageEditPlusLoraGalleryGroupPhotoInput,
  zQwenImageEditPlusLoraGalleryIntegrateProductInput,
  zQwenImageEditPlusLoraGalleryLightingRestorationInput,
  zQwenImageEditPlusLoraGalleryMultipleAnglesInput,
  zQwenImageEditPlusLoraGalleryNextSceneInput,
  zQwenImageEditPlusLoraGalleryRemoveElementInput,
  zQwenImageEditPlusLoraGalleryRemoveLightingInput,
  zQwenImageEditPlusLoraGalleryShirtDesignInput,
  zQwenImageEditPlusLoraInput,
  zQwenImageImageToImageInput,
  zQwenImageInput,
  zQwenImageLayeredInput,
  zQwenImageLayeredLoraInput,
  zQwenImageMaxEditInput,
  zQwenImageMaxTextToImageInput,
  zRealisticVisionInput,
  zRecraft20bInput,
  zRecraftUpscaleCreativeInput,
  zRecraftUpscaleCrispInput,
  zRecraftV3ImageToImageInput,
  zRecraftV3TextToImageInput,
  zRecraftV4ProTextToImageInput,
  zRecraftV4ProTextToVectorInput,
  zRecraftV4TextToImageInput,
  zRecraftV4TextToVectorInput,
  zRecraftVectorizeInput,
  zReimagine32Input,
  zRembgEnhanceInput,
  zReplaceBackgroundInput,
  zRetoucherInput,
  zRifeInput,
  zRundiffusionPhotoFluxInput,
  zSam2AutoSegmentInput,
  zSam2ImageInput,
  zSam31ImageInput,
  zSam31ImageRleInput,
  zSam3ImageInput,
  zSam3ImageRleInput,
  zSanaInput,
  zSanaSprintInput,
  zSanaV1516bInput,
  zSanaV1548bInput,
  zSd15DepthControlnetInput,
  zSdxlControlnetUnionImageToImageInput,
  zSdxlControlnetUnionInpaintingInput,
  zSdxlControlnetUnionInput,
  zSeedvrUpscaleImageInput,
  zSeedvrUpscaleImageSeamlessInput,
  zSmartResizeInput,
  zStableCascadeInput,
  zStableCascadeSoteDiffusionInput,
  zStableDiffusionV15Input,
  zStableDiffusionV35LargeInput,
  zStableDiffusionV35MediumInput,
  zStableDiffusionV3MediumImageToImageInput,
  zStableDiffusionV3MediumInput,
  zStarVectorInput,
  zStep1xEditInput,
  zStepxEdit2Input,
  zSwin2SrInput,
  zSwitti512Input,
  zSwittiInput,
  zTheraInput,
  zTopazUpscaleImageInput,
  zUnoInput,
  zUpscaleCreativeInput,
  zUsoInput,
  zV26ImageToImageInput,
  zV26TextToImageInput,
  zVecglypherImageToSvgInput,
  zVecglypherInput,
  zViduQ2ReferenceToImageInput,
  zViduQ2TextToImageInput,
  zViduReferenceToImageInput,
  zWan25PreviewImageToImageInput,
  zWan25PreviewTextToImageInput,
  zWanV225bTextToImageInput,
  zWanV22A14bImageToImageInput,
  zWanV22A14bTextToImageInput,
  zWanV22A14bTextToImageLoraInput,
  zWanV27EditInput,
  zWanV27ProEditInput,
  zWanV27ProTextToImageInput,
  zWanV27TextToImageInput,
  zWorkflowUtilitiesExtractNthFrameInput,
  zZImageBaseInput,
  zZImageBaseLoraInput,
  zZImageTurboControlnetInput,
  zZImageTurboControlnetLoraInput,
  zZImageTurboImageToImageInput,
  zZImageTurboImageToImageLoraInput,
  zZImageTurboInpaintInput,
  zZImageTurboInpaintLoraInput,
  zZImageTurboInput,
  zZImageTurboLoraInput,
  zZImageTurboTilingInput,
  zZImageTurboTilingLoraInput,
} from "./zod.gen";

/** Zod schema for image endpoints using discriminatedUnion */
export const ImageEndpointSchema = z.discriminatedUnion("endpoint", [
  z.object({
    endpoint: z.literal("bria/embed-product"),
    input: zEmbedProductInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/fibo-bbq-preview/generate"),
    input: zFiboBbqPreviewGenerateInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/fibo-edit/add_object_by_text"),
    input: zFiboEditAddObjectByTextInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/fibo-edit/blend"),
    input: zFiboEditBlendInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/fibo-edit/colorize"),
    input: zFiboEditColorizeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/fibo-edit/edit"),
    input: zFiboEditEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/fibo-edit/erase_by_text"),
    input: zFiboEditEraseByTextInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/fibo-edit/relight"),
    input: zFiboEditRelightInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/fibo-edit/replace_object_by_text"),
    input: zFiboEditReplaceObjectByTextInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/fibo-edit/reseason"),
    input: zFiboEditReseasonInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/fibo-edit/restore"),
    input: zFiboEditRestoreInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/fibo-edit/restyle"),
    input: zFiboEditRestyleInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/fibo-edit/rewrite_text"),
    input: zFiboEditRewriteTextInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/fibo-edit/sketch_to_colored_image"),
    input: zFiboEditSketchToColoredImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/fibo-lite/generate"),
    input: zFiboLiteGenerateInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/fibo/generate"),
    input: zFiboGenerateInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/reimagine/3.2"),
    input: zReimagine32Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/replace-background"),
    input: zReplaceBackgroundInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("bria/upscale/creative"),
    input: zUpscaleCreativeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("clarityai/crystal-upscaler"),
    input: zCrystalUpscalerInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/aura-flow"),
    input: zAuraFlowInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/aura-sr"),
    input: zAuraSrInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bagel"),
    input: zBagelInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bagel/edit"),
    input: zBagelEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ben/v2/image"),
    input: zBenV2ImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bitdance"),
    input: zBitdanceInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bria/background/remove"),
    input: zBriaBackgroundRemoveInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bria/background/replace"),
    input: zBriaBackgroundReplaceInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bria/eraser"),
    input: zBriaEraserInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bria/expand"),
    input: zBriaExpandInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bria/genfill"),
    input: zBriaGenfillInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bria/product-shot"),
    input: zBriaProductShotInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bria/reimagine"),
    input: zBriaReimagineInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bria/text-to-image/base"),
    input: zBriaTextToImageBaseInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bria/text-to-image/fast"),
    input: zBriaTextToImageFastInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bria/text-to-image/hd"),
    input: zBriaTextToImageHdInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/dreamina/v3.1/text-to-image"),
    input: zBytedanceDreaminaV31TextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seedream/v3/text-to-image"),
    input: zBytedanceSeedreamV3TextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seedream/v4.5/edit"),
    input: zBytedanceSeedreamV45EditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seedream/v4.5/text-to-image"),
    input: zBytedanceSeedreamV45TextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seedream/v4/edit"),
    input: zBytedanceSeedreamV4EditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seedream/v4/text-to-image"),
    input: zBytedanceSeedreamV4TextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seedream/v5/lite/edit"),
    input: zBytedanceSeedreamV5LiteEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seedream/v5/lite/text-to-image"),
    input: zBytedanceSeedreamV5LiteTextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/cartoonify"),
    input: zCartoonifyInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/cat-vton"),
    input: zCatVtonInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ccsr"),
    input: zCcsrInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/chain-of-zoom"),
    input: zChainOfZoomInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/chrono-edit"),
    input: zChronoEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/chrono-edit-lora"),
    input: zChronoEditLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/chrono-edit-lora-gallery/paintbrush"),
    input: zChronoEditLoraGalleryPaintbrushInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/chrono-edit-lora-gallery/upscaler"),
    input: zChronoEditLoraGalleryUpscalerInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/clarity-upscaler"),
    input: zClarityUpscalerInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/codeformer"),
    input: zCodeformerInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/cogview4"),
    input: zCogview4Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/creative-upscaler"),
    input: zCreativeUpscalerInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ddcolor"),
    input: zDdcolorInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/docres"),
    input: zDocresInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/docres/dewarp"),
    input: zDocresDewarpInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/drct-super-resolution"),
    input: zDrctSuperResolutionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/dreamo"),
    input: zDreamoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/dreamomni2/edit"),
    input: zDreamomni2EditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/dreamshaper"),
    input: zDreamshaperInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/dwpose"),
    input: zDwposeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/emu-3.5-image/edit-image"),
    input: zEmu35ImageEditImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/emu-3.5-image/text-to-image"),
    input: zEmu35ImageTextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/era-3d"),
    input: zEra3dInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ernie-image"),
    input: zErnieImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ernie-image/lora"),
    input: zErnieImageLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ernie-image/lora/turbo"),
    input: zErnieImageLoraTurboInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ernie-image/turbo"),
    input: zErnieImageTurboInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/esrgan"),
    input: zEsrganInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/evf-sam"),
    input: zEvfSamInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/f-lite/standard"),
    input: zFLiteStandardInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/f-lite/texture"),
    input: zFLiteTextureInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/face-to-sticker"),
    input: zFaceToStickerInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fashn/tryon/v1.5"),
    input: zFashnTryonV15Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fashn/tryon/v1.6"),
    input: zFashnTryonV16Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-fooocus-sdxl"),
    input: zFastFooocusSdxlInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-fooocus-sdxl/image-to-image"),
    input: zFastFooocusSdxlImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-lcm-diffusion"),
    input: zFastLcmDiffusionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-lcm-diffusion/image-to-image"),
    input: zFastLcmDiffusionImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-lcm-diffusion/inpainting"),
    input: zFastLcmDiffusionInpaintingInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-lightning-sdxl"),
    input: zFastLightningSdxlInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-lightning-sdxl/image-to-image"),
    input: zFastLightningSdxlImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-lightning-sdxl/inpainting"),
    input: zFastLightningSdxlInpaintingInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-sdxl"),
    input: zFastSdxlInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-sdxl-controlnet-canny"),
    input: zFastSdxlControlnetCannyInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-sdxl-controlnet-canny/image-to-image"),
    input: zFastSdxlControlnetCannyImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-sdxl-controlnet-canny/inpainting"),
    input: zFastSdxlControlnetCannyInpaintingInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-sdxl/image-to-image"),
    input: zFastSdxlImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-sdxl/inpainting"),
    input: zFastSdxlInpaintingInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/firered-image-edit"),
    input: zFireredImageEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/firered-image-edit-v1.1"),
    input: zFireredImageEditV11Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/florence-2-large/caption-to-phrase-grounding"),
    input: zFlorence2LargeCaptionToPhraseGroundingInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/florence-2-large/dense-region-caption"),
    input: zFlorence2LargeDenseRegionCaptionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/florence-2-large/object-detection"),
    input: zFlorence2LargeObjectDetectionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/florence-2-large/ocr-with-region"),
    input: zFlorence2LargeOcrWithRegionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/florence-2-large/open-vocabulary-detection"),
    input: zFlorence2LargeOpenVocabularyDetectionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/florence-2-large/referring-expression-segmentation",
    ),
    input: zFlorence2LargeReferringExpressionSegmentationInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/florence-2-large/region-proposal"),
    input: zFlorence2LargeRegionProposalInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/florence-2-large/region-to-segmentation"),
    input: zFlorence2LargeRegionToSegmentationInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flowedit"),
    input: zFloweditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-1/dev"),
    input: zFlux1DevInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-1/dev/image-to-image"),
    input: zFlux1DevImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-1/dev/redux"),
    input: zFlux1DevReduxInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-1/krea"),
    input: zFlux1KreaInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-1/krea/image-to-image"),
    input: zFlux1KreaImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-1/krea/redux"),
    input: zFlux1KreaReduxInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-1/schnell"),
    input: zFlux1SchnellInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-1/schnell/redux"),
    input: zFlux1SchnellReduxInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-1/srpo"),
    input: zFlux1SrpoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-1/srpo/image-to-image"),
    input: zFlux1SrpoImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2"),
    input: zFlux2Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2-flex"),
    input: zFlux2FlexInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2-flex/edit"),
    input: zFlux2FlexEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2-lora-gallery/add-background"),
    input: zFlux2LoraGalleryAddBackgroundInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2-lora-gallery/apartment-staging"),
    input: zFlux2LoraGalleryApartmentStagingInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2-lora-gallery/ballpoint-pen-sketch"),
    input: zFlux2LoraGalleryBallpointPenSketchInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2-lora-gallery/digital-comic-art"),
    input: zFlux2LoraGalleryDigitalComicArtInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2-lora-gallery/face-to-full-portrait"),
    input: zFlux2LoraGalleryFaceToFullPortraitInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2-lora-gallery/hdr-style"),
    input: zFlux2LoraGalleryHdrStyleInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2-lora-gallery/multiple-angles"),
    input: zFlux2LoraGalleryMultipleAnglesInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2-lora-gallery/realism"),
    input: zFlux2LoraGalleryRealismInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2-lora-gallery/satellite-view-style"),
    input: zFlux2LoraGallerySatelliteViewStyleInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2-lora-gallery/sepia-vintage"),
    input: zFlux2LoraGallerySepiaVintageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2-lora-gallery/virtual-tryon"),
    input: zFlux2LoraGalleryVirtualTryonInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2-max"),
    input: zFlux2MaxInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2-max/edit"),
    input: zFlux2MaxEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2-pro"),
    input: zFlux2ProInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2-pro/edit"),
    input: zFlux2ProEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2/edit"),
    input: zFlux2EditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2/flash"),
    input: zFlux2FlashInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2/flash/edit"),
    input: zFlux2FlashEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2/klein/4b"),
    input: zFlux2Klein4bInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2/klein/4b/base"),
    input: zFlux2Klein4bBaseInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2/klein/4b/base/edit"),
    input: zFlux2Klein4bBaseEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2/klein/4b/base/edit/lora"),
    input: zFlux2Klein4bBaseEditLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2/klein/4b/base/lora"),
    input: zFlux2Klein4bBaseLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2/klein/4b/edit"),
    input: zFlux2Klein4bEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2/klein/4b/edit/lora"),
    input: zFlux2Klein4bEditLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2/klein/4b/lora"),
    input: zFlux2Klein4bLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2/klein/9b"),
    input: zFlux2Klein9bInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2/klein/9b/base"),
    input: zFlux2Klein9bBaseInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2/klein/9b/base/edit"),
    input: zFlux2Klein9bBaseEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2/klein/9b/base/edit/lora"),
    input: zFlux2Klein9bBaseEditLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2/klein/9b/base/lora"),
    input: zFlux2Klein9bBaseLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2/klein/9b/edit"),
    input: zFlux2Klein9bEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2/klein/9b/edit/lora"),
    input: zFlux2Klein9bEditLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2/klein/9b/lora"),
    input: zFlux2Klein9bLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2/klein/realtime"),
    input: zFlux2KleinRealtimeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2/lora"),
    input: zFlux2LoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2/lora/edit"),
    input: zFlux2LoraEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2/turbo"),
    input: zFlux2TurboInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2/turbo/edit"),
    input: zFlux2TurboEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-control-lora-canny"),
    input: zFluxControlLoraCannyInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-control-lora-canny/image-to-image"),
    input: zFluxControlLoraCannyImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-control-lora-depth"),
    input: zFluxControlLoraDepthInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-control-lora-depth/image-to-image"),
    input: zFluxControlLoraDepthImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-differential-diffusion"),
    input: zFluxDifferentialDiffusionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-general"),
    input: zFluxGeneralInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-general/differential-diffusion"),
    input: zFluxGeneralDifferentialDiffusionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-general/image-to-image"),
    input: zFluxGeneralImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-general/inpainting"),
    input: zFluxGeneralInpaintingInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-general/rf-inversion"),
    input: zFluxGeneralRfInversionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-kontext-lora"),
    input: zFluxKontextLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-kontext-lora/inpaint"),
    input: zFluxKontextLoraInpaintInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-kontext-lora/text-to-image"),
    input: zFluxKontextLoraTextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-kontext/dev"),
    input: zFluxKontextDevInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-krea-lora"),
    input: zFluxKreaLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-krea-lora/image-to-image"),
    input: zFluxKreaLoraImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-krea-lora/inpainting"),
    input: zFluxKreaLoraInpaintingInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-krea-lora/stream"),
    input: zFluxKreaLoraStreamInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-lora"),
    input: zFluxLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-lora-canny"),
    input: zFluxLoraCannyInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-lora-depth"),
    input: zFluxLoraDepthInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-lora-fill"),
    input: zFluxLoraFillInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-lora/image-to-image"),
    input: zFluxLoraImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-lora/inpainting"),
    input: zFluxLoraInpaintingInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-lora/stream"),
    input: zFluxLoraStreamInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-pro/kontext"),
    input: zFluxProKontextInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-pro/kontext/max"),
    input: zFluxProKontextMaxInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-pro/kontext/max/multi"),
    input: zFluxProKontextMaxMultiInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-pro/kontext/max/text-to-image"),
    input: zFluxProKontextMaxTextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-pro/kontext/multi"),
    input: zFluxProKontextMultiInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-pro/kontext/text-to-image"),
    input: zFluxProKontextTextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-pro/v1.1"),
    input: zFluxProV11Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-pro/v1.1-ultra"),
    input: zFluxProV11UltraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-pro/v1.1-ultra-finetuned"),
    input: zFluxProV11UltraFinetunedInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-pro/v1.1-ultra/redux"),
    input: zFluxProV11UltraReduxInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-pro/v1.1/redux"),
    input: zFluxProV11ReduxInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-pro/v1/fill"),
    input: zFluxProV1FillInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-pro/v1/fill-finetuned"),
    input: zFluxProV1FillFinetunedInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-pulid"),
    input: zFluxPulidInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-subject"),
    input: zFluxSubjectInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-vision-upscaler"),
    input: zFluxVisionUpscalerInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux/dev"),
    input: zFluxDevInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux/dev/image-to-image"),
    input: zFluxDevImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux/dev/redux"),
    input: zFluxDevReduxInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux/krea"),
    input: zFluxKreaInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux/krea/image-to-image"),
    input: zFluxKreaImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux/krea/redux"),
    input: zFluxKreaReduxInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux/schnell"),
    input: zFluxSchnellInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux/schnell/redux"),
    input: zFluxSchnellReduxInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux/srpo"),
    input: zFluxSrpoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux/srpo/image-to-image"),
    input: zFluxSrpoImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fooocus"),
    input: zFooocusInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fooocus/image-prompt"),
    input: zFooocusImagePromptInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fooocus/inpaint"),
    input: zFooocusInpaintInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fooocus/upscale-or-vary"),
    input: zFooocusUpscaleOrVaryInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/gemini-25-flash-image"),
    input: zGemini25FlashImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/gemini-25-flash-image/edit"),
    input: zGemini25FlashImageEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/gemini-3-pro-image-preview"),
    input: zGemini3ProImagePreviewInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/gemini-3-pro-image-preview/edit"),
    input: zGemini3ProImagePreviewEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/gemini-3.1-flash-image-preview"),
    input: zGemini31FlashImagePreviewInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/gemini-3.1-flash-image-preview/edit"),
    input: zGemini31FlashImagePreviewEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/genfocus"),
    input: zGenfocusInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/genfocus/all-in-focus"),
    input: zGenfocusAllInFocusInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ghiblify"),
    input: zGhiblifyInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/glm-image"),
    input: zGlmImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/glm-image/image-to-image"),
    input: zGlmImageImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/gpt-image-1-mini"),
    input: zGptImage1MiniInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/gpt-image-1-mini/edit"),
    input: zGptImage1MiniEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/gpt-image-1.5"),
    input: zGptImage15Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/gpt-image-1.5/edit"),
    input: zGptImage15EditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/gpt-image-1/edit-image"),
    input: zGptImage1EditImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/gpt-image-1/text-to-image"),
    input: zGptImage1TextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hidream-e1-1"),
    input: zHidreamE11Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hidream-i1-dev"),
    input: zHidreamI1DevInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hidream-i1-fast"),
    input: zHidreamI1FastInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hidream-i1-full"),
    input: zHidreamI1FullInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hidream-i1-full/image-to-image"),
    input: zHidreamI1FullImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hidream-o1-image"),
    input: zHidreamO1ImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hidream-o1-image/dev"),
    input: zHidreamO1ImageDevInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hidream-o1-image/dev/edit"),
    input: zHidreamO1ImageDevEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hidream-o1-image/edit"),
    input: zHidreamO1ImageEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan_world"),
    input: zHunyuanWorldInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-image/v2.1/text-to-image"),
    input: zHunyuanImageV21TextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-image/v3/instruct/edit"),
    input: zHunyuanImageV3InstructEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-image/v3/instruct/text-to-image"),
    input: zHunyuanImageV3InstructTextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-image/v3/text-to-image"),
    input: zHunyuanImageV3TextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hy-wu-edit"),
    input: zHyWuEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/iclight-v2"),
    input: zIclightV2Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ideogram/character"),
    input: zIdeogramCharacterInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ideogram/character/edit"),
    input: zIdeogramCharacterEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ideogram/character/remix"),
    input: zIdeogramCharacterRemixInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ideogram/custom-models/generate"),
    input: zIdeogramCustomModelsGenerateInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ideogram/remove-background"),
    input: zIdeogramRemoveBackgroundInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ideogram/upscale"),
    input: zIdeogramUpscaleInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ideogram/v2"),
    input: zIdeogramV2Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ideogram/v2/edit"),
    input: zIdeogramV2EditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ideogram/v2/remix"),
    input: zIdeogramV2RemixInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ideogram/v2/turbo"),
    input: zIdeogramV2TurboInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ideogram/v2/turbo/edit"),
    input: zIdeogramV2TurboEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ideogram/v2/turbo/remix"),
    input: zIdeogramV2TurboRemixInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ideogram/v2a"),
    input: zIdeogramV2aInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ideogram/v2a/remix"),
    input: zIdeogramV2aRemixInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ideogram/v2a/turbo"),
    input: zIdeogramV2aTurboInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ideogram/v2a/turbo/remix"),
    input: zIdeogramV2aTurboRemixInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ideogram/v3"),
    input: zIdeogramV3Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ideogram/v3/edit"),
    input: zIdeogramV3EditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ideogram/v3/generate-transparent"),
    input: zIdeogramV3GenerateTransparentInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ideogram/v3/layerize-text"),
    input: zIdeogramV3LayerizeTextInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ideogram/v3/reframe"),
    input: zIdeogramV3ReframeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ideogram/v3/remix"),
    input: zIdeogramV3RemixInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ideogram/v3/replace-background"),
    input: zIdeogramV3ReplaceBackgroundInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/illusion-diffusion"),
    input: zIllusionDiffusionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-apps-v2/age-modify"),
    input: zImageAppsV2AgeModifyInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-apps-v2/city-teleport"),
    input: zImageAppsV2CityTeleportInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-apps-v2/expression-change"),
    input: zImageAppsV2ExpressionChangeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-apps-v2/hair-change"),
    input: zImageAppsV2HairChangeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-apps-v2/headshot-photo"),
    input: zImageAppsV2HeadshotPhotoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-apps-v2/makeup-application"),
    input: zImageAppsV2MakeupApplicationInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-apps-v2/object-removal"),
    input: zImageAppsV2ObjectRemovalInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-apps-v2/outpaint"),
    input: zImageAppsV2OutpaintInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-apps-v2/perspective"),
    input: zImageAppsV2PerspectiveInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-apps-v2/photo-restoration"),
    input: zImageAppsV2PhotoRestorationInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-apps-v2/photography-effects"),
    input: zImageAppsV2PhotographyEffectsInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-apps-v2/portrait-enhance"),
    input: zImageAppsV2PortraitEnhanceInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-apps-v2/product-holding"),
    input: zImageAppsV2ProductHoldingInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-apps-v2/product-photography"),
    input: zImageAppsV2ProductPhotographyInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-apps-v2/relighting"),
    input: zImageAppsV2RelightingInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-apps-v2/style-transfer"),
    input: zImageAppsV2StyleTransferInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-apps-v2/texture-transform"),
    input: zImageAppsV2TextureTransformInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-apps-v2/virtual-try-on"),
    input: zImageAppsV2VirtualTryOnInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-editing/age-progression"),
    input: zImageEditingAgeProgressionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-editing/baby-version"),
    input: zImageEditingBabyVersionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-editing/background-change"),
    input: zImageEditingBackgroundChangeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-editing/broccoli-haircut"),
    input: zImageEditingBroccoliHaircutInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-editing/cartoonify"),
    input: zImageEditingCartoonifyInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-editing/color-correction"),
    input: zImageEditingColorCorrectionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-editing/expression-change"),
    input: zImageEditingExpressionChangeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-editing/face-enhancement"),
    input: zImageEditingFaceEnhancementInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-editing/hair-change"),
    input: zImageEditingHairChangeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-editing/object-removal"),
    input: zImageEditingObjectRemovalInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-editing/photo-restoration"),
    input: zImageEditingPhotoRestorationInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-editing/plushie-style"),
    input: zImageEditingPlushieStyleInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-editing/professional-photo"),
    input: zImageEditingProfessionalPhotoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-editing/realism"),
    input: zImageEditingRealismInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-editing/reframe"),
    input: zImageEditingReframeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-editing/retouch"),
    input: zImageEditingRetouchInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-editing/scene-composition"),
    input: zImageEditingSceneCompositionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-editing/style-transfer"),
    input: zImageEditingStyleTransferInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-editing/text-removal"),
    input: zImageEditingTextRemovalInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-editing/time-of-day"),
    input: zImageEditingTimeOfDayInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-editing/weather-effect"),
    input: zImageEditingWeatherEffectInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-editing/wojak-style"),
    input: zImageEditingWojakStyleInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-editing/youtube-thumbnails"),
    input: zImageEditingYoutubeThumbnailsInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-preprocessors/depth-anything/v2"),
    input: zImagePreprocessorsDepthAnythingV2Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-preprocessors/hed"),
    input: zImagePreprocessorsHedInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-preprocessors/lineart"),
    input: zImagePreprocessorsLineartInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-preprocessors/midas"),
    input: zImagePreprocessorsMidasInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-preprocessors/mlsd"),
    input: zImagePreprocessorsMlsdInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-preprocessors/pidi"),
    input: zImagePreprocessorsPidiInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-preprocessors/sam"),
    input: zImagePreprocessorsSamInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-preprocessors/scribble"),
    input: zImagePreprocessorsScribbleInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-preprocessors/teed"),
    input: zImagePreprocessorsTeedInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image-preprocessors/zoe"),
    input: zImagePreprocessorsZoeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image2pixel"),
    input: zImage2PixelInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/image2svg"),
    input: zImage2SvgInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/imagen3"),
    input: zImagen3Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/imagen3/fast"),
    input: zImagen3FastInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/imagen4/preview"),
    input: zImagen4PreviewInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/imagen4/preview/fast"),
    input: zImagen4PreviewFastInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/imagen4/preview/ultra"),
    input: zImagen4PreviewUltraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/imageutils/depth"),
    input: zImageutilsDepthInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/imageutils/marigold-depth"),
    input: zImageutilsMarigoldDepthInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/imageutils/rembg"),
    input: zImageutilsRembgInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/inpaint"),
    input: zInpaintInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/instant-character"),
    input: zInstantCharacterInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/invisible-watermark"),
    input: zInvisibleWatermarkInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ip-adapter-face-id"),
    input: zIpAdapterFaceIdInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/janus"),
    input: zJanusInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/joyai-image-edit"),
    input: zJoyaiImageEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-image/o1"),
    input: zKlingImageO1Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-image/o3/image-to-image"),
    input: zKlingImageO3ImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-image/o3/text-to-image"),
    input: zKlingImageO3TextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-image/v3/image-to-image"),
    input: zKlingImageV3ImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-image/v3/text-to-image"),
    input: zKlingImageV3TextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling/v1-5/kolors-virtual-try-on"),
    input: zKlingV15KolorsVirtualTryOnInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kolors"),
    input: zKolorsInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kolors/image-to-image"),
    input: zKolorsImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/layer-diffusion"),
    input: zLayerDiffusionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/lcm"),
    input: zLcmInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/lcm-sd15-i2i"),
    input: zLcmSd15I2iInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/leffa/pose-transfer"),
    input: zLeffaPoseTransferInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/leffa/virtual-tryon"),
    input: zLeffaVirtualTryonInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/lightning-models"),
    input: zLightningModelsInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/live-portrait/image"),
    input: zLivePortraitImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/longcat-image"),
    input: zLongcatImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/longcat-image/edit"),
    input: zLongcatImageEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/lora"),
    input: zLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/lora/image-to-image"),
    input: zLoraImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/lora/inpaint"),
    input: zLoraInpaintInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/lucidflux"),
    input: zLucidfluxInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/luma-photon"),
    input: zLumaPhotonInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/luma-photon/flash"),
    input: zLumaPhotonFlashInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/luma-photon/flash/modify"),
    input: zLumaPhotonFlashModifyInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/luma-photon/flash/reframe"),
    input: zLumaPhotonFlashReframeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/luma-photon/modify"),
    input: zLumaPhotonModifyInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/luma-photon/reframe"),
    input: zLumaPhotonReframeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/lumina-image/v2"),
    input: zLuminaImageV2Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/image-01"),
    input: zMinimaxImage01Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/image-01/subject-reference"),
    input: zMinimaxImage01SubjectReferenceInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/mix-dehaze-net"),
    input: zMixDehazeNetInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/moondream-next/detection"),
    input: zMoondreamNextDetectionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/moondream3-preview/segment"),
    input: zMoondream3PreviewSegmentInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/nafnet/deblur"),
    input: zNafnetDeblurInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/nafnet/denoise"),
    input: zNafnetDenoiseInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/nano-banana"),
    input: zNanoBananaInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/nano-banana-2"),
    input: zNanoBanana2Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/nano-banana-2/edit"),
    input: zNanoBanana2EditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/nano-banana-pro"),
    input: zNanoBananaProInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/nano-banana-pro/edit"),
    input: zNanoBananaProEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/nano-banana/edit"),
    input: zNanoBananaEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/nucleus-image"),
    input: zNucleusImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/object-removal"),
    input: zObjectRemovalInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/object-removal/bbox"),
    input: zObjectRemovalBboxInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/object-removal/mask"),
    input: zObjectRemovalMaskInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/omni-zero"),
    input: zOmniZeroInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/omnigen-v1"),
    input: zOmnigenV1Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/omnigen-v2"),
    input: zOmnigenV2Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/onereward"),
    input: zOnerewardInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ovis-image"),
    input: zOvisImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pasd"),
    input: zPasdInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/patina"),
    input: zPatinaInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/patina/material"),
    input: zPatinaMaterialInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/patina/material/extract"),
    input: zPatinaMaterialExtractInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/phota"),
    input: zPhotaInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/phota/edit"),
    input: zPhotaEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/phota/enhance"),
    input: zPhotaEnhanceInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/photomaker"),
    input: zPhotomakerInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/physic-edit"),
    input: zPhysicEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/piflow"),
    input: zPiflowInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixart-sigma"),
    input: zPixartSigmaInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/playground-v25"),
    input: zPlaygroundV25Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/playground-v25/image-to-image"),
    input: zPlaygroundV25ImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/playground-v25/inpainting"),
    input: zPlaygroundV25InpaintingInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/plushify"),
    input: zPlushifyInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pony-v7"),
    input: zPonyV7Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/post-processing"),
    input: zPostProcessingInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/post-processing/blur"),
    input: zPostProcessingBlurInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/post-processing/chromatic-aberration"),
    input: zPostProcessingChromaticAberrationInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/post-processing/color-correction"),
    input: zPostProcessingColorCorrectionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/post-processing/color-tint"),
    input: zPostProcessingColorTintInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/post-processing/desaturate"),
    input: zPostProcessingDesaturateInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/post-processing/dissolve"),
    input: zPostProcessingDissolveInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/post-processing/dodge-burn"),
    input: zPostProcessingDodgeBurnInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/post-processing/grain"),
    input: zPostProcessingGrainInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/post-processing/parabolize"),
    input: zPostProcessingParabolizeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/post-processing/sharpen"),
    input: zPostProcessingSharpenInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/post-processing/solarize"),
    input: zPostProcessingSolarizeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/post-processing/vignette"),
    input: zPostProcessingVignetteInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pulid"),
    input: zPulidInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image"),
    input: zQwenImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-2/edit"),
    input: zQwenImage2EditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-2/pro/edit"),
    input: zQwenImage2ProEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-2/pro/text-to-image"),
    input: zQwenImage2ProTextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-2/text-to-image"),
    input: zQwenImage2TextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-2512"),
    input: zQwenImage2512Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-2512/lora"),
    input: zQwenImage2512LoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-edit"),
    input: zQwenImageEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-edit-2509"),
    input: zQwenImageEdit2509Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-edit-2509-lora"),
    input: zQwenImageEdit2509LoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/qwen-image-edit-2509-lora-gallery/add-background",
    ),
    input: zQwenImageEdit2509LoraGalleryAddBackgroundInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/qwen-image-edit-2509-lora-gallery/face-to-full-portrait",
    ),
    input: zQwenImageEdit2509LoraGalleryFaceToFullPortraitInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-edit-2509-lora-gallery/group-photo"),
    input: zQwenImageEdit2509LoraGalleryGroupPhotoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/qwen-image-edit-2509-lora-gallery/integrate-product",
    ),
    input: zQwenImageEdit2509LoraGalleryIntegrateProductInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/qwen-image-edit-2509-lora-gallery/lighting-restoration",
    ),
    input: zQwenImageEdit2509LoraGalleryLightingRestorationInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/qwen-image-edit-2509-lora-gallery/multiple-angles",
    ),
    input: zQwenImageEdit2509LoraGalleryMultipleAnglesInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-edit-2509-lora-gallery/next-scene"),
    input: zQwenImageEdit2509LoraGalleryNextSceneInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/qwen-image-edit-2509-lora-gallery/remove-element",
    ),
    input: zQwenImageEdit2509LoraGalleryRemoveElementInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/qwen-image-edit-2509-lora-gallery/remove-lighting",
    ),
    input: zQwenImageEdit2509LoraGalleryRemoveLightingInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/qwen-image-edit-2509-lora-gallery/shirt-design",
    ),
    input: zQwenImageEdit2509LoraGalleryShirtDesignInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-edit-2511"),
    input: zQwenImageEdit2511Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-edit-2511-multiple-angles"),
    input: zQwenImageEdit2511MultipleAnglesInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-edit-2511/lora"),
    input: zQwenImageEdit2511LoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-edit-lora"),
    input: zQwenImageEditLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-edit-plus"),
    input: zQwenImageEditPlusInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-edit-plus-lora"),
    input: zQwenImageEditPlusLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/qwen-image-edit-plus-lora-gallery/add-background",
    ),
    input: zQwenImageEditPlusLoraGalleryAddBackgroundInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/qwen-image-edit-plus-lora-gallery/face-to-full-portrait",
    ),
    input: zQwenImageEditPlusLoraGalleryFaceToFullPortraitInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-edit-plus-lora-gallery/group-photo"),
    input: zQwenImageEditPlusLoraGalleryGroupPhotoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/qwen-image-edit-plus-lora-gallery/integrate-product",
    ),
    input: zQwenImageEditPlusLoraGalleryIntegrateProductInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/qwen-image-edit-plus-lora-gallery/lighting-restoration",
    ),
    input: zQwenImageEditPlusLoraGalleryLightingRestorationInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/qwen-image-edit-plus-lora-gallery/multiple-angles",
    ),
    input: zQwenImageEditPlusLoraGalleryMultipleAnglesInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-edit-plus-lora-gallery/next-scene"),
    input: zQwenImageEditPlusLoraGalleryNextSceneInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/qwen-image-edit-plus-lora-gallery/remove-element",
    ),
    input: zQwenImageEditPlusLoraGalleryRemoveElementInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/qwen-image-edit-plus-lora-gallery/remove-lighting",
    ),
    input: zQwenImageEditPlusLoraGalleryRemoveLightingInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/qwen-image-edit-plus-lora-gallery/shirt-design",
    ),
    input: zQwenImageEditPlusLoraGalleryShirtDesignInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-edit/image-to-image"),
    input: zQwenImageEditImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-edit/inpaint"),
    input: zQwenImageEditInpaintInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-layered"),
    input: zQwenImageLayeredInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-layered/lora"),
    input: zQwenImageLayeredLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-max/edit"),
    input: zQwenImageMaxEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-max/text-to-image"),
    input: zQwenImageMaxTextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image/image-to-image"),
    input: zQwenImageImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/realistic-vision"),
    input: zRealisticVisionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/recraft-20b"),
    input: zRecraft20bInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/recraft/upscale/creative"),
    input: zRecraftUpscaleCreativeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/recraft/upscale/crisp"),
    input: zRecraftUpscaleCrispInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/recraft/v3/image-to-image"),
    input: zRecraftV3ImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/recraft/v3/text-to-image"),
    input: zRecraftV3TextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/recraft/v4/pro/text-to-image"),
    input: zRecraftV4ProTextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/recraft/v4/pro/text-to-vector"),
    input: zRecraftV4ProTextToVectorInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/recraft/v4/text-to-image"),
    input: zRecraftV4TextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/recraft/v4/text-to-vector"),
    input: zRecraftV4TextToVectorInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/recraft/vectorize"),
    input: zRecraftVectorizeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/retoucher"),
    input: zRetoucherInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/rife"),
    input: zRifeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sam-3-1/image"),
    input: zSam31ImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sam-3-1/image-rle"),
    input: zSam31ImageRleInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sam-3/image"),
    input: zSam3ImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sam-3/image-rle"),
    input: zSam3ImageRleInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sam2/auto-segment"),
    input: zSam2AutoSegmentInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sam2/image"),
    input: zSam2ImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sana"),
    input: zSanaInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sana/sprint"),
    input: zSanaSprintInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sana/v1.5/1.6b"),
    input: zSanaV1516bInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sana/v1.5/4.8b"),
    input: zSanaV1548bInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sd15-depth-controlnet"),
    input: zSd15DepthControlnetInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sdxl-controlnet-union"),
    input: zSdxlControlnetUnionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sdxl-controlnet-union/image-to-image"),
    input: zSdxlControlnetUnionImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sdxl-controlnet-union/inpainting"),
    input: zSdxlControlnetUnionInpaintingInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/seedvr/upscale/image"),
    input: zSeedvrUpscaleImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/seedvr/upscale/image/seamless"),
    input: zSeedvrUpscaleImageSeamlessInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/smart-resize"),
    input: zSmartResizeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/stable-cascade"),
    input: zStableCascadeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/stable-cascade/sote-diffusion"),
    input: zStableCascadeSoteDiffusionInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/stable-diffusion-v15"),
    input: zStableDiffusionV15Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/stable-diffusion-v3-medium"),
    input: zStableDiffusionV3MediumInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/stable-diffusion-v3-medium/image-to-image"),
    input: zStableDiffusionV3MediumImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/stable-diffusion-v35-large"),
    input: zStableDiffusionV35LargeInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/stable-diffusion-v35-medium"),
    input: zStableDiffusionV35MediumInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/star-vector"),
    input: zStarVectorInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/step1x-edit"),
    input: zStep1xEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/stepx-edit2"),
    input: zStepxEdit2Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/swin2sr"),
    input: zSwin2SrInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/switti"),
    input: zSwittiInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/switti/512"),
    input: zSwitti512Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/thera"),
    input: zTheraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/topaz/upscale/image"),
    input: zTopazUpscaleImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/uno"),
    input: zUnoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/uso"),
    input: zUsoInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vecglypher"),
    input: zVecglypherInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vecglypher/image-to-svg"),
    input: zVecglypherImageToSvgInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q2/reference-to-image"),
    input: zViduQ2ReferenceToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q2/text-to-image"),
    input: zViduQ2TextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/reference-to-image"),
    input: zViduReferenceToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-25-preview/image-to-image"),
    input: zWan25PreviewImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-25-preview/text-to-image"),
    input: zWan25PreviewTextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-5b/text-to-image"),
    input: zWanV225bTextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-a14b/image-to-image"),
    input: zWanV22A14bImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-a14b/text-to-image"),
    input: zWanV22A14bTextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-a14b/text-to-image/lora"),
    input: zWanV22A14bTextToImageLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.7/edit"),
    input: zWanV27EditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.7/pro/edit"),
    input: zWanV27ProEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.7/pro/text-to-image"),
    input: zWanV27ProTextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.7/text-to-image"),
    input: zWanV27TextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/workflow-utilities/extract-nth-frame"),
    input: zWorkflowUtilitiesExtractNthFrameInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/z-image/base"),
    input: zZImageBaseInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/z-image/base/lora"),
    input: zZImageBaseLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/z-image/turbo"),
    input: zZImageTurboInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/z-image/turbo/controlnet"),
    input: zZImageTurboControlnetInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/z-image/turbo/controlnet/lora"),
    input: zZImageTurboControlnetLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/z-image/turbo/image-to-image"),
    input: zZImageTurboImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/z-image/turbo/image-to-image/lora"),
    input: zZImageTurboImageToImageLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/z-image/turbo/inpaint"),
    input: zZImageTurboInpaintInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/z-image/turbo/inpaint/lora"),
    input: zZImageTurboInpaintLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/z-image/turbo/lora"),
    input: zZImageTurboLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/z-image/turbo/tiling"),
    input: zZImageTurboTilingInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("fal-ai/z-image/turbo/tiling/lora"),
    input: zZImageTurboTilingLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("imagineart/imagineart-1.5-preview/text-to-image"),
    input: zImagineart15PreviewTextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("imagineart/imagineart-1.5-pro-preview/text-to-image"),
    input: zImagineart15ProPreviewTextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("imagineart/imagineart-2.0-preview/text-to-image"),
    input: zImagineart20PreviewTextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("openai/gpt-image-2"),
    input: zGptImage2Input,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("openai/gpt-image-2/edit"),
    input: zGptImage2EditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("pixelcut/background-removal"),
    input: zBackgroundRemovalInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("rundiffusion-fal/juggernaut-flux-lora"),
    input: zJuggernautFluxLoraInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("rundiffusion-fal/juggernaut-flux-lora/inpainting"),
    input: zJuggernautFluxLoraInpaintingInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("rundiffusion-fal/rundiffusion-photo-flux"),
    input: zRundiffusionPhotoFluxInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("smoretalk-ai/rembg-enhance"),
    input: zRembgEnhanceInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("wan/v2.6/image-to-image"),
    input: zV26ImageToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("wan/v2.6/text-to-image"),
    input: zV26TextToImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("xai/grok-imagine-image"),
    input: zGrokImagineImageInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("xai/grok-imagine-image/edit"),
    input: zGrokImagineImageEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("xai/grok-imagine-image/quality/edit"),
    input: zGrokImagineImageQualityEditInput,
    output: zQueueStatus,
  }),
  z.object({
    endpoint: z.literal("xai/grok-imagine-image/quality/text-to-image"),
    input: zGrokImagineImageQualityTextToImageInput,
    output: zQueueStatus,
  }),
]);

/** Inferred type from ImageEndpointSchema */
export type ImageEndpoint = z.infer<typeof ImageEndpointSchema>;
