// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * TranscribeInput
 */
export const zCohereTranscribeInput = z.object({
  max_new_tokens: z.int().gte(1).lte(1024).optional().default(256),
  language: z
    .enum([
      "en",
      "fr",
      "de",
      "it",
      "es",
      "pt",
      "el",
      "nl",
      "pl",
      "zh",
      "ja",
      "ko",
      "vi",
      "ar",
    ])
    .optional()
    .default("en"),
  punctuation: z.boolean().optional().default(true),
  audio_url: z.string(),
});

/**
 * TranscribeOutput
 */
export const zCohereTranscribeOutput = z.object({
  timings: z.record(z.string(), z.number()).optional(),
  text: z.string(),
});

/**
 * SpeechToTextRequest
 */
export const zElevenlabsSpeechToTextInput = z.object({
  audio_url: z.string(),
  tag_audio_events: z.boolean().optional().default(true),
  diarize: z.boolean().optional().default(true),
  language_code: z.union([z.string(), z.unknown()]).optional(),
});

/**
 * SpeechToTextRequestScribeV2
 */
export const zElevenlabsSpeechToTextScribeV2Input = z.object({
  audio_url: z.string(),
  keyterms: z.array(z.string()).max(100).optional().default([]),
  tag_audio_events: z.boolean().optional().default(true),
  diarize: z.boolean().optional().default(true),
  language_code: z.union([z.string(), z.unknown()]).optional(),
});

/**
 * AudioInput
 */
export const zNemotron3NanoOmniAudioInput = z.object({
  system_prompt: z.union([z.string(), z.unknown()]).optional(),
  audio_url: z.string(),
  prompt: z.string().min(1),
  reasoning_mode: z.enum(["think", "no_think"]).optional().default("no_think"),
  temperature: z.number().gte(0).lte(2).optional().default(0.7),
  top_p: z.number().gte(0).lte(1).optional().default(0.95),
  max_tokens: z.int().gte(1).lte(20000).optional().default(1024),
});

/**
 * VideoInput
 */
export const zNemotron3NanoOmniVideoInput = z.object({
  video_url: z.string(),
  system_prompt: z.union([z.string(), z.unknown()]).optional(),
  prompt: z.string().min(1),
  reasoning_mode: z.enum(["think", "no_think"]).optional().default("no_think"),
  temperature: z.number().gte(0).lte(2).optional().default(0.7),
  top_p: z.number().gte(0).lte(1).optional().default(0.95),
  max_tokens: z.int().gte(1).lte(20000).optional().default(1024),
});

/**
 * VisionInput
 */
export const zNemotron3NanoOmniVisionInput = z.object({
  system_prompt: z.union([z.string(), z.unknown()]).optional(),
  image_url: z.string(),
  prompt: z.string().min(1),
  reasoning_mode: z.enum(["think", "no_think"]).optional().default("no_think"),
  temperature: z.number().gte(0).lte(2).optional().default(0.7),
  top_p: z.number().gte(0).lte(1).optional().default(0.95),
  max_tokens: z.int().gte(1).lte(20000).optional().default(1024),
});

/**
 * PromptTokensDetails
 */
export const zPromptTokensDetails = z.object({
  cache_write_tokens: z.int().optional().default(0),
  cached_tokens: z.int().optional().default(0),
});

export const zQueueStatus = z.object({
  status: z.enum(["IN_QUEUE", "IN_PROGRESS", "COMPLETED"]),
  request_id: z.string(),
  response_url: z.string().optional(),
  status_url: z.string().optional(),
  cancel_url: z.string().optional(),
  logs: z.record(z.string(), z.unknown()).optional(),
  metrics: z.record(z.string(), z.unknown()).optional(),
  queue_position: z.int().optional(),
});

/**
 * VideoEnterpriseInput
 */
export const zRouterVideoEnterpriseInput = z.object({
  video_urls: z.union([z.array(z.string()), z.unknown()]).optional(),
  temperature: z.number().gte(0).lte(2).optional().default(1),
  max_tokens: z.union([z.int().gte(1), z.unknown()]).optional(),
  reasoning: z.boolean().optional().default(false),
  prompt: z.string(),
  model: z.string(),
  system_prompt: z.union([z.string(), z.unknown()]).optional(),
});

/**
 * VideoInput
 */
export const zRouterVideoInput = z.object({
  video_urls: z.union([z.array(z.string()), z.unknown()]).optional(),
  temperature: z.number().gte(0).lte(2).optional().default(1),
  max_tokens: z.union([z.int().gte(1), z.unknown()]).optional(),
  reasoning: z.boolean().optional().default(false),
  prompt: z.string(),
  model: z.string(),
  system_prompt: z.union([z.string(), z.unknown()]).optional(),
});

/**
 * SileroVADInput
 */
export const zSileroVadInput = z.object({
  audio_url: z.string(),
});

/**
 * SmartTurnInput
 */
export const zSmartTurnInput = z.object({
  audio_url: z.string(),
});

/**
 * Output
 */
export const zSmartTurnOutput = z.object({
  probability: z.number(),
  prediction: z.int(),
  metrics: z.record(z.string(), z.unknown()),
});

/**
 * SpeechTimestamp
 */
export const zSpeechTimestamp = z.object({
  start: z.number(),
  end: z.number(),
});

/**
 * SileroVADOutput
 */
export const zSileroVadOutput = z.object({
  timestamps: z.array(zSpeechTimestamp),
  has_speech: z.boolean(),
});

/**
 * SpeechInput
 */
export const zSpeechToTextInput = z.object({
  audio_url: z.string(),
  use_pnc: z.boolean().optional().default(true),
});

/**
 * SpeechOutput
 */
export const zSpeechToTextOutput = z.object({
  output: z.string(),
  partial: z.boolean().optional().default(false),
});

/**
 * SpeechInput
 */
export const zSpeechToTextStreamInput = z.object({
  audio_url: z.string(),
  use_pnc: z.boolean().optional().default(true),
});

export const zSpeechToTextStreamOutput = z.unknown();

/**
 * SpeechInput
 */
export const zSpeechToTextTurboInput = z.object({
  audio_url: z.string(),
  use_pnc: z.boolean().optional().default(true),
});

/**
 * SpeechOutput
 */
export const zSpeechToTextTurboOutput = z.object({
  output: z.string(),
  partial: z.boolean().optional().default(false),
});

/**
 * SpeechInput
 */
export const zSpeechToTextTurboStreamInput = z.object({
  audio_url: z.string(),
  use_pnc: z.boolean().optional().default(true),
});

export const zSpeechToTextTurboStreamOutput = z.unknown();

/**
 * TranscriptionWord
 */
export const zTranscriptionWord = z.object({
  text: z.string(),
  speaker_id: z.union([z.string(), z.unknown()]).optional(),
  start: z.union([z.number(), z.unknown()]).optional(),
  type: z.string(),
  end: z.union([z.number(), z.unknown()]).optional(),
});

/**
 * TranscriptionOutput
 */
export const zElevenlabsSpeechToTextOutput = z.object({
  text: z.string(),
  words: z.array(zTranscriptionWord),
  language_probability: z.number(),
  language_code: z.string(),
});

/**
 * TranscriptionOutputV2
 */
export const zElevenlabsSpeechToTextScribeV2Output = z.object({
  text: z.string(),
  words: z.array(zTranscriptionWord),
  language_probability: z.number(),
  language_code: z.string(),
});

/**
 * UsageInfo
 */
export const zUsageInfo = z.object({
  output_tokens: z.int(),
  input_tokens: z.int(),
});

/**
 * BaseOutput
 */
export const zNemotron3NanoOmniAudioOutput = z.object({
  output: z.string(),
  finish_reason: z.string().optional().default("stop"),
  usage: zUsageInfo,
});

/**
 * BaseOutput
 */
export const zNemotron3NanoOmniVideoOutput = z.object({
  output: z.string(),
  finish_reason: z.string().optional().default("stop"),
  usage: zUsageInfo,
});

/**
 * BaseOutput
 */
export const zNemotron3NanoOmniVisionOutput = z.object({
  output: z.string(),
  finish_reason: z.string().optional().default("stop"),
  usage: zUsageInfo,
});

/**
 * UsageInfo
 */
export const zUsageInfoType2 = z.object({
  prompt_tokens: z.union([z.int(), z.unknown()]).optional(),
  prompt_tokens_details: z
    .union([zPromptTokensDetails, z.unknown()])
    .optional(),
  total_tokens: z.int().optional().default(0),
  cost: z.number(),
  completion_tokens: z.union([z.int(), z.unknown()]).optional(),
});

/**
 * VideoOutput
 */
export const zRouterVideoEnterpriseOutput = z.object({
  usage: z.union([zUsageInfoType2, z.unknown()]),
  output: z.string(),
});

/**
 * VideoOutput
 */
export const zRouterVideoOutput = z.object({
  usage: z.union([zUsageInfoType2, z.unknown()]),
  output: z.string(),
});

/**
 * WhisperChunk
 */
export const zWhisperChunk = z.object({
  timestamp: z.tuple([]),
  text: z.string(),
});

/**
 * WhisperInput
 */
export const zWizperInput = z.object({
  chunk_level: z.string().optional().default("segment"),
  version: z.string().optional().default("3"),
  task: z.enum(["transcribe", "translate"]).optional().default("transcribe"),
  merge_chunks: z.boolean().optional().default(true),
  audio_url: z.string(),
  language: z
    .union([
      z.enum([
        "af",
        "am",
        "ar",
        "as",
        "az",
        "ba",
        "be",
        "bg",
        "bn",
        "bo",
        "br",
        "bs",
        "ca",
        "cs",
        "cy",
        "da",
        "de",
        "el",
        "en",
        "es",
        "et",
        "eu",
        "fa",
        "fi",
        "fo",
        "fr",
        "gl",
        "gu",
        "ha",
        "haw",
        "he",
        "hi",
        "hr",
        "ht",
        "hu",
        "hy",
        "id",
        "is",
        "it",
        "ja",
        "jw",
        "ka",
        "kk",
        "km",
        "kn",
        "ko",
        "la",
        "lb",
        "ln",
        "lo",
        "lt",
        "lv",
        "mg",
        "mi",
        "mk",
        "ml",
        "mn",
        "mr",
        "ms",
        "mt",
        "my",
        "ne",
        "nl",
        "nn",
        "no",
        "oc",
        "pa",
        "pl",
        "ps",
        "pt",
        "ro",
        "ru",
        "sa",
        "sd",
        "si",
        "sk",
        "sl",
        "sn",
        "so",
        "sq",
        "sr",
        "su",
        "sv",
        "sw",
        "ta",
        "te",
        "tg",
        "th",
        "tk",
        "tl",
        "tr",
        "tt",
        "uk",
        "ur",
        "uz",
        "vi",
        "yi",
        "yo",
        "zh",
      ]),
      z.unknown(),
    ])
    .optional(),
  max_segment_len: z.int().gte(10).lte(29).optional().default(29),
});

/**
 * WhisperOutput
 */
export const zWizperOutput = z.object({
  text: z.string(),
  chunks: z.array(zWhisperChunk),
  languages: z.array(
    z.enum([
      "af",
      "am",
      "ar",
      "as",
      "az",
      "ba",
      "be",
      "bg",
      "bn",
      "bo",
      "br",
      "bs",
      "ca",
      "cs",
      "cy",
      "da",
      "de",
      "el",
      "en",
      "es",
      "et",
      "eu",
      "fa",
      "fi",
      "fo",
      "fr",
      "gl",
      "gu",
      "ha",
      "haw",
      "he",
      "hi",
      "hr",
      "ht",
      "hu",
      "hy",
      "id",
      "is",
      "it",
      "ja",
      "jw",
      "ka",
      "kk",
      "km",
      "kn",
      "ko",
      "la",
      "lb",
      "ln",
      "lo",
      "lt",
      "lv",
      "mg",
      "mi",
      "mk",
      "ml",
      "mn",
      "mr",
      "ms",
      "mt",
      "my",
      "ne",
      "nl",
      "nn",
      "no",
      "oc",
      "pa",
      "pl",
      "ps",
      "pt",
      "ro",
      "ru",
      "sa",
      "sd",
      "si",
      "sk",
      "sl",
      "sn",
      "so",
      "sq",
      "sr",
      "su",
      "sv",
      "sw",
      "ta",
      "te",
      "tg",
      "th",
      "tk",
      "tl",
      "tr",
      "tt",
      "uk",
      "ur",
      "uz",
      "vi",
      "yi",
      "yo",
      "zh",
    ]),
  ),
});

export const zPostFalAiCohereTranscribeBody = zCohereTranscribeInput;

/**
 * The request status.
 */
export const zPostFalAiCohereTranscribeResponse = zQueueStatus;

export const zGetFalAiCohereTranscribeRequestsByRequestIdPath = z.object({
  request_id: z.string(),
});

/**
 * Result of the request.
 */
export const zGetFalAiCohereTranscribeRequestsByRequestIdResponse =
  zCohereTranscribeOutput;

export const zPutFalAiCohereTranscribeRequestsByRequestIdCancelPath = z.object({
  request_id: z.string(),
});

/**
 * The request was cancelled.
 */
export const zPutFalAiCohereTranscribeRequestsByRequestIdCancelResponse =
  z.object({
    success: z.boolean().optional(),
  });

export const zGetFalAiCohereTranscribeRequestsByRequestIdStatusPath = z.object({
  request_id: z.string(),
});

export const zGetFalAiCohereTranscribeRequestsByRequestIdStatusQuery = z.object(
  {
    logs: z.number().optional(),
  },
);

/**
 * The request status.
 */
export const zGetFalAiCohereTranscribeRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiElevenlabsSpeechToTextBody =
  zElevenlabsSpeechToTextInput;

/**
 * The request status.
 */
export const zPostFalAiElevenlabsSpeechToTextResponse = zQueueStatus;

export const zGetFalAiElevenlabsSpeechToTextRequestsByRequestIdPath = z.object({
  request_id: z.string(),
});

/**
 * Result of the request.
 */
export const zGetFalAiElevenlabsSpeechToTextRequestsByRequestIdResponse =
  zElevenlabsSpeechToTextOutput;

export const zPutFalAiElevenlabsSpeechToTextRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string(),
  });

/**
 * The request was cancelled.
 */
export const zPutFalAiElevenlabsSpeechToTextRequestsByRequestIdCancelResponse =
  z.object({
    success: z.boolean().optional(),
  });

export const zGetFalAiElevenlabsSpeechToTextRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string(),
  });

export const zGetFalAiElevenlabsSpeechToTextRequestsByRequestIdStatusQuery =
  z.object({
    logs: z.number().optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiElevenlabsSpeechToTextRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiElevenlabsSpeechToTextScribeV2Body =
  zElevenlabsSpeechToTextScribeV2Input;

/**
 * The request status.
 */
export const zPostFalAiElevenlabsSpeechToTextScribeV2Response = zQueueStatus;

export const zGetFalAiElevenlabsSpeechToTextScribeV2RequestsByRequestIdPath =
  z.object({
    request_id: z.string(),
  });

/**
 * Result of the request.
 */
export const zGetFalAiElevenlabsSpeechToTextScribeV2RequestsByRequestIdResponse =
  zElevenlabsSpeechToTextScribeV2Output;

export const zPutFalAiElevenlabsSpeechToTextScribeV2RequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string(),
  });

/**
 * The request was cancelled.
 */
export const zPutFalAiElevenlabsSpeechToTextScribeV2RequestsByRequestIdCancelResponse =
  z.object({
    success: z.boolean().optional(),
  });

export const zGetFalAiElevenlabsSpeechToTextScribeV2RequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string(),
  });

export const zGetFalAiElevenlabsSpeechToTextScribeV2RequestsByRequestIdStatusQuery =
  z.object({
    logs: z.number().optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiElevenlabsSpeechToTextScribeV2RequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiSileroVadBody = zSileroVadInput;

/**
 * The request status.
 */
export const zPostFalAiSileroVadResponse = zQueueStatus;

export const zGetFalAiSileroVadRequestsByRequestIdPath = z.object({
  request_id: z.string(),
});

/**
 * Result of the request.
 */
export const zGetFalAiSileroVadRequestsByRequestIdResponse = zSileroVadOutput;

export const zPutFalAiSileroVadRequestsByRequestIdCancelPath = z.object({
  request_id: z.string(),
});

/**
 * The request was cancelled.
 */
export const zPutFalAiSileroVadRequestsByRequestIdCancelResponse = z.object({
  success: z.boolean().optional(),
});

export const zGetFalAiSileroVadRequestsByRequestIdStatusPath = z.object({
  request_id: z.string(),
});

export const zGetFalAiSileroVadRequestsByRequestIdStatusQuery = z.object({
  logs: z.number().optional(),
});

/**
 * The request status.
 */
export const zGetFalAiSileroVadRequestsByRequestIdStatusResponse = zQueueStatus;

export const zPostFalAiSmartTurnBody = zSmartTurnInput;

/**
 * The request status.
 */
export const zPostFalAiSmartTurnResponse = zQueueStatus;

export const zGetFalAiSmartTurnRequestsByRequestIdPath = z.object({
  request_id: z.string(),
});

/**
 * Result of the request.
 */
export const zGetFalAiSmartTurnRequestsByRequestIdResponse = zSmartTurnOutput;

export const zPutFalAiSmartTurnRequestsByRequestIdCancelPath = z.object({
  request_id: z.string(),
});

/**
 * The request was cancelled.
 */
export const zPutFalAiSmartTurnRequestsByRequestIdCancelResponse = z.object({
  success: z.boolean().optional(),
});

export const zGetFalAiSmartTurnRequestsByRequestIdStatusPath = z.object({
  request_id: z.string(),
});

export const zGetFalAiSmartTurnRequestsByRequestIdStatusQuery = z.object({
  logs: z.number().optional(),
});

/**
 * The request status.
 */
export const zGetFalAiSmartTurnRequestsByRequestIdStatusResponse = zQueueStatus;

export const zPostFalAiSpeechToTextBody = zSpeechToTextInput;

/**
 * The request status.
 */
export const zPostFalAiSpeechToTextResponse = zQueueStatus;

export const zGetFalAiSpeechToTextRequestsByRequestIdPath = z.object({
  request_id: z.string(),
});

/**
 * Result of the request.
 */
export const zGetFalAiSpeechToTextRequestsByRequestIdResponse =
  zSpeechToTextOutput;

export const zPutFalAiSpeechToTextRequestsByRequestIdCancelPath = z.object({
  request_id: z.string(),
});

/**
 * The request was cancelled.
 */
export const zPutFalAiSpeechToTextRequestsByRequestIdCancelResponse = z.object({
  success: z.boolean().optional(),
});

export const zGetFalAiSpeechToTextRequestsByRequestIdStatusPath = z.object({
  request_id: z.string(),
});

export const zGetFalAiSpeechToTextRequestsByRequestIdStatusQuery = z.object({
  logs: z.number().optional(),
});

/**
 * The request status.
 */
export const zGetFalAiSpeechToTextRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiSpeechToTextStreamBody = zSpeechToTextStreamInput;

/**
 * The request status.
 */
export const zPostFalAiSpeechToTextStreamResponse = zQueueStatus;

export const zGetFalAiSpeechToTextStreamRequestsByRequestIdPath = z.object({
  request_id: z.string(),
});

/**
 * Result of the request.
 */
export const zGetFalAiSpeechToTextStreamRequestsByRequestIdResponse =
  zSpeechToTextStreamOutput;

export const zPutFalAiSpeechToTextStreamRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string(),
  });

/**
 * The request was cancelled.
 */
export const zPutFalAiSpeechToTextStreamRequestsByRequestIdCancelResponse =
  z.object({
    success: z.boolean().optional(),
  });

export const zGetFalAiSpeechToTextStreamRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string(),
  });

export const zGetFalAiSpeechToTextStreamRequestsByRequestIdStatusQuery =
  z.object({
    logs: z.number().optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiSpeechToTextStreamRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiSpeechToTextTurboBody = zSpeechToTextTurboInput;

/**
 * The request status.
 */
export const zPostFalAiSpeechToTextTurboResponse = zQueueStatus;

export const zGetFalAiSpeechToTextTurboRequestsByRequestIdPath = z.object({
  request_id: z.string(),
});

/**
 * Result of the request.
 */
export const zGetFalAiSpeechToTextTurboRequestsByRequestIdResponse =
  zSpeechToTextTurboOutput;

export const zPutFalAiSpeechToTextTurboRequestsByRequestIdCancelPath = z.object(
  {
    request_id: z.string(),
  },
);

/**
 * The request was cancelled.
 */
export const zPutFalAiSpeechToTextTurboRequestsByRequestIdCancelResponse =
  z.object({
    success: z.boolean().optional(),
  });

export const zGetFalAiSpeechToTextTurboRequestsByRequestIdStatusPath = z.object(
  {
    request_id: z.string(),
  },
);

export const zGetFalAiSpeechToTextTurboRequestsByRequestIdStatusQuery =
  z.object({
    logs: z.number().optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiSpeechToTextTurboRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiSpeechToTextTurboStreamBody =
  zSpeechToTextTurboStreamInput;

/**
 * The request status.
 */
export const zPostFalAiSpeechToTextTurboStreamResponse = zQueueStatus;

export const zGetFalAiSpeechToTextTurboStreamRequestsByRequestIdPath = z.object(
  {
    request_id: z.string(),
  },
);

/**
 * Result of the request.
 */
export const zGetFalAiSpeechToTextTurboStreamRequestsByRequestIdResponse =
  zSpeechToTextTurboStreamOutput;

export const zPutFalAiSpeechToTextTurboStreamRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string(),
  });

/**
 * The request was cancelled.
 */
export const zPutFalAiSpeechToTextTurboStreamRequestsByRequestIdCancelResponse =
  z.object({
    success: z.boolean().optional(),
  });

export const zGetFalAiSpeechToTextTurboStreamRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string(),
  });

export const zGetFalAiSpeechToTextTurboStreamRequestsByRequestIdStatusQuery =
  z.object({
    logs: z.number().optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiSpeechToTextTurboStreamRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostFalAiWizperBody = zWizperInput;

/**
 * The request status.
 */
export const zPostFalAiWizperResponse = zQueueStatus;

export const zGetFalAiWizperRequestsByRequestIdPath = z.object({
  request_id: z.string(),
});

/**
 * Result of the request.
 */
export const zGetFalAiWizperRequestsByRequestIdResponse = zWizperOutput;

export const zPutFalAiWizperRequestsByRequestIdCancelPath = z.object({
  request_id: z.string(),
});

/**
 * The request was cancelled.
 */
export const zPutFalAiWizperRequestsByRequestIdCancelResponse = z.object({
  success: z.boolean().optional(),
});

export const zGetFalAiWizperRequestsByRequestIdStatusPath = z.object({
  request_id: z.string(),
});

export const zGetFalAiWizperRequestsByRequestIdStatusQuery = z.object({
  logs: z.number().optional(),
});

/**
 * The request status.
 */
export const zGetFalAiWizperRequestsByRequestIdStatusResponse = zQueueStatus;

export const zPostNvidiaNemotron3NanoOmniAudioBody =
  zNemotron3NanoOmniAudioInput;

/**
 * The request status.
 */
export const zPostNvidiaNemotron3NanoOmniAudioResponse = zQueueStatus;

export const zGetNvidiaNemotron3NanoOmniAudioRequestsByRequestIdPath = z.object(
  {
    request_id: z.string(),
  },
);

/**
 * Result of the request.
 */
export const zGetNvidiaNemotron3NanoOmniAudioRequestsByRequestIdResponse =
  zNemotron3NanoOmniAudioOutput;

export const zPutNvidiaNemotron3NanoOmniAudioRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string(),
  });

/**
 * The request was cancelled.
 */
export const zPutNvidiaNemotron3NanoOmniAudioRequestsByRequestIdCancelResponse =
  z.object({
    success: z.boolean().optional(),
  });

export const zGetNvidiaNemotron3NanoOmniAudioRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string(),
  });

export const zGetNvidiaNemotron3NanoOmniAudioRequestsByRequestIdStatusQuery =
  z.object({
    logs: z.number().optional(),
  });

/**
 * The request status.
 */
export const zGetNvidiaNemotron3NanoOmniAudioRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostNvidiaNemotron3NanoOmniVideoBody =
  zNemotron3NanoOmniVideoInput;

/**
 * The request status.
 */
export const zPostNvidiaNemotron3NanoOmniVideoResponse = zQueueStatus;

export const zGetNvidiaNemotron3NanoOmniVideoRequestsByRequestIdPath = z.object(
  {
    request_id: z.string(),
  },
);

/**
 * Result of the request.
 */
export const zGetNvidiaNemotron3NanoOmniVideoRequestsByRequestIdResponse =
  zNemotron3NanoOmniVideoOutput;

export const zPutNvidiaNemotron3NanoOmniVideoRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string(),
  });

/**
 * The request was cancelled.
 */
export const zPutNvidiaNemotron3NanoOmniVideoRequestsByRequestIdCancelResponse =
  z.object({
    success: z.boolean().optional(),
  });

export const zGetNvidiaNemotron3NanoOmniVideoRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string(),
  });

export const zGetNvidiaNemotron3NanoOmniVideoRequestsByRequestIdStatusQuery =
  z.object({
    logs: z.number().optional(),
  });

/**
 * The request status.
 */
export const zGetNvidiaNemotron3NanoOmniVideoRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostNvidiaNemotron3NanoOmniVisionBody =
  zNemotron3NanoOmniVisionInput;

/**
 * The request status.
 */
export const zPostNvidiaNemotron3NanoOmniVisionResponse = zQueueStatus;

export const zGetNvidiaNemotron3NanoOmniVisionRequestsByRequestIdPath =
  z.object({
    request_id: z.string(),
  });

/**
 * Result of the request.
 */
export const zGetNvidiaNemotron3NanoOmniVisionRequestsByRequestIdResponse =
  zNemotron3NanoOmniVisionOutput;

export const zPutNvidiaNemotron3NanoOmniVisionRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string(),
  });

/**
 * The request was cancelled.
 */
export const zPutNvidiaNemotron3NanoOmniVisionRequestsByRequestIdCancelResponse =
  z.object({
    success: z.boolean().optional(),
  });

export const zGetNvidiaNemotron3NanoOmniVisionRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string(),
  });

export const zGetNvidiaNemotron3NanoOmniVisionRequestsByRequestIdStatusQuery =
  z.object({
    logs: z.number().optional(),
  });

/**
 * The request status.
 */
export const zGetNvidiaNemotron3NanoOmniVisionRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zPostOpenrouterRouterVideoBody = zRouterVideoInput;

/**
 * The request status.
 */
export const zPostOpenrouterRouterVideoResponse = zQueueStatus;

export const zPostOpenrouterRouterVideoEnterpriseBody =
  zRouterVideoEnterpriseInput;

/**
 * The request status.
 */
export const zPostOpenrouterRouterVideoEnterpriseResponse = zQueueStatus;

export const zGetOpenrouterRouterVideoEnterpriseRequestsByRequestIdPath =
  z.object({
    request_id: z.string(),
  });

/**
 * Result of the request.
 */
export const zGetOpenrouterRouterVideoEnterpriseRequestsByRequestIdResponse =
  zRouterVideoEnterpriseOutput;

export const zPutOpenrouterRouterVideoEnterpriseRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string(),
  });

/**
 * The request was cancelled.
 */
export const zPutOpenrouterRouterVideoEnterpriseRequestsByRequestIdCancelResponse =
  z.object({
    success: z.boolean().optional(),
  });

export const zGetOpenrouterRouterVideoEnterpriseRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string(),
  });

export const zGetOpenrouterRouterVideoEnterpriseRequestsByRequestIdStatusQuery =
  z.object({
    logs: z.number().optional(),
  });

/**
 * The request status.
 */
export const zGetOpenrouterRouterVideoEnterpriseRequestsByRequestIdStatusResponse =
  zQueueStatus;

export const zGetOpenrouterRouterVideoRequestsByRequestIdPath = z.object({
  request_id: z.string(),
});

/**
 * Result of the request.
 */
export const zGetOpenrouterRouterVideoRequestsByRequestIdResponse =
  zRouterVideoOutput;

export const zPutOpenrouterRouterVideoRequestsByRequestIdCancelPath = z.object({
  request_id: z.string(),
});

/**
 * The request was cancelled.
 */
export const zPutOpenrouterRouterVideoRequestsByRequestIdCancelResponse =
  z.object({
    success: z.boolean().optional(),
  });

export const zGetOpenrouterRouterVideoRequestsByRequestIdStatusPath = z.object({
  request_id: z.string(),
});

export const zGetOpenrouterRouterVideoRequestsByRequestIdStatusQuery = z.object(
  {
    logs: z.number().optional(),
  },
);

/**
 * The request status.
 */
export const zGetOpenrouterRouterVideoRequestsByRequestIdStatusResponse =
  zQueueStatus;
