// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * Image
 *
 * Represents an image file.
 */
export const zImage = z.object({
  width: z.union([z.int(), z.unknown()]).optional(),
  content_type: z.union([z.string(), z.unknown()]).optional(),
  file_size: z.union([z.int(), z.unknown()]).optional(),
  url: z.string(),
  height: z.union([z.int(), z.unknown()]).optional(),
  file_name: z.union([z.string(), z.unknown()]).optional(),
});

export const zQueueStatus = z.object({
  status: z.enum(["IN_QUEUE", "IN_PROGRESS", "COMPLETED"]),
  request_id: z.string(),
  response_url: z.string().optional(),
  status_url: z.string().optional(),
  cancel_url: z.string().optional(),
  logs: z.record(z.string(), z.unknown()).optional(),
  metrics: z.record(z.string(), z.unknown()).optional(),
  queue_position: z.int().optional(),
});

/**
 * PickImageByIndexInput
 *
 * Input model for selecting a single image from an array by 1-based index.
 *
 * Pass-through utility: the URL is returned as provided in the input,
 * without fetching or re-uploading the image.
 */
export const zWorkflowUtilitiesPickImageByIndexInput = z.object({
  index: z.int(),
  fallback_index: z
    .enum(["first-image", "last-image"])
    .optional()
    .default("first-image"),
  image_urls: z.array(z.string()),
});

/**
 * PickImageByIndexOutput
 *
 * Output model for the picked image.
 */
export const zWorkflowUtilitiesPickImageByIndexOutput = z.object({
  image: zImage,
  images: z.array(zImage),
});

export const zPostFalAiWorkflowUtilitiesPickImageByIndexBody =
  zWorkflowUtilitiesPickImageByIndexInput;

/**
 * The request status.
 */
export const zPostFalAiWorkflowUtilitiesPickImageByIndexResponse = zQueueStatus;

export const zGetFalAiWorkflowUtilitiesPickImageByIndexRequestsByRequestIdPath =
  z.object({
    request_id: z.string(),
  });

/**
 * Result of the request.
 */
export const zGetFalAiWorkflowUtilitiesPickImageByIndexRequestsByRequestIdResponse =
  zWorkflowUtilitiesPickImageByIndexOutput;

export const zPutFalAiWorkflowUtilitiesPickImageByIndexRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string(),
  });

/**
 * The request was cancelled.
 */
export const zPutFalAiWorkflowUtilitiesPickImageByIndexRequestsByRequestIdCancelResponse =
  z.object({
    success: z.boolean().optional(),
  });

export const zGetFalAiWorkflowUtilitiesPickImageByIndexRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string(),
  });

export const zGetFalAiWorkflowUtilitiesPickImageByIndexRequestsByRequestIdStatusQuery =
  z.object({
    logs: z.number().optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiWorkflowUtilitiesPickImageByIndexRequestsByRequestIdStatusResponse =
  zQueueStatus;
