// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * Image
 *
 * Represents an image file.
 */
export const zImage = z
  .object({
    width: z.union([z.int(), z.unknown()]).optional(),
    content_type: z.union([z.string(), z.unknown()]).optional(),
    file_size: z.union([z.int(), z.unknown()]).optional(),
    url: z.string().register(z.globalRegistry, {
      description: "The URL where the file can be downloaded from.",
    }),
    height: z.union([z.int(), z.unknown()]).optional(),
    file_name: z.union([z.string(), z.unknown()]).optional(),
  })
  .register(z.globalRegistry, {
    description: "Represents an image file.",
  });

export const zQueueStatus = z.object({
  status: z.enum(["IN_QUEUE", "IN_PROGRESS", "COMPLETED"]),
  request_id: z.string().register(z.globalRegistry, {
    description: "The request id.",
  }),
  response_url: z
    .string()
    .register(z.globalRegistry, {
      description: "The response url.",
    })
    .optional(),
  status_url: z
    .string()
    .register(z.globalRegistry, {
      description: "The status url.",
    })
    .optional(),
  cancel_url: z
    .string()
    .register(z.globalRegistry, {
      description: "The cancel url.",
    })
    .optional(),
  logs: z
    .record(z.string(), z.unknown())
    .register(z.globalRegistry, {
      description: "The logs.",
    })
    .optional(),
  metrics: z
    .record(z.string(), z.unknown())
    .register(z.globalRegistry, {
      description: "The metrics.",
    })
    .optional(),
  queue_position: z
    .int()
    .register(z.globalRegistry, {
      description: "The queue position.",
    })
    .optional(),
});

/**
 * PickImageByIndexInput
 *
 * Input model for selecting a single image from an array by 1-based index.
 *
 * Pass-through utility: the URL is returned as provided in the input,
 * without fetching or re-uploading the image.
 */
export const zWorkflowUtilitiesPickImageByIndexInput = z
  .object({
    index: z.int().register(z.globalRegistry, {
      description:
        "1-based position of the image to return. Value 1 returns the first image, 2 returns the second, and so on.",
    }),
    fallback_index: z
      .enum(["first-image", "last-image"])
      .register(z.globalRegistry, {
        description:
          "Behavior when `index` exceeds the length of `image_urls`. When `first-image`, returns the first image in the array. When `last-image`, returns the last image in the array. This input has no effect when `index` is within range, when `index` is below 1, or when `image_urls` is empty (the latter two cases still return validation errors). Default is `first-image`.",
      })
      .optional()
      .default("first-image"),
    image_urls: z.array(z.string()).register(z.globalRegistry, {
      description: "Array of image URLs to select from",
    }),
  })
  .register(z.globalRegistry, {
    description:
      "Input model for selecting a single image from an array by 1-based index.\n\nPass-through utility: the URL is returned as provided in the input,\nwithout fetching or re-uploading the image.",
  });

/**
 * PickImageByIndexOutput
 *
 * Output model for the picked image.
 */
export const zWorkflowUtilitiesPickImageByIndexOutput = z
  .object({
    image: zImage,
    images: z.array(zImage).register(z.globalRegistry, {
      description:
        "Single-element array containing the selected image. Included so downstream nodes that expect an `images` reference (matching merge and other utilities) work without changes.",
    }),
  })
  .register(z.globalRegistry, {
    description: "Output model for the picked image.",
  });

export const zPostFalAiWorkflowUtilitiesPickImageByIndexBody =
  zWorkflowUtilitiesPickImageByIndexInput;

/**
 * The request status.
 */
export const zPostFalAiWorkflowUtilitiesPickImageByIndexResponse = zQueueStatus;

export const zGetFalAiWorkflowUtilitiesPickImageByIndexRequestsByRequestIdPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * Result of the request.
 */
export const zGetFalAiWorkflowUtilitiesPickImageByIndexRequestsByRequestIdResponse =
  zWorkflowUtilitiesPickImageByIndexOutput;

export const zPutFalAiWorkflowUtilitiesPickImageByIndexRequestsByRequestIdCancelPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

/**
 * The request was cancelled.
 */
export const zPutFalAiWorkflowUtilitiesPickImageByIndexRequestsByRequestIdCancelResponse =
  z
    .object({
      success: z
        .boolean()
        .register(z.globalRegistry, {
          description: "Whether the request was cancelled successfully.",
        })
        .optional(),
    })
    .register(z.globalRegistry, {
      description: "The request was cancelled.",
    });

export const zGetFalAiWorkflowUtilitiesPickImageByIndexRequestsByRequestIdStatusPath =
  z.object({
    request_id: z.string().register(z.globalRegistry, {
      description: "Request ID",
    }),
  });

export const zGetFalAiWorkflowUtilitiesPickImageByIndexRequestsByRequestIdStatusQuery =
  z.object({
    logs: z
      .number()
      .register(z.globalRegistry, {
        description:
          "Whether to include logs (`1`) in the response or not (`0`).",
      })
      .optional(),
  });

/**
 * The request status.
 */
export const zGetFalAiWorkflowUtilitiesPickImageByIndexRequestsByRequestIdStatusResponse =
  zQueueStatus;
