// This file is auto-generated by @hey-api/openapi-ts

export const AestheticsSchema = {
  type: "object",
  properties: {
    color_scheme: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The color scheme of the image to be generated.",
      title: "Color Scheme",
    },
    mood_atmosphere: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The mood and atmosphere of the image to be generated.",
      title: "Mood Atmosphere",
    },
    composition: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The composition of the image to be generated.",
      title: "Composition",
    },
  },
  "x-fal-order-properties": ["composition", "color_scheme", "mood_atmosphere"],
  title: "Aesthetics",
} as const;

export const AestheticsDetailsSchema = {
  "x-fal-order-properties": [
    "composition",
    "color_scheme",
    "mood_atmosphere",
    "aesthetic_score",
    "preference_score",
  ],
  title: "AestheticsDetails",
  type: "object",
  description: "Aesthetic analysis of the image.",
  required: [
    "composition",
    "color_scheme",
    "mood_atmosphere",
    "aesthetic_score",
    "preference_score",
  ],
  properties: {
    mood_atmosphere: {
      type: "string",
      description: "E.g., 'serene', 'energetic', 'mysterious', 'joyful'.",
      title: "Mood Atmosphere",
    },
    preference_score: {
      type: "string",
      description: "E.g., 'very low', 'low', 'medium', 'high', 'very high'.",
      title: "Preference Score",
    },
    composition: {
      type: "string",
      description:
        "E.g., 'rule of thirds', 'symmetrical', 'centered', 'leading lines'.",
      title: "Composition",
    },
    aesthetic_score: {
      type: "string",
      description: "E.g., 'very low', 'low', 'medium', 'high', 'very high'.",
      title: "Aesthetic Score",
    },
    color_scheme: {
      type: "string",
      description:
        "E.g., 'monochromatic blue', 'warm complementary colors', 'high contrast'.",
      title: "Color Scheme",
    },
  },
} as const;

export const AestheticsType2Schema = {
  title: "Aesthetics",
  type: "object",
  properties: {
    preference_score: {
      title: "Preference Score",
      type: "string",
      description: "The preference score of the image.",
    },
    composition: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Composition",
      description: "The composition of the image to be generated.",
    },
    mood_atmosphere: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Mood Atmosphere",
      description: "The mood and atmosphere of the image to be generated.",
    },
    aesthetic_score: {
      title: "Aesthetic Score",
      type: "string",
      description: "The aesthetic score of the image.",
    },
    color_scheme: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Color Scheme",
      description: "The color scheme of the image to be generated.",
    },
  },
  "x-fal-order-properties": [
    "composition",
    "color_scheme",
    "mood_atmosphere",
    "aesthetic_score",
    "preference_score",
  ],
  required: ["aesthetic_score", "preference_score"],
} as const;

export const BagelUnderstandInputSchema = {
  required: ["image_url", "prompt"],
  properties: {
    seed: {
      title: "Seed",
      type: "integer",
      description: "The seed to use for the generation.",
    },
    prompt: {
      description: "The prompt to query the image with.",
      title: "Prompt",
      type: "string",
      examples: ["What is shown in the image? "],
    },
    image_url: {
      description: "The image for the query.",
      title: "Image Url",
      type: "string",
      examples: [
        "https://storage.googleapis.com/falserverless/bagel/wRhCPSyiKTiLnnWvUpGIl.jpeg",
      ],
      "x-fal-file-input": true,
    },
  },
  title: "ImageUnderstandingInput",
  "x-fal-order-properties": ["image_url", "prompt", "seed"],
  type: "object",
} as const;

export const BagelUnderstandOutputSchema = {
  required: ["text", "seed", "prompt", "timings"],
  properties: {
    prompt: {
      title: "Prompt",
      type: "string",
      description: "The query used for the generation.",
    },
    timings: {
      title: "Timings",
      type: "object",
      description: "The timings of the generation.",
    },
    text: {
      title: "Text",
      type: "string",
      description: "The answer to the query.",
    },
    seed: {
      title: "Seed",
      type: "integer",
      description: "The seed used for the generation.",
    },
  },
  title: "TextOutput",
  "x-fal-order-properties": ["text", "seed", "prompt", "timings"],
  type: "object",
} as const;

export const bria_fibo_vlm_StructuredPromptSchema = {
  title: "StructuredPrompt",
  type: "object",
  properties: {
    background_setting: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Background Setting",
      description: "The background setting of the image to be generated.",
    },
    artistic_style: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Artistic Style",
      description: "The artistic style of the image to be generated.",
    },
    style_medium: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Style Medium",
      description: "The style medium of the image to be generated.",
    },
    text_render: {
      anyOf: [
        {
          type: "array",
          items: {},
        },
        {
          type: "null",
        },
      ],
      title: "Text Render",
      description: "A list of text to be rendered in the image.",
      default: [],
    },
    objects: {
      anyOf: [
        {
          type: "array",
          items: {
            $ref: "#/components/schemas/PromptObject",
          },
        },
        {
          type: "null",
        },
      ],
      title: "Objects",
      description:
        "A list of objects in the image to be generated, along with their attributes and relationships to other objects in the image.",
      default: [],
    },
    context: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Context",
      description: "The context of the image to be generated.",
    },
    photographic_characteristics: {
      anyOf: [
        {
          $ref: "#/components/schemas/PhotographicCharacteristics",
        },
        {
          type: "null",
        },
      ],
      description:
        "The photographic characteristics of the image to be generated.",
    },
    aesthetics: {
      anyOf: [
        {
          $ref: "#/components/schemas/AestheticsType2",
        },
        {
          type: "null",
        },
      ],
      description: "The aesthetics of the image to be generated.",
    },
    lighting: {
      anyOf: [
        {
          $ref: "#/components/schemas/Lighting",
        },
        {
          type: "null",
        },
      ],
      description: "The lighting of the image to be generated.",
    },
    short_description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Short Description",
      description: "A short description of the image to be generated.",
    },
  },
  "x-fal-order-properties": [
    "short_description",
    "objects",
    "background_setting",
    "lighting",
    "aesthetics",
    "photographic_characteristics",
    "style_medium",
    "text_render",
    "context",
    "artistic_style",
  ],
} as const;

export const FiboEditEditStructured_instructionInputSchema = {
  type: "object",
  "x-fal-order-properties": [
    "image_url",
    "mask_url",
    "instruction",
    "seed",
    "sync_mode",
  ],
  title: "StructuredInstructionInputModel",
  properties: {
    instruction: {
      title: "Instruction",
      examples: ["change lighting to starlight nighttime"],
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "Instruction for image editing.",
    },
    seed: {
      title: "Seed",
      default: 5555,
      type: "integer",
      description: "Random seed for reproducibility.",
    },
    sync_mode: {
      title: "Sync Mode",
      default: false,
      type: "boolean",
      description:
        "If true, returns the image directly in the response (increases latency).",
    },
    mask_url: {
      title: "Mask Url",
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "Reference image mask (file or URL). Optional.",
    },
    image_url: {
      title: "Image Url",
      examples: [
        "https://v3b.fal.media/files/b/0a8b07e8/GYKVk2EVivg_MC3jRRZi3_png%20-%202026-01-13T094835.850%20(3).png",
      ],
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "Reference image (file or URL).",
    },
  },
} as const;

export const FiboEditEditStructured_instructionOutputSchema = {} as const;

export const FiboGenerateStructured_promptInputSchema = {
  type: "object",
  properties: {
    structured_prompt: {
      anyOf: [
        {
          $ref: "#/components/schemas/StructuredPrompt",
        },
        {
          type: "null",
        },
      ],
      description: "The structured prompt to generate an image from.",
    },
    prompt: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      examples: [
        "A hyper-detailed, ultra-fluffy owl sitting in the trees at night, looking directly at the camera with wide, adorable, expressive eyes. Its feathers are soft and voluminous, catching the cool moonlight with subtle silver highlights. The owl’s gaze is curious and full of charm, giving it a whimsical, storybook-like personality.",
      ],
      description: "Prompt for image generation.",
      title: "Prompt",
    },
    image_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "Reference image (file or URL).",
      title: "Image Url",
    },
    seed: {
      type: "integer",
      description: "Random seed for reproducibility.",
      title: "Seed",
      default: 5555,
    },
  },
  "x-fal-order-properties": [
    "prompt",
    "structured_prompt",
    "image_url",
    "seed",
  ],
  title: "StructuredPromptModel",
} as const;

export const FiboGenerateStructured_promptOutputSchema = {} as const;

export const FiboLiteGenerateStructured_promptInputSchema = {
  "x-fal-order-properties": [
    "prompt",
    "structured_prompt",
    "image_url",
    "seed",
  ],
  title: "StructuredPromptInput",
  type: "object",
  properties: {
    image_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "Input image URL",
      title: "Image Url",
    },
    prompt: {
      title: "Prompt",
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The prompt to generate.",
      examples: [
        'Oil painting of a fluffy, wide-eyed cat sitting upright, holding a small wooden sign reading "Feed Me." Rich textures, dramatic brushstrokes, warm tones, and vintage charm.',
      ],
    },
    structured_prompt: {
      anyOf: [
        {
          $ref: "#/components/schemas/StructuredPromptType2",
        },
        {
          type: "null",
        },
      ],
      description: "The structured prompt to generate.",
    },
    seed: {
      type: "integer",
      default: 7,
      description: "Seed for the random number generator.",
      title: "Seed",
    },
  },
} as const;

export const FiboLiteGenerateStructured_promptLiteInputSchema = {
  title: "StructuredPromptModel",
  type: "object",
  properties: {
    prompt: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Prompt",
      description: "Prompt for image generation.",
      examples: [
        "A hyper-detailed, ultra-fluffy owl sitting in the trees at night, looking directly at the camera with wide, adorable, expressive eyes. Its feathers are soft and voluminous, catching the cool moonlight with subtle silver highlights. The owl's gaze is curious and full of charm, giving it a whimsical, storybook-like personality.",
      ],
    },
    seed: {
      title: "Seed",
      type: "integer",
      description: "Random seed for reproducibility.",
      default: 5555,
    },
    structured_prompt: {
      anyOf: [
        {
          $ref: "#/components/schemas/bria_fibo-vlm_StructuredPrompt",
        },
        {
          type: "null",
        },
      ],
      description: "The structured prompt to generate an image from.",
    },
    image_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Image Url",
      description: "Reference image (file or URL).",
    },
  },
  "x-fal-order-properties": [
    "prompt",
    "structured_prompt",
    "image_url",
    "seed",
  ],
} as const;

export const FiboLiteGenerateStructured_promptLiteOutputSchema = {} as const;

export const FiboLiteGenerateStructured_promptOutputSchema = {} as const;

export const FileSchema = {
  type: "object",
  title: "File",
  required: ["url"],
  properties: {
    file_name: {
      description:
        "The name of the file. It will be auto-generated if not provided.",
      examples: ["z9RV14K95DvU.png"],
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "File Name",
    },
    file_size: {
      description: "The size of the file in bytes.",
      examples: [4404019],
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "File Size",
    },
    content_type: {
      description: "The mime type of the file.",
      examples: ["image/png"],
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Content Type",
    },
    url: {
      description: "The URL where the file can be downloaded from.",
      type: "string",
      title: "Url",
    },
  },
  "x-fal-order-properties": ["url", "content_type", "file_name", "file_size"],
} as const;

export const LightingSchema = {
  type: "object",
  properties: {
    conditions: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description:
        "The conditions of the lighting in the image to be generated.",
      title: "Conditions",
    },
    direction: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description:
        "The direction of the lighting in the image to be generated.",
      title: "Direction",
    },
    shadows: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The shadows in the image to be generated.",
      title: "Shadows",
    },
  },
  "x-fal-order-properties": ["conditions", "direction", "shadows"],
  title: "Lighting",
} as const;

export const LightingDetailsSchema = {
  "x-fal-order-properties": ["conditions", "direction", "shadows"],
  title: "LightingDetails",
  type: "object",
  description: "Lighting information for the image.",
  required: ["conditions", "direction"],
  properties: {
    conditions: {
      type: "string",
      description:
        "E.g., 'bright daylight', 'dim indoor', 'studio lighting', 'golden hour'.",
      title: "Conditions",
    },
    direction: {
      type: "string",
      description: "E.g., 'front-lit', 'backlit', 'side-lit from left'.",
      title: "Direction",
    },
    shadows: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "Describe the presence of shadows.",
      title: "Shadows",
    },
  },
} as const;

export const ObjectDescriptionSchema = {
  "x-fal-order-properties": [
    "description",
    "location",
    "relationship",
    "relative_size",
    "shape_and_color",
    "texture",
    "appearance_details",
    "number_of_objects",
    "pose",
    "expression",
    "clothing",
    "action",
    "gender",
    "skin_tone_and_texture",
    "orientation",
  ],
  title: "ObjectDescription",
  type: "object",
  description: "Detailed object description with all attributes.",
  required: ["description", "location", "relationship"],
  properties: {
    pose: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "Describe the body position.",
      title: "Pose",
    },
    number_of_objects: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      description: "The number of objects in the cluster.",
      title: "Number Of Objects",
    },
    action: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "Describe the action of the human.",
      title: "Action",
    },
    expression: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "Describe facial expression.",
      title: "Expression",
    },
    gender: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "Describe the gender of the human.",
      title: "Gender",
    },
    description: {
      type: "string",
      description: "Short description of the object.",
      title: "Description",
    },
    clothing: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "Describe attire.",
      title: "Clothing",
    },
    orientation: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "Describe the orientation of the human.",
      title: "Orientation",
    },
    skin_tone_and_texture: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "Describe the skin tone and texture.",
      title: "Skin Tone And Texture",
    },
    shape_and_color: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "Describe the basic shape and dominant color.",
      title: "Shape And Color",
    },
    location: {
      type: "string",
      description: "E.g., 'center', 'top-left', 'bottom-right foreground'.",
      title: "Location",
    },
    relationship: {
      type: "string",
      description:
        "Describe the relationship between the object and the other objects in the image.",
      title: "Relationship",
    },
    appearance_details: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "Any other notable visual details.",
      title: "Appearance Details",
    },
    texture: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "E.g., 'smooth', 'rough', 'metallic', 'furry'.",
      title: "Texture",
    },
    relative_size: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "E.g., 'small', 'medium', 'large within frame'.",
      title: "Relative Size",
    },
  },
} as const;

export const OmnilottieImageToLottieInputSchema = {
  type: "object",
  title: "ImageToLottieInput",
  required: ["prompt", "image_url"],
  properties: {
    image_url: {
      description: "URL of the reference image to animate.",
      type: "string",
      examples: [
        "https://storage.googleapis.com/falserverless/gallery/00de75e2c031cb3fc3f472e356aba5b6.png",
      ],
      title: "Image Url",
      "x-fal-file-input": true,
    },
    temperature: {
      description: "Sampling temperature for generation.",
      minimum: 0,
      type: "number",
      title: "Temperature",
      maximum: 2,
      default: 0.9,
    },
    top_p: {
      description: "Nucleus sampling probability threshold.",
      minimum: 0,
      type: "number",
      title: "Top P",
      maximum: 1,
      default: 0.25,
    },
    prompt: {
      description: "Text description guiding the animation of the image.",
      type: "string",
      examples: [
        "A cyan-colored, elongated shape resembling a smiley face, consisting of two pink oval eyes with navy blue circular pupils positioned symmetrically. The shape rotates gradually around its horizontal axis, revealing small animated sparklesâpink and tealâthat appear sporadically near the eyes, enhancing the dynamic visual effect.",
      ],
      title: "Prompt",
    },
    top_k: {
      description: "Top-k sampling parameter.",
      minimum: 1,
      type: "integer",
      title: "Top K",
      maximum: 100,
      default: 5,
    },
    max_tokens: {
      description: "Maximum number of Lottie tokens to generate.",
      minimum: 256,
      type: "integer",
      title: "Max Tokens",
      maximum: 8192,
      default: 4096,
    },
  },
  "x-fal-order-properties": [
    "prompt",
    "image_url",
    "max_tokens",
    "temperature",
    "top_p",
    "top_k",
  ],
} as const;

export const OmnilottieImageToLottieOutputSchema = {
  type: "object",
  title: "LottieOutput",
  required: ["lottie_file"],
  properties: {
    lottie_file: {
      description: "The generated Lottie animation as a JSON file.",
      $ref: "#/components/schemas/File",
    },
  },
  "x-fal-order-properties": ["lottie_file"],
} as const;

export const OmnilottieInputSchema = {
  type: "object",
  title: "TextToLottieInput",
  required: ["prompt"],
  properties: {
    temperature: {
      description: "Sampling temperature for generation.",
      minimum: 0,
      type: "number",
      title: "Temperature",
      maximum: 2,
      default: 0.9,
    },
    top_p: {
      description: "Nucleus sampling probability threshold.",
      minimum: 0,
      type: "number",
      title: "Top P",
      maximum: 1,
      default: 0.25,
    },
    prompt: {
      description: "Text description of the Lottie animation to generate.",
      type: "string",
      examples: ["A red ball bouncing up and down"],
      title: "Prompt",
    },
    top_k: {
      description: "Top-k sampling parameter.",
      minimum: 1,
      type: "integer",
      title: "Top K",
      maximum: 100,
      default: 5,
    },
    max_tokens: {
      description: "Maximum number of Lottie tokens to generate.",
      minimum: 256,
      type: "integer",
      title: "Max Tokens",
      maximum: 8192,
      default: 4096,
    },
  },
  "x-fal-order-properties": [
    "prompt",
    "max_tokens",
    "temperature",
    "top_p",
    "top_k",
  ],
} as const;

export const OmnilottieOutputSchema = {
  type: "object",
  title: "LottieOutput",
  required: ["lottie_file"],
  properties: {
    lottie_file: {
      description: "The generated Lottie animation as a JSON file.",
      $ref: "#/components/schemas/File",
    },
  },
  "x-fal-order-properties": ["lottie_file"],
} as const;

export const OmnilottieVideoToLottieInputSchema = {
  type: "object",
  title: "VideoToLottieInput",
  required: ["video_url"],
  properties: {
    top_k: {
      description: "Top-k sampling parameter.",
      minimum: 1,
      type: "integer",
      title: "Top K",
      maximum: 100,
      default: 5,
    },
    temperature: {
      description: "Sampling temperature for generation.",
      minimum: 0,
      type: "number",
      title: "Temperature",
      maximum: 2,
      default: 0.9,
    },
    top_p: {
      description: "Nucleus sampling probability threshold.",
      minimum: 0,
      type: "number",
      title: "Top P",
      maximum: 1,
      default: 0.25,
    },
    prompt: {
      description: "Optional text description guiding the conversion.",
      title: "Prompt",
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    video_url: {
      description: "URL of the video to convert into a Lottie animation.",
      type: "string",
      examples: [
        "https://storage.googleapis.com/falserverless/gallery/0dd62535b46d6f8ecf42f22dc0e148cd.mp4",
      ],
      title: "Video Url",
      "x-fal-file-input": true,
    },
    max_tokens: {
      description: "Maximum number of Lottie tokens to generate.",
      minimum: 256,
      type: "integer",
      title: "Max Tokens",
      maximum: 8192,
      default: 4096,
    },
  },
  "x-fal-order-properties": [
    "prompt",
    "video_url",
    "max_tokens",
    "temperature",
    "top_p",
    "top_k",
  ],
} as const;

export const OmnilottieVideoToLottieOutputSchema = {
  type: "object",
  title: "LottieOutput",
  required: ["lottie_file"],
  properties: {
    lottie_file: {
      description: "The generated Lottie animation as a JSON file.",
      $ref: "#/components/schemas/File",
    },
  },
  "x-fal-order-properties": ["lottie_file"],
} as const;

export const PhotographicCharacteristicsSchema = {
  type: "object",
  properties: {
    camera_angle: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The angle of the camera in the image to be generated.",
      title: "Camera Angle",
    },
    focus: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The focus in the image to be generated.",
      title: "Focus",
    },
    lens_focal_length: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The focal length of the lens in the image to be generated.",
      title: "Lens Focal Length",
    },
    depth_of_field: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The depth of field in the image to be generated.",
      title: "Depth Of Field",
    },
  },
  "x-fal-order-properties": [
    "depth_of_field",
    "focus",
    "camera_angle",
    "lens_focal_length",
  ],
  title: "PhotographicCharacteristics",
} as const;

export const PhotographicCharacteristicsDetailsSchema = {
  "x-fal-order-properties": [
    "depth_of_field",
    "focus",
    "camera_angle",
    "lens_focal_length",
  ],
  title: "PhotographicCharacteristicsDetails",
  type: "object",
  description: "Photographic characteristics of the image.",
  required: ["depth_of_field", "focus", "camera_angle", "lens_focal_length"],
  properties: {
    lens_focal_length: {
      type: "string",
      description: "E.g., 'wide-angle', 'telephoto', 'macro', 'fisheye'.",
      title: "Lens Focal Length",
    },
    camera_angle: {
      type: "string",
      description:
        "E.g., 'eye-level', 'low angle', 'high angle', 'dutch angle'.",
      title: "Camera Angle",
    },
    depth_of_field: {
      type: "string",
      description: "E.g., 'shallow', 'deep', 'bokeh background'.",
      title: "Depth Of Field",
    },
    focus: {
      type: "string",
      description:
        "E.g., 'sharp focus on subject', 'soft focus', 'motion blur'.",
      title: "Focus",
    },
  },
} as const;

export const PromptObjectSchema = {
  type: "object",
  properties: {
    number_of_objects: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      description: "The number of objects in the image.",
      title: "Number Of Objects",
    },
    clothing: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The clothing of the object in the image.",
      title: "Clothing",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "A description of the object to be generated.",
      title: "Description",
    },
    relative_size: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The relative size of the object in the image.",
      title: "Relative Size",
    },
    skin_tone_and_texture: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The skin tone and texture of the object in the image.",
      title: "Skin Tone And Texture",
    },
    texture: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The texture of the object.",
      title: "Texture",
    },
    expression: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The expression of the object in the image.",
      title: "Expression",
    },
    action: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The action of the object in the image.",
      title: "Action",
    },
    pose: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The pose of the object in the image.",
      title: "Pose",
    },
    appearance_details: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The appearance details of the object.",
      title: "Appearance Details",
    },
    gender: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The gender of the object in the image.",
      title: "Gender",
    },
    relationship: {
      type: "string",
      description:
        "The relationship of the object to other objects in the image.",
      title: "Relationship",
    },
    location: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The location of the object in the image.",
      title: "Location",
    },
    orientation: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The orientation of the object in the image.",
      title: "Orientation",
    },
    shape_and_color: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The shape and color of the object.",
      title: "Shape And Color",
    },
  },
  "x-fal-order-properties": [
    "description",
    "location",
    "relationship",
    "relative_size",
    "shape_and_color",
    "texture",
    "appearance_details",
    "number_of_objects",
    "pose",
    "expression",
    "clothing",
    "action",
    "gender",
    "skin_tone_and_texture",
    "orientation",
  ],
  title: "PromptObject",
  required: ["relationship"],
} as const;

export const QueueStatusSchema = {
  type: "object",
  properties: {
    status: {
      type: "string",
      enum: ["IN_QUEUE", "IN_PROGRESS", "COMPLETED"],
    },
    request_id: {
      type: "string",
      description: "The request id.",
    },
    response_url: {
      type: "string",
      description: "The response url.",
    },
    status_url: {
      type: "string",
      description: "The status url.",
    },
    cancel_url: {
      type: "string",
      description: "The cancel url.",
    },
    logs: {
      type: "object",
      description: "The logs.",
      additionalProperties: true,
    },
    metrics: {
      type: "object",
      description: "The metrics.",
      additionalProperties: true,
    },
    queue_position: {
      type: "integer",
      description: "The queue position.",
    },
  },
  required: ["status", "request_id"],
} as const;

export const StructuredPromptSchema = {
  type: "object",
  properties: {
    objects: {
      anyOf: [
        {
          type: "array",
          items: {
            $ref: "#/components/schemas/PromptObject",
          },
        },
        {
          type: "null",
        },
      ],
      description:
        "A list of objects in the image to be generated, along with their attributes and relationships to other objects in the image.",
      title: "Objects",
      default: [],
    },
    text_render: {
      anyOf: [
        {
          type: "array",
          items: {},
        },
        {
          type: "null",
        },
      ],
      description: "A list of text to be rendered in the image.",
      title: "Text Render",
      default: [],
    },
    style_medium: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The style medium of the image to be generated.",
      title: "Style Medium",
    },
    background_setting: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The background setting of the image to be generated.",
      title: "Background Setting",
    },
    artistic_style: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The artistic style of the image to be generated.",
      title: "Artistic Style",
    },
    context: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The context of the image to be generated.",
      title: "Context",
    },
    photographic_characteristics: {
      anyOf: [
        {
          $ref: "#/components/schemas/PhotographicCharacteristics",
        },
        {
          type: "null",
        },
      ],
      description:
        "The photographic characteristics of the image to be generated.",
    },
    aesthetics: {
      anyOf: [
        {
          $ref: "#/components/schemas/Aesthetics",
        },
        {
          type: "null",
        },
      ],
      description: "The aesthetics of the image to be generated.",
    },
    short_description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "A short description of the image to be generated.",
      title: "Short Description",
    },
    lighting: {
      anyOf: [
        {
          $ref: "#/components/schemas/Lighting",
        },
        {
          type: "null",
        },
      ],
      description: "The lighting of the image to be generated.",
    },
  },
  "x-fal-order-properties": [
    "short_description",
    "objects",
    "background_setting",
    "lighting",
    "aesthetics",
    "photographic_characteristics",
    "style_medium",
    "text_render",
    "context",
    "artistic_style",
  ],
  title: "StructuredPrompt",
} as const;

export const StructuredPromptType2Schema = {
  "x-fal-order-properties": [
    "short_description",
    "objects",
    "background_setting",
    "lighting",
    "aesthetics",
    "photographic_characteristics",
    "style_medium",
    "text_render",
    "context",
    "artistic_style",
    "subject_emotions",
  ],
  title: "StructuredPrompt",
  type: "object",
  required: [
    "short_description",
    "objects",
    "background_setting",
    "lighting",
    "aesthetics",
    "context",
    "artistic_style",
  ],
  properties: {
    background_setting: {
      type: "string",
      description:
        "Describe the overall environment, setting, or background, including any notable background elements.",
      title: "Background Setting",
    },
    short_description: {
      type: "string",
      description: "A concise summary of the image content, 200 words maximum.",
      title: "Short Description",
    },
    subject_emotions: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description:
        "Explicitly describe any visible emotions or expressions on subjects.",
      title: "Subject Emotions",
    },
    lighting: {
      $ref: "#/components/schemas/LightingDetails",
      description: "Details about the lighting.",
    },
    photographic_characteristics: {
      anyOf: [
        {
          $ref: "#/components/schemas/PhotographicCharacteristicsDetails",
        },
        {
          type: "null",
        },
      ],
      description: "Details about photographic characteristics.",
    },
    objects: {
      type: "array",
      items: {
        $ref: "#/components/schemas/ObjectDescription",
      },
      description: "List of prominent foreground/midground objects.",
      title: "Objects",
    },
    aesthetics: {
      $ref: "#/components/schemas/AestheticsDetails",
      description: "Details about the image aesthetics.",
    },
    context: {
      type: "string",
      description:
        "Provide any additional context that helps understand the image better.",
      title: "Context",
    },
    text_render: {
      anyOf: [
        {
          type: "array",
          items: {
            $ref: "#/components/schemas/TextRender",
          },
        },
        {
          type: "null",
        },
      ],
      description: "List of text renders in the image.",
      title: "Text Render",
    },
    artistic_style: {
      type: "string",
      description:
        "describe specific artistic characteristics, 3 words maximum.",
      title: "Artistic Style",
    },
    style_medium: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "Identify the artistic style or medium.",
      title: "Style Medium",
    },
  },
} as const;

export const TextRenderSchema = {
  "x-fal-order-properties": [
    "text",
    "location",
    "size",
    "color",
    "font",
    "appearance_details",
  ],
  title: "TextRender",
  type: "object",
  description: "Text rendering information in the image.",
  required: ["text", "location", "size", "color", "font"],
  properties: {
    color: {
      type: "string",
      description: "E.g., 'red', 'blue', 'green'.",
      title: "Color",
    },
    font: {
      type: "string",
      description: "E.g., 'realistic', 'cartoonish', 'minimalist'.",
      title: "Font",
    },
    appearance_details: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "Any other notable visual details.",
      title: "Appearance Details",
    },
    size: {
      type: "string",
      description: "E.g., 'small', 'medium', 'large within frame'.",
      title: "Size",
    },
    text: {
      type: "string",
      description: "The text content.",
      title: "Text",
    },
    location: {
      type: "string",
      description: "E.g., 'center', 'top-left', 'bottom-right foreground'.",
      title: "Location",
    },
  },
} as const;
