// AUTO-GENERATED - Do not edit manually
// Generated from types.gen.ts via scripts/generate-endpoint-maps.ts

import { z } from "zod";

import {
  zErnieImageTrainerInput,
  zErnieImageTrainerOutput,
  zFlux2Klein4bBaseTrainerEditInput,
  zFlux2Klein4bBaseTrainerEditOutput,
  zFlux2Klein4bBaseTrainerInput,
  zFlux2Klein4bBaseTrainerOutput,
  zFlux2Klein9bBaseTrainerEditInput,
  zFlux2Klein9bBaseTrainerEditOutput,
  zFlux2Klein9bBaseTrainerInput,
  zFlux2Klein9bBaseTrainerOutput,
  zFlux2TrainerEditInput,
  zFlux2TrainerEditOutput,
  zFlux2TrainerInput,
  zFlux2TrainerOutput,
  zFlux2TrainerV2EditInput,
  zFlux2TrainerV2EditOutput,
  zFlux2TrainerV2Input,
  zFlux2TrainerV2Output,
  zFluxKontextTrainerInput,
  zFluxKontextTrainerOutput,
  zFluxKreaTrainerInput,
  zFluxKreaTrainerOutput,
  zFluxLoraFastTrainingInput,
  zFluxLoraFastTrainingOutput,
  zFluxLoraPortraitTrainerInput,
  zFluxLoraPortraitTrainerOutput,
  zHunyuanVideoLoraTrainingInput,
  zHunyuanVideoLoraTrainingOutput,
  zLtx23V2vTrainerInput,
  zLtx23V2vTrainerOutput,
  zLtx23VideoTrainerInput,
  zLtx23VideoTrainerOutput,
  zLtx2VideoTrainerInput,
  zLtx2VideoTrainerOutput,
  zLtxVideoTrainerInput,
  zLtxVideoTrainerOutput,
  zPhotaCreateProfileInput,
  zPhotaCreateProfileOutput,
  zQwenImage2512TrainerInput,
  zQwenImage2512TrainerOutput,
  zQwenImage2512TrainerV2Input,
  zQwenImage2512TrainerV2Output,
  zQwenImageEdit2509TrainerInput,
  zQwenImageEdit2509TrainerOutput,
  zQwenImageEdit2511TrainerInput,
  zQwenImageEdit2511TrainerOutput,
  zQwenImageEditPlusTrainerInput,
  zQwenImageEditPlusTrainerOutput,
  zQwenImageEditTrainerInput,
  zQwenImageEditTrainerOutput,
  zQwenImageLayeredTrainerInput,
  zQwenImageLayeredTrainerOutput,
  zQwenImageTrainerInput,
  zQwenImageTrainerOutput,
  zQwenImageTrainerV2Input,
  zQwenImageTrainerV2Output,
  zRecraftV3CreateStyleInput,
  zRecraftV3CreateStyleOutput,
  zTurboFluxTrainerInput,
  zTurboFluxTrainerOutput,
  zWan22ImageTrainerInput,
  zWan22ImageTrainerOutput,
  zWan22TrainerI2vA14bInput,
  zWan22TrainerI2vA14bOutput,
  zWan22TrainerT2vA14bInput,
  zWan22TrainerT2vA14bOutput,
  zWanTrainerFlf2V720pInput,
  zWanTrainerFlf2V720pOutput,
  zWanTrainerI2V720pInput,
  zWanTrainerI2V720pOutput,
  zWanTrainerInput,
  zWanTrainerOutput,
  zWanTrainerT2V14bInput,
  zWanTrainerT2V14bOutput,
  zWanTrainerT2vInput,
  zWanTrainerT2vOutput,
  zZImageBaseTrainerInput,
  zZImageBaseTrainerOutput,
  zZImageTrainerInput,
  zZImageTrainerOutput,
  zZImageTurboTrainerV2Input,
  zZImageTurboTrainerV2Output,
} from "./zod.gen";

/** Zod schema for training endpoints using discriminatedUnion */
export const TrainingEndpointSchema = z.discriminatedUnion("endpoint", [
  z.object({
    endpoint: z.literal("fal-ai/ernie-image-trainer"),
    input: zErnieImageTrainerInput,
    output: zErnieImageTrainerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2-klein-4b-base-trainer"),
    input: zFlux2Klein4bBaseTrainerInput,
    output: zFlux2Klein4bBaseTrainerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2-klein-4b-base-trainer/edit"),
    input: zFlux2Klein4bBaseTrainerEditInput,
    output: zFlux2Klein4bBaseTrainerEditOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2-klein-9b-base-trainer"),
    input: zFlux2Klein9bBaseTrainerInput,
    output: zFlux2Klein9bBaseTrainerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2-klein-9b-base-trainer/edit"),
    input: zFlux2Klein9bBaseTrainerEditInput,
    output: zFlux2Klein9bBaseTrainerEditOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2-trainer"),
    input: zFlux2TrainerInput,
    output: zFlux2TrainerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2-trainer-v2"),
    input: zFlux2TrainerV2Input,
    output: zFlux2TrainerV2Output,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2-trainer-v2/edit"),
    input: zFlux2TrainerV2EditInput,
    output: zFlux2TrainerV2EditOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-2-trainer/edit"),
    input: zFlux2TrainerEditInput,
    output: zFlux2TrainerEditOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-kontext-trainer"),
    input: zFluxKontextTrainerInput,
    output: zFluxKontextTrainerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-krea-trainer"),
    input: zFluxKreaTrainerInput,
    output: zFluxKreaTrainerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-lora-fast-training"),
    input: zFluxLoraFastTrainingInput,
    output: zFluxLoraFastTrainingOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flux-lora-portrait-trainer"),
    input: zFluxLoraPortraitTrainerInput,
    output: zFluxLoraPortraitTrainerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-video-lora-training"),
    input: zHunyuanVideoLoraTrainingInput,
    output: zHunyuanVideoLoraTrainingOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-trainer"),
    input: zLtxVideoTrainerInput,
    output: zLtxVideoTrainerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx2-video-trainer"),
    input: zLtx2VideoTrainerInput,
    output: zLtx2VideoTrainerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx23-v2v-trainer"),
    input: zLtx23V2vTrainerInput,
    output: zLtx23V2vTrainerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx23-video-trainer"),
    input: zLtx23VideoTrainerInput,
    output: zLtx23VideoTrainerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/phota/create-profile"),
    input: zPhotaCreateProfileInput,
    output: zPhotaCreateProfileOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-2512-trainer"),
    input: zQwenImage2512TrainerInput,
    output: zQwenImage2512TrainerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-2512-trainer-v2"),
    input: zQwenImage2512TrainerV2Input,
    output: zQwenImage2512TrainerV2Output,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-edit-2509-trainer"),
    input: zQwenImageEdit2509TrainerInput,
    output: zQwenImageEdit2509TrainerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-edit-2511-trainer"),
    input: zQwenImageEdit2511TrainerInput,
    output: zQwenImageEdit2511TrainerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-edit-plus-trainer"),
    input: zQwenImageEditPlusTrainerInput,
    output: zQwenImageEditPlusTrainerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-edit-trainer"),
    input: zQwenImageEditTrainerInput,
    output: zQwenImageEditTrainerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-layered-trainer"),
    input: zQwenImageLayeredTrainerInput,
    output: zQwenImageLayeredTrainerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-trainer"),
    input: zQwenImageTrainerInput,
    output: zQwenImageTrainerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/qwen-image-trainer-v2"),
    input: zQwenImageTrainerV2Input,
    output: zQwenImageTrainerV2Output,
  }),
  z.object({
    endpoint: z.literal("fal-ai/recraft/v3/create-style"),
    input: zRecraftV3CreateStyleInput,
    output: zRecraftV3CreateStyleOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/turbo-flux-trainer"),
    input: zTurboFluxTrainerInput,
    output: zTurboFluxTrainerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-22-image-trainer"),
    input: zWan22ImageTrainerInput,
    output: zWan22ImageTrainerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-22-trainer/i2v-a14b"),
    input: zWan22TrainerI2vA14bInput,
    output: zWan22TrainerI2vA14bOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-22-trainer/t2v-a14b"),
    input: zWan22TrainerT2vA14bInput,
    output: zWan22TrainerT2vA14bOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-trainer"),
    input: zWanTrainerInput,
    output: zWanTrainerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-trainer/flf2v-720p"),
    input: zWanTrainerFlf2V720pInput,
    output: zWanTrainerFlf2V720pOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-trainer/i2v-720p"),
    input: zWanTrainerI2V720pInput,
    output: zWanTrainerI2V720pOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-trainer/t2v"),
    input: zWanTrainerT2vInput,
    output: zWanTrainerT2vOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-trainer/t2v-14b"),
    input: zWanTrainerT2V14bInput,
    output: zWanTrainerT2V14bOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/z-image-base-trainer"),
    input: zZImageBaseTrainerInput,
    output: zZImageBaseTrainerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/z-image-trainer"),
    input: zZImageTrainerInput,
    output: zZImageTrainerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/z-image-turbo-trainer-v2"),
    input: zZImageTurboTrainerV2Input,
    output: zZImageTurboTrainerV2Output,
  }),
]);

/** Inferred type from TrainingEndpointSchema */
export type TrainingEndpoint = z.infer<typeof TrainingEndpointSchema>;
