// AUTO-GENERATED - Do not edit manually
// Generated from types.gen.ts via scripts/generate-endpoint-maps.ts

import { z } from "zod";

import {
  zAiAvatarInput,
  zAiAvatarMultiInput,
  zAiAvatarMultiOutput,
  zAiAvatarMultiTextInput,
  zAiAvatarMultiTextOutput,
  zAiAvatarOutput,
  zAiAvatarSingleTextInput,
  zAiAvatarSingleTextOutput,
  zAiFaceSwapFaceswapvideoInput,
  zAiFaceSwapFaceswapvideoOutput,
  zAmtInterpolationFrameInterpolationInput,
  zAmtInterpolationFrameInterpolationOutput,
  zAmtInterpolationInput,
  zAmtInterpolationOutput,
  zAnimatediffSparsectrlLcmInput,
  zAnimatediffSparsectrlLcmOutput,
  zAutoCaptionInput,
  zAutoCaptionOutput,
  zAvatarsAudioToVideoInput,
  zAvatarsAudioToVideoInputType2,
  zAvatarsAudioToVideoOutput,
  zAvatarsAudioToVideoOutputType2,
  zAvatarsTextToVideoInput,
  zAvatarsTextToVideoInputType2,
  zAvatarsTextToVideoOutput,
  zAvatarsTextToVideoOutputType2,
  zBenV2VideoInput,
  zBenV2VideoOutput,
  zBirefnetV2VideoInput,
  zBirefnetV2VideoOutput,
  zBriaVideoEraserEraseKeypointsInput,
  zBriaVideoEraserEraseKeypointsOutput,
  zBriaVideoEraserEraseMaskInput,
  zBriaVideoEraserEraseMaskOutput,
  zBriaVideoEraserErasePromptInput,
  zBriaVideoEraserErasePromptOutput,
  zBytedanceOmnihumanInput,
  zBytedanceOmnihumanOutput,
  zBytedanceOmnihumanV15Input,
  zBytedanceOmnihumanV15Output,
  zBytedanceSeedanceV15ProImageToVideoInput,
  zBytedanceSeedanceV15ProImageToVideoOutput,
  zBytedanceSeedanceV15ProTextToVideoInput,
  zBytedanceSeedanceV15ProTextToVideoOutput,
  zBytedanceSeedanceV1LiteImageToVideoInput,
  zBytedanceSeedanceV1LiteImageToVideoOutput,
  zBytedanceSeedanceV1LiteReferenceToVideoInput,
  zBytedanceSeedanceV1LiteReferenceToVideoOutput,
  zBytedanceSeedanceV1LiteTextToVideoInput,
  zBytedanceSeedanceV1LiteTextToVideoOutput,
  zBytedanceSeedanceV1ProFastImageToVideoInput,
  zBytedanceSeedanceV1ProFastImageToVideoOutput,
  zBytedanceSeedanceV1ProFastTextToVideoInput,
  zBytedanceSeedanceV1ProFastTextToVideoOutput,
  zBytedanceSeedanceV1ProImageToVideoInput,
  zBytedanceSeedanceV1ProImageToVideoOutput,
  zBytedanceSeedanceV1ProTextToVideoInput,
  zBytedanceSeedanceV1ProTextToVideoOutput,
  zBytedanceUpscalerUpscaleVideoInput,
  zBytedanceUpscalerUpscaleVideoOutput,
  zBytedanceVideoStylizeInput,
  zBytedanceVideoStylizeOutput,
  zCogvideox5bImageToVideoInput,
  zCogvideox5bImageToVideoOutput,
  zCogvideox5bInput,
  zCogvideox5bOutput,
  zCogvideox5bVideoToVideoInput,
  zCogvideox5bVideoToVideoOutput,
  zControlnextInput,
  zControlnextOutput,
  zCreatifyAuroraInput,
  zCreatifyAuroraOutput,
  zCrystalVideoUpscalerInput,
  zCrystalVideoUpscalerOutput,
  zDecartLucy5bImageToVideoInput,
  zDecartLucy5bImageToVideoOutput,
  zDubbingInput,
  zDubbingOutput,
  zDwposeVideoInput,
  zDwposeVideoOutput,
  zEchomimicV3Input,
  zEchomimicV3Output,
  zEdittoInput,
  zEdittoOutput,
  zElevenlabsDubbingInput,
  zElevenlabsDubbingOutput,
  zFabric10FastInput,
  zFabric10FastOutput,
  zFabric10Input,
  zFabric10Output,
  zFabric10TextInput,
  zFabric10TextOutput,
  zFastAnimatediffTextToVideoInput,
  zFastAnimatediffTextToVideoOutput,
  zFastAnimatediffTurboTextToVideoInput,
  zFastAnimatediffTurboTextToVideoOutput,
  zFastAnimatediffTurboVideoToVideoInput,
  zFastAnimatediffTurboVideoToVideoOutput,
  zFastAnimatediffVideoToVideoInput,
  zFastAnimatediffVideoToVideoOutput,
  zFastSvdLcmInput,
  zFastSvdLcmOutput,
  zFastSvdLcmTextToVideoInput,
  zFastSvdLcmTextToVideoOutput,
  zFastSvdTextToVideoInput,
  zFastSvdTextToVideoOutput,
  zFfmpegApiComposeInput,
  zFfmpegApiComposeOutput,
  zFfmpegApiMergeAudioVideoInput,
  zFfmpegApiMergeAudioVideoOutput,
  zFfmpegApiMergeVideosInput,
  zFfmpegApiMergeVideosOutput,
  zFilmVideoInput,
  zFilmVideoOutput,
  zFlashvsrUpscaleVideoInput,
  zFlashvsrUpscaleVideoOutput,
  zFramepackF1Input,
  zFramepackF1Output,
  zFramepackFlf2vInput,
  zFramepackFlf2vOutput,
  zFramepackInput,
  zFramepackOutput,
  zGrokImagineVideoEditVideoInput,
  zGrokImagineVideoEditVideoOutput,
  zGrokImagineVideoImageToVideoInput,
  zGrokImagineVideoImageToVideoOutput,
  zGrokImagineVideoTextToVideoInput,
  zGrokImagineVideoTextToVideoOutput,
  zHunyuanAvatarInput,
  zHunyuanAvatarOutput,
  zHunyuanCustomInput,
  zHunyuanCustomOutput,
  zHunyuanPortraitInput,
  zHunyuanPortraitOutput,
  zHunyuanVideoFoleyInput,
  zHunyuanVideoFoleyOutput,
  zHunyuanVideoImageToVideoInput,
  zHunyuanVideoImageToVideoOutput,
  zHunyuanVideoImg2VidLoraInput,
  zHunyuanVideoImg2VidLoraOutput,
  zHunyuanVideoInput,
  zHunyuanVideoLoraInput,
  zHunyuanVideoLoraOutput,
  zHunyuanVideoLoraVideoToVideoInput,
  zHunyuanVideoLoraVideoToVideoOutput,
  zHunyuanVideoOutput,
  zHunyuanVideoV15ImageToVideoInput,
  zHunyuanVideoV15ImageToVideoOutput,
  zHunyuanVideoV15TextToVideoInput,
  zHunyuanVideoV15TextToVideoOutput,
  zHunyuanVideoVideoToVideoInput,
  zHunyuanVideoVideoToVideoOutput,
  zInfinitalkInput,
  zInfinitalkOutput,
  zInfinitalkSingleTextInput,
  zInfinitalkSingleTextOutput,
  zInfinitalkVideoToVideoInput,
  zInfinitalkVideoToVideoOutput,
  zInfinityStarTextToVideoInput,
  zInfinityStarTextToVideoOutput,
  zKandinsky5ProImageToVideoInput,
  zKandinsky5ProImageToVideoOutput,
  zKandinsky5ProTextToVideoInput,
  zKandinsky5ProTextToVideoOutput,
  zKandinsky5TextToVideoDistillInput,
  zKandinsky5TextToVideoDistillOutput,
  zKandinsky5TextToVideoInput,
  zKandinsky5TextToVideoOutput,
  zKlingVideoAiAvatarV2ProInput,
  zKlingVideoAiAvatarV2ProOutput,
  zKlingVideoAiAvatarV2StandardInput,
  zKlingVideoAiAvatarV2StandardOutput,
  zKlingVideoLipsyncAudioToVideoInput,
  zKlingVideoLipsyncAudioToVideoOutput,
  zKlingVideoLipsyncTextToVideoInput,
  zKlingVideoLipsyncTextToVideoOutput,
  zKlingVideoO1ImageToVideoInput,
  zKlingVideoO1ImageToVideoOutput,
  zKlingVideoO1ReferenceToVideoInput,
  zKlingVideoO1ReferenceToVideoOutput,
  zKlingVideoO1StandardImageToVideoInput,
  zKlingVideoO1StandardImageToVideoOutput,
  zKlingVideoO1StandardReferenceToVideoInput,
  zKlingVideoO1StandardReferenceToVideoOutput,
  zKlingVideoO1StandardVideoToVideoEditInput,
  zKlingVideoO1StandardVideoToVideoEditOutput,
  zKlingVideoO1StandardVideoToVideoReferenceInput,
  zKlingVideoO1StandardVideoToVideoReferenceOutput,
  zKlingVideoO1VideoToVideoEditInput,
  zKlingVideoO1VideoToVideoEditOutput,
  zKlingVideoO1VideoToVideoReferenceInput,
  zKlingVideoO1VideoToVideoReferenceOutput,
  zKlingVideoV15ProEffectsInput,
  zKlingVideoV15ProEffectsOutput,
  zKlingVideoV15ProImageToVideoInput,
  zKlingVideoV15ProImageToVideoOutput,
  zKlingVideoV15ProTextToVideoInput,
  zKlingVideoV15ProTextToVideoOutput,
  zKlingVideoV16ProEffectsInput,
  zKlingVideoV16ProEffectsOutput,
  zKlingVideoV16ProElementsInput,
  zKlingVideoV16ProElementsOutput,
  zKlingVideoV16ProImageToVideoInput,
  zKlingVideoV16ProImageToVideoOutput,
  zKlingVideoV16ProTextToVideoInput,
  zKlingVideoV16ProTextToVideoOutput,
  zKlingVideoV16StandardEffectsInput,
  zKlingVideoV16StandardEffectsOutput,
  zKlingVideoV16StandardElementsInput,
  zKlingVideoV16StandardElementsOutput,
  zKlingVideoV16StandardImageToVideoInput,
  zKlingVideoV16StandardImageToVideoOutput,
  zKlingVideoV16StandardTextToVideoInput,
  zKlingVideoV16StandardTextToVideoOutput,
  zKlingVideoV1ProAiAvatarInput,
  zKlingVideoV1ProAiAvatarOutput,
  zKlingVideoV1StandardAiAvatarInput,
  zKlingVideoV1StandardAiAvatarOutput,
  zKlingVideoV1StandardEffectsInput,
  zKlingVideoV1StandardEffectsOutput,
  zKlingVideoV1StandardImageToVideoInput,
  zKlingVideoV1StandardImageToVideoOutput,
  zKlingVideoV1StandardTextToVideoInput,
  zKlingVideoV1StandardTextToVideoOutput,
  zKlingVideoV21MasterImageToVideoInput,
  zKlingVideoV21MasterImageToVideoOutput,
  zKlingVideoV21MasterTextToVideoInput,
  zKlingVideoV21MasterTextToVideoOutput,
  zKlingVideoV21ProImageToVideoInput,
  zKlingVideoV21ProImageToVideoOutput,
  zKlingVideoV21StandardImageToVideoInput,
  zKlingVideoV21StandardImageToVideoOutput,
  zKlingVideoV25TurboProImageToVideoInput,
  zKlingVideoV25TurboProImageToVideoOutput,
  zKlingVideoV25TurboProTextToVideoInput,
  zKlingVideoV25TurboProTextToVideoOutput,
  zKlingVideoV25TurboStandardImageToVideoInput,
  zKlingVideoV25TurboStandardImageToVideoOutput,
  zKlingVideoV26ProImageToVideoInput,
  zKlingVideoV26ProImageToVideoOutput,
  zKlingVideoV26ProMotionControlInput,
  zKlingVideoV26ProMotionControlOutput,
  zKlingVideoV26ProTextToVideoInput,
  zKlingVideoV26ProTextToVideoOutput,
  zKlingVideoV26StandardMotionControlInput,
  zKlingVideoV26StandardMotionControlOutput,
  zKlingVideoV2MasterImageToVideoInput,
  zKlingVideoV2MasterImageToVideoOutput,
  zKlingVideoV2MasterTextToVideoInput,
  zKlingVideoV2MasterTextToVideoOutput,
  zKreaWan14bTextToVideoInput,
  zKreaWan14bTextToVideoOutput,
  zKreaWan14bVideoToVideoInput,
  zKreaWan14bVideoToVideoOutput,
  zLatentsyncInput,
  zLatentsyncOutput,
  zLightxRecameraInput,
  zLightxRecameraOutput,
  zLightxRelightInput,
  zLightxRelightOutput,
  zLipsyncInput,
  zLipsyncOutput,
  zLiveAvatarInput,
  zLiveAvatarOutput,
  zLivePortraitInput,
  zLivePortraitOutput,
  zLongcatMultiAvatarImageAudioToVideoInput,
  zLongcatMultiAvatarImageAudioToVideoOutput,
  zLongcatSingleAvatarAudioToVideoInput,
  zLongcatSingleAvatarAudioToVideoOutput,
  zLongcatSingleAvatarImageAudioToVideoInput,
  zLongcatSingleAvatarImageAudioToVideoOutput,
  zLongcatVideoDistilledImageToVideo480pInput,
  zLongcatVideoDistilledImageToVideo480pOutput,
  zLongcatVideoDistilledImageToVideo720pInput,
  zLongcatVideoDistilledImageToVideo720pOutput,
  zLongcatVideoDistilledTextToVideo480pInput,
  zLongcatVideoDistilledTextToVideo480pOutput,
  zLongcatVideoDistilledTextToVideo720pInput,
  zLongcatVideoDistilledTextToVideo720pOutput,
  zLongcatVideoImageToVideo480pInput,
  zLongcatVideoImageToVideo480pOutput,
  zLongcatVideoImageToVideo720pInput,
  zLongcatVideoImageToVideo720pOutput,
  zLongcatVideoTextToVideo480pInput,
  zLongcatVideoTextToVideo480pOutput,
  zLongcatVideoTextToVideo720pInput,
  zLongcatVideoTextToVideo720pOutput,
  zLtx219bAudioToVideoInput,
  zLtx219bAudioToVideoLoraInput,
  zLtx219bAudioToVideoLoraOutput,
  zLtx219bAudioToVideoOutput,
  zLtx219bDistilledAudioToVideoInput,
  zLtx219bDistilledAudioToVideoLoraInput,
  zLtx219bDistilledAudioToVideoLoraOutput,
  zLtx219bDistilledAudioToVideoOutput,
  zLtx219bDistilledExtendVideoInput,
  zLtx219bDistilledExtendVideoLoraInput,
  zLtx219bDistilledExtendVideoLoraOutput,
  zLtx219bDistilledExtendVideoOutput,
  zLtx219bDistilledImageToVideoInput,
  zLtx219bDistilledImageToVideoLoraInput,
  zLtx219bDistilledImageToVideoLoraOutput,
  zLtx219bDistilledImageToVideoOutput,
  zLtx219bDistilledTextToVideoInput,
  zLtx219bDistilledTextToVideoLoraInput,
  zLtx219bDistilledTextToVideoLoraOutput,
  zLtx219bDistilledTextToVideoOutput,
  zLtx219bDistilledVideoToVideoInput,
  zLtx219bDistilledVideoToVideoLoraInput,
  zLtx219bDistilledVideoToVideoLoraOutput,
  zLtx219bDistilledVideoToVideoOutput,
  zLtx219bExtendVideoInput,
  zLtx219bExtendVideoLoraInput,
  zLtx219bExtendVideoLoraOutput,
  zLtx219bExtendVideoOutput,
  zLtx219bImageToVideoInput,
  zLtx219bImageToVideoLoraInput,
  zLtx219bImageToVideoLoraOutput,
  zLtx219bImageToVideoOutput,
  zLtx219bTextToVideoInput,
  zLtx219bTextToVideoLoraInput,
  zLtx219bTextToVideoLoraOutput,
  zLtx219bTextToVideoOutput,
  zLtx219bVideoToVideoInput,
  zLtx219bVideoToVideoLoraInput,
  zLtx219bVideoToVideoLoraOutput,
  zLtx219bVideoToVideoOutput,
  zLtx2ImageToVideoFastInput,
  zLtx2ImageToVideoFastOutput,
  zLtx2ImageToVideoInput,
  zLtx2ImageToVideoOutput,
  zLtx2RetakeVideoInput,
  zLtx2RetakeVideoOutput,
  zLtx2TextToVideoFastInput,
  zLtx2TextToVideoFastOutput,
  zLtx2TextToVideoInput,
  zLtx2TextToVideoOutput,
  zLtxVideo13bDevExtendInput,
  zLtxVideo13bDevExtendOutput,
  zLtxVideo13bDevImageToVideoInput,
  zLtxVideo13bDevImageToVideoOutput,
  zLtxVideo13bDevInput,
  zLtxVideo13bDevMulticonditioningInput,
  zLtxVideo13bDevMulticonditioningOutput,
  zLtxVideo13bDevOutput,
  zLtxVideo13bDistilledExtendInput,
  zLtxVideo13bDistilledExtendOutput,
  zLtxVideo13bDistilledImageToVideoInput,
  zLtxVideo13bDistilledImageToVideoOutput,
  zLtxVideo13bDistilledInput,
  zLtxVideo13bDistilledMulticonditioningInput,
  zLtxVideo13bDistilledMulticonditioningOutput,
  zLtxVideo13bDistilledOutput,
  zLtxVideoImageToVideoInput,
  zLtxVideoImageToVideoOutput,
  zLtxVideoInput,
  zLtxVideoLoraImageToVideoInput,
  zLtxVideoLoraImageToVideoOutput,
  zLtxVideoLoraMulticonditioningInput,
  zLtxVideoLoraMulticonditioningOutput,
  zLtxVideoOutput,
  zLtxVideoV095ExtendInput,
  zLtxVideoV095ExtendOutput,
  zLtxVideoV095Input,
  zLtxVideoV095MulticonditioningInput,
  zLtxVideoV095MulticonditioningOutput,
  zLtxVideoV095Output,
  zLtxv13B098DistilledExtendInput,
  zLtxv13B098DistilledExtendOutput,
  zLtxv13B098DistilledImageToVideoInput,
  zLtxv13B098DistilledImageToVideoOutput,
  zLtxv13B098DistilledInput,
  zLtxv13B098DistilledMulticonditioningInput,
  zLtxv13B098DistilledMulticonditioningOutput,
  zLtxv13B098DistilledOutput,
  zLucy14bImageToVideoInput,
  zLucy14bImageToVideoOutput,
  zLucyEditDevInput,
  zLucyEditDevOutput,
  zLucyEditFastInput,
  zLucyEditFastOutput,
  zLucyEditProInput,
  zLucyEditProOutput,
  zLucyRestyleInput,
  zLucyRestyleOutput,
  zLumaDreamMachineRay2FlashImageToVideoInput,
  zLumaDreamMachineRay2FlashImageToVideoOutput,
  zLumaDreamMachineRay2FlashInput,
  zLumaDreamMachineRay2FlashModifyInput,
  zLumaDreamMachineRay2FlashModifyOutput,
  zLumaDreamMachineRay2FlashOutput,
  zLumaDreamMachineRay2FlashReframeInput,
  zLumaDreamMachineRay2FlashReframeOutput,
  zLumaDreamMachineRay2ImageToVideoInput,
  zLumaDreamMachineRay2ImageToVideoOutput,
  zLumaDreamMachineRay2Input,
  zLumaDreamMachineRay2ModifyInput,
  zLumaDreamMachineRay2ModifyOutput,
  zLumaDreamMachineRay2Output,
  zLumaDreamMachineRay2ReframeInput,
  zLumaDreamMachineRay2ReframeOutput,
  zLynxInput,
  zLynxOutput,
  zMagiDistilledExtendVideoInput,
  zMagiDistilledExtendVideoOutput,
  zMagiDistilledImageToVideoInput,
  zMagiDistilledImageToVideoOutput,
  zMagiDistilledInput,
  zMagiDistilledOutput,
  zMagiExtendVideoInput,
  zMagiExtendVideoOutput,
  zMagiImageToVideoInput,
  zMagiImageToVideoOutput,
  zMagiInput,
  zMagiOutput,
  zMareyI2vInput,
  zMareyI2vOutput,
  zMareyMotionTransferInput,
  zMareyMotionTransferOutput,
  zMareyPoseTransferInput,
  zMareyPoseTransferOutput,
  zMareyT2vInput,
  zMareyT2vOutput,
  zMinimaxHailuo02FastImageToVideoInput,
  zMinimaxHailuo02FastImageToVideoOutput,
  zMinimaxHailuo02ProImageToVideoInput,
  zMinimaxHailuo02ProImageToVideoOutput,
  zMinimaxHailuo02ProTextToVideoInput,
  zMinimaxHailuo02ProTextToVideoOutput,
  zMinimaxHailuo02StandardImageToVideoInput,
  zMinimaxHailuo02StandardImageToVideoOutput,
  zMinimaxHailuo02StandardTextToVideoInput,
  zMinimaxHailuo02StandardTextToVideoOutput,
  zMinimaxHailuo23FastProImageToVideoInput,
  zMinimaxHailuo23FastProImageToVideoOutput,
  zMinimaxHailuo23FastStandardImageToVideoInput,
  zMinimaxHailuo23FastStandardImageToVideoOutput,
  zMinimaxHailuo23ProImageToVideoInput,
  zMinimaxHailuo23ProImageToVideoOutput,
  zMinimaxHailuo23ProTextToVideoInput,
  zMinimaxHailuo23ProTextToVideoOutput,
  zMinimaxHailuo23StandardImageToVideoInput,
  zMinimaxHailuo23StandardImageToVideoOutput,
  zMinimaxHailuo23StandardTextToVideoInput,
  zMinimaxHailuo23StandardTextToVideoOutput,
  zMinimaxVideo01DirectorImageToVideoInput,
  zMinimaxVideo01DirectorImageToVideoOutput,
  zMinimaxVideo01DirectorInput,
  zMinimaxVideo01DirectorOutput,
  zMinimaxVideo01ImageToVideoInput,
  zMinimaxVideo01ImageToVideoOutput,
  zMinimaxVideo01Input,
  zMinimaxVideo01LiveImageToVideoInput,
  zMinimaxVideo01LiveImageToVideoOutput,
  zMinimaxVideo01LiveInput,
  zMinimaxVideo01LiveOutput,
  zMinimaxVideo01Output,
  zMinimaxVideo01SubjectReferenceInput,
  zMinimaxVideo01SubjectReferenceOutput,
  zMmaudioV2Input,
  zMmaudioV2Output,
  zMochiV1Input,
  zMochiV1Output,
  zMusetalkInput,
  zMusetalkOutput,
  zOneToAllAnimation13bInput,
  zOneToAllAnimation13bOutput,
  zOneToAllAnimation14bInput,
  zOneToAllAnimation14bOutput,
  zOviImageToVideoInput,
  zOviImageToVideoOutput,
  zOviInput,
  zOviOutput,
  zPikaV15PikaffectsInput,
  zPikaV15PikaffectsOutput,
  zPikaV21ImageToVideoInput,
  zPikaV21ImageToVideoOutput,
  zPikaV21TextToVideoInput,
  zPikaV21TextToVideoOutput,
  zPikaV22ImageToVideoInput,
  zPikaV22ImageToVideoOutput,
  zPikaV22PikaframesInput,
  zPikaV22PikaframesOutput,
  zPikaV22PikascenesInput,
  zPikaV22PikascenesOutput,
  zPikaV22TextToVideoInput,
  zPikaV22TextToVideoOutput,
  zPikaV2PikadditionsInput,
  zPikaV2PikadditionsOutput,
  zPikaV2TurboImageToVideoInput,
  zPikaV2TurboImageToVideoOutput,
  zPikaV2TurboTextToVideoInput,
  zPikaV2TurboTextToVideoOutput,
  zPixverseExtendFastInput,
  zPixverseExtendFastOutput,
  zPixverseExtendInput,
  zPixverseExtendOutput,
  zPixverseLipsyncInput,
  zPixverseLipsyncOutput,
  zPixverseSoundEffectsInput,
  zPixverseSoundEffectsOutput,
  zPixverseSwapInput,
  zPixverseSwapOutput,
  zPixverseV35EffectsInput,
  zPixverseV35EffectsOutput,
  zPixverseV35ImageToVideoFastInput,
  zPixverseV35ImageToVideoFastOutput,
  zPixverseV35ImageToVideoInput,
  zPixverseV35ImageToVideoOutput,
  zPixverseV35TextToVideoFastInput,
  zPixverseV35TextToVideoFastOutput,
  zPixverseV35TextToVideoInput,
  zPixverseV35TextToVideoOutput,
  zPixverseV35TransitionInput,
  zPixverseV35TransitionOutput,
  zPixverseV45EffectsInput,
  zPixverseV45EffectsOutput,
  zPixverseV45ImageToVideoFastInput,
  zPixverseV45ImageToVideoFastOutput,
  zPixverseV45ImageToVideoInput,
  zPixverseV45ImageToVideoOutput,
  zPixverseV45TextToVideoFastInput,
  zPixverseV45TextToVideoFastOutput,
  zPixverseV45TextToVideoInput,
  zPixverseV45TextToVideoOutput,
  zPixverseV45TransitionInput,
  zPixverseV45TransitionOutput,
  zPixverseV4EffectsInput,
  zPixverseV4EffectsOutput,
  zPixverseV4ImageToVideoFastInput,
  zPixverseV4ImageToVideoFastOutput,
  zPixverseV4ImageToVideoInput,
  zPixverseV4ImageToVideoOutput,
  zPixverseV4TextToVideoFastInput,
  zPixverseV4TextToVideoFastOutput,
  zPixverseV4TextToVideoInput,
  zPixverseV4TextToVideoOutput,
  zPixverseV55EffectsInput,
  zPixverseV55EffectsOutput,
  zPixverseV55ImageToVideoInput,
  zPixverseV55ImageToVideoOutput,
  zPixverseV55TextToVideoInput,
  zPixverseV55TextToVideoOutput,
  zPixverseV55TransitionInput,
  zPixverseV55TransitionOutput,
  zPixverseV56ImageToVideoInput,
  zPixverseV56ImageToVideoOutput,
  zPixverseV56TextToVideoInput,
  zPixverseV56TextToVideoOutput,
  zPixverseV56TransitionInput,
  zPixverseV56TransitionOutput,
  zPixverseV5EffectsInput,
  zPixverseV5EffectsOutput,
  zPixverseV5ImageToVideoInput,
  zPixverseV5ImageToVideoOutput,
  zPixverseV5TextToVideoInput,
  zPixverseV5TextToVideoOutput,
  zPixverseV5TransitionInput,
  zPixverseV5TransitionOutput,
  zRifeVideoInput,
  zRifeVideoOutput,
  zSadtalkerInput,
  zSadtalkerOutput,
  zSadtalkerReferenceInput,
  zSadtalkerReferenceOutput,
  zSam2VideoInput,
  zSam2VideoOutput,
  zSam3VideoInput,
  zSam3VideoOutput,
  zSam3VideoRleInput,
  zSam3VideoRleOutput,
  zSanaVideoInput,
  zSanaVideoOutput,
  zScailInput,
  zScailOutput,
  zSeedvrUpscaleVideoInput,
  zSeedvrUpscaleVideoOutput,
  zSfxV15VideoToVideoInput,
  zSfxV15VideoToVideoOutput,
  zSfxV1VideoToVideoInput,
  zSfxV1VideoToVideoOutput,
  zSkyreelsI2vInput,
  zSkyreelsI2vOutput,
  zSora2ImageToVideoInput,
  zSora2ImageToVideoOutput,
  zSora2ImageToVideoProInput,
  zSora2ImageToVideoProOutput,
  zSora2TextToVideoInput,
  zSora2TextToVideoOutput,
  zSora2TextToVideoProInput,
  zSora2TextToVideoProOutput,
  zSora2VideoToVideoRemixInput,
  zSora2VideoToVideoRemixOutput,
  zStableAvatarInput,
  zStableAvatarOutput,
  zStableVideoInput,
  zStableVideoOutput,
  zSteadyDancerInput,
  zSteadyDancerOutput,
  zSyncLipsyncInput,
  zSyncLipsyncOutput,
  zSyncLipsyncReact1Input,
  zSyncLipsyncReact1Output,
  zSyncLipsyncV2Input,
  zSyncLipsyncV2Output,
  zSyncLipsyncV2ProInput,
  zSyncLipsyncV2ProOutput,
  zT2vTurboInput,
  zT2vTurboOutput,
  zThinksoundAudioInput,
  zThinksoundAudioOutput,
  zThinksoundInput,
  zThinksoundOutput,
  zTopazUpscaleVideoInput,
  zTopazUpscaleVideoOutput,
  zTranspixarInput,
  zTranspixarOutput,
  zV26ImageToVideoFlashInput,
  zV26ImageToVideoFlashOutput,
  zV26ImageToVideoInput,
  zV26ImageToVideoOutput,
  zV26ReferenceToVideoInput,
  zV26ReferenceToVideoOutput,
  zV26TextToVideoInput,
  zV26TextToVideoOutput,
  zVeo2ImageToVideoInput,
  zVeo2ImageToVideoOutput,
  zVeo2Input,
  zVeo2Output,
  zVeo31ExtendVideoInput,
  zVeo31ExtendVideoOutput,
  zVeo31FastExtendVideoInput,
  zVeo31FastExtendVideoOutput,
  zVeo31FastFirstLastFrameToVideoInput,
  zVeo31FastFirstLastFrameToVideoOutput,
  zVeo31FastImageToVideoInput,
  zVeo31FastImageToVideoOutput,
  zVeo31FastInput,
  zVeo31FastOutput,
  zVeo31FirstLastFrameToVideoInput,
  zVeo31FirstLastFrameToVideoOutput,
  zVeo31ImageToVideoInput,
  zVeo31ImageToVideoOutput,
  zVeo31Input,
  zVeo31Output,
  zVeo31ReferenceToVideoInput,
  zVeo31ReferenceToVideoOutput,
  zVeo3FastImageToVideoInput,
  zVeo3FastImageToVideoOutput,
  zVeo3FastInput,
  zVeo3FastOutput,
  zVeo3ImageToVideoInput,
  zVeo3ImageToVideoOutput,
  zVeo3Input,
  zVeo3Output,
  zVideoAsPromptInput,
  zVideoAsPromptOutput,
  zVideoBackgroundRemovalFastInput,
  zVideoBackgroundRemovalFastOutput,
  zVideoBackgroundRemovalGreenScreenInput,
  zVideoBackgroundRemovalGreenScreenOutput,
  zVideoBackgroundRemovalInput,
  zVideoBackgroundRemovalInputType2,
  zVideoBackgroundRemovalOutput,
  zVideoBackgroundRemovalOutputType2,
  zVideoEraseKeypointsInput,
  zVideoEraseKeypointsOutput,
  zVideoEraseMaskInput,
  zVideoEraseMaskOutput,
  zVideoErasePromptInput,
  zVideoErasePromptOutput,
  zVideoIncreaseResolutionInput,
  zVideoIncreaseResolutionOutput,
  zVideoSoundEffectsGeneratorInput,
  zVideoSoundEffectsGeneratorOutput,
  zVideoUpscalerInput,
  zVideoUpscalerOutput,
  zViduImageToVideoInput,
  zViduImageToVideoOutput,
  zViduQ1ImageToVideoInput,
  zViduQ1ImageToVideoOutput,
  zViduQ1ReferenceToVideoInput,
  zViduQ1ReferenceToVideoOutput,
  zViduQ1StartEndToVideoInput,
  zViduQ1StartEndToVideoOutput,
  zViduQ1TextToVideoInput,
  zViduQ1TextToVideoOutput,
  zViduQ2ImageToVideoProInput,
  zViduQ2ImageToVideoProOutput,
  zViduQ2ImageToVideoTurboInput,
  zViduQ2ImageToVideoTurboOutput,
  zViduQ2ReferenceToVideoProInput,
  zViduQ2ReferenceToVideoProOutput,
  zViduQ2TextToVideoInput,
  zViduQ2TextToVideoOutput,
  zViduQ2VideoExtensionProInput,
  zViduQ2VideoExtensionProOutput,
  zViduQ3ImageToVideoInput,
  zViduQ3ImageToVideoOutput,
  zViduQ3TextToVideoInput,
  zViduQ3TextToVideoOutput,
  zViduReferenceToVideoInput,
  zViduReferenceToVideoOutput,
  zViduStartEndToVideoInput,
  zViduStartEndToVideoOutput,
  zViduTemplateToVideoInput,
  zViduTemplateToVideoOutput,
  zWan22VaceFunA14bDepthInput,
  zWan22VaceFunA14bDepthOutput,
  zWan22VaceFunA14bInpaintingInput,
  zWan22VaceFunA14bInpaintingOutput,
  zWan22VaceFunA14bOutpaintingInput,
  zWan22VaceFunA14bOutpaintingOutput,
  zWan22VaceFunA14bPoseInput,
  zWan22VaceFunA14bPoseOutput,
  zWan22VaceFunA14bReframeInput,
  zWan22VaceFunA14bReframeOutput,
  zWan25PreviewImageToVideoInput,
  zWan25PreviewImageToVideoOutput,
  zWan25PreviewTextToVideoInput,
  zWan25PreviewTextToVideoOutput,
  zWanAlphaInput,
  zWanAlphaOutput,
  zWanAtiInput,
  zWanAtiOutput,
  zWanEffectsInput,
  zWanEffectsOutput,
  zWanFlf2vInput,
  zWanFlf2vOutput,
  zWanFunControlInput,
  zWanFunControlOutput,
  zWanI2vInput,
  zWanI2vLoraInput,
  zWanI2vLoraOutput,
  zWanI2vOutput,
  zWanMoveInput,
  zWanMoveOutput,
  zWanProImageToVideoInput,
  zWanProImageToVideoOutput,
  zWanProTextToVideoInput,
  zWanProTextToVideoOutput,
  zWanT2vInput,
  zWanT2vLoraInput,
  zWanT2vLoraOutput,
  zWanT2vOutput,
  zWanV2214bAnimateMoveInput,
  zWanV2214bAnimateMoveOutput,
  zWanV2214bAnimateReplaceInput,
  zWanV2214bAnimateReplaceOutput,
  zWanV2214bSpeechToVideoInput,
  zWanV2214bSpeechToVideoOutput,
  zWanV225bImageToVideoInput,
  zWanV225bImageToVideoOutput,
  zWanV225bTextToVideoDistillInput,
  zWanV225bTextToVideoDistillOutput,
  zWanV225bTextToVideoFastWanInput,
  zWanV225bTextToVideoFastWanOutput,
  zWanV225bTextToVideoInput,
  zWanV225bTextToVideoOutput,
  zWanV22A14bImageToVideoInput,
  zWanV22A14bImageToVideoLoraInput,
  zWanV22A14bImageToVideoLoraOutput,
  zWanV22A14bImageToVideoOutput,
  zWanV22A14bImageToVideoTurboInput,
  zWanV22A14bImageToVideoTurboOutput,
  zWanV22A14bTextToVideoInput,
  zWanV22A14bTextToVideoLoraInput,
  zWanV22A14bTextToVideoLoraOutput,
  zWanV22A14bTextToVideoOutput,
  zWanV22A14bTextToVideoTurboInput,
  zWanV22A14bTextToVideoTurboOutput,
  zWanV22A14bVideoToVideoInput,
  zWanV22A14bVideoToVideoOutput,
  zWanVace13bInput,
  zWanVace13bOutput,
  zWanVace14bDepthInput,
  zWanVace14bDepthOutput,
  zWanVace14bInpaintingInput,
  zWanVace14bInpaintingOutput,
  zWanVace14bInput,
  zWanVace14bOutpaintingInput,
  zWanVace14bOutpaintingOutput,
  zWanVace14bOutput,
  zWanVace14bPoseInput,
  zWanVace14bPoseOutput,
  zWanVace14bReframeInput,
  zWanVace14bReframeOutput,
  zWanVaceAppsLongReframeInput,
  zWanVaceAppsLongReframeOutput,
  zWanVaceAppsVideoEditInput,
  zWanVaceAppsVideoEditOutput,
  zWanVaceInput,
  zWanVaceOutput,
  zWanVisionEnhancerInput,
  zWanVisionEnhancerOutput,
  zWorkflowUtilitiesAutoSubtitleInput,
  zWorkflowUtilitiesAutoSubtitleOutput,
} from "./zod.gen";

/** Zod schema for video endpoints using discriminatedUnion */
export const VideoEndpointSchema = z.discriminatedUnion("endpoint", [
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/distilled/audio-to-video/lora"),
    input: zLtx219bDistilledAudioToVideoLoraInput,
    output: zLtx219bDistilledAudioToVideoLoraOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/audio-to-video/lora"),
    input: zLtx219bAudioToVideoLoraInput,
    output: zLtx219bAudioToVideoLoraOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/distilled/audio-to-video"),
    input: zLtx219bDistilledAudioToVideoInput,
    output: zLtx219bDistilledAudioToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/audio-to-video"),
    input: zLtx219bAudioToVideoInput,
    output: zLtx219bAudioToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/elevenlabs/dubbing"),
    input: zElevenlabsDubbingInput,
    output: zElevenlabsDubbingOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/longcat-multi-avatar/image-audio-to-video"),
    input: zLongcatMultiAvatarImageAudioToVideoInput,
    output: zLongcatMultiAvatarImageAudioToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/longcat-single-avatar/image-audio-to-video"),
    input: zLongcatSingleAvatarImageAudioToVideoInput,
    output: zLongcatSingleAvatarImageAudioToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/longcat-single-avatar/audio-to-video"),
    input: zLongcatSingleAvatarAudioToVideoInput,
    output: zLongcatSingleAvatarAudioToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("argil/avatars/audio-to-video"),
    input: zAvatarsAudioToVideoInput,
    output: zAvatarsAudioToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-14b/speech-to-video"),
    input: zWanV2214bSpeechToVideoInput,
    output: zWanV2214bSpeechToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/stable-avatar"),
    input: zStableAvatarInput,
    output: zStableAvatarOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/echomimic-v3"),
    input: zEchomimicV3Input,
    output: zEchomimicV3Output,
  }),
  z.object({
    endpoint: z.literal("veed/avatars/audio-to-video"),
    input: zAvatarsAudioToVideoInputType2,
    output: zAvatarsAudioToVideoOutputType2,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-effects"),
    input: zWanEffectsInput,
    output: zWanEffectsOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo2/image-to-video"),
    input: zVeo2ImageToVideoInput,
    output: zVeo2ImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-pro/image-to-video"),
    input: zWanProImageToVideoInput,
    output: zWanProImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1.6/pro/image-to-video"),
    input: zKlingVideoV16ProImageToVideoInput,
    output: zKlingVideoV16ProImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/video-01/image-to-video"),
    input: zMinimaxVideo01ImageToVideoInput,
    output: zMinimaxVideo01ImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/hailuo-2.3/pro/image-to-video"),
    input: zMinimaxHailuo23ProImageToVideoInput,
    output: zMinimaxHailuo23ProImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-25-preview/image-to-video"),
    input: zWan25PreviewImageToVideoInput,
    output: zWan25PreviewImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v2.5-turbo/pro/image-to-video"),
    input: zKlingVideoV25TurboProImageToVideoInput,
    output: zKlingVideoV25TurboProImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/hailuo-02/standard/image-to-video"),
    input: zMinimaxHailuo02StandardImageToVideoInput,
    output: zMinimaxHailuo02StandardImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seedance/v1/pro/image-to-video"),
    input: zBytedanceSeedanceV1ProImageToVideoInput,
    output: zBytedanceSeedanceV1ProImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v2.1/master/image-to-video"),
    input: zKlingVideoV21MasterImageToVideoInput,
    output: zKlingVideoV21MasterImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v2.1/standard/image-to-video"),
    input: zKlingVideoV21StandardImageToVideoInput,
    output: zKlingVideoV21StandardImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v4.5/image-to-video"),
    input: zPixverseV45ImageToVideoInput,
    output: zPixverseV45ImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v2/master/image-to-video"),
    input: zKlingVideoV2MasterImageToVideoInput,
    output: zKlingVideoV2MasterImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-i2v"),
    input: zWanI2vInput,
    output: zWanI2vOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q3/image-to-video"),
    input: zViduQ3ImageToVideoInput,
    output: zViduQ3ImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("xai/grok-imagine-video/image-to-video"),
    input: zGrokImagineVideoImageToVideoInput,
    output: zGrokImagineVideoImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v5.6/transition"),
    input: zPixverseV56TransitionInput,
    output: zPixverseV56TransitionOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v5.6/image-to-video"),
    input: zPixverseV56ImageToVideoInput,
    output: zPixverseV56ImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q2/reference-to-video/pro"),
    input: zViduQ2ReferenceToVideoProInput,
    output: zViduQ2ReferenceToVideoProOutput,
  }),
  z.object({
    endpoint: z.literal("wan/v2.6/image-to-video/flash"),
    input: zV26ImageToVideoFlashInput,
    output: zV26ImageToVideoFlashOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/distilled/image-to-video/lora"),
    input: zLtx219bDistilledImageToVideoLoraInput,
    output: zLtx219bDistilledImageToVideoLoraOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/distilled/image-to-video"),
    input: zLtx219bDistilledImageToVideoInput,
    output: zLtx219bDistilledImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/image-to-video/lora"),
    input: zLtx219bImageToVideoLoraInput,
    output: zLtx219bImageToVideoLoraOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/image-to-video"),
    input: zLtx219bImageToVideoInput,
    output: zLtx219bImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-move"),
    input: zWanMoveInput,
    output: zWanMoveOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kandinsky5-pro/image-to-video"),
    input: zKandinsky5ProImageToVideoInput,
    output: zKandinsky5ProImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seedance/v1.5/pro/image-to-video"),
    input: zBytedanceSeedanceV15ProImageToVideoInput,
    output: zBytedanceSeedanceV15ProImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/live-avatar"),
    input: zLiveAvatarInput,
    output: zLiveAvatarOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-video-v1.5/image-to-video"),
    input: zHunyuanVideoV15ImageToVideoInput,
    output: zHunyuanVideoV15ImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("wan/v2.6/image-to-video"),
    input: zV26ImageToVideoInput,
    output: zV26ImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o1/standard/reference-to-video"),
    input: zKlingVideoO1StandardReferenceToVideoInput,
    output: zKlingVideoO1StandardReferenceToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o1/standard/image-to-video"),
    input: zKlingVideoO1StandardImageToVideoInput,
    output: zKlingVideoO1StandardImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/creatify/aurora"),
    input: zCreatifyAuroraInput,
    output: zCreatifyAuroraOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/ai-avatar/v2/pro"),
    input: zKlingVideoAiAvatarV2ProInput,
    output: zKlingVideoAiAvatarV2ProOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/ai-avatar/v2/standard"),
    input: zKlingVideoAiAvatarV2StandardInput,
    output: zKlingVideoAiAvatarV2StandardOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v2.6/pro/image-to-video"),
    input: zKlingVideoV26ProImageToVideoInput,
    output: zKlingVideoV26ProImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v5.5/effects"),
    input: zPixverseV55EffectsInput,
    output: zPixverseV55EffectsOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v5.5/transition"),
    input: zPixverseV55TransitionInput,
    output: zPixverseV55TransitionOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v5.5/image-to-video"),
    input: zPixverseV55ImageToVideoInput,
    output: zPixverseV55ImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o1/image-to-video"),
    input: zKlingVideoO1ImageToVideoInput,
    output: zKlingVideoO1ImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o1/reference-to-video"),
    input: zKlingVideoO1ReferenceToVideoInput,
    output: zKlingVideoO1ReferenceToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2/image-to-video/fast"),
    input: zLtx2ImageToVideoFastInput,
    output: zLtx2ImageToVideoFastOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2/image-to-video"),
    input: zLtx2ImageToVideoInput,
    output: zLtx2ImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("bytedance/lynx"),
    input: zLynxInput,
    output: zLynxOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/swap"),
    input: zPixverseSwapInput,
    output: zPixverseSwapOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pika/v2.2/pikaframes"),
    input: zPikaV22PikaframesInput,
    output: zPikaV22PikaframesOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/longcat-video/image-to-video/720p"),
    input: zLongcatVideoImageToVideo720pInput,
    output: zLongcatVideoImageToVideo720pOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/longcat-video/image-to-video/480p"),
    input: zLongcatVideoImageToVideo480pInput,
    output: zLongcatVideoImageToVideo480pOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/longcat-video/distilled/image-to-video/720p"),
    input: zLongcatVideoDistilledImageToVideo720pInput,
    output: zLongcatVideoDistilledImageToVideo720pOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/longcat-video/distilled/image-to-video/480p"),
    input: zLongcatVideoDistilledImageToVideo480pInput,
    output: zLongcatVideoDistilledImageToVideo480pOutput,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/minimax/hailuo-2.3-fast/standard/image-to-video",
    ),
    input: zMinimaxHailuo23FastStandardImageToVideoInput,
    output: zMinimaxHailuo23FastStandardImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/hailuo-2.3/standard/image-to-video"),
    input: zMinimaxHailuo23StandardImageToVideoInput,
    output: zMinimaxHailuo23StandardImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/hailuo-2.3-fast/pro/image-to-video"),
    input: zMinimaxHailuo23FastProImageToVideoInput,
    output: zMinimaxHailuo23FastProImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seedance/v1/pro/fast/image-to-video"),
    input: zBytedanceSeedanceV1ProFastImageToVideoInput,
    output: zBytedanceSeedanceV1ProFastImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q2/image-to-video/turbo"),
    input: zViduQ2ImageToVideoTurboInput,
    output: zViduQ2ImageToVideoTurboOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q2/image-to-video/pro"),
    input: zViduQ2ImageToVideoProInput,
    output: zViduQ2ImageToVideoProOutput,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/kling-video/v2.5-turbo/standard/image-to-video",
    ),
    input: zKlingVideoV25TurboStandardImageToVideoInput,
    output: zKlingVideoV25TurboStandardImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3.1/fast/first-last-frame-to-video"),
    input: zVeo31FastFirstLastFrameToVideoInput,
    output: zVeo31FastFirstLastFrameToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3.1/first-last-frame-to-video"),
    input: zVeo31FirstLastFrameToVideoInput,
    output: zVeo31FirstLastFrameToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3.1/reference-to-video"),
    input: zVeo31ReferenceToVideoInput,
    output: zVeo31ReferenceToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3.1/fast/image-to-video"),
    input: zVeo31FastImageToVideoInput,
    output: zVeo31FastImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3.1/image-to-video"),
    input: zVeo31ImageToVideoInput,
    output: zVeo31ImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sora-2/image-to-video/pro"),
    input: zSora2ImageToVideoProInput,
    output: zSora2ImageToVideoProOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sora-2/image-to-video"),
    input: zSora2ImageToVideoInput,
    output: zSora2ImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ovi/image-to-video"),
    input: zOviImageToVideoInput,
    output: zOviImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("veed/fabric-1.0/fast"),
    input: zFabric10FastInput,
    output: zFabric10FastOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/omnihuman/v1.5"),
    input: zBytedanceOmnihumanV15Input,
    output: zBytedanceOmnihumanV15Output,
  }),
  z.object({
    endpoint: z.literal("veed/fabric-1.0"),
    input: zFabric10Input,
    output: zFabric10Output,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1/standard/ai-avatar"),
    input: zKlingVideoV1StandardAiAvatarInput,
    output: zKlingVideoV1StandardAiAvatarOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1/pro/ai-avatar"),
    input: zKlingVideoV1ProAiAvatarInput,
    output: zKlingVideoV1ProAiAvatarOutput,
  }),
  z.object({
    endpoint: z.literal("decart/lucy-14b/image-to-video"),
    input: zLucy14bImageToVideoInput,
    output: zLucy14bImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seedance/v1/lite/reference-to-video"),
    input: zBytedanceSeedanceV1LiteReferenceToVideoInput,
    output: zBytedanceSeedanceV1LiteReferenceToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-ati"),
    input: zWanAtiInput,
    output: zWanAtiOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/decart/lucy-5b/image-to-video"),
    input: zDecartLucy5bImageToVideoInput,
    output: zDecartLucy5bImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v5/transition"),
    input: zPixverseV5TransitionInput,
    output: zPixverseV5TransitionOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v5/effects"),
    input: zPixverseV5EffectsInput,
    output: zPixverseV5EffectsOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v5/image-to-video"),
    input: zPixverseV5ImageToVideoInput,
    output: zPixverseV5ImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("moonvalley/marey/i2v"),
    input: zMareyI2vInput,
    output: zMareyI2vOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/video-stylize"),
    input: zBytedanceVideoStylizeInput,
    output: zBytedanceVideoStylizeOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-a14b/image-to-video/lora"),
    input: zWanV22A14bImageToVideoLoraInput,
    output: zWanV22A14bImageToVideoLoraOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/hailuo-02-fast/image-to-video"),
    input: zMinimaxHailuo02FastImageToVideoInput,
    output: zMinimaxHailuo02FastImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3/image-to-video"),
    input: zVeo3ImageToVideoInput,
    output: zVeo3ImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-a14b/image-to-video/turbo"),
    input: zWanV22A14bImageToVideoTurboInput,
    output: zWanV22A14bImageToVideoTurboOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-5b/image-to-video"),
    input: zWanV225bImageToVideoInput,
    output: zWanV225bImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-a14b/image-to-video"),
    input: zWanV22A14bImageToVideoInput,
    output: zWanV22A14bImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/omnihuman"),
    input: zBytedanceOmnihumanInput,
    output: zBytedanceOmnihumanOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltxv-13b-098-distilled/image-to-video"),
    input: zLtxv13B098DistilledImageToVideoInput,
    output: zLtxv13B098DistilledImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3/fast/image-to-video"),
    input: zVeo3FastImageToVideoInput,
    output: zVeo3FastImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q1/reference-to-video"),
    input: zViduQ1ReferenceToVideoInput,
    output: zViduQ1ReferenceToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ai-avatar/single-text"),
    input: zAiAvatarSingleTextInput,
    output: zAiAvatarSingleTextOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ai-avatar"),
    input: zAiAvatarInput,
    output: zAiAvatarOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ai-avatar/multi-text"),
    input: zAiAvatarMultiTextInput,
    output: zAiAvatarMultiTextOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ai-avatar/multi"),
    input: zAiAvatarMultiInput,
    output: zAiAvatarMultiOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/hailuo-02/pro/image-to-video"),
    input: zMinimaxHailuo02ProImageToVideoInput,
    output: zMinimaxHailuo02ProImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seedance/v1/lite/image-to-video"),
    input: zBytedanceSeedanceV1LiteImageToVideoInput,
    output: zBytedanceSeedanceV1LiteImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-avatar"),
    input: zHunyuanAvatarInput,
    output: zHunyuanAvatarOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v2.1/pro/image-to-video"),
    input: zKlingVideoV21ProImageToVideoInput,
    output: zKlingVideoV21ProImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-portrait"),
    input: zHunyuanPortraitInput,
    output: zHunyuanPortraitOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1.6/standard/elements"),
    input: zKlingVideoV16StandardElementsInput,
    output: zKlingVideoV16StandardElementsOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1.6/pro/elements"),
    input: zKlingVideoV16ProElementsInput,
    output: zKlingVideoV16ProElementsOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-13b-distilled/image-to-video"),
    input: zLtxVideo13bDistilledImageToVideoInput,
    output: zLtxVideo13bDistilledImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-13b-dev/image-to-video"),
    input: zLtxVideo13bDevImageToVideoInput,
    output: zLtxVideo13bDevImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-lora/image-to-video"),
    input: zLtxVideoLoraImageToVideoInput,
    output: zLtxVideoLoraImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v4.5/transition"),
    input: zPixverseV45TransitionInput,
    output: zPixverseV45TransitionOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v4.5/image-to-video/fast"),
    input: zPixverseV45ImageToVideoFastInput,
    output: zPixverseV45ImageToVideoFastOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v4.5/effects"),
    input: zPixverseV45EffectsInput,
    output: zPixverseV45EffectsOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-custom"),
    input: zHunyuanCustomInput,
    output: zHunyuanCustomOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/framepack/f1"),
    input: zFramepackF1Input,
    output: zFramepackF1Output,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q1/start-end-to-video"),
    input: zViduQ1StartEndToVideoInput,
    output: zViduQ1StartEndToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q1/image-to-video"),
    input: zViduQ1ImageToVideoInput,
    output: zViduQ1ImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/magi/image-to-video"),
    input: zMagiImageToVideoInput,
    output: zMagiImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v4/effects"),
    input: zPixverseV4EffectsInput,
    output: zPixverseV4EffectsOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/magi-distilled/image-to-video"),
    input: zMagiDistilledImageToVideoInput,
    output: zMagiDistilledImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/framepack/flf2v"),
    input: zFramepackFlf2vInput,
    output: zFramepackFlf2vOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-flf2v"),
    input: zWanFlf2vInput,
    output: zWanFlf2vOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/framepack"),
    input: zFramepackInput,
    output: zFramepackOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v4/image-to-video/fast"),
    input: zPixverseV4ImageToVideoFastInput,
    output: zPixverseV4ImageToVideoFastOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v4/image-to-video"),
    input: zPixverseV4ImageToVideoInput,
    output: zPixverseV4ImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v3.5/effects"),
    input: zPixverseV35EffectsInput,
    output: zPixverseV35EffectsOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v3.5/transition"),
    input: zPixverseV35TransitionInput,
    output: zPixverseV35TransitionOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/luma-dream-machine/ray-2-flash/image-to-video"),
    input: zLumaDreamMachineRay2FlashImageToVideoInput,
    output: zLumaDreamMachineRay2FlashImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pika/v1.5/pikaffects"),
    input: zPikaV15PikaffectsInput,
    output: zPikaV15PikaffectsOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pika/v2.1/image-to-video"),
    input: zPikaV21ImageToVideoInput,
    output: zPikaV21ImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pika/v2.2/image-to-video"),
    input: zPikaV22ImageToVideoInput,
    output: zPikaV22ImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pika/v2.2/pikascenes"),
    input: zPikaV22PikascenesInput,
    output: zPikaV22PikascenesOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pika/v2/turbo/image-to-video"),
    input: zPikaV2TurboImageToVideoInput,
    output: zPikaV2TurboImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/image-to-video"),
    input: zViduImageToVideoInput,
    output: zViduImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/reference-to-video"),
    input: zViduReferenceToVideoInput,
    output: zViduReferenceToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/start-end-to-video"),
    input: zViduStartEndToVideoInput,
    output: zViduStartEndToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/template-to-video"),
    input: zViduTemplateToVideoInput,
    output: zViduTemplateToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-i2v-lora"),
    input: zWanI2vLoraInput,
    output: zWanI2vLoraOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-video-image-to-video"),
    input: zHunyuanVideoImageToVideoInput,
    output: zHunyuanVideoImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/video-01-director/image-to-video"),
    input: zMinimaxVideo01DirectorImageToVideoInput,
    output: zMinimaxVideo01DirectorImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/skyreels-i2v"),
    input: zSkyreelsI2vInput,
    output: zSkyreelsI2vOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/luma-dream-machine/ray-2/image-to-video"),
    input: zLumaDreamMachineRay2ImageToVideoInput,
    output: zLumaDreamMachineRay2ImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-video-img2vid-lora"),
    input: zHunyuanVideoImg2VidLoraInput,
    output: zHunyuanVideoImg2VidLoraOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v3.5/image-to-video/fast"),
    input: zPixverseV35ImageToVideoFastInput,
    output: zPixverseV35ImageToVideoFastOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v3.5/image-to-video"),
    input: zPixverseV35ImageToVideoInput,
    output: zPixverseV35ImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/video-01-subject-reference"),
    input: zMinimaxVideo01SubjectReferenceInput,
    output: zMinimaxVideo01SubjectReferenceOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1.6/standard/image-to-video"),
    input: zKlingVideoV16StandardImageToVideoInput,
    output: zKlingVideoV16StandardImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sadtalker/reference"),
    input: zSadtalkerReferenceInput,
    output: zSadtalkerReferenceOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/video-01-live/image-to-video"),
    input: zMinimaxVideo01LiveImageToVideoInput,
    output: zMinimaxVideo01LiveImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video/image-to-video"),
    input: zLtxVideoImageToVideoInput,
    output: zLtxVideoImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/cogvideox-5b/image-to-video"),
    input: zCogvideox5bImageToVideoInput,
    output: zCogvideox5bImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1.5/pro/image-to-video"),
    input: zKlingVideoV15ProImageToVideoInput,
    output: zKlingVideoV15ProImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1/standard/image-to-video"),
    input: zKlingVideoV1StandardImageToVideoInput,
    output: zKlingVideoV1StandardImageToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/stable-video"),
    input: zStableVideoInput,
    output: zStableVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/amt-interpolation/frame-interpolation"),
    input: zAmtInterpolationFrameInterpolationInput,
    output: zAmtInterpolationFrameInterpolationOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/live-portrait"),
    input: zLivePortraitInput,
    output: zLivePortraitOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/musetalk"),
    input: zMusetalkInput,
    output: zMusetalkOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sadtalker"),
    input: zSadtalkerInput,
    output: zSadtalkerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-svd-lcm"),
    input: zFastSvdLcmInput,
    output: zFastSvdLcmOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v2.5-turbo/pro/text-to-video"),
    input: zKlingVideoV25TurboProTextToVideoInput,
    output: zKlingVideoV25TurboProTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3/fast"),
    input: zVeo3FastInput,
    output: zVeo3FastOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/hailuo-02/standard/text-to-video"),
    input: zMinimaxHailuo02StandardTextToVideoInput,
    output: zMinimaxHailuo02StandardTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3"),
    input: zVeo3Input,
    output: zVeo3Output,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v2/master/text-to-video"),
    input: zKlingVideoV2MasterTextToVideoInput,
    output: zKlingVideoV2MasterTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q3/text-to-video"),
    input: zViduQ3TextToVideoInput,
    output: zViduQ3TextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("xai/grok-imagine-video/text-to-video"),
    input: zGrokImagineVideoTextToVideoInput,
    output: zGrokImagineVideoTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v5.6/text-to-video"),
    input: zPixverseV56TextToVideoInput,
    output: zPixverseV56TextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/distilled/text-to-video/lora"),
    input: zLtx219bDistilledTextToVideoLoraInput,
    output: zLtx219bDistilledTextToVideoLoraOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/distilled/text-to-video"),
    input: zLtx219bDistilledTextToVideoInput,
    output: zLtx219bDistilledTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/text-to-video/lora"),
    input: zLtx219bTextToVideoLoraInput,
    output: zLtx219bTextToVideoLoraOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/text-to-video"),
    input: zLtx219bTextToVideoInput,
    output: zLtx219bTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kandinsky5-pro/text-to-video"),
    input: zKandinsky5ProTextToVideoInput,
    output: zKandinsky5ProTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seedance/v1.5/pro/text-to-video"),
    input: zBytedanceSeedanceV15ProTextToVideoInput,
    output: zBytedanceSeedanceV15ProTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("wan/v2.6/text-to-video"),
    input: zV26TextToVideoInput,
    output: zV26TextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("veed/fabric-1.0/text"),
    input: zFabric10TextInput,
    output: zFabric10TextOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v2.6/pro/text-to-video"),
    input: zKlingVideoV26ProTextToVideoInput,
    output: zKlingVideoV26ProTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v5.5/text-to-video"),
    input: zPixverseV55TextToVideoInput,
    output: zPixverseV55TextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2/text-to-video/fast"),
    input: zLtx2TextToVideoFastInput,
    output: zLtx2TextToVideoFastOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2/text-to-video"),
    input: zLtx2TextToVideoInput,
    output: zLtx2TextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-video-v1.5/text-to-video"),
    input: zHunyuanVideoV15TextToVideoInput,
    output: zHunyuanVideoV15TextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/infinity-star/text-to-video"),
    input: zInfinityStarTextToVideoInput,
    output: zInfinityStarTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sana-video"),
    input: zSanaVideoInput,
    output: zSanaVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/longcat-video/text-to-video/720p"),
    input: zLongcatVideoTextToVideo720pInput,
    output: zLongcatVideoTextToVideo720pOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/longcat-video/text-to-video/480p"),
    input: zLongcatVideoTextToVideo480pInput,
    output: zLongcatVideoTextToVideo480pOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/longcat-video/distilled/text-to-video/720p"),
    input: zLongcatVideoDistilledTextToVideo720pInput,
    output: zLongcatVideoDistilledTextToVideo720pOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/longcat-video/distilled/text-to-video/480p"),
    input: zLongcatVideoDistilledTextToVideo480pInput,
    output: zLongcatVideoDistilledTextToVideo480pOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/hailuo-2.3/standard/text-to-video"),
    input: zMinimaxHailuo23StandardTextToVideoInput,
    output: zMinimaxHailuo23StandardTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/hailuo-2.3/pro/text-to-video"),
    input: zMinimaxHailuo23ProTextToVideoInput,
    output: zMinimaxHailuo23ProTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seedance/v1/pro/fast/text-to-video"),
    input: zBytedanceSeedanceV1ProFastTextToVideoInput,
    output: zBytedanceSeedanceV1ProFastTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q2/text-to-video"),
    input: zViduQ2TextToVideoInput,
    output: zViduQ2TextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/krea-wan-14b/text-to-video"),
    input: zKreaWan14bTextToVideoInput,
    output: zKreaWan14bTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-alpha"),
    input: zWanAlphaInput,
    output: zWanAlphaOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kandinsky5/text-to-video/distill"),
    input: zKandinsky5TextToVideoDistillInput,
    output: zKandinsky5TextToVideoDistillOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kandinsky5/text-to-video"),
    input: zKandinsky5TextToVideoInput,
    output: zKandinsky5TextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3.1/fast"),
    input: zVeo31FastInput,
    output: zVeo31FastOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3.1"),
    input: zVeo31Input,
    output: zVeo31Output,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sora-2/text-to-video/pro"),
    input: zSora2TextToVideoProInput,
    output: zSora2TextToVideoProOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sora-2/text-to-video"),
    input: zSora2TextToVideoInput,
    output: zSora2TextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ovi"),
    input: zOviInput,
    output: zOviOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-25-preview/text-to-video"),
    input: zWan25PreviewTextToVideoInput,
    output: zWan25PreviewTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("argil/avatars/text-to-video"),
    input: zAvatarsTextToVideoInput,
    output: zAvatarsTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v5/text-to-video"),
    input: zPixverseV5TextToVideoInput,
    output: zPixverseV5TextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/infinitalk/single-text"),
    input: zInfinitalkSingleTextInput,
    output: zInfinitalkSingleTextOutput,
  }),
  z.object({
    endpoint: z.literal("moonvalley/marey/t2v"),
    input: zMareyT2vInput,
    output: zMareyT2vOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-a14b/text-to-video/lora"),
    input: zWanV22A14bTextToVideoLoraInput,
    output: zWanV22A14bTextToVideoLoraOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-5b/text-to-video/distill"),
    input: zWanV225bTextToVideoDistillInput,
    output: zWanV225bTextToVideoDistillOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-5b/text-to-video/fast-wan"),
    input: zWanV225bTextToVideoFastWanInput,
    output: zWanV225bTextToVideoFastWanOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-a14b/text-to-video/turbo"),
    input: zWanV22A14bTextToVideoTurboInput,
    output: zWanV22A14bTextToVideoTurboOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-5b/text-to-video"),
    input: zWanV225bTextToVideoInput,
    output: zWanV225bTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-a14b/text-to-video"),
    input: zWanV22A14bTextToVideoInput,
    output: zWanV22A14bTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltxv-13b-098-distilled"),
    input: zLtxv13B098DistilledInput,
    output: zLtxv13B098DistilledOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/hailuo-02/pro/text-to-video"),
    input: zMinimaxHailuo02ProTextToVideoInput,
    output: zMinimaxHailuo02ProTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seedance/v1/pro/text-to-video"),
    input: zBytedanceSeedanceV1ProTextToVideoInput,
    output: zBytedanceSeedanceV1ProTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance/seedance/v1/lite/text-to-video"),
    input: zBytedanceSeedanceV1LiteTextToVideoInput,
    output: zBytedanceSeedanceV1LiteTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v2.1/master/text-to-video"),
    input: zKlingVideoV21MasterTextToVideoInput,
    output: zKlingVideoV21MasterTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("veed/avatars/text-to-video"),
    input: zAvatarsTextToVideoInputType2,
    output: zAvatarsTextToVideoOutputType2,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-13b-dev"),
    input: zLtxVideo13bDevInput,
    output: zLtxVideo13bDevOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-13b-distilled"),
    input: zLtxVideo13bDistilledInput,
    output: zLtxVideo13bDistilledOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v4.5/text-to-video/fast"),
    input: zPixverseV45TextToVideoFastInput,
    output: zPixverseV45TextToVideoFastOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v4.5/text-to-video"),
    input: zPixverseV45TextToVideoInput,
    output: zPixverseV45TextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q1/text-to-video"),
    input: zViduQ1TextToVideoInput,
    output: zViduQ1TextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/magi"),
    input: zMagiInput,
    output: zMagiOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/magi-distilled"),
    input: zMagiDistilledInput,
    output: zMagiDistilledOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v4/text-to-video"),
    input: zPixverseV4TextToVideoInput,
    output: zPixverseV4TextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v4/text-to-video/fast"),
    input: zPixverseV4TextToVideoFastInput,
    output: zPixverseV4TextToVideoFastOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/lipsync/audio-to-video"),
    input: zKlingVideoLipsyncAudioToVideoInput,
    output: zKlingVideoLipsyncAudioToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/lipsync/text-to-video"),
    input: zKlingVideoLipsyncTextToVideoInput,
    output: zKlingVideoLipsyncTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-t2v-lora"),
    input: zWanT2vLoraInput,
    output: zWanT2vLoraOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/luma-dream-machine/ray-2-flash"),
    input: zLumaDreamMachineRay2FlashInput,
    output: zLumaDreamMachineRay2FlashOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pika/v2.1/text-to-video"),
    input: zPikaV21TextToVideoInput,
    output: zPikaV21TextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pika/v2.2/text-to-video"),
    input: zPikaV22TextToVideoInput,
    output: zPikaV22TextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pika/v2/turbo/text-to-video"),
    input: zPikaV2TurboTextToVideoInput,
    output: zPikaV2TurboTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-pro/text-to-video"),
    input: zWanProTextToVideoInput,
    output: zWanProTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1.6/pro/effects"),
    input: zKlingVideoV16ProEffectsInput,
    output: zKlingVideoV16ProEffectsOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1.6/standard/effects"),
    input: zKlingVideoV16StandardEffectsInput,
    output: zKlingVideoV16StandardEffectsOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1.5/pro/effects"),
    input: zKlingVideoV15ProEffectsInput,
    output: zKlingVideoV15ProEffectsOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1/standard/effects"),
    input: zKlingVideoV1StandardEffectsInput,
    output: zKlingVideoV1StandardEffectsOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-v095"),
    input: zLtxVideoV095Input,
    output: zLtxVideoV095Output,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1.6/pro/text-to-video"),
    input: zKlingVideoV16ProTextToVideoInput,
    output: zKlingVideoV16ProTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-t2v"),
    input: zWanT2vInput,
    output: zWanT2vOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo2"),
    input: zVeo2Input,
    output: zVeo2Output,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/video-01-director"),
    input: zMinimaxVideo01DirectorInput,
    output: zMinimaxVideo01DirectorOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v3.5/text-to-video"),
    input: zPixverseV35TextToVideoInput,
    output: zPixverseV35TextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/v3.5/text-to-video/fast"),
    input: zPixverseV35TextToVideoFastInput,
    output: zPixverseV35TextToVideoFastOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/luma-dream-machine/ray-2"),
    input: zLumaDreamMachineRay2Input,
    output: zLumaDreamMachineRay2Output,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-video-lora"),
    input: zHunyuanVideoLoraInput,
    output: zHunyuanVideoLoraOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/transpixar"),
    input: zTranspixarInput,
    output: zTranspixarOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/cogvideox-5b"),
    input: zCogvideox5bInput,
    output: zCogvideox5bOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1.6/standard/text-to-video"),
    input: zKlingVideoV16StandardTextToVideoInput,
    output: zKlingVideoV16StandardTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/video-01-live"),
    input: zMinimaxVideo01LiveInput,
    output: zMinimaxVideo01LiveOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1/standard/text-to-video"),
    input: zKlingVideoV1StandardTextToVideoInput,
    output: zKlingVideoV1StandardTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v1.5/pro/text-to-video"),
    input: zKlingVideoV15ProTextToVideoInput,
    output: zKlingVideoV15ProTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/mochi-v1"),
    input: zMochiV1Input,
    output: zMochiV1Output,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-video"),
    input: zHunyuanVideoInput,
    output: zHunyuanVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video"),
    input: zLtxVideoInput,
    output: zLtxVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-svd/text-to-video"),
    input: zFastSvdTextToVideoInput,
    output: zFastSvdTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-svd-lcm/text-to-video"),
    input: zFastSvdLcmTextToVideoInput,
    output: zFastSvdLcmTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/t2v-turbo"),
    input: zT2vTurboInput,
    output: zT2vTurboOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-animatediff/text-to-video"),
    input: zFastAnimatediffTextToVideoInput,
    output: zFastAnimatediffTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-animatediff/turbo/text-to-video"),
    input: zFastAnimatediffTurboTextToVideoInput,
    output: zFastAnimatediffTurboTextToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/minimax/video-01"),
    input: zMinimaxVideo01Input,
    output: zMinimaxVideo01Output,
  }),
  z.object({
    endpoint: z.literal("fal-ai/animatediff-sparsectrl-lcm"),
    input: zAnimatediffSparsectrlLcmInput,
    output: zAnimatediffSparsectrlLcmOutput,
  }),
  z.object({
    endpoint: z.literal("bria/video/background-removal"),
    input: zVideoBackgroundRemovalInput,
    output: zVideoBackgroundRemovalOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/mmaudio-v2"),
    input: zMmaudioV2Input,
    output: zMmaudioV2Output,
  }),
  z.object({
    endpoint: z.literal("xai/grok-imagine-video/edit-video"),
    input: zGrokImagineVideoEditVideoInput,
    output: zGrokImagineVideoEditVideoOutput,
  }),
  z.object({
    endpoint: z.literal("half-moon-ai/ai-face-swap/faceswapvideo"),
    input: zAiFaceSwapFaceswapvideoInput,
    output: zAiFaceSwapFaceswapvideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/distilled/video-to-video/lora"),
    input: zLtx219bDistilledVideoToVideoLoraInput,
    output: zLtx219bDistilledVideoToVideoLoraOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/distilled/video-to-video"),
    input: zLtx219bDistilledVideoToVideoInput,
    output: zLtx219bDistilledVideoToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/video-to-video/lora"),
    input: zLtx219bVideoToVideoLoraInput,
    output: zLtx219bVideoToVideoLoraOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/video-to-video"),
    input: zLtx219bVideoToVideoInput,
    output: zLtx219bVideoToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/distilled/extend-video/lora"),
    input: zLtx219bDistilledExtendVideoLoraInput,
    output: zLtx219bDistilledExtendVideoLoraOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/distilled/extend-video"),
    input: zLtx219bDistilledExtendVideoInput,
    output: zLtx219bDistilledExtendVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/extend-video/lora"),
    input: zLtx219bExtendVideoLoraInput,
    output: zLtx219bExtendVideoLoraOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2-19b/extend-video"),
    input: zLtx219bExtendVideoInput,
    output: zLtx219bExtendVideoOutput,
  }),
  z.object({
    endpoint: z.literal("bria/video/erase/keypoints"),
    input: zVideoEraseKeypointsInput,
    output: zVideoEraseKeypointsOutput,
  }),
  z.object({
    endpoint: z.literal("bria/video/erase/prompt"),
    input: zVideoErasePromptInput,
    output: zVideoErasePromptOutput,
  }),
  z.object({
    endpoint: z.literal("bria/video/erase/mask"),
    input: zVideoEraseMaskInput,
    output: zVideoEraseMaskOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/lightx/relight"),
    input: zLightxRelightInput,
    output: zLightxRelightOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/lightx/recamera"),
    input: zLightxRecameraInput,
    output: zLightxRecameraOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v2.6/standard/motion-control"),
    input: zKlingVideoV26StandardMotionControlInput,
    output: zKlingVideoV26StandardMotionControlOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/v2.6/pro/motion-control"),
    input: zKlingVideoV26ProMotionControlInput,
    output: zKlingVideoV26ProMotionControlOutput,
  }),
  z.object({
    endpoint: z.literal("decart/lucy-restyle"),
    input: zLucyRestyleInput,
    output: zLucyRestyleOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/scail"),
    input: zScailInput,
    output: zScailOutput,
  }),
  z.object({
    endpoint: z.literal("clarityai/crystal-video-upscaler"),
    input: zCrystalVideoUpscalerInput,
    output: zCrystalVideoUpscalerOutput,
  }),
  z.object({
    endpoint: z.literal("bria/bria_video_eraser/erase/mask"),
    input: zBriaVideoEraserEraseMaskInput,
    output: zBriaVideoEraserEraseMaskOutput,
  }),
  z.object({
    endpoint: z.literal("bria/bria_video_eraser/erase/keypoints"),
    input: zBriaVideoEraserEraseKeypointsInput,
    output: zBriaVideoEraserEraseKeypointsOutput,
  }),
  z.object({
    endpoint: z.literal("bria/bria_video_eraser/erase/prompt"),
    input: zBriaVideoEraserErasePromptInput,
    output: zBriaVideoEraserErasePromptOutput,
  }),
  z.object({
    endpoint: z.literal("wan/v2.6/reference-to-video"),
    input: zV26ReferenceToVideoInput,
    output: zV26ReferenceToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3.1/fast/extend-video"),
    input: zVeo31FastExtendVideoInput,
    output: zVeo31FastExtendVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/veo3.1/extend-video"),
    input: zVeo31ExtendVideoInput,
    output: zVeo31ExtendVideoOutput,
  }),
  z.object({
    endpoint: z.literal(
      "fal-ai/kling-video/o1/standard/video-to-video/reference",
    ),
    input: zKlingVideoO1StandardVideoToVideoReferenceInput,
    output: zKlingVideoO1StandardVideoToVideoReferenceOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o1/standard/video-to-video/edit"),
    input: zKlingVideoO1StandardVideoToVideoEditInput,
    output: zKlingVideoO1StandardVideoToVideoEditOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/steady-dancer"),
    input: zSteadyDancerInput,
    output: zSteadyDancerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/one-to-all-animation/1.3b"),
    input: zOneToAllAnimation13bInput,
    output: zOneToAllAnimation13bOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/one-to-all-animation/14b"),
    input: zOneToAllAnimation14bInput,
    output: zOneToAllAnimation14bOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-vision-enhancer"),
    input: zWanVisionEnhancerInput,
    output: zWanVisionEnhancerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sync-lipsync/react-1"),
    input: zSyncLipsyncReact1Input,
    output: zSyncLipsyncReact1Output,
  }),
  z.object({
    endpoint: z.literal("veed/video-background-removal/fast"),
    input: zVideoBackgroundRemovalFastInput,
    output: zVideoBackgroundRemovalFastOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o1/video-to-video/edit"),
    input: zKlingVideoO1VideoToVideoEditInput,
    output: zKlingVideoO1VideoToVideoEditOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/kling-video/o1/video-to-video/reference"),
    input: zKlingVideoO1VideoToVideoReferenceInput,
    output: zKlingVideoO1VideoToVideoReferenceOutput,
  }),
  z.object({
    endpoint: z.literal("veed/video-background-removal"),
    input: zVideoBackgroundRemovalInputType2,
    output: zVideoBackgroundRemovalOutputType2,
  }),
  z.object({
    endpoint: z.literal("veed/video-background-removal/green-screen"),
    input: zVideoBackgroundRemovalGreenScreenInput,
    output: zVideoBackgroundRemovalGreenScreenOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-2/retake-video"),
    input: zLtx2RetakeVideoInput,
    output: zLtx2RetakeVideoOutput,
  }),
  z.object({
    endpoint: z.literal("decart/lucy-edit/fast"),
    input: zLucyEditFastInput,
    output: zLucyEditFastOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sam-3/video-rle"),
    input: zSam3VideoRleInput,
    output: zSam3VideoRleOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sam-3/video"),
    input: zSam3VideoInput,
    output: zSam3VideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/editto"),
    input: zEdittoInput,
    output: zEdittoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/flashvsr/upscale/video"),
    input: zFlashvsrUpscaleVideoInput,
    output: zFlashvsrUpscaleVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/workflow-utilities/auto-subtitle"),
    input: zWorkflowUtilitiesAutoSubtitleInput,
    output: zWorkflowUtilitiesAutoSubtitleOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/bytedance-upscaler/upscale/video"),
    input: zBytedanceUpscalerUpscaleVideoInput,
    output: zBytedanceUpscalerUpscaleVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/video-as-prompt"),
    input: zVideoAsPromptInput,
    output: zVideoAsPromptOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/birefnet/v2/video"),
    input: zBirefnetV2VideoInput,
    output: zBirefnetV2VideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/vidu/q2/video-extension/pro"),
    input: zViduQ2VideoExtensionProInput,
    output: zViduQ2VideoExtensionProOutput,
  }),
  z.object({
    endpoint: z.literal("mirelo-ai/sfx-v1.5/video-to-video"),
    input: zSfxV15VideoToVideoInput,
    output: zSfxV15VideoToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/krea-wan-14b/video-to-video"),
    input: zKreaWan14bVideoToVideoInput,
    output: zKreaWan14bVideoToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sora-2/video-to-video/remix"),
    input: zSora2VideoToVideoRemixInput,
    output: zSora2VideoToVideoRemixOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-vace-apps/long-reframe"),
    input: zWanVaceAppsLongReframeInput,
    output: zWanVaceAppsLongReframeOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/infinitalk/video-to-video"),
    input: zInfinitalkVideoToVideoInput,
    output: zInfinitalkVideoToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/seedvr/upscale/video"),
    input: zSeedvrUpscaleVideoInput,
    output: zSeedvrUpscaleVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-vace-apps/video-edit"),
    input: zWanVaceAppsVideoEditInput,
    output: zWanVaceAppsVideoEditOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-14b/animate/replace"),
    input: zWanV2214bAnimateReplaceInput,
    output: zWanV2214bAnimateReplaceOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-14b/animate/move"),
    input: zWanV2214bAnimateMoveInput,
    output: zWanV2214bAnimateMoveOutput,
  }),
  z.object({
    endpoint: z.literal("decart/lucy-edit/pro"),
    input: zLucyEditProInput,
    output: zLucyEditProOutput,
  }),
  z.object({
    endpoint: z.literal("decart/lucy-edit/dev"),
    input: zLucyEditDevInput,
    output: zLucyEditDevOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-22-vace-fun-a14b/reframe"),
    input: zWan22VaceFunA14bReframeInput,
    output: zWan22VaceFunA14bReframeOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-22-vace-fun-a14b/outpainting"),
    input: zWan22VaceFunA14bOutpaintingInput,
    output: zWan22VaceFunA14bOutpaintingOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-22-vace-fun-a14b/inpainting"),
    input: zWan22VaceFunA14bInpaintingInput,
    output: zWan22VaceFunA14bInpaintingOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-22-vace-fun-a14b/depth"),
    input: zWan22VaceFunA14bDepthInput,
    output: zWan22VaceFunA14bDepthOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-22-vace-fun-a14b/pose"),
    input: zWan22VaceFunA14bPoseInput,
    output: zWan22VaceFunA14bPoseOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-video-foley"),
    input: zHunyuanVideoFoleyInput,
    output: zHunyuanVideoFoleyOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sync-lipsync/v2/pro"),
    input: zSyncLipsyncV2ProInput,
    output: zSyncLipsyncV2ProOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-fun-control"),
    input: zWanFunControlInput,
    output: zWanFunControlOutput,
  }),
  z.object({
    endpoint: z.literal("bria/video/increase-resolution"),
    input: zVideoIncreaseResolutionInput,
    output: zVideoIncreaseResolutionOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/infinitalk"),
    input: zInfinitalkInput,
    output: zInfinitalkOutput,
  }),
  z.object({
    endpoint: z.literal("mirelo-ai/sfx-v1/video-to-video"),
    input: zSfxV1VideoToVideoInput,
    output: zSfxV1VideoToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("moonvalley/marey/pose-transfer"),
    input: zMareyPoseTransferInput,
    output: zMareyPoseTransferOutput,
  }),
  z.object({
    endpoint: z.literal("moonvalley/marey/motion-transfer"),
    input: zMareyMotionTransferInput,
    output: zMareyMotionTransferOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ffmpeg-api/merge-videos"),
    input: zFfmpegApiMergeVideosInput,
    output: zFfmpegApiMergeVideosOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan/v2.2-a14b/video-to-video"),
    input: zWanV22A14bVideoToVideoInput,
    output: zWanV22A14bVideoToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltxv-13b-098-distilled/extend"),
    input: zLtxv13B098DistilledExtendInput,
    output: zLtxv13B098DistilledExtendOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/rife/video"),
    input: zRifeVideoInput,
    output: zRifeVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/film/video"),
    input: zFilmVideoInput,
    output: zFilmVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/luma-dream-machine/ray-2-flash/modify"),
    input: zLumaDreamMachineRay2FlashModifyInput,
    output: zLumaDreamMachineRay2FlashModifyOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltxv-13b-098-distilled/multiconditioning"),
    input: zLtxv13B098DistilledMulticonditioningInput,
    output: zLtxv13B098DistilledMulticonditioningOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/sound-effects"),
    input: zPixverseSoundEffectsInput,
    output: zPixverseSoundEffectsOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/thinksound/audio"),
    input: zThinksoundAudioInput,
    output: zThinksoundAudioOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/thinksound"),
    input: zThinksoundInput,
    output: zThinksoundOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/extend/fast"),
    input: zPixverseExtendFastInput,
    output: zPixverseExtendFastOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/extend"),
    input: zPixverseExtendInput,
    output: zPixverseExtendOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pixverse/lipsync"),
    input: zPixverseLipsyncInput,
    output: zPixverseLipsyncOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/luma-dream-machine/ray-2/modify"),
    input: zLumaDreamMachineRay2ModifyInput,
    output: zLumaDreamMachineRay2ModifyOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-vace-14b/reframe"),
    input: zWanVace14bReframeInput,
    output: zWanVace14bReframeOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-vace-14b/outpainting"),
    input: zWanVace14bOutpaintingInput,
    output: zWanVace14bOutpaintingOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-vace-14b/inpainting"),
    input: zWanVace14bInpaintingInput,
    output: zWanVace14bInpaintingOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-vace-14b/pose"),
    input: zWanVace14bPoseInput,
    output: zWanVace14bPoseOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-vace-14b/depth"),
    input: zWanVace14bDepthInput,
    output: zWanVace14bDepthOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/dwpose/video"),
    input: zDwposeVideoInput,
    output: zDwposeVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ffmpeg-api/merge-audio-video"),
    input: zFfmpegApiMergeAudioVideoInput,
    output: zFfmpegApiMergeAudioVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-vace-1-3b"),
    input: zWanVace13bInput,
    output: zWanVace13bOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/luma-dream-machine/ray-2-flash/reframe"),
    input: zLumaDreamMachineRay2FlashReframeInput,
    output: zLumaDreamMachineRay2FlashReframeOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/luma-dream-machine/ray-2/reframe"),
    input: zLumaDreamMachineRay2ReframeInput,
    output: zLumaDreamMachineRay2ReframeOutput,
  }),
  z.object({
    endpoint: z.literal("veed/lipsync"),
    input: zLipsyncInput,
    output: zLipsyncOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-vace-14b"),
    input: zWanVace14bInput,
    output: zWanVace14bOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-13b-distilled/extend"),
    input: zLtxVideo13bDistilledExtendInput,
    output: zLtxVideo13bDistilledExtendOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-13b-distilled/multiconditioning"),
    input: zLtxVideo13bDistilledMulticonditioningInput,
    output: zLtxVideo13bDistilledMulticonditioningOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-13b-dev/multiconditioning"),
    input: zLtxVideo13bDevMulticonditioningInput,
    output: zLtxVideo13bDevMulticonditioningOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-13b-dev/extend"),
    input: zLtxVideo13bDevExtendInput,
    output: zLtxVideo13bDevExtendOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-lora/multiconditioning"),
    input: zLtxVideoLoraMulticonditioningInput,
    output: zLtxVideoLoraMulticonditioningOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/magi/extend-video"),
    input: zMagiExtendVideoInput,
    output: zMagiExtendVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/magi-distilled/extend-video"),
    input: zMagiDistilledExtendVideoInput,
    output: zMagiDistilledExtendVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/wan-vace"),
    input: zWanVaceInput,
    output: zWanVaceOutput,
  }),
  z.object({
    endpoint: z.literal("cassetteai/video-sound-effects-generator"),
    input: zVideoSoundEffectsGeneratorInput,
    output: zVideoSoundEffectsGeneratorOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sync-lipsync/v2"),
    input: zSyncLipsyncV2Input,
    output: zSyncLipsyncV2Output,
  }),
  z.object({
    endpoint: z.literal("fal-ai/latentsync"),
    input: zLatentsyncInput,
    output: zLatentsyncOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/pika/v2/pikadditions"),
    input: zPikaV2PikadditionsInput,
    output: zPikaV2PikadditionsOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-v095/extend"),
    input: zLtxVideoV095ExtendInput,
    output: zLtxVideoV095ExtendOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ltx-video-v095/multiconditioning"),
    input: zLtxVideoV095MulticonditioningInput,
    output: zLtxVideoV095MulticonditioningOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/topaz/upscale/video"),
    input: zTopazUpscaleVideoInput,
    output: zTopazUpscaleVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ben/v2/video"),
    input: zBenV2VideoInput,
    output: zBenV2VideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-video-lora/video-to-video"),
    input: zHunyuanVideoLoraVideoToVideoInput,
    output: zHunyuanVideoLoraVideoToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/hunyuan-video/video-to-video"),
    input: zHunyuanVideoVideoToVideoInput,
    output: zHunyuanVideoVideoToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/ffmpeg-api/compose"),
    input: zFfmpegApiComposeInput,
    output: zFfmpegApiComposeOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sync-lipsync"),
    input: zSyncLipsyncInput,
    output: zSyncLipsyncOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/auto-caption"),
    input: zAutoCaptionInput,
    output: zAutoCaptionOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/dubbing"),
    input: zDubbingInput,
    output: zDubbingOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/video-upscaler"),
    input: zVideoUpscalerInput,
    output: zVideoUpscalerOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/cogvideox-5b/video-to-video"),
    input: zCogvideox5bVideoToVideoInput,
    output: zCogvideox5bVideoToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/controlnext"),
    input: zControlnextInput,
    output: zControlnextOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/sam2/video"),
    input: zSam2VideoInput,
    output: zSam2VideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/amt-interpolation"),
    input: zAmtInterpolationInput,
    output: zAmtInterpolationOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-animatediff/turbo/video-to-video"),
    input: zFastAnimatediffTurboVideoToVideoInput,
    output: zFastAnimatediffTurboVideoToVideoOutput,
  }),
  z.object({
    endpoint: z.literal("fal-ai/fast-animatediff/video-to-video"),
    input: zFastAnimatediffVideoToVideoInput,
    output: zFastAnimatediffVideoToVideoOutput,
  }),
]);

/** Inferred type from VideoEndpointSchema */
export type VideoEndpoint = z.infer<typeof VideoEndpointSchema>;
